import { test } from "node:test";
import assert from "node:assert/strict";
import { resolvePracticeTime, wallTimeCandidates, planOccurrences, validateResponsibility } from "../../src/features/assignment-participants/scheduling.ts";
import { authorizeCheckIn, saveCheckIn, latestCompletion, type CheckInRepository, type CheckInReceipt } from "../../src/features/assignment-participants/checkins.ts";
import { inDoNotDisturb, reminderDecision, LOCKSCREEN_PRACTICE_NOTICE } from "../../src/features/assignment-participants/reminders.ts";
import type { CheckIn } from "../../src/features/assignment-participants/contracts.ts";
import { parent, child, owner, context, responsibility, preferences, NOW } from "./fixtures.ts";
const fallback = { localTime: "18:30", timezone: "Asia/Jerusalem", selectedByAccountId: parent.accountId, selectedAt: NOW };
test("explicit agreed time wins over case default", () => assert.equal(resolvePracticeTime(responsibility, fallback).localTime, "19:00"));
test("saved default is visible as default, not invented session content", () => assert.deepEqual(resolvePracticeTime({ ...responsibility, localTime: null }, fallback), { localTime: "18:30", timezone: "Asia/Jerusalem", timeOrigin: "case_default" }));
test("missing both time and default holds activation", () => assert.throws(() => resolvePracticeTime({ ...responsibility, localTime: null }, null), /TIME_REQUIRED/));
test("normal Jerusalem clock time resolves by timezone", () => assert.deepEqual(wallTimeCandidates("2026-09-22", "19:00", "Asia/Jerusalem"), ["2026-09-22T16:00:00.000Z"]));
test("DST nonexistent time is not silently shifted", () => assert.deepEqual(wallTimeCandidates("2026-03-29", "02:30", "Europe/Berlin"), []));
test("DST ambiguous time yields both instants", () => assert.equal(wallTimeCandidates("2026-10-25", "02:30", "Europe/Berlin").length, 2));
test("daily occurrence range bounded and stable", () => { const a = planOccurrences(responsibility, null, "2026-09-22", 7), b = planOccurrences(responsibility, null, "2026-09-22", 7); assert.equal(a.occurrences.length, 7); assert.deepEqual(a, b); assert.equal(new Set(a.occurrences.map(x => x.id)).size, 7); });
test("paused assignment cannot schedule reminders", () => assert.throws(() => planOccurrences({ ...responsibility, state: "paused" }, null, "2026-09-22"), /NOT_PUBLISHED/));
test("new version has distinct occurrence IDs", () => assert.notEqual(planOccurrences(responsibility, null, "2026-09-22", 1).occurrences[0]?.id, planOccurrences({ ...responsibility, version: 2 }, null, "2026-09-22", 1).occurrences[0]?.id));
test("unsupported calendar range rejected", () => assert.throws(() => planOccurrences(responsibility, null, "2026-09-22", 999), /HORIZON/));
test("responsibility assignee must also have visibility", () => assert.throws(() => validateResponsibility({ ...responsibility, audienceAccountIds: ["child-a"] }), /VISIBILITY/));
test("child own-device checkin preserves identity", () => assert.equal(authorizeCheckIn(child, context, responsibility, null), "self"));
test("parent assisted checkin does not impersonate child", () => { assert.equal(authorizeCheckIn(parent, context, responsibility, "together"), "parent_assisted_child"); assert.equal(authorizeCheckIn(parent, context, responsibility, "parent_report"), "parent_reporting_child"); assert.throws(() => authorizeCheckIn(parent, context, responsibility, null), /ASSISTANCE/); });
test("practitioner cannot impersonate assignee", () => assert.throws(() => authorizeCheckIn(owner, context, responsibility, null)));
test("reminder status does not confer checkin authority", () => { const r = { ...responsibility, assistedByParentAccountIds: [] }; assert.throws(() => authorizeCheckIn(parent, context, r, "together")); });
test("overnight do-not-disturb handles each recipient timezone", () => { assert.equal(inDoNotDisturb("2026-09-22T19:00:00Z", preferences), true); assert.equal(inDoNotDisturb("2026-09-22T16:00:00Z", preferences), false); });
const occurrence = () => planOccurrences(responsibility, null, "2026-09-22", 1).occurrences[0]!;
test("parent gets remind-child purpose for own current grant", () => assert.deepEqual(reminderDecision(context, responsibility, occurrence(), preferences, "2026-09-22T16:00:00Z", false), { eligible: true, purpose: "remind_child", channels: ["in_app", "push"] }));
for (const [label, change] of Object.entries({ "opt-out": { practiceEnabled: false }, "no channels": { channels: [] }, "wrong person": { accountId: "unknown" } }))
    test(`reminder suppresses ${label}`, () => assert.equal(reminderDecision(context, responsibility, occurrence(), { ...preferences, ...change }, "2026-09-22T16:00:00Z", false).eligible, false));
test("completed tasks never trigger this due reminder", () => assert.equal(reminderDecision(context, responsibility, occurrence(), preferences, "2026-09-22T16:00:00Z", true).eligible, false));
test("overdue restart does not backfill old reminders", () => assert.equal(reminderDecision(context, responsibility, occurrence(), preferences, "2026-09-23T16:00:00Z", false).eligible, false));
test("lockscreen text contains no task or child details", () => { assert.equal(LOCKSCREEN_PRACTICE_NOTICE.en.includes(responsibility.instructions), false); assert.equal(LOCKSCREEN_PRACTICE_NOTICE.en.includes(child.personId), false); });
test("assisted persistence captures real account, replay and version conflict", async () => {
    let current: CheckIn | null = null;
    const receipts = new Map<string, CheckInReceipt>();
    let saves = 0;
    const repo: CheckInRepository = { async transaction(_id, fn) { return fn({ async freshFacts() { return { actor: parent, context, responsibility, occurrence: occurrence(), current }; }, async receipt(k) { return receipts.get(k) ?? null; }, async save(record, key, digest) { current = record; receipts.set(key, { record, digest }); saves++; } }); } };
    const req = { id: "check1", idempotencyKey: "key1", occurrenceId: occurrence().id, expectedRevision: 0, state: "done" as const, note: "We marked this together.", assisted: "together" as const, now: NOW };
    const result = await saveCheckIn(repo, req);
    assert.equal(result.authenticatedAccountId, parent.accountId);
    assert.equal(result.subjectPersonId, child.personId);
    assert.equal(result.authorship, "parent_assisted_child");
    await saveCheckIn(repo, req);
    assert.equal(saves, 1);
    await assert.rejects(() => saveCheckIn(repo, { ...req, note: "different" }), /IDEMPOTENCY_CONFLICT/);
    await assert.rejects(() => saveCheckIn(repo, { ...req, idempotencyKey: "key2" }), /CONFLICT/);
    assert.equal(latestCompletion([result], responsibility, occurrence().id), "done");
});
test("no record is unreported, not not-done", () => assert.equal(latestCompletion([], responsibility, occurrence().id), "unreported"));
