"use client";

import { useEffect, useRef, useState } from "react";
import { sessionInfo } from "./client.ts";

type Locale = "en" | "he";
type Member = { accountId: string; displayName: string; email: string; locale: Locale; role: "parent" | "adult_client" | "child"; state: "invited" | "active" | "revoked"; guardianRevokedAt: string | null };
type Access = { caseId: string; kind: "minor" | "adult"; childAccountsEnabled: boolean; members: Member[] };

const copy = {
  en: { title: "Case access", loading: "Loading authorized access…", failed: "Unable to confirm case access. Reload before making changes.", none: "No invited or active family access is recorded for this case.", parent: "Parent", child: "Child account", adult: "Adult client", invite: "Invite", inviteAs: "Account type", inviteConfirm: "I confirm that this invitation grants this person access to this case.", name: "Name", email: "Email", language: "Invitation language", send: "Send invitation", sent: "Invitation requested. Reload access to confirm the current state.", revoke: "Revoke access", revokeConfirm: "Confirm revoke access", cancel: "Cancel", revoked: "Access revoked. Reload access to confirm the current state.", reload: "Reload case access", review: "I reviewed current case access", caseOnly: "Parent access is case-specific. Revoking an independent child login revokes that account and its sessions.", uncertain: "The result could not be confirmed. Do not repeat the action; reload case access first.", active: "Active", invited: "Invited", revokedState: "Revoked", busy: "Working…" },
  he: { title: "גישה לתיק", loading: "טוען גישה מורשית…", failed: "לא ניתן לאשר את הגישה לתיק. יש לטעון מחדש לפני שינוי.", none: "לא נרשמה גישת משפחה מוזמנת או פעילה לתיק זה.", parent: "הורה", child: "חשבון ילד/ה", adult: "לקוח/ה בגיר/ה", invite: "הזמנה", inviteAs: "סוג החשבון", inviteConfirm: "אני מאשר/ת שהזמנה זו מעניקה לאדם זה גישה לתיק.", name: "שם", email: "דוא״ל", language: "שפת ההזמנה", send: "שליחת הזמנה", sent: "ההזמנה התבקשה. יש לטעון מחדש את הגישה כדי לאשר את המצב הנוכחי.", revoke: "ביטול גישה", revokeConfirm: "אישור ביטול הגישה", cancel: "ביטול", revoked: "הגישה בוטלה. יש לטעון מחדש את הגישה כדי לאשר את המצב הנוכחי.", reload: "טעינה מחדש של גישה לתיק", review: "עיינתי בגישה הנוכחית לתיק", caseOnly: "גישת הורה מוגבלת לתיק. ביטול חשבון ילד/ה עצמאי מבטל את החשבון ואת ההפעלות שלו.", uncertain: "לא ניתן לאשר את התוצאה. אין לחזור על הפעולה; יש לטעון מחדש את הגישה לתיק.", active: "פעיל", invited: "מוזמן", revokedState: "בוטל", busy: "מעבד…" },
} as const;

function status(locale: Locale, value: Member["state"]) { const t = copy[locale]; return value === "active" ? t.active : value === "invited" ? t.invited : t.revokedState; }

export function CaseAccess({ locale, caseId }: { locale: Locale; /** Internal case context only; never rendered as a form field. */ caseId: string }) {
  return <CaseAccessBody key={`${locale}:${caseId}`} locale={locale} caseId={caseId} />;
}

export function CaseAccessBody({ locale, caseId }: { locale: Locale; caseId: string }) {
  const t = copy[locale], mounted = useRef(false), epoch = useRef(0), inFlight = useRef(false), uncertainRef = useRef(false);
  const [access, setAccess] = useState<Access | null>(null), [error, setError] = useState(false), [busy, setBusy] = useState(false), [uncertain, setUncertain] = useState(false), [notice, setNotice] = useState(""), [name, setName] = useState(""), [email, setEmail] = useState(""), [inviteLocale, setInviteLocale] = useState<Locale>(locale), [inviteRole,setInviteRole]=useState<"parent"|"child">("parent"), [confirmedInvite, setConfirmedInvite] = useState(false), [confirmRevoke, setConfirmRevoke] = useState<string | null>(null), [revision, setRevision] = useState(0);
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; }; }, []);
  useEffect(() => { const controller = new AbortController(), current = ++epoch.current; queueMicrotask(() => { if (mounted.current && epoch.current === current && !controller.signal.aborted) { setAccess(null); setError(false); if (!uncertainRef.current) setNotice(""); setConfirmRevoke(null); } }); void fetch(`/api/identity/case-access?caseId=${encodeURIComponent(caseId)}`, { credentials: "same-origin", cache: "no-store", signal: controller.signal }).then(async response => { const payload = await response.json() as { ok?: boolean; data?: Access }; if (!response.ok || !payload.ok || !payload.data || payload.data.caseId !== caseId || !Array.isArray(payload.data.members)) throw new Error("READ_FAILED"); if (mounted.current && epoch.current === current) setAccess(payload.data); }).catch(() => { if (mounted.current && epoch.current === current && !controller.signal.aborted) setError(true); }); return () => { controller.abort(); }; }, [caseId, revision]);
  function reload() { if (!busy) setRevision(value => value + 1); }
  async function mutate(path: "/api/identity/invites/parent" | "/api/identity/invites/adult" | "/api/identity/invites/child" | "/api/identity/guardians/revoke" | "/api/identity/accounts/revoke", body: Record<string, unknown>, success: string) { if (inFlight.current || uncertainRef.current) return; inFlight.current = true; const current = epoch.current; setBusy(true); setNotice(""); try { const session = await sessionInfo(); if (!mounted.current || epoch.current !== current) return; const response = await fetch(path, { method: "POST", credentials: "same-origin", cache: "no-store", headers: { "Content-Type": "application/json", "X-CSRF-Token": session.csrfToken }, body: JSON.stringify(body) }); const payload = await response.json() as { ok?: boolean }; if (!response.ok || !payload.ok) throw new Error("MUTATION_UNCONFIRMED"); if (mounted.current && epoch.current === current) { setNotice(success); setRevision(value => value + 1); } } catch { if (mounted.current && epoch.current === current) { uncertainRef.current = true; setUncertain(true); setNotice(t.uncertain); } } finally { inFlight.current = false; if (mounted.current) setBusy(false); } }
  function invite() { if (!access || !name.trim() || !email.trim() || !confirmedInvite) return; const path=access.kind==="adult"?"/api/identity/invites/adult":inviteRole==="child"?"/api/identity/invites/child":"/api/identity/invites/parent"; void mutate(path, { caseId, displayName: name.trim(), email: email.trim(), locale: inviteLocale }, t.sent); }
  function revoke(member: Member) { if (!access || member.role === "adult_client" || member.guardianRevokedAt || confirmRevoke !== member.accountId) return; void mutate(member.role==="child"?"/api/identity/accounts/revoke":"/api/identity/guardians/revoke", member.role==="child"?{accountId:member.accountId}:{caseId,accountId:member.accountId}, t.revoked); }
  const visibleMembers = access?.members.filter(member => access.kind === "minor" ? member.role === "parent" || member.role === "child" : member.role === "adult_client") ?? [];
  return <section className="lsw-card lsw-stack" dir={locale === "he" ? "rtl" : "ltr"}><h2>{t.title}</h2>{!access && !error && <p role="status">{t.loading}</p>}{error && <p role="alert">{t.failed}</p>}{access && <><p>{access.kind === "minor" ? `${t.parent}${access.childAccountsEnabled?` / ${t.child}`:""}` : t.adult}</p>{!visibleMembers.length ? <p>{t.none}</p> : <ul>{visibleMembers.map(member => <li key={member.accountId}><strong>{member.displayName}</strong> · {member.role==="child"?t.child:member.role==="parent"?t.parent:t.adult} · {member.email} · {member.guardianRevokedAt ? t.revokedState : status(locale, member.state)}{member.role !== "adult_client" && member.state !== "revoked" && !member.guardianRevokedAt && <>{confirmRevoke === member.accountId ? <span className="lsw-actions"><button type="button" disabled={busy || uncertain} onClick={() => revoke(member)}>{busy ? t.busy : t.revokeConfirm}</button><button type="button" disabled={busy} onClick={() => setConfirmRevoke(null)}>{t.cancel}</button></span> : <button type="button" disabled={busy || uncertain} onClick={() => setConfirmRevoke(member.accountId)}>{t.revoke}</button>}</>}</li>)}</ul>}<p className="lsw-help">{t.caseOnly}</p><fieldset disabled={busy || uncertain}><legend>{t.invite}</legend>{access.kind==="minor"&&access.childAccountsEnabled?<label>{t.inviteAs}<select value={inviteRole} onChange={event=>setInviteRole(event.target.value as "parent"|"child")}><option value="parent">{t.parent}</option><option value="child">{t.child}</option></select></label>:null}<label>{t.name}<input value={name} maxLength={160} autoComplete="name" onChange={event => setName(event.target.value)} /></label><label>{t.email}<input type="email" value={email} maxLength={254} autoComplete="email" onChange={event => setEmail(event.target.value)} /></label><label>{t.language}<select value={inviteLocale} onChange={event => setInviteLocale(event.target.value as Locale)}><option value="en">English</option><option value="he">עברית</option></select></label><label><input type="checkbox" checked={confirmedInvite} onChange={event => setConfirmedInvite(event.target.checked)} />{t.inviteConfirm}</label><button type="button" disabled={!name.trim() || !email.trim() || !confirmedInvite} onClick={invite}>{t.send}</button></fieldset></>}{notice && <p role="status">{notice}</p>}{uncertain && access && <button type="button" disabled={busy} onClick={() => { uncertainRef.current = false; setUncertain(false); }}>{t.review}</button>}<button type="button" disabled={busy} onClick={reload}>{t.reload}</button></section>;
}
