import {beforeAll,afterAll,expect,test,vi} from 'vitest';import {randomBytes,randomUUID} from 'node:crypto';vi.mock('server-only',()=>({}));
import {fixture,poolStore,type Fixture} from '../calendar/fixture.ts';import {CalendarStore} from '../../../src/features/calendar/store.ts';import {InternalTaskService} from '../../../src/features/calendar/tasks.ts';import {projectCommunityTasks} from '../../../src/features/community-reply/threads.ts';import {contentDayKey} from '../../../src/features/marketing-overview/calendar-model.ts';
let f:Fixture;beforeAll(async()=>{f=await fixture();});afterAll(async()=>{await f?.pool.end();});
test('native production binder creates one encrypted uncased task, survives an unknown acknowledgement and never reopens a completed task on replay',async()=>{
 const service=new InternalTaskService(new CalendarStore(poolStore(f.pool),f.keyring,f.db.clock),randomBytes(32)),id=randomUUID(),threadId=randomUUID(),now=new Date().toISOString(),response={id,threadId,commentId:'202',parentCommentId:'101',commentUrl:'https://www.facebook.com/groups/demo/posts/10?comment_id=101&reply_comment_id=202',text:'DEMO public narrative excluded from task',postedAt:now,capturedAt:now,expiresAt:new Date(Date.now()+86400000).toISOString(),taskId:null};
 const pending=vi.fn().mockResolvedValue({responses:[response],more:false}),acknowledge=vi.fn().mockRejectedValueOnce(Error('DEMO unknown remote acknowledgement')).mockResolvedValue(undefined);
 const before=(await f.pool.query('SELECT count(*)::int n FROM ls_calendar.tasks WHERE workspace_id=$1',[f.workspaceId])).rows[0].n;
 await expect(projectCommunityTasks(f.practitioner.actor,service,{pending,acknowledge})).rejects.toThrow('DEMO unknown remote acknowledgement');expect((await f.pool.query('SELECT count(*)::int n FROM ls_calendar.tasks WHERE workspace_id=$1',[f.workspaceId])).rows[0].n).toBe(before+1);
 expect(await projectCommunityTasks(f.practitioner.actor,service,{pending,acknowledge})).toEqual({linked:1,more:false});const taskId=acknowledge.mock.calls[1]![2];const fresh=new InternalTaskService(new CalendarStore(poolStore(f.pool),f.keyring,f.db.clock),randomBytes(32));const replay=await projectCommunityTasks(f.practitioner.actor,fresh,{pending,acknowledge});expect(replay.linked).toBe(1);expect(acknowledge.mock.calls[2]![2]).toBe(taskId);
 const row=(await f.pool.query('SELECT *,due_date::text AS due FROM ls_calendar.tasks WHERE workspace_id=$1 AND id=$2',[f.workspaceId,taskId])).rows[0];expect(row.case_id).toBeNull();expect(row.note_ciphertext).toBeNull();expect(row.due).toBe(contentDayKey(now));expect(row.title_ciphertext).not.toContain('Community');expect(row.source_path_ciphertext).not.toContain(threadId);
 const task=(await service.list(f.practitioner.actor,new Date(Date.now()-86400000).toISOString(),new Date(Date.now()+86400000).toISOString(),null)).find(t=>t.id===taskId)!;await service.complete(f.practitioner.actor,task.id,randomUUID(),task.version);await projectCommunityTasks(f.practitioner.actor,service,{pending,acknowledge});expect((await f.pool.query('SELECT state FROM ls_calendar.tasks WHERE workspace_id=$1 AND id=$2',[f.workspaceId,taskId])).rows[0].state).toBe('done');expect((await f.pool.query('SELECT count(*)::int n FROM ls_calendar.task_history WHERE workspace_id=$1 AND task_id=$2',[f.workspaceId,taskId])).rows[0].n).toBe(2);
 expect((await f.pool.query('SELECT count(*)::int n FROM ls_calendar.events WHERE workspace_id=$1',[f.workspaceId])).rows[0].n).toBe(0);
});
test('wrong ordinary roles, a changed practitioner role and revoked session cannot create a Community task or acknowledge it',async()=>{
 const service=new InternalTaskService(new CalendarStore(poolStore(f.pool),f.keyring,f.db.clock),randomBytes(32)),pending=vi.fn().mockResolvedValue({responses:[],more:false}),acknowledge=vi.fn();await expect(projectCommunityTasks(f.parent.actor,service,{pending,acknowledge})).rejects.toMatchObject({code:'FORBIDDEN'});expect(pending).not.toHaveBeenCalled();
 const now=new Date().toISOString(),response={id:randomUUID(),threadId:randomUUID(),capturedAt:now},source=vi.fn().mockResolvedValue({responses:[response],more:false});await f.pool.query("UPDATE ls_identity.accounts SET role='parent' WHERE workspace_id=$1 AND id=$2",[f.workspaceId,f.practitioner.actor.id]);await expect(projectCommunityTasks(f.practitioner.actor,service,{pending:source,acknowledge})).rejects.toMatchObject({code:'FORBIDDEN'});expect(acknowledge).not.toHaveBeenCalled();await f.pool.query("UPDATE ls_identity.accounts SET role='practitioner' WHERE workspace_id=$1 AND id=$2",[f.workspaceId,f.practitioner.actor.id]);await f.pool.query('UPDATE ls_identity.sessions SET revoked_at=clock_timestamp() WHERE token_digest=$1',[f.practitioner.actor.sessionDigest]);await expect(projectCommunityTasks(f.practitioner.actor,service,{pending:source,acknowledge})).rejects.toMatchObject({code:'UNAUTHENTICATED'});expect(acknowledge).not.toHaveBeenCalled();
});
