"use client";
import './coordination.css';
import {useCallback,useEffect,useRef,useState} from 'react';
import {IdentityClientError} from '../identity/client.ts';
import {loginHref} from '../identity/login-return.ts';
import {UnsavedChangesGuard} from '../../ui/workspace/draft-guard.tsx';
import {coordinationCommand,coordinationReadback,readCoordination,saveCoordination,type CoordinationCommand} from './coordination-client.ts';
import type {CompletionMode,PracticeCoordinationPage} from './types.ts';
const words={
 en:{title:'Who completes this practice?',loading:'Loading current coordination…',me:'Me',parent:'Authorized parent',assignees:'Assigned participants',reminders:'Reminder routing candidates',routing:'Routing does not enable delivery, change anyone’s preferences or grant access.',any:'One assigned participant can report for the shared item',each:'Each assigned parent reports separately',mode:'Completion rule',save:'Save coordination',cancel:'Cancel editing',dirty:'Discard unsaved coordination changes?',future:'Changes apply prospectively, starting one minute after saving. Existing occurrences and their reports keep their original responsibility. This does not schedule practice or send a reminder.',saved:'Coordination saved and read back.',error:'Could not read current coordination. Your selections are retained.',failed:'Coordination was not saved. Your selections are retained.',uncertain:'The save result is unknown. Do not save again; check the recorded versions first. Your selections are locked and retained.',check:'Check recorded versions',discard:'I checked the versions; discard this attempt',discardUnknown:'An earlier request may still have succeeded. After checking the recorded versions, discard this retained attempt?',retry:'Read current coordination',denied:'Your account no longer has access to coordinate this practice.',auth:'Sign in again to reopen this practice.',signIn:'Sign in',history:'Recorded coordination',effective:'Effective from',none:'No coordination is recorded yet.',bounded:'Only the 20 newest versions are shown. Earlier versions remain retained.',noParticipants:'No currently authorized participant is available for this audience.'},
 he:{title:'מי משלים את התרגול הזה?',loading:'טוען את התיאום הנוכחי…',me:'אני',parent:'הורה מורשה',assignees:'משתתפים שהוקצו',reminders:'מועמדים לקבלת תזכורת',routing:'בחירת נמענים אינה מפעילה משלוח, משנה את ההעדפות שלהם או מקנה גישה.',any:'משתתף אחד שהוקצה יכול לדווח עבור הפריט המשותף',each:'כל הורה שהוקצה מדווח בנפרד',mode:'כלל ההשלמה',save:'שמירת התיאום',cancel:'ביטול עריכה',dirty:'לבטל את שינויי התיאום שטרם נשמרו?',future:'השינוי חל קדימה, החל מדקה לאחר השמירה. התרגולים והדיווחים הקיימים שומרים את האחריות המקורית. הפעולה אינה קובעת תרגול או שולחת תזכורת.',saved:'התיאום נשמר ונקרא מחדש.',error:'לא ניתן לקרוא את התיאום הנוכחי. הבחירות נשמרות כאן.',failed:'התיאום לא נשמר. הבחירות נשמרות כאן.',uncertain:'תוצאת השמירה אינה ידועה. אל תשמרו שוב; בדקו קודם את הגרסאות שנרשמו. הבחירות נעולות ונשמרות כאן.',check:'בדיקת הגרסאות שנרשמו',discard:'בדקתי את הגרסאות; ביטול ניסיון זה',discardUnknown:'ייתכן שבקשה קודמת כבר הצליחה. לאחר בדיקת הגרסאות, לבטל את הניסיון שנשמר כאן?',retry:'קריאת התיאום הנוכחי',denied:'לחשבון שלך אין עוד גישה לתיאום התרגול הזה.',auth:'יש להיכנס מחדש כדי לפתוח את התרגול.',signIn:'כניסה',history:'התיאום שנרשם',effective:'חל מתאריך',none:'עדיין לא נרשם תיאום.',bounded:'מוצגות רק 20 הגרסאות האחרונות. הגרסאות הקודמות נשמרו.',noParticipants:'אין כרגע משתתף מורשה זמין לקהל הזה.'}
} as const;
export function PracticeCoordinationWorkspace({locale,role,caseId,audienceId,assignmentId}:{locale:'en'|'he';role:'parent'|'adult_client';caseId:string;audienceId:string;assignmentId:string}){
 const t=words[locale],mounted=useRef(false),inFlight=useRef(false),[page,setPage]=useState<PracticeCoordinationPage|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[code,setCode]=useState(''),[notice,setNotice]=useState('');
 const [assignees,setAssignees]=useState<string[]>([]),[reminders,setReminders]=useState<string[]>([]),[mode,setMode]=useState<CompletionMode>('any_assignee'),[dirty,setDirty]=useState(false),[attempt,setAttempt]=useState<{command:CoordinationCommand;versionId?:string}|null>(null),[checked,setChecked]=useState(false);
 const initialize=useCallback((value:PracticeCoordinationPage)=>{const latest=value.versions[0],selected=value.role==='adult_client'?[value.ownAccountId]:latest?.assigneeAccountIds.filter(id=>value.eligibleAccountIds.includes(id))??[value.ownAccountId].filter(id=>value.eligibleAccountIds.includes(id));setAssignees(selected);setReminders(latest?.reminderCandidateAccountIds.filter(id=>selected.includes(id))??[]);setMode(selected.length===2&&latest?.completionMode==='each_assignee'?'each_assignee':'any_assignee');},[]);
 useEffect(()=>{mounted.current=true;const controller=new AbortController();void readCoordination(assignmentId,caseId,audienceId,controller.signal).then(value=>{if(!controller.signal.aborted){if(value.role!==role)throw new IdentityClientError('NOT_FOUND');setPage(value);initialize(value);setLoading(false);}}).catch(failure=>{if(!controller.signal.aborted){setPage(null);setCode(failure instanceof IdentityClientError?failure.code:'UNAVAILABLE');setError(t.error);setLoading(false);}});return()=>{mounted.current=false;controller.abort();};},[assignmentId,caseId,audienceId,role,t.error,initialize]);
 const failed=(failure:unknown,message:string)=>{const value=failure instanceof IdentityClientError?failure.code:'UNAVAILABLE';setCode(value);setError(message);if(['UNAUTHENTICATED','FORBIDDEN','NOT_FOUND'].includes(value))setPage(null);};
 const load=async()=>{const value=await readCoordination(assignmentId,caseId,audienceId);if(value.role!==role)throw new IdentityClientError('NOT_FOUND');return value;};
 const refresh=async()=>{if(inFlight.current)return;inFlight.current=true;setBusy(true);try{const value=await load();if(!mounted.current)return;setPage(value);setChecked(true);const row=attempt?coordinationReadback(attempt.command,value,attempt.versionId):null;if(row){setAttempt(null);setDirty(false);initialize(value);setError('');setCode('');setNotice(t.saved);}else if(!attempt){setError('');setCode('');if(!dirty)initialize(value);}}catch(failure){if(mounted.current)failed(failure,t.error);}finally{inFlight.current=false;if(mounted.current)setBusy(false);}};
 const save=async()=>{if(!page||busy||attempt||inFlight.current||!assignees.length)return;const command=coordinationCommand(assignmentId,assignees,mode,reminders);let versionId:string|undefined;inFlight.current=true;setBusy(true);setError('');setNotice('');setDirty(true);try{const receipt=await saveCoordination(command,page.ownAccountId,role);versionId=receipt.versionId;const value=await load();if(!versionId||!coordinationReadback(command,value,versionId))throw new IdentityClientError('UNAVAILABLE');if(mounted.current){setPage(value);initialize(value);setDirty(false);setNotice(t.saved);}}catch(failure){if(!mounted.current)return;const uncertain=versionId!==undefined||!(failure instanceof IdentityClientError)||['UNAVAILABLE','INTERNAL'].includes(failure.code);if(uncertain){setAttempt({command,...(versionId?{versionId}:{})});setChecked(false);setError(t.uncertain);}else failed(failure,t.failed);}finally{inFlight.current=false;if(mounted.current)setBusy(false);}};
 const locked=busy||attempt!==null,denied=['UNAUTHENTICATED','NOT_FOUND','FORBIDDEN'].includes(code),base=`/${locale}/${role==='parent'?'family':'client'}/practice?`+new URLSearchParams({caseId,audienceId,assignmentId});
 return <details className="lsw-details lsw-coordination"><summary>{t.title}</summary><div className="lsw-stack"><UnsavedChangesGuard dirty={dirty||attempt!==null} message={t.dirty}/>
  {loading&&<p role="status">{t.loading}</p>}{notice&&<p role="status">{notice}</p>}{error&&<div role="alert"><p>{denied?code==='UNAUTHENTICATED'?t.auth:t.denied:error}</p>{code==='UNAUTHENTICATED'?<a href={loginHref(locale,base)}>{t.signIn}</a>:!denied&&<button type="button" className="lsw-button lsw-button--secondary" disabled={busy} onClick={()=>void refresh()}>{attempt?t.check:t.retry}</button>}{attempt&&checked&&!denied&&<button type="button" disabled={busy} onClick={()=>{if(window.confirm(t.discardUnknown)){setAttempt(null);setDirty(false);setError('');if(page)initialize(page);}}}>{t.discard}</button>}</div>}
  {page&&<><CoordinationForm locale={locale} page={page} assignees={assignees} reminders={reminders} mode={mode} locked={locked} onChange={(next,recipients,rule)=>{setAssignees(next);setReminders(recipients);setMode(rule);setDirty(true);setNotice('');}} onSave={()=>void save()} onCancel={()=>{if(!dirty||window.confirm(t.dirty)){initialize(page);setDirty(false);setError('');setNotice('');}}}/>
   <details className="lsw-details"><summary>{t.history}</summary>{!page.versions.length?<p>{t.none}</p>:<ul>{page.versions.map(row=><li key={row.versionId}><span>{row.assigneeAccountIds.map(id=>id===page.ownAccountId?t.me:page.eligibleAccountIds.includes(id)?`${t.parent} ${page.eligibleAccountIds.indexOf(id)+1}`:locale==='he'?'משתתף שהוקצה בעבר':'Previously assigned participant').join(' · ')}</span><p>{row.completionMode==='each_assignee'?t.each:t.any}</p><p>{t.effective}: <time dateTime={row.effectiveFrom}>{new Date(row.effectiveFrom).toLocaleString(locale==='he'?'he-IL':'en-GB',{timeZone:'Asia/Jerusalem'})}</time></p></li>)}</ul>}{page.hasMore&&<p>{t.bounded}</p>}</details></>}
 </div></details>;
}
export function CoordinationForm({locale,page,assignees,reminders,mode,locked,onChange,onSave,onCancel}:{locale:'en'|'he';page:PracticeCoordinationPage;assignees:readonly string[];reminders:readonly string[];mode:CompletionMode;locked:boolean;onChange:(assignees:string[],reminders:string[],mode:CompletionMode)=>void;onSave:()=>void;onCancel:()=>void}){
 const t=words[locale];return <form className="lsw-stack" onSubmit={event=>{event.preventDefault();if(!locked&&assignees.length)onSave();}}><fieldset className="lsw-stack" disabled={locked}><legend>{t.assignees}</legend>{!page.eligibleAccountIds.length&&<p>{t.noParticipants}</p>}{page.eligibleAccountIds.map((id,index)=><label className="lsw-check" key={id}><input type="checkbox" checked={assignees.includes(id)} disabled={page.role==='adult_client'} onChange={event=>{const next=event.target.checked?[...assignees,id]:assignees.filter(value=>value!==id);onChange(next,reminders.filter(value=>next.includes(value)),next.length===2?mode:'any_assignee');}}/>{id===page.ownAccountId?t.me:`${t.parent} ${index+1}`}</label>)}
  {page.role==='parent'&&assignees.length===2&&<label className="lsw-field">{t.mode}<select aria-label={t.mode} value={mode} onChange={event=>onChange([...assignees],[...reminders],event.target.value as CompletionMode)}><option value="any_assignee">{t.any}</option><option value="each_assignee">{t.each}</option></select></label>}
  <fieldset className="lsw-coordination-routing"><legend>{t.reminders}</legend>{assignees.map(id=><label className="lsw-check" key={id}><input type="checkbox" checked={reminders.includes(id)} onChange={event=>onChange([...assignees],event.target.checked?[...reminders,id]:reminders.filter(value=>value!==id),mode)}/>{id===page.ownAccountId?t.me:`${t.parent} ${page.eligibleAccountIds.indexOf(id)+1}`}</label>)}<p className="lsw-help">{t.routing}</p></fieldset><p className="lsw-help">{t.future}</p><div className="lsw-actions"><button className="lsw-button lsw-button--primary" type="submit" disabled={!assignees.length}>{t.save}</button><button className="lsw-button lsw-button--secondary" type="button" onClick={onCancel}>{t.cancel}</button></div>
 </fieldset></form>;
}
