"use client";
import {useEffect,useRef,useState} from "react";
import {IdentityClientError} from "../identity/client.ts";
import {UnsavedChangesGuard} from "../../ui/workspace/draft-guard.tsx";
import type {ManagedPracticeVersion} from "./types.ts";
import {recurrenceInput,type RecurrenceCommand,type RecurrencePlan} from "./recurrence-input.ts";
import {readRecurrence,saveRecurrence,recurrenceReadback} from "./management-client.ts";
export function RecurrenceControls({locale,row,disabled,onState}:{locale:"en"|"he";row:ManagedPracticeVersion;disabled:boolean;onState:(value:{dirty:boolean;locked:boolean})=>void}){
 const he=locale==="he",word=(en:string,heb:string)=>he?heb:en,[from,setFrom]=useState(""),[to,setTo]=useState(""),[preview,setPreview]=useState<{key:string;plan:RecurrencePlan}|null>(null),[pending,setPending]=useState<{input:RecurrenceCommand;plan:RecurrencePlan}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[savedKey,setSavedKey]=useState("");
 const alive=useRef(true),active=useRef(false),controller=useRef<AbortController|null>(null),stateRef=useRef(onState);
 useEffect(()=>{stateRef.current=onState;},[onState]);
  const input={assignmentId:row.assignmentId,expectedVersionId:row.versionId,expectedSnapshotDigest:row.immutableSnapshotDigest??"",from,to},key=JSON.stringify(input),confirmed=preview?.key===key?preview.plan:null,locked=busy||pending!==null,dirty=pending!==null||Boolean(from||to)&&savedKey!==key;
 useEffect(()=>{stateRef.current({dirty,locked});},[dirty,locked]);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;controller.current?.abort();stateRef.current({dirty:false,locked:false});};},[]);
 const fail=(failure:unknown)=>{const code=failure instanceof IdentityClientError?failure.code:"UNAVAILABLE";return ['NOT_FOUND','FORBIDDEN','UNAUTHENTICATED'].includes(code)?word("Current account or case access could not be confirmed. Nothing new is scheduled; sign in or check current authorization.","לא ניתן לאשר גישה נוכחית לחשבון או לתיק. לא נקבע תרגול חדש; יש להיכנס או לבדוק הרשאות."):code==="CONFLICT"?word("The exact source or coordination changed, or a clock change needs a choice. No partial range was scheduled. Read the published schedule and prepare a fresh preview.","המקור או התיאום השתנו, או שהחלפת שעון דורשת בחירה. לא נקבע טווח חלקי. יש לבדוק את לוח הזמנים שפורסם ולהכין תצוגה חדשה."):word("The calendar could not be verified. Your dates are retained. Retry the read.","לא ניתן לאמת את היומן. התאריכים נשארו כאן; נסו לקרוא שוב.");};
 const review=async()=>{if(active.current||disabled||pending||!recurrenceInput.safeParse(input).success)return;active.current=true;setBusy(true);setError("");setPreview(null);const abort=new AbortController();controller.current=abort;try{const plan=await readRecurrence(input,row.caseId,row.audienceId,abort.signal);if(alive.current&&!abort.signal.aborted)setPreview({key,plan});}catch(failure){if(alive.current&&!abort.signal.aborted)setError(fail(failure));}finally{active.current=false;if(alive.current)setBusy(false);}};
 const finish=(attempt:{input:RecurrenceCommand;plan:RecurrencePlan})=>{setPending(null);setPreview(null);setSavedKey(JSON.stringify({assignmentId:attempt.input.assignmentId,expectedVersionId:attempt.input.expectedVersionId,expectedSnapshotDigest:attempt.input.expectedSnapshotDigest,from:attempt.input.from,to:attempt.input.to}));setError("");};
 const confirm=async(attempt=pending)=>{if(active.current||disabled||!attempt)return;active.current=true;setBusy(true);setError("");let accepted=false;try{const response=await saveRecurrence(attempt.input,row.caseId,row.audienceId);accepted=true;const {expectedPlanDigest,...read}=attempt.input;void expectedPlanDigest;const current=await readRecurrence(read,row.caseId,row.audienceId);if(!recurrenceReadback(attempt.plan,response)||!recurrenceReadback(attempt.plan,current))throw new IdentityClientError("UNAVAILABLE");if(alive.current)finish(attempt);}catch(failure){if(!alive.current)return;const uncertain=accepted||!(failure instanceof IdentityClientError)||['UNAVAILABLE','INTERNAL'].includes(failure.code);if(uncertain){setPending(attempt);setError(word("The result is unknown. Your confirmed dates are locked. Check saved calendar entries before retrying this same plan.","התוצאה טרם אושרה. התאריכים שאושרו נעולים. יש לבדוק רשומות יומן לפני ניסיון חוזר של אותה תוכנית."));}else{if(!pending)setPreview(null);setError(fail(failure));}}finally{active.current=false;if(alive.current)setBusy(false);}};
 const check=async()=>{if(active.current||!pending)return;active.current=true;setBusy(true);try{const {expectedPlanDigest,...read}=pending.input;void expectedPlanDigest;const current=await readRecurrence(read,row.caseId,row.audienceId);if(alive.current){if(recurrenceReadback(pending.plan,current))finish(pending);else setError(word("Not every confirmed entry has been read back. The same plan is retained; retry it without changing its dates or source.","טרם נקראו כל הרשומות שאושרו. אותה תוכנית נשמרת כאן; אפשר לנסות אותה שוב בלי לשנות תאריכים או מקור."));}}catch(failure){if(alive.current)setError(fail(failure));}finally{active.current=false;if(alive.current)setBusy(false);}};
 return <details className="lsw-details"><summary>{word("Schedule recurring practice","קביעת תרגול חוזר")}</summary><div className="lsw-stack"><UnsavedChangesGuard dirty={dirty} message={word("Your calendar dates or unresolved schedule would be lost. Leave this view?","תאריכי היומן או התוכנית שטרם אושרה יאבדו. לצאת מהתצוגה?")}/><form className="lsw-stack" onSubmit={event=>{event.preventDefault();if(event.currentTarget.checkValidity())void review();}}><fieldset disabled={disabled||locked} className="lsw-stack"><legend>{word("Review an exact date range","בדיקת טווח תאריכים מדויק")}</legend><div className="lsw-two-fields"><label className="lsw-field">{word("First date","תאריך ראשון")}<input type="date" required min={row.startsOn} max={row.endsOn??undefined} value={from} onChange={event=>{setFrom(event.target.value);setPreview(null);setError("");}}/></label><label className="lsw-field">{word("Last date (included)","תאריך אחרון (כולל)")}<input type="date" required min={from||row.startsOn} max={row.endsOn??undefined} value={to} onChange={event=>{setTo(event.target.value);setPreview(null);setError("");}}/></label></div><p>{word("Up to 42 dates, using only the published weekdays and chosen time. These are practice entries, not appointments. No message is sent.","עד 42 תאריכים, רק בימים ובשעה שנבחרו בגרסה שפורסמה. אלו תרגולים, לא פגישות; לא נשלחת הודעה.")}</p><p><bdi>{row.responsibility?.localTime} · {row.responsibility?.timezone}</bdi></p><button className="lsw-button lsw-button--secondary" type="submit" disabled={!recurrenceInput.safeParse(input).success}>{word("Review calendar entries","בדיקת רשומות היומן")}</button></fieldset></form>
 {confirmed&&<section aria-label={word("Exact recurring schedule preview","תצוגה מדויקת של התרגול החוזר")}><h4>{word("Confirm this source and these calendar entries","אישור המקור ורשומות היומן האלה")}</h4><p>{word("Published version","גרסה שפורסמה")} {row.version} · <bdi>{confirmed.from} — {confirmed.to}</bdi> · {confirmed.items.length}</p><details className="lsw-details"><summary>{word("Dates and existing entries","תאריכים ורשומות קיימות")}</summary><ul>{confirmed.items.map(item=><li key={item.id}><bdi>{item.occursOn} · {confirmed.localTime} · {confirmed.timezone}</bdi> — {item.existing?word("Already recorded; kept unchanged","כבר נרשם; יישמר ללא שינוי"):word("New practice entry","תרגול חדש")}</li>)}</ul></details><div className="lsw-actions"><button className="lsw-button lsw-button--primary" disabled={disabled||locked} onClick={()=>void confirm({input:{...input,expectedPlanDigest:confirmed.planDigest},plan:confirmed})}>{word("Confirm recurring schedule","אישור התרגול החוזר")}</button><button className="lsw-button lsw-button--secondary" disabled={locked} onClick={()=>setPreview(null)}>{word("Cancel preview","ביטול התצוגה המקדימה")}</button></div></section>}
 {busy&&<p role="status">{word("Checking the exact calendar…","בודק את היומן המדויק…")}</p>}{!dirty&&savedKey===key&&<p role="status">{word("Every calendar entry was saved and read back. No provider message was sent.","כל רשומות היומן נשמרו ונקראו מחדש. לא נשלחה הודעה דרך ספק.")}</p>}{error&&<div role="alert"><p>{error}</p>{pending?<div className="lsw-actions"><button disabled={busy} onClick={()=>void check()}>{word("Check saved calendar entries","בדיקת רשומות היומן השמורות")}</button><button disabled={busy||disabled} onClick={()=>void confirm()}>{word("Retry the same confirmed schedule","ניסיון חוזר של אותה תוכנית שאושרה")}</button></div>:<button disabled={busy||disabled} onClick={()=>void review()}>{word("Retry the read","ניסיון קריאה חוזר")}</button>}</div>}</div></details>;
}
