"use client";
import type {ResponsibilityInput,ResponsibilityParticipants} from "./responsibility-input.ts";
const words={
 en:{title:"Scheduled responsibility",enable:"Set participants and an explicit schedule",client:"Child / adult practice",parent:"Parent support",actors:"Who reports this responsibility?",assist:"Parents allowed to help or report for the child",noChild:"No child login is enabled. An authorized parent can report without a child device.",noActors:"No authorized participants are available in this audience.",time:"Chosen local time",zone:"Time zone",origin:"Time selected by",practitioner:"Practitioner",agreement:"Session agreement",days:"Days of the week",morning:"Morning practice",evening:"Evening practice",period:"Practice period",completion:"Completion rule",any:"One assigned person reports",each:"Each of the two parents reports",routing:"Reminder recipients (not reporting permission)",none:"No reminder",self:"My responsibility",support:"Parent support",childReminder:"Remind the child",fold:"If this time repeats when clocks change",unresolved:"Require a choice before scheduling",earlier:"Earlier occurrence",later:"Later occurrence",effects:"A date range and chosen time are required. Saving a draft does not schedule, send or publish anything.",notRecorded:"Participant and time were not recorded for this older version.",schedule:"Schedule one occurrence",date:"Occurrence date",scheduled:"Scheduled and read back.",cancelFuture:"Publishing a revision cancels only unreported future timed occurrences; earlier results stay unchanged."},
 he:{title:"אחריות מתוזמנת",enable:"הגדרת משתתפים ולוח זמנים מפורש",client:"תרגול לילד או לבוגר",parent:"תמיכת הורים",actors:"מי מדווח על האחריות הזאת?",assist:"הורים מורשים לסייע או לדווח עבור הילד",noChild:"לא הופעלה כניסה לילד. הורה מורשה יכול לדווח בלי מכשיר של הילד.",noActors:"אין משתתפים מורשים זמינים בקהל הזה.",time:"שעה מקומית שנבחרה",zone:"אזור זמן",origin:"מקור בחירת השעה",practitioner:"איש המקצוע",agreement:"סיכום במפגש",days:"ימי השבוע",morning:"תרגול בוקר",evening:"תרגול ערב",period:"זמן התרגול",completion:"כלל ההשלמה",any:"דיווח של משתתף מוגדר אחד",each:"כל אחד משני ההורים מדווח",routing:"נמעני תזכורת — לא הרשאת דיווח",none:"ללא תזכורת",self:"האחריות שלי",support:"תמיכת הורה",childReminder:"תזכורת לילד",fold:"אם השעה חוזרת בעת החלפת שעון",unresolved:"דרישת בחירה לפני קביעת המועד",earlier:"המופע המוקדם",later:"המופע המאוחר",effects:"יש לבחור טווח תאריכים ושעה. שמירת טיוטה אינה קובעת מועד, שולחת או מפרסמת דבר.",notRecorded:"המשתתף והשעה לא תועדו בגרסה הקודמת הזאת.",schedule:"קביעת מופע אחד",date:"תאריך התרגול",scheduled:"המועד נקבע ונקרא מחדש.",cancelFuture:"פרסום גרסה חדשה מבטל רק תרגולים עתידיים מתוזמנים שטרם דווחו; תוצאות קודמות נשארות ללא שינוי."}
}as const;
export const responsibilityWords=words;
export function blankResponsibility():ResponsibilityInput{return {participant:"client",period:"morning",assigneeAccountIds:[],assistedByParentAccountIds:[],reminderRecipients:[],completionMode:"any_assignee",weekdays:[],localTime:"",timezone:"",timeOrigin:"practitioner",foldChoice:null};}
export function ResponsibilityEditor({locale,value,participants,locked,onChange}:{locale:"en"|"he";value:ResponsibilityInput;participants:ResponsibilityParticipants;locked:boolean;onChange:(value:ResponsibilityInput)=>void}){
 const t=words[locale],parents=participants.accounts.filter(row=>row.role==="parent"),subjects=participants.accounts.filter(row=>row.role=== (participants.caseKind==="minor"?"child":"adult_client"));
 const actors=value.participant==="parent"?parents:subjects;
 const label=(row:ResponsibilityParticipants["accounts"][number])=>(row.role==="parent"?(locale==="he"?"הורה":"Parent"):row.role==="child"?(locale==="he"?"ילד":"Child"):locale==="he"?"בוגר":"Adult")+" · "+row.accountId.slice(-8);
 const toggle=(ids:string[],id:string)=>ids.includes(id)?ids.filter(value=>value!==id):[...ids,id];
 return <fieldset disabled={locked} className="lsw-stack"><legend>{t.title}</legend>
  <label className="lsw-field">{t.title}<select value={value.participant} onChange={event=>onChange({...value,participant:event.target.value as ResponsibilityInput["participant"],assigneeAccountIds:[],assistedByParentAccountIds:[],reminderRecipients:[],completionMode:"any_assignee"})}><option value="client">{t.client}</option>{participants.caseKind==="minor"&&<option value="parent">{t.parent}</option>}</select></label>
  {!participants.accounts.length&&<p role="status">{t.noActors}</p>}
  <fieldset className="lsw-stack"><legend>{t.actors}</legend>{actors.map(row=><label key={row.accountId}><input type="checkbox" checked={value.assigneeAccountIds.includes(row.accountId)} onChange={()=>{const ids=toggle(value.assigneeAccountIds,row.accountId);onChange({...value,assigneeAccountIds:ids,completionMode:ids.length===2?value.completionMode:"any_assignee",reminderRecipients:value.reminderRecipients.filter(recipient=>recipient.purpose!=="self"||ids.includes(recipient.accountId))});}}/> {label(row)}</label>)}</fieldset>
  {value.participant==="client"&&participants.caseKind==="minor"&&<fieldset className="lsw-stack"><legend>{t.assist}</legend>{!subjects.length&&<p>{t.noChild}</p>}{parents.map(row=><label key={row.accountId}><input type="checkbox" checked={value.assistedByParentAccountIds.includes(row.accountId)} onChange={()=>onChange({...value,assistedByParentAccountIds:toggle(value.assistedByParentAccountIds,row.accountId)})}/> {label(row)}</label>)}</fieldset>}
  <label className="lsw-field">{t.completion}<select value={value.completionMode} onChange={event=>onChange({...value,completionMode:event.target.value as ResponsibilityInput["completionMode"]})}><option value="any_assignee">{t.any}</option>{value.participant==="parent"&&value.assigneeAccountIds.length===2&&<option value="each_assignee">{t.each}</option>}</select></label>
  <div className="lsw-two-fields"><label className="lsw-field">{t.time}<input type="time" value={value.localTime} required onChange={event=>onChange({...value,localTime:event.target.value})}/></label><label className="lsw-field">{t.zone}<input value={value.timezone} required maxLength={100} placeholder="Asia/Jerusalem" autoComplete="off" onChange={event=>onChange({...value,timezone:event.target.value})}/></label></div>
  <fieldset className="lsw-actions"><legend>{t.days}</legend>{[0,1,2,3,4,5,6].map(day=><label key={day}><input type="checkbox" checked={value.weekdays.includes(day)} onChange={()=>onChange({...value,weekdays:value.weekdays.includes(day)?value.weekdays.filter(value=>value!==day):[...value.weekdays,day].sort()})}/> {new Intl.DateTimeFormat(locale==="he"?"he-IL":"en-GB",{weekday:"short",timeZone:"UTC"}).format(new Date(Date.UTC(2026,9,4+day)))}</label>)}</fieldset>
  <label className="lsw-field">{t.period}<select value={value.period} onChange={event=>onChange({...value,period:event.target.value as ResponsibilityInput["period"]})}><option value="morning">{t.morning}</option><option value="evening">{t.evening}</option></select></label>
  <label className="lsw-field">{t.origin}<select value={value.timeOrigin} onChange={event=>onChange({...value,timeOrigin:event.target.value as ResponsibilityInput["timeOrigin"]})}><option value="practitioner">{t.practitioner}</option><option value="session_agreement">{t.agreement}</option></select></label>
  <label className="lsw-field">{t.fold}<select value={value.foldChoice??""} onChange={event=>onChange({...value,foldChoice:event.target.value?event.target.value as "earlier"|"later":null})}><option value="">{t.unresolved}</option><option value="earlier">{t.earlier}</option><option value="later">{t.later}</option></select></label>
  <fieldset className="lsw-stack"><legend>{t.routing}</legend>{participants.accounts.map(row=><label className="lsw-field" key={row.accountId}>{label(row)}<select value={value.reminderRecipients.find(recipient=>recipient.accountId===row.accountId)?.purpose??""} onChange={event=>onChange({...value,reminderRecipients:[...value.reminderRecipients.filter(recipient=>recipient.accountId!==row.accountId),...(event.target.value?[{accountId:row.accountId,purpose:event.target.value as ResponsibilityInput["reminderRecipients"][number]["purpose"]}]:[])]})}><option value="">{t.none}</option>{value.assigneeAccountIds.includes(row.accountId)&&<option value="self">{t.self}</option>}{row.role==="parent"&&<option value="support">{t.support}</option>}{row.role==="parent"&&value.participant==="client"&&<option value="remind_child">{t.childReminder}</option>}</select></label>)}</fieldset>
  <p className="lsw-help">{t.effects}</p>
 </fieldset>;
}
