/** Retained production binder + native PG. Synthetic fixture actors are NOT password-login evidence. */
import {afterEach,expect,test} from 'vitest';
import {randomBytes,randomUUID,createHash} from 'node:crypto';
import {fixture,poolStore,type Fixture} from '../calendar/fixture.ts';
import {HomePracticeService} from '../../../src/features/home-practice/service.ts';
import {CheckInService} from '../../../src/features/checkins/service.ts';
import {IdentityPreferenceService} from '../../../src/features/identity/preferences.ts';
import {IdentitySessions} from '../../../src/features/identity/session-adapter.ts';
import {PostgresIdentityRateStore} from '../../../src/features/identity/rate-store.ts';
import {durableAuditSink} from '../../../src/features/identity/history.ts';
import {PracticeReminderService} from '../../../src/features/reminders/service.ts';
import {ReminderHttp} from '../../../src/features/reminders/http.ts';
import {practiceReminderIntegrity,PRACTICE_REMINDER_SCHEMA_SHA256} from '../../../src/db/practice-reminder-integrity.ts';
import {practiceMigrationInventory} from '../home-practice/legacy-practice-fixture.ts';
import type {ResponsibilityInput} from '../../../src/features/home-practice/responsibility-input.ts';
import type {IdentityConfig} from '../../../src/features/identity/config.ts';
import type {Actor,NotificationPreference} from '../../../src/features/identity/types.ts';
import type {SqlSession} from '../../../src/features/identity/store.ts';
import {asId} from '../../../src/lib/ids.ts';
import {seal,tokenDigest} from '../../../src/features/identity/crypto.ts';
const opened:Fixture[]=[];
afterEach(async()=>{await Promise.all(opened.splice(0).map(f=>f.pool.end()));});
async function setup(demo=false){
 const f=await fixture({demoFirst:demo});opened.push(f);const store=poolStore(f.pool),base=new Date(),due=new Date(Math.ceil((base.getTime()+120000)/60000)*60000);let now=base;
 const clock={now:()=>new Date(now)},config:IdentityConfig={enabled:true,origin:'https://synthetic.example.invalid',workspaceId:f.workspaceId,csrfKey:randomBytes(32),lookupKey:randomBytes(32),rateLimitKey:randomUUID(),keyring:f.keyring,sessionSeconds:3600,childAccountsEnabled:true};
 const practice=new HomePracticeService(store,config,clock),checkins=new CheckInService(store,clock,f.keyring),preferences=new IdentityPreferenceService(store,config,clock),reminders=new PracticeReminderService(store,f.workspaceId,clock),sessions=new IdentitySessions(store,config,clock);
 const http=new ReminderHttp(config,clock,{sessions,service:reminders,limits:new PostgresIdentityRateStore(store),audit:durableAuditSink(store)});
 const responsibility:ResponsibilityInput={participant:'parent',period:'morning',assigneeAccountIds:[f.parent.actor.id,f.parentTwo.actor.id],assistedByParentAccountIds:[],reminderRecipients:[{accountId:f.parent.actor.id,purpose:'self'},{accountId:f.parentTwo.actor.id,purpose:'self'}],completionMode:'each_assignee',weekdays:[0,1,2,3,4,5,6],localTime:due.toISOString().slice(11,16),timezone:'UTC',timeOrigin:'practitioner',foldChoice:null};
 const day=due.toISOString().slice(0,10),end=new Date(due.getTime()+3*86400000).toISOString().slice(0,10);
 async function publish(r=responsibility){const saved=await practice.createDraft(f.practitioner.actor,{caseId:f.first.id,audienceId:f.first.audienceId,templateKey:'Synthetic reminder',templateVersion:'synthetic-v1',instructions:'Synthetic confidential instructions must not enter reminders',startsOn:day,endsOn:end,responsibility:r},randomUUID());await practice.publish(f.practitioner.actor,saved.assignmentId,saved.versionId,randomUUID());return saved;}
 async function schedule(r=responsibility){const saved=await publish(r),occurrence=await practice.schedule(f.practitioner.actor,{assignmentId:saved.assignmentId,occursOn:day,period:r.period},randomUUID());return{saved,occurrence};}
 const rows=async()=>(await f.pool.query('SELECT * FROM ls_notifications.notification_outbox WHERE workspace_id=$1 ORDER BY recipient_account_id,channel',[f.workspaceId])).rows;
 const deliveries=async()=>(await f.pool.query('SELECT * FROM ls_notifications.message_deliveries WHERE workspace_id=$1',[f.workspaceId])).rows;
 async function prefs(actor:Actor,patch:(row:NotificationPreference)=>NotificationPreference){await preferences.replace(actor,actor.id,(await preferences.list(actor,actor.id)).map(patch),randomUUID());}
 function request(method='GET',path:string[]=[],token:string|null=f.parent.token,body:unknown={},extra:Record<string,string>={}){const headers=new Headers({'x-forwarded-host':'synthetic.example.invalid','x-forwarded-proto':'https',...extra});if(token)headers.set('Cookie','__Host-ls-session='+token);if(method==='PATCH'){headers.set('Origin',config.origin);headers.set('Content-Type','application/json');if(!headers.has('X-CSRF-Token')&&token)headers.set('X-CSRF-Token',sessions.csrf(token));}return http.handle(new Request('http://127.0.0.1:8080/api/notifications'+(path.length?'/'+path.join('/'):'') ,{method,headers,...(method==='GET'?{}:{body:JSON.stringify(body)})}),path);}
 async function subject(role:'child'|'adult_client'){
  const personId=asId((await f.pool.query('SELECT cl.person_id FROM ls_cases.cases c JOIN ls_cases.clients cl ON cl.workspace_id=c.workspace_id AND cl.id=c.client_id WHERE c.id=$1',[f.first.id])).rows[0].person_id,'person'),id=asId(randomUUID(),'account'),token=randomBytes(32).toString('base64url'),created=base;
  if(role==='adult_client')await f.pool.query("UPDATE ls_identity.people SET kind='adult' WHERE workspace_id=$1 AND id=$2",[f.workspaceId,personId]);
  const actor:Actor={id,workspaceId:f.workspaceId,personId,role,state:'active',locale:'en',sessionDigest:tokenDigest(token),expiresAt:base.getTime()+8*3600000};
  await f.pool.query(`INSERT INTO ls_identity.accounts(id,workspace_id,role,state,locale,email_blind,email_ciphertext,email_verified_at,password_hash,created_at,updated_at) VALUES($1,$2,$3,'active','en',$4,$5,$6,'synthetic-non-login-hash',$6,$6)`,[id,f.workspaceId,role,createHash('sha256').update(id).digest('hex'),seal('synthetic-'+id+'@example.invalid',`email:${f.workspaceId}:${id}`,f.keyring),created]);
  await f.pool.query('INSERT INTO ls_identity.account_subjects(workspace_id,account_id,person_id) VALUES($1,$2,$3)',[f.workspaceId,id,personId]);await f.pool.query('INSERT INTO ls_identity.sessions(token_digest,workspace_id,account_id,created_at,expires_at) VALUES($1,$2,$3,$4,$5)',[actor.sessionDigest,f.workspaceId,id,created,new Date(actor.expiresAt)]);await f.pool.query('INSERT INTO ls_cases.audience_accounts(workspace_id,case_id,audience_id,account_id,granted_at) VALUES($1,$2,$3,$4,$5)',[f.workspaceId,f.first.id,f.first.audienceId,id,created]);return{actor,token};
 }
 return{f,store,config,clock,base,due,day,end,practice,checkins,preferences,reminders,responsibility,publish,schedule,rows,deliveries,prefs,request,subject,advance:(value=due.getTime()+1000)=>{now=new Date(value);}};
}
test('atomic exact-source clock, bounded neutral queue, concurrent replay and own durable read status',async()=>{
 const h=await setup(),{f}=h,{saved,occurrence}=await h.schedule();expect(await h.rows()).toHaveLength(8);expect((await h.rows()).every(row=>row.source_id===saved.assignmentId&&row.source_version_id===saved.versionId&&row.coordination_version_id===occurrence.coordinationVersionId&&row.due_at.toISOString()===h.due.toISOString()&&row.state==='queued')).toBe(true);
 expect(JSON.stringify(await h.rows())).not.toContain('confidential');await Promise.all([h.practice.schedule(f.practitioner.actor,{assignmentId:saved.assignmentId,occursOn:h.day,period:'morning'},randomUUID()),h.practice.schedule(f.practitioner.actor,{assignmentId:saved.assignmentId,occursOn:h.day,period:'morning'},randomUUID())]);expect(await h.rows()).toHaveLength(8);expect((await h.reminders.list(f.parent.actor)).items).toEqual([]);
 h.advance();const page=await h.reminders.list(f.parent.actor);expect(page.items).toHaveLength(1);expect(page.items[0]).toMatchObject({caseId:f.first.id,occursOn:h.day,purpose:'self',channel:'in_app',state:'available',readAt:null});expect(page.externalDeliveryActive).toBe(false);expect(await h.deliveries()).toHaveLength(1);
 expect((await h.reminders.list(f.parentTwo.actor)).items).toHaveLength(1);expect(await h.deliveries()).toHaveLength(2);const id=page.items[0]!.id,first=await h.reminders.markRead(f.parent.actor,id);h.advance(h.due.getTime()+10000);expect(await h.reminders.markRead(f.parent.actor,id)).toEqual(first);expect((await h.reminders.list(f.parent.actor)).items[0]?.readAt).toBe(first.readAt);expect(await h.deliveries()).toHaveLength(2);
 await expect(h.reminders.markRead(f.parentTwo.actor,id)).rejects.toMatchObject({code:'NOT_FOUND'});expect((await h.reminders.list(f.outsider.actor)).items).toEqual([]);expect((await h.reminders.list(f.practitioner.actor)).items).toEqual([]);
},30000);
test('each-assignee completion suppresses only its self reminder; last report closes all',async()=>{
 const h=await setup(),{f}=h,{occurrence}=await h.schedule();h.advance();await h.checkins.submit(f.parent.actor,{occurrenceId:occurrence.id,status:'not_done',idempotencyKey:randomUUID()},randomUUID());await h.reminders.processDue();expect((await h.reminders.list(f.parent.actor)).items).toEqual([]);expect((await h.reminders.list(f.parentTwo.actor)).items).toHaveLength(1);await h.checkins.submit(f.parentTwo.actor,{occurrenceId:occurrence.id,status:'done',idempotencyKey:randomUUID()},randomUUID());expect((await h.reminders.list(f.parentTwo.actor)).items).toEqual([]);expect((await h.rows()).every(row=>row.state==='suppressed')).toBe(true);
},30000);
test('any assignee closes both reminders; cancelling a real future source suppresses without sending',async()=>{
 const h=await setup(),{f}=h,{occurrence}=await h.schedule({...h.responsibility,completionMode:'any_assignee'});await h.checkins.submit(f.parent.actor,{occurrenceId:occurrence.id,status:'done',idempotencyKey:randomUUID()},randomUUID());h.advance();await h.reminders.processDue();expect((await h.rows()).every(row=>row.state==='suppressed'&&row.reason==='completed')).toBe(true);expect(await h.deliveries()).toEqual([]);
 const c=await setup(),{saved}=await c.schedule(),revised=await c.practice.revise(c.f.practitioner.actor,{assignmentId:saved.assignmentId,instructions:'Synthetic revised future practice',startsOn:c.day,endsOn:c.end},randomUUID());await c.practice.publish(c.f.practitioner.actor,saved.assignmentId,revised.versionId,randomUUID());c.advance();await c.reminders.processDue();expect((await c.rows()).every(row=>row.state==='suppressed'&&row.reason==='cancelled')).toBe(true);expect(await c.deliveries()).toEqual([]);
},30000);
test('any-assignee completion, independent opt-out and parent-without-child-device reminder rights',async()=>{
 const h=await setup(),{f}=h;await h.schedule({...h.responsibility,completionMode:'any_assignee'});await h.prefs(f.parent.actor,row=>row.eventType==='practice_due'?{...row,enabled:false}:row);await expect(h.preferences.replace(f.parent.actor,f.parentTwo.actor.id,await h.preferences.list(f.parent.actor,f.parent.actor.id),randomUUID())).rejects.toMatchObject({code:'NOT_FOUND'});h.advance();expect((await h.reminders.list(f.parent.actor)).items).toEqual([]);expect((await h.reminders.list(f.parentTwo.actor)).items).toHaveLength(1);
 const h2=await setup(),f2=h2.f,{occurrence}=await h2.schedule({...h2.responsibility,participant:'client',assigneeAccountIds:[],assistedByParentAccountIds:[f2.parent.actor.id],reminderRecipients:[{accountId:f2.parentTwo.actor.id,purpose:'remind_child'}],completionMode:'any_assignee'});h2.advance();expect((await h2.reminders.list(f2.parentTwo.actor)).items[0]?.purpose).toBe('remind_child');await expect(h2.checkins.submit(f2.parentTwo.actor,{occurrenceId:occurrence.id,status:'done',idempotencyKey:randomUUID()},randomUUID())).rejects.toMatchObject({code:'NOT_FOUND'});await h2.checkins.submit(f2.parent.actor,{occurrenceId:occurrence.id,status:'done',idempotencyKey:randomUUID(),assistance:{mode:'together',note:'Synthetic private feedback'}},randomUUID());expect((await h2.reminders.list(f2.parentTwo.actor)).items).toEqual([]);
},30000);
test.each(['child','adult_client']as const)('normal native authorization keeps optional %s reminders bound to its subject',async role=>{
 const h=await setup(),account=await h.subject(role),{f}=h;await h.schedule({...h.responsibility,participant:'client',assigneeAccountIds:[account.actor.id],assistedByParentAccountIds:role==='child'?[f.parent.actor.id]:[],reminderRecipients:[{accountId:account.actor.id,purpose:'self'}],completionMode:'any_assignee'});h.advance();expect((await h.reminders.list(account.actor)).items).toHaveLength(1);expect((await h.reminders.list(f.parent.actor)).items).toEqual([]);const response=await h.request('GET',[],account.token);expect(response.status).toBe(200);if(role==='child'){h.config.childAccountsEnabled=false;expect((await h.request('GET',[],account.token)).status).toBe(403);}expect(await h.deliveries()).toHaveLength(1);
},30000);
test.each(['guardian','audience','account','case','source']as const)('current %s revocation suppresses queued and already-available notices',async boundary=>{
 const h=await setup(),{f}=h,{saved}=await h.schedule();h.advance();const page=await h.reminders.list(f.parent.actor),id=page.items[0]!.id;
 if(boundary==='guardian')await f.pool.query('UPDATE ls_cases.case_guardians SET revoked_at=now() WHERE workspace_id=$1 AND case_id=$2 AND account_id=$3',[f.workspaceId,f.first.id,f.parent.actor.id]);
 if(boundary==='audience')await f.pool.query('UPDATE ls_cases.audience_accounts SET revoked_at=now() WHERE workspace_id=$1 AND case_id=$2 AND account_id=$3',[f.workspaceId,f.first.id,f.parent.actor.id]);
 if(boundary==='account')await f.pool.query("UPDATE ls_identity.accounts SET state='revoked' WHERE workspace_id=$1 AND id=$2",[f.workspaceId,f.parent.actor.id]);
 if(boundary==='case')await f.pool.query("UPDATE ls_cases.cases SET state='paused' WHERE workspace_id=$1 AND id=$2",[f.workspaceId,f.first.id]);
 if(boundary==='source'){const next=await h.practice.revise(f.practitioner.actor,{assignmentId:saved.assignmentId,instructions:'Synthetic revised',startsOn:h.day,endsOn:h.end},randomUUID());await h.practice.publish(f.practitioner.actor,saved.assignmentId,next.versionId,randomUUID());}
 h.advance(h.due.getTime()+360000);await h.reminders.processDue();await expect(h.reminders.markRead(f.parent.actor,id)).rejects.toMatchObject({code:boundary==='account'?'UNAUTHENTICATED':'NOT_FOUND'});if(boundary!=='account')expect((await h.reminders.list(f.parent.actor)).items).toEqual([]);expect((await h.rows()).filter(row=>row.recipient_account_id===f.parent.actor.id).every(row=>row.state==='suppressed')).toBe(true);
 const receipts=await h.deliveries();expect(receipts).toHaveLength(boundary==='case'||boundary==='source'?1:2);const own=(await h.rows()).filter(row=>row.recipient_account_id===f.parent.actor.id);expect(receipts.filter(receipt=>own.some(row=>row.id===receipt.outbox_id))).toHaveLength(1);
},30000);
test('quiet hours use own zone; channels remain explicitly blocked without external receipts; expiry never backfills',async()=>{
 const h=await setup(),{f}=h;await h.schedule();await h.prefs(f.parent.actor,row=>row.eventType==='practice_due'?{...row,enabled:true,timezone:'UTC',quietStart:'00:00',quietEnd:'23:59'}:row);h.advance();let page=await h.reminders.list(f.parent.actor);expect(page.items).toHaveLength(4);expect(page.items.filter(row=>row.channel!=='in_app').every(row=>row.state==='blocked'&&row.reason==='do_not_disturb')).toBe(true);expect(page.items.find(row=>row.channel==='in_app')?.state).toBe('available');
 await h.prefs(f.parent.actor,row=>({...row,quietStart:null,quietEnd:null}));h.advance(h.due.getTime()+360000);page=await h.reminders.list(f.parent.actor);expect(page.items.find(row=>row.channel==='email')?.reason).toBe('provider_not_configured');expect(page.items.filter(row=>row.channel==='push'||row.channel==='whatsapp').every(row=>row.reason==='channel_not_verified')).toBe(true);expect(await h.deliveries()).toHaveLength(1);
 h.advance(h.due.getTime()+3600001);await h.reminders.processDue();expect((await h.rows()).filter(row=>row.channel!=='in_app'&&row.recipient_account_id===f.parent.actor.id).every(row=>row.state==='expired')).toBe(true);
 const late=await setup();await late.schedule();late.advance(late.due.getTime()+3600001);expect((await late.reminders.list(late.f.parent.actor)).items).toEqual([]);expect(await late.deliveries()).toEqual([]);
},30000);
test('DEMO never calls external providers and real native HTTP preserves replay, denials and privacy headers',async()=>{
 const h=await setup(true),{f}=h;await h.schedule();await h.prefs(f.parent.actor,row=>row.eventType==='practice_due'?{...row,enabled:true}:row);h.advance();const response=await h.request(),data=(await response.json()).data;expect(response.status).toBe(200);expect(data.items.filter((row:{channel:string;reason:string})=>row.channel!=='in_app').every((row:{reason:string})=>row.reason==='demo_external_denied')).toBe(true);const id=data.items.find((row:{channel:string})=>row.channel==='in_app').id;
 expect((await h.request('PATCH',[id,'read'],f.parent.token,{}, {'X-CSRF-Token':'invalid'})).status).toBe(403);expect((await h.request('PATCH',[id,'read'],f.parent.token,{accountId:f.parentTwo.actor.id})).status).toBe(400);expect((await h.request('PATCH',[id,'read'],f.outsider.token)).status).toBe(404);expect((await h.request('GET',[],null)).status).toBe(401);
 const first=(await(await h.request('PATCH',[id,'read'])).json()).data;expect((await(await h.request('PATCH',[id,'read'])).json()).data).toEqual(first);expect((await(await h.request()).json()).data.items.find((row:{id:string})=>row.id===id).readAt).toBe(first.readAt);expect(await h.deliveries()).toHaveLength(1);expect(response.headers.get('Cache-Control')).toBe('private, no-store');expect(response.headers.get('Vary')).toBe('Cookie');expect(JSON.stringify(data)).not.toMatch(/confidential|email_ciphertext|token|password|transcript/);
},30000);
test('queue insertion failure rolls back occurrence/audit and cannot be masked as scheduling success',async()=>{
 const h=await setup(),{f}=h,saved=await h.publish(),name='synthetic_notice_failure_'+randomUUID().replaceAll('-','');await f.pool.query(`ALTER TABLE ls_notifications.notification_outbox ADD CONSTRAINT ${name} CHECK(workspace_id<>'${f.workspaceId}'::uuid)`);
 try{await expect(h.practice.schedule(f.practitioner.actor,{assignmentId:saved.assignmentId,occursOn:h.day,period:'morning'},randomUUID())).rejects.toThrow();expect(await h.rows()).toEqual([]);expect((await f.pool.query('SELECT count(*)::int AS count FROM ls_practice.practice_occurrences WHERE workspace_id=$1',[f.workspaceId])).rows[0].count).toBe(0);expect((await f.pool.query("SELECT count(*)::int AS count FROM ls_practice.action_history WHERE workspace_id=$1 AND action='practice_occurrence_scheduled'",[f.workspaceId])).rows[0].count).toBe(0);}finally{await f.pool.query(`ALTER TABLE ls_notifications.notification_outbox DROP CONSTRAINT ${name}`);}
 await h.practice.schedule(f.practitioner.actor,{assignmentId:saved.assignmentId,occursOn:h.day,period:'morning'},randomUUID());expect(await h.rows()).toHaveLength(8);
},30000);
test('native recurrence queues exact new rows atomically and never multiplies replayed notices',async()=>{
 const h=await setup(),{f}=h,saved=await h.publish(),source=(await h.practice.management(f.practitioner.actor,f.first.id,f.first.audienceId)).items.find(row=>row.versionId===saved.versionId)!;
 const input={assignmentId:saved.assignmentId,expectedVersionId:saved.versionId,expectedSnapshotDigest:source.immutableSnapshotDigest!,from:h.day,to:h.end},plan=await h.practice.recurrence(f.practitioner.actor,input),command={...input,expectedPlanDigest:plan.planDigest};expect(plan.items).toHaveLength(4);await Promise.all([h.practice.scheduleRange(f.practitioner.actor,command,randomUUID()),h.practice.scheduleRange(f.practitioner.actor,command,randomUUID())]);const rows=await h.rows();expect(rows).toHaveLength(32);expect(new Set(rows.map(row=>row.idempotency_key)).size).toBe(32);for(const item of plan.items)expect(rows.filter(row=>row.occurrence_id===item.id).every(row=>row.due_at.toISOString()===item.occursAt)).toBe(true);expect(await h.deliveries()).toEqual([]);
},30000);
test('bounded processor progresses without starving new rows; cursor pages have no overlap or fabricated count',async()=>{
 const h=await setup(),{f}=h;for(let i=0;i<41;i++)await h.schedule();h.advance();expect((await h.reminders.processDue()).morePending).toBe(true);let last=true;for(let i=0;i<16&&last;i++)last=(await h.reminders.processDue()).morePending;expect(last).toBe(false);expect(await h.deliveries()).toHaveLength(82);
 const first=await h.reminders.list(f.parent.actor);expect(first.items).toHaveLength(40);expect(first.nextCursor).not.toBeNull();const second=await h.reminders.list(f.parent.actor,first.nextCursor);expect(second.items).toHaveLength(1);expect(second.nextCursor).toBeNull();expect(new Set([...first.items,...second.items].map(row=>row.id)).size).toBe(41);expect((await h.reminders.list(f.outsider.actor,first.nextCursor)).items).toEqual([]);
 for(const cursor of ['', 'x'.repeat(161),Buffer.from(JSON.stringify(['not-a-date',randomUUID()])).toString('base64url')])await expect(h.reminders.list(f.parent.actor,cursor)).rejects.toMatchObject({code:'INVALID_REQUEST'});
},30000);
test('actual new PG catalog is independently observed; function/trigger/ACL drift and receipt mutation fail closed',async()=>{
 const h=await setup(),{f}=h;await h.schedule();h.advance();await h.reminders.list(f.parent.actor);const files=practiceMigrationInventory(),client=await f.pool.connect(),tx:SqlSession={query:async<R extends object>(sql:string,values:readonly unknown[]=[]) =>(await client.query<R>(sql,[...values])).rows};
 try{const proof=await practiceReminderIntegrity(tx,files);expect(proof.catalogSha256).toBe(PRACTICE_REMINDER_SCHEMA_SHA256);expect(proof.prior).toEqual({metadataAbsent:false,schemaCatalog:true,foreignKeys:true,permissions:true,reviewedFunctions:true,immutableHistory:true,referencesSound:true});expect(proof.current).toEqual({metadataAbsent:false,schemaCatalog:true,foreignKeys:true,permissions:true,reviewedFunctions:true,referencesSound:true});
  for(const [sql,key]of [["ALTER FUNCTION ls_notifications.check_delivery_scope() SECURITY DEFINER","reviewedFunctions"],["ALTER TABLE ls_notifications.notification_outbox DISABLE TRIGGER check_practice_notice_scope","schemaCatalog"],["GRANT SELECT ON ls_notifications.notification_outbox TO PUBLIC","permissions"],["GRANT EXECUTE ON FUNCTION ls_notifications.check_delivery_scope() TO PUBLIC","permissions"]]as const){await client.query('BEGIN');try{await client.query(sql);expect((await practiceReminderIntegrity(tx,files)).current[key]).toBe(false);}finally{await client.query('ROLLBACK');}}
  const row=(await h.rows())[0],receipt=(await h.deliveries())[0];await expect(f.pool.query('UPDATE ls_notifications.notification_outbox SET due_at=due_at+interval \'1 minute\' WHERE id=$1',[row.id])).rejects.toMatchObject({code:'23514'});await expect(f.pool.query('DELETE FROM ls_notifications.notification_outbox WHERE id=$1',[row.id])).rejects.toMatchObject({code:'23514'});await expect(f.pool.query('UPDATE ls_notifications.message_deliveries SET recorded_at=recorded_at+interval \'1 minute\' WHERE id=$1',[receipt.id])).rejects.toMatchObject({code:'23514'});expect(await practiceReminderIntegrity(tx,files)).toEqual(proof);
 }finally{client.release();}
},30000);
