import {afterEach,expect,test} from "vitest";
import {randomUUID} from "node:crypto";
import {fixture,poolStore,type Fixture} from "../calendar/fixture.ts";
import {SessionDatabaseService} from "../../../src/features/session-workflow/database.ts";
import {blankMetrics} from "../../../src/features/session-workflow/metrics.ts";
import {systemClock} from "../../../src/features/identity/types.ts";
const opened:Fixture[]=[];afterEach(async()=>{await Promise.all(opened.splice(0).map(item=>item.pool.end()));});
test("native session record keeps observations private and snapshots only current recipients",async()=>{
 const f=await fixture();opened.push(f);const service=new SessionDatabaseService(poolStore(f.pool),f.keyring,systemClock);
 const past=await f.seed(f.at(-24)),future=await f.seed(f.at(48));const ensured=await service.ensureForAppointment(f.practitioner.actor,f.first.id,past);
 expect(await service.ensureForAppointment(f.practitioner.actor,f.first.id,past)).toEqual(ensured);
 await expect(service.list(f.parent.actor,f.first.id)).rejects.toMatchObject({code:"NOT_FOUND"});
 await expect(service.detail(f.outsider.actor,ensured.sessionId)).rejects.toMatchObject({code:"NOT_FOUND"});
 const consentKey=randomUUID(),consentInput={signedByAccountId:f.parent.actor.id,signedAt:new Date().toISOString(),authorityState:"checked" as const,recordingAllowed:true,transcriptionAllowed:true,aiProcessingAllowed:true,childInformed:true,policyVersion:"session-recording-v1",evidence:"Synthetic signed consent evidence"},consent=await service.recordConsent(f.practitioner.actor,ensured.sessionId,consentInput,consentKey);
 expect(consent.permissionToRecord).toBe(true);expect(await service.recordConsent(f.practitioner.actor,ensured.sessionId,consentInput,consentKey)).toEqual(consent);
 expect((await service.detail(f.practitioner.actor,ensured.sessionId)).processing.permissionToRecord).toBe(true);
 const withdrawn=await service.withdrawConsent(f.practitioner.actor,ensured.sessionId,consent.version,randomUUID());expect(withdrawn.version).toBe(consent.version+1);expect((await service.detail(f.practitioner.actor,ensured.sessionId)).processing.permissionToRecord).toBe(false);
 const rawConsent=await f.pool.query("SELECT evidence_ciphertext FROM ls_sessions.recording_consents WHERE workspace_id=$1 AND case_id=$2 ORDER BY version LIMIT 1",[f.workspaceId,f.first.id]);expect(rawConsent.rows[0].evidence_ciphertext).not.toContain("Synthetic signed consent evidence");
 const values=blankMetrics();values.engagement={score:7,notObservedReason:null,note:"Synthetic private engagement note"};
 const metricKey=randomUUID(),metric=await service.saveObservations(f.practitioner.actor,ensured.sessionId,values,0,metricKey);
 expect(metric.revision).toBe(1);expect(await service.saveObservations(f.practitioner.actor,ensured.sessionId,values,0,metricKey)).toEqual(metric);
 await expect(service.saveObservations(f.practitioner.actor,ensured.sessionId,{...values,engagement:{score:8,notObservedReason:null,note:"changed"}},0,metricKey)).rejects.toMatchObject({code:"CONFLICT"});
 const raw=await f.pool.query("SELECT values_ciphertext FROM ls_sessions.practitioner_observations WHERE workspace_id=$1 AND session_id=$2",[f.workspaceId,ensured.sessionId]);expect(raw.rows[0].values_ciphertext).not.toContain("Synthetic private engagement note");
 const saved=await service.saveRecap(f.practitioner.actor,ensured.sessionId,{locale:"en",focus:["regulation"],practices:[],nextStep:"Synthetic agreed next step",expectedVersion:0},randomUUID());expect(saved.recap.attendance.state).toBe("unrecorded");expect(saved.recap.nextAppointment?.id).toBe(future);
 const detail=await service.detail(f.practitioner.actor,ensured.sessionId);expect(detail.recipients).toHaveLength(2);expect(detail.recapDigest).toMatch(/^[a-f0-9]{64}$/);
 await f.pool.query("UPDATE ls_cases.case_guardians SET revoked_at=clock_timestamp() WHERE workspace_id=$1 AND case_id=$2 AND account_id=$3",[f.workspaceId,f.first.id,f.parentTwo.actor.id]);
 await expect(service.share(f.practitioner.actor,ensured.sessionId,{expectedVersion:1,expectedDigest:detail.recapDigest!,recipientAccountIds:detail.recipients.map(item=>item.accountId)},randomUUID())).rejects.toMatchObject({code:"NOT_FOUND"});
 const refreshed=await service.detail(f.practitioner.actor,ensured.sessionId),shareKey=randomUUID();expect(refreshed.recipients).toHaveLength(1);
 const shared=await service.share(f.practitioner.actor,ensured.sessionId,{expectedVersion:1,expectedDigest:refreshed.recapDigest!,recipientAccountIds:refreshed.recipients.map(item=>item.accountId)},shareKey);
 expect(await service.share(f.practitioner.actor,ensured.sessionId,{expectedVersion:1,expectedDigest:refreshed.recapDigest!,recipientAccountIds:refreshed.recipients.map(item=>item.accountId)},shareKey)).toEqual(shared);
 const publication=await f.pool.query("SELECT p.id,count(r.account_id)::integer AS recipients,count(e.publication_id)::integer AS events FROM ls_sessions.publications p JOIN ls_sessions.publication_recipients r ON r.workspace_id=p.workspace_id AND r.publication_id=p.id JOIN ls_sessions.publication_events e ON e.workspace_id=p.workspace_id AND e.publication_id=p.id WHERE p.workspace_id=$1 AND p.id=$2 GROUP BY p.id",[f.workspaceId,shared.publicationId]);expect(publication.rows[0]).toMatchObject({recipients:1,events:1});
 expect(await service.sharedRecaps(f.parent.actor,f.first.id)).toHaveLength(1);
 await expect(service.sharedRecaps(f.outsider.actor,f.first.id)).rejects.toMatchObject({code:"NOT_FOUND"});
 await f.pool.query("UPDATE ls_cases.case_guardians SET revoked_at=NULL,granted_at=clock_timestamp() WHERE workspace_id=$1 AND case_id=$2 AND account_id=$3",[f.workspaceId,f.first.id,f.parentTwo.actor.id]);
 expect(await service.sharedRecaps(f.parentTwo.actor,f.first.id)).toEqual([]);
},30_000);
