/** Populated32→33: exact one CHECK replacement, not a live migration. */
import {expect,test,vi} from "vitest";
import {readFileSync} from "node:fs";
import {createHash,randomBytes,randomUUID} from "node:crypto";
import pg from "pg";
import {fixture,poolStore,safeTestUrl,type Fixture} from "../calendar/fixture.ts";
import {migrate,type MigrationClient} from "../../../src/db/migration-runner.ts";
import type {Migration} from "../../../src/db/migration-plan.ts";
import {scopedDisclosureCatalog,speakerReceiptIntegrity,SPEAKER_CORRECTION_RECEIPTS_MIGRATION} from "../../../src/db/scoped-disclosure-integrity.ts";
import type {SqlSession} from "../../../src/features/identity/store.ts";
import {SessionDatabaseService} from "../../../src/features/session-workflow/database.ts";
import {privateRecordAad,sealPrivateRecord} from "../../../src/features/session-workflow/private-records.ts";
import {systemClock} from "../../../src/features/identity/types.ts";
test("populated native speaker suffix preserves all13 tables, all32 ledger rows, catalog/ACL and old command replay",async()=>{
 const cluster=new URL(safeTestUrl());expect(["localhost","127.0.0.1","[::1]"]).toContain(cluster.hostname);const name="ls_calendar_test_speaker_upgrade_"+randomBytes(8).toString("hex");if(!/^ls_calendar_test_speaker_upgrade_[a-f0-9]{16}$/.test(name))throw Error("DISPOSABLE_NAME_REQUIRED");
 const adminUrl=new URL(cluster);adminUrl.pathname="/postgres";const dbUrl=new URL(cluster);dbUrl.pathname="/"+name;
 const admin=new pg.Pool({connectionString:adminUrl.toString(),ssl:false,max:1}),pool=new pg.Pool({connectionString:dbUrl.toString(),ssl:false,max:1});let created=false,client:pg.PoolClient|undefined,f:Fixture|undefined;
 try{await admin.query(`CREATE DATABASE "${name}"`);created=true;client=await pool.connect();
  const manifest=JSON.parse(readFileSync(new URL("../../../migrations/manifest.json",import.meta.url),"utf8")) as {name:string;sha256:string}[],inventory:Migration[]=manifest.map(row=>{const sql=readFileSync(new URL(`../../../migrations/${row.name}`,import.meta.url),"utf8");expect(createHash("sha256").update(sql).digest("hex")).toBe(row.sha256);return {name:row.name,checksum:row.sha256,sql};});
  // This retained test proves the historical populated32→33 boundary. Later
  // suffixes have separate populated-upgrade and final native coverage.
  const end=inventory.findIndex(row=>row.name===SPEAKER_CORRECTION_RECEIPTS_MIGRATION.name);expect(end).toBe(32);const files=inventory.slice(0,end+1);expect(files).toHaveLength(33);expect(files.at(-1)?.name).toBe(SPEAKER_CORRECTION_RECEIPTS_MIGRATION.name);
  const runner:MigrationClient={query:async(sql,args)=>client!.query(sql,args?[...args]:undefined)},tx:SqlSession={query:async <R extends object>(sql:string,args:readonly unknown[]=[]) => (await client!.query<R>(sql,[...args])).rows};expect(await migrate(runner,files.slice(0,-1),false)).toEqual({applied:32,pending:0});vi.stubEnv("TEST_DATABASE_URL",dbUrl.toString());vi.stubEnv("LS_CALENDAR_TEST_ALLOW","true");f=await fixture();
  const service=new SessionDatabaseService(poolStore(f.pool),f.keyring,systemClock),sessionId=(await service.ensureForAppointment(f.practitioner.actor,f.first.id,await f.seed(f.at(-24)))).sessionId,key=randomUUID(),input={signedByAccountId:f.parent.actor.id,signedAt:f.at(-48),authorityState:"needs_review" as const,recordingAllowed:false,transcriptionAllowed:false,aiProcessingAllowed:false,childInformed:false,policyVersion:"DEMO-upgrade",evidence:"DEMO — Synthetic original encrypted receipt",expectedVersion:0},consent=await service.recordConsent(f.practitioner.actor,sessionId,input,key);
  const tables=(await client.query<{name:string}>("SELECT tablename AS name FROM pg_tables WHERE schemaname='ls_sessions' ORDER BY tablename")).rows;expect(tables).toHaveLength(13);for(const row of tables)expect(row.name).toMatch(/^[a-z_]+$/);
  const snapshot=async()=>{const data:Record<string,unknown>={};for(const {name:table}of tables)data[table]=(await client!.query(`SELECT to_jsonb(t) AS row FROM ls_sessions.${table} t ORDER BY to_jsonb(t)::text`)).rows;return data;};const before=await snapshot(),ledger=(await client.query("SELECT * FROM ls_control.migrations ORDER BY name")).rows,catalog=await scopedDisclosureCatalog(tx);
  const old={baselineOperation:false,currentOperation:true,schemaCatalog:true,foreignKeys:true,permissions:true},pending={prior:old,current:{...old,currentOperation:false}},applied={prior:{...old,currentOperation:false},current:old};expect(await speakerReceiptIntegrity(tx,files)).toEqual(pending);
  const newKey=randomUUID(),cipher=sealPrivateRecord({version:1,revision:1,recordedAt:f.at(-1)},privateRecordAad("speakers",{workspaceId:f.workspaceId,caseId:f.first.id,sessionId},1),f.keyring),insert="INSERT INTO ls_sessions.command_receipts(workspace_id,case_id,session_id,actor_account_id,operation,idempotency_key,body_digest,result_ciphertext) VALUES($1,$2,$3,$4,'save_speakers',$5,$6,$7)",args=[f.workspaceId,f.first.id,sessionId,f.practitioner.actor.id,newKey,'a'.repeat(64),cipher];
  await expect(client.query(insert,args)).rejects.toMatchObject({code:"23514"});expect(await snapshot()).toEqual(before);
  expect(await migrate(runner,files,false)).toEqual({applied:1,pending:0});expect(await snapshot()).toEqual(before);expect((await client.query("SELECT * FROM ls_control.migrations WHERE name<>$1 ORDER BY name",[SPEAKER_CORRECTION_RECEIPTS_MIGRATION.name])).rows).toEqual(ledger);expect((await scopedDisclosureCatalog(tx)).sha256).toBe(catalog.sha256);expect(await speakerReceiptIntegrity(tx,files)).toEqual(applied);expect(await service.recordConsent(f.practitioner.actor,sessionId,input,key)).toEqual(consent);expect(await migrate(runner,files,true)).toEqual({applied:0,pending:0});expect(await migrate(runner,files,false)).toEqual({applied:0,pending:0});
  for(const [sql,key]of [["ALTER TABLE ls_sessions.transcripts ADD COLUMN drift text","schemaCatalog"],["GRANT SELECT ON ls_sessions.transcripts TO PUBLIC","permissions"],["ALTER TABLE ls_sessions.command_receipts DROP CONSTRAINT command_receipts_operation_check","currentOperation"],["ALTER TABLE ls_sessions.transcripts DISABLE TRIGGER ALL","foreignKeys"]]as const){await client.query("BEGIN");try{await client.query(sql);expect((await speakerReceiptIntegrity(tx,files)).current[key]).toBe(false);}finally{await client.query("ROLLBACK");}}
  expect(await speakerReceiptIntegrity(tx,files)).toEqual(applied);await client.query(insert,args);expect((await client.query("SELECT result_ciphertext FROM ls_sessions.command_receipts WHERE idempotency_key=$1",[newKey])).rows[0].result_ciphertext).toBe(cipher);
 }finally{vi.unstubAllEnvs();await f?.pool.end();client?.release();await pool.end();if(created)await admin.query(`DROP DATABASE "${name}"`);await admin.end();}
},30_000);
