import {expect,test,vi} from "vitest";
vi.mock("server-only",()=>({}));
import {audienceInterestHttp,type AudienceInterestHttpDependencies} from "../../../src/features/contact-ops/server/audience-interest-http.ts";
import {SESSION_COOKIE} from "../../../src/lib/security/session.ts";
import type {Actor} from "../../../src/features/identity/types.ts";
const origin="https://synthetic.invalid",token="a".repeat(43),csrf="b".repeat(43),actor={role:"practitioner"} as Actor;
const command={action:"record_interest" as const,topic:"bna_content" as const,state:"expressed" as const,operationId:"00000000-0000-4000-8000-000000000001",expectedEpoch:3,expectedVersion:null,displayName:"Synthetic reader",phone:"+972520000001",observedAt:"2026-10-08T10:00:00.000Z",sourceRef:"Synthetic owner note",observation:{kind:"article_request" as const,evidence:"Synthetic request"}};
const request=(method="GET",body:unknown=command,query="?expectedEpoch=3&state=all&page=1",headers:Record<string,string>={})=>new Request(`http://127.0.0.1:8080/api/private/audience-interest${method==="GET"?query:""}`,{method,headers:{cookie:`${SESSION_COOKIE}=${token}`,"x-forwarded-proto":"https","x-forwarded-host":"synthetic.invalid",...(method==="POST"?{origin,"content-type":"application/json","x-csrf-token":csrf}:{}),...headers},...(method==="POST"?{body:JSON.stringify(body)}:{})});
function dependencies(){const list=vi.fn(async()=>({items:[],total:0,page:1,pageSize:25,pages:1,authorityEpoch:3})),record=vi.fn(async()=>({personId:"00000000-0000-4000-8000-000000000002",version:1,replayed:false,authorityEpoch:3}));const d:AudienceInterestHttpDependencies={origin,actor:async()=>actor,csrf:()=>csrf,store:{list,record}};return {d,list,record};}

test("ordinary practitioner can read bounded native audience filters",async()=>{const {d,list}=dependencies(),response=await audienceInterestHttp(request(),async()=>d);expect(response.status).toBe(200);expect(list).toHaveBeenCalledWith(actor,{expectedEpoch:3,search:"",state:"all",page:1,pageSize:25});expect(response.headers.get("cache-control")).toBe("private, no-store");});
test("write requires same-origin CSRF and carries no provider or permission action",async()=>{const {d,record}=dependencies();expect((await audienceInterestHttp(request("POST"),async()=>d)).status).toBe(200);expect(record).toHaveBeenCalledWith(actor,command);for(const headers of [{origin:"https://evil.invalid"},{"x-csrf-token":"bad"},{"sec-fetch-site":"cross-site"}])expect((await audienceInterestHttp(request("POST",command,"",headers),async()=>d)).status).toBe(403);for(const body of [{...command,permission:"granted"},{...command,send:true},{...command,action:"create_prospect"}])expect((await audienceInterestHttp(request("POST",body),async()=>d)).status).toBe(400);});
test.each(["parent","child","adult_client"] as const)("%s cannot read or write the private audience",async role=>{const {d,list,record}=dependencies();d.actor=async()=>({...actor,role});expect((await audienceInterestHttp(request(),async()=>d)).status).toBe(403);expect((await audienceInterestHttp(request("POST"),async()=>d)).status).toBe(403);expect(list).not.toHaveBeenCalled();expect(record).not.toHaveBeenCalled();});
test("duplicate or coercible query keys and malformed cookies fail before the store",async()=>{const {d,list}=dependencies();for(const query of ["?expectedEpoch=03","?expectedEpoch=3&expectedEpoch=3","?expectedEpoch=3&role=practitioner","?expectedEpoch=3&page=0"])expect((await audienceInterestHttp(request("GET",command,query),async()=>d)).status).toBe(400);const missing=new Request("https://synthetic.invalid/api/private/audience-interest?expectedEpoch=3");expect((await audienceInterestHttp(missing,async()=>d)).status).toBe(401);expect(list).not.toHaveBeenCalled();});
