"use client";
import { useId, useMemo, useState } from "react";
import type { Locale } from "./types.ts";
import type { SessionDetail } from "./database.ts";
import { consentTimeCandidates, type ConsentVersion } from "./consent-contract.ts";
import { consentRecordPort, consentWithdrawalPort } from "./consent-client.ts";
import { useCommand } from "../../ui/revamp/use-command.ts";
import { UnsavedChangesGuard } from "../../ui/workspace/draft-guard.tsx";
const words = {
  en: { title: "Recording and processing consent", help: "Record the actual standing decision, signature date and document version. Check authority and known restrictions; an account appearing here does not establish that one parent's consent is sufficient. This is not a legal certification or a new waiver.", none: "No consent recorded", new: "Record new consent", signer: "Signing account", choose: "Choose the actual signer", signed: "Actual signature date and time", zone: "Signature time zone", fold: "This time occurs twice. Choose the actual offset", invalidTime: "Enter a valid past signature time and time zone. Nonexistent local times cannot be saved.", policy: "Signed document / policy version", evidence: "Authority, restrictions and signature evidence", authority: "Authority status", needs_review: "Needs review — recording disabled", checked: "Authority checked (record your basis)", restricted: "Known restriction — recording disabled", recording: "Recording allowed in the recorded decision", transcription: "Transcription allowed", ai: "AI processing allowed", informed: "Child informed where applicable", save: "Save consent version", saving: "Saving and checking…", saved: "Saved and read back from the protected record", uncertain: "The result is not yet confirmed. Your input is retained and locked. Check this same attempt before submitting anything else.", reconcile: "Check this attempt", failed: "This change was not accepted. Your input is still here. Review the actual signature fields and current authority before retrying.", conflict: "The saved consent changed. Your input is still here; read the current session before deciding whether to create a new version.", reload: "Read current session", cancel: "Cancel editing", discard: "Discard this unsaved consent input?", dirty: "There is unsaved or unconfirmed consent input. Leave this page?", withdraw: "Withdraw current consent", confirmWithdraw: "Withdraw this consent version? Recording and processing will no longer be authorized by it; the prior record is retained.", withdrawn: "Withdrawn", version: "Version", signature: "Recorded signature", login: "Sign in if needed", noSigner: "No current parent or adult signing account is authorized for this case. No child account is a recording-consent signer.", neutral: "Saving this record does not upload, send, charge or make a disclosure.", flagsOff: "Recording and processing stay disabled unless authority and every applicable permission are explicitly recorded." },
  he: { title: "הסכמה להקלטה ולעיבוד", help: "יש לתעד את ההחלטה בפועל, מועד החתימה וגרסת המסמך. יש לבדוק סמכות ומגבלות ידועות; הופעת חשבון ברשימה אינה קובעת שהסכמת הורה אחד מספיקה. זה אינו אישור משפטי או ויתור חדש.", none: "לא נרשמה הסכמה", new: "רישום הסכמה חדשה", signer: "חשבון החותם", choose: "בחירת החותם בפועל", signed: "מועד החתימה בפועל", zone: "אזור הזמן של החתימה", fold: "השעה מופיעה פעמיים. יש לבחור את ההיסט בפועל", invalidTime: "יש להזין מועד חתימה תקף בעבר ואזור זמן. אי אפשר לשמור שעה מקומית שאינה קיימת.", policy: "גרסת המסמך או המדיניות שנחתמו", evidence: "תיעוד סמכות, מגבלות ואסמכתה לחתימה", authority: "מצב הסמכות", needs_review: "נדרשת בדיקה — ההקלטה חסומה", checked: "הסמכות נבדקה (יש לתעד את הבסיס)", restricted: "קיימת מגבלה — ההקלטה חסומה", recording: "הקלטה הותרה בהחלטה שתועדה", transcription: "תמלול הותר", ai: "עיבוד AI הותר", informed: "הילד עודכן כאשר הדבר נדרש", save: "שמירת גרסת הסכמה", saving: "שומר ובודק…", saved: "נשמר ונקרא מחדש מהרשומה המוגנת", uncertain: "התוצאה עדיין לא אושרה. הקלט נשאר כאן ונעול. יש לבדוק את הניסיון הזה לפני שליחה נוספת.", reconcile: "בדיקת הניסיון הזה", failed: "השינוי לא התקבל. הקלט נשאר כאן. יש לבדוק את מועד החתימה ואת הסמכות הנוכחית לפני ניסיון נוסף.", conflict: "ההסכמה השמורה השתנתה. הקלט נשאר כאן; יש לקרוא את מצב המפגש לפני החלטה על יצירת גרסה חדשה.", reload: "קריאת מצב המפגש", cancel: "ביטול העריכה", discard: "לבטל את הקלט שטרם נשמר?", dirty: "יש קלט הסכמה שלא נשמר או שתוצאתו לא אושרה. לצאת מהעמוד?", withdraw: "ביטול ההסכמה הנוכחית", confirmWithdraw: "לבטל את גרסת ההסכמה הזאת? היא לא תתיר עוד הקלטה ועיבוד; הרשומה הקודמת נשמרת.", withdrawn: "בוטלה", version: "גרסה", signature: "החתימה שתועדה", login: "כניסה במידת הצורך", noSigner: "אין בתיק חשבון הורה או מקבל שירות בוגר מורשה לחתימה כרגע. חשבון ילד אינו חותם על הסכמה להקלטה.", neutral: "שמירת הרשומה אינה מעלה קובץ, שולחת הודעה, מחייבת תשלום או מוסרת מידע.", flagsOff: "הקלטה ועיבוד חסומים עד לתיעוד מפורש של הסמכות ושל כל ההרשאות הנדרשות." },
};
export function SessionConsentPanel(props: { locale: Locale; model: SessionDetail; refresh: () => void }) {
  return <ConsentPanelInner key={`${props.model.caseId}:${props.model.sessionId}`} {...props} />;
}
function ConsentPanelInner({ locale, model, refresh }: { locale: Locale; model: SessionDetail; refresh: () => void }) {
  const t = words[locale], titleId = useId(), current = model.processing.consent;
  const [signer, setSigner] = useState(""), [signedTime, setSignedTime] = useState(""), [timezone, setTimezone] = useState(() => Intl.DateTimeFormat().resolvedOptions().timeZone), [fold, setFold] = useState("");
  const [policy, setPolicy] = useState(current?.policyVersion ?? ""), [evidence, setEvidence] = useState(""), [authority, setAuthority] = useState<ConsentVersion["authorityState"]>("needs_review");
  const [recording, setRecording] = useState(false), [transcription, setTranscription] = useState(false), [ai, setAi] = useState(false), [informed, setInformed] = useState(false), [saved, setSaved] = useState<ConsentVersion | null>(null), [validation, setValidation] = useState(false), [open, setOpen] = useState(false);
  const scope = useMemo(() => ({ workspaceId: model.workspaceId, caseId: model.caseId, sessionId: model.sessionId }), [model.workspaceId, model.caseId, model.sessionId]);
  const recordPort = useMemo(() => consentRecordPort(scope), [scope]), withdrawalPort = useMemo(() => consentWithdrawalPort(scope), [scope]);
  const clear = () => { setSigner(""); setSignedTime(""); setFold(""); setEvidence(""); setAuthority("needs_review"); setRecording(false); setTranscription(false); setAi(false); setInformed(false); setValidation(false); };
  const record = useCommand(recordPort, value => { setSaved(value); setPolicy(value.policyVersion); clear(); setOpen(false); refresh(); }), withdraw = useCommand(withdrawalPort, value => { setSaved(value); refresh(); });
  const locked = record.locked || withdraw.locked, dirty = Boolean(signer || signedTime || evidence || policy !== (current?.policyVersion ?? "") || authority !== "needs_review" || recording || transcription || ai || informed);
  const candidates = useMemo(() => consentTimeCandidates(signedTime, timezone), [signedTime, timezone]), signedAt = candidates.length === 1 ? candidates[0] : candidates.includes(fold) ? fold : null;
  const validSigner = model.consentSigners.some(item => item.accountId === signer), active = current?.withdrawnAt === null;
  const fmt = (value: string) => new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
  const error = record.error || withdraw.error;
  return <section className="lsw-card lsw-stack lsw-consent" lang={locale} dir={locale === "he" ? "rtl" : "ltr"} aria-labelledby={titleId}>
    <UnsavedChangesGuard dirty={dirty || locked} message={t.dirty} /><h2 id={titleId}>{t.title}</h2>
    {current ? <p role="status">{t.version} {current.version} · {current.withdrawnAt ? t.withdrawn : t[current.authorityState]} · {t.signature}: <time dateTime={current.signedAt}>{fmt(current.signedAt)}</time> · <span dir="auto">{current.policyVersion}</span></p> : <p role="status">{t.none}</p>}
    {saved && !dirty && <p role="status">{t.saved} · {t.version} {saved.version}</p>}
    <details className="lsw-details" open={open} onToggle={event => setOpen(event.currentTarget.open)}><summary>{t.new}</summary>
      <p>{t.help}</p>
      {!model.consentSigners.length && <p role="alert">{t.noSigner}</p>}
      <form className="lsw-stack" onSubmit={event => { event.preventDefault(); if (locked) return; if (!signedAt || Date.parse(signedAt) > Date.now()) { setValidation(true); return; } setValidation(false); if (validSigner) void record.execute({ signedByAccountId: signer, signedAt, authorityState: authority, recordingAllowed: recording, transcriptionAllowed: transcription, aiProcessingAllowed: ai, childInformed: informed, policyVersion: policy, evidence, expectedVersion: current?.version ?? 0 }); }}>
        <fieldset className="lsw-stack" disabled={locked || !model.consentSigners.length}><legend>{t.new}</legend>
          <label className="lsw-field">{t.signer}<select aria-label={t.signer} required value={signer} onChange={event => { setSigner(event.target.value); setSaved(null); }}><option value="">{t.choose}</option>{model.consentSigners.map(item => <option key={item.accountId} value={item.accountId}>{item.name}</option>)}</select></label>
          <div className="lsw-two-fields"><label className="lsw-field">{t.signed}<input aria-label={t.signed} type="datetime-local" step="1" required value={signedTime} onChange={event => { setSignedTime(event.target.value); setFold(""); setSaved(null); }} /></label><label className="lsw-field">{t.zone}<input aria-label={t.zone} dir="ltr" required value={timezone} maxLength={100} onChange={event => { setTimezone(event.target.value); setFold(""); }} /></label></div>
          {candidates.length > 1 && <label className="lsw-field">{t.fold}<select required value={fold} onChange={event => setFold(event.target.value)}><option value="">{t.fold}</option>{candidates.map(value => <option key={value} value={value}>{new Intl.DateTimeFormat(locale, { timeZone: timezone, hour: "numeric", minute: "numeric", timeZoneName: "shortOffset" }).format(new Date(value))}</option>)}</select></label>}
          <label className="lsw-field">{t.policy}<input aria-label={t.policy} dir="auto" required maxLength={100} value={policy} onChange={event => { setPolicy(event.target.value); setSaved(null); }} /></label>
          <label className="lsw-field">{t.authority}<select aria-label={t.authority} value={authority} onChange={event => { if (["needs_review", "checked", "restricted"].includes(event.target.value)) setAuthority(event.target.value as ConsentVersion["authorityState"]); }}><option value="needs_review">{t.needs_review}</option><option value="checked">{t.checked}</option><option value="restricted">{t.restricted}</option></select></label>
          <label className="lsw-field">{t.evidence}<textarea aria-label={t.evidence} dir="auto" rows={5} required maxLength={4000} value={evidence} onChange={event => { setEvidence(event.target.value); setSaved(null); }} /></label>
          {([[recording, setRecording, t.recording], [transcription, setTranscription, t.transcription], [ai, setAi, t.ai], [informed, setInformed, t.informed]] as const).map(([checked, setChecked, label]) => <label className="lsw-choice" key={label}><input type="checkbox" checked={checked} onChange={event => setChecked(event.target.checked)} /> {label}</label>)}
          <p className="lsw-help">{t.flagsOff}</p><p className="lsw-help">{t.neutral}</p><div className="lsw-actions"><button className="lsw-button lsw-button--primary" type="submit" disabled={locked || !validSigner}>{record.phase === "pending" ? t.saving : t.save}</button><button className="lsw-button lsw-button--secondary" type="button" onClick={() => { if (!dirty || window.confirm(t.discard)) { clear(); setPolicy(current?.policyVersion ?? ""); setOpen(false); } }}>{t.cancel}</button></div>
        </fieldset>
      </form>
    </details>
    {validation && <p role="alert">{t.invalidTime}</p>}
    {error && <div role="alert"><p>{error === "CONFLICT" ? t.conflict : t.failed}</p><button className="lsw-button lsw-button--secondary" type="button" disabled={locked} onClick={refresh}>{t.reload}</button></div>}
    {(record.phase === "unknown" || withdraw.phase === "unknown") && <div role="alert"><p>{t.uncertain}</p><button className="lsw-button" type="button" onClick={() => void (record.phase === "unknown" ? record.reconcile() : withdraw.reconcile())}>{t.reconcile}</button><a href={`/${locale}/login?` + new URLSearchParams({ next: `/${locale}/app/cases/${model.caseId}/sessions/${model.sessionId}` })}>{t.login}</a></div>}
    {active && <button className="lsw-button lsw-button--secondary" type="button" disabled={locked || dirty} onClick={() => { if (window.confirm(t.confirmWithdraw)) void withdraw.execute({ expectedVersion: current.version }); }}>{withdraw.phase === "pending" ? t.saving : t.withdraw}</button>}
  </section>;
}
