"use client";
import {useEffect,useId,useMemo,useState} from "react";
import type {Locale} from "./types.ts";
import type {SessionDetail} from "./database.ts";
import {consentTimeCandidates} from "./consent-contract.ts";
import {disclosureRecordPort,disclosureRevokePort,disclosureUsePort,readDisclosures} from "./disclosure-client.ts";
import type {DisclosureInput,DisclosureView} from "./disclosure-contract.ts";
import {useCommand} from "../../ui/revamp/use-command.ts";
import {UnsavedChangesGuard} from "../../ui/workspace/draft-guard.tsx";
const copy={
 en:{title:"Scoped disclosure records",new:"Record a specific authorization",help:"Record the actual signed scope and authority, including restrictions and the document reference. An account is not proof that one parent's signature is sufficient. This is not a blanket waiver or legal certification. These records stay practitioner-private and do not send anything or unlock clinical records.",empty:"No scoped disclosure recorded for this session.",loading:"Loading protected records…",readError:"These records could not be confirmed. Previously loaded scope is not proof of current authority. Retry this read.",retry:"Retry this read",signer:"Actual signing account",choose:"Choose the actual signer",recipient:"Specific recipient",purpose:"Specific purpose",topic:"Permitted topic",basis:"Signature, document reference, authority and restrictions",authority:"Authority status",needs_review:"Needs review — use disabled",checked:"Authority checked (record your basis)",restricted:"Known restriction — use disabled",channel:"Authorized communication channel",phone:"Phone",meeting:"Meeting",secure_message:"Secure message",discussion:"Child discussion recorded where applicable",authorized:"Actual signature date and time",expires:"Authorization expires",zone:"Time zone",fold:"Choose the actual offset for this repeated time",invalid:"Enter valid times, an actual past signature and an expiry after it. Nonexistent or ambiguous local times need correction.",save:"Save scoped authorization",saved:"Saved and read back from the protected record",cancel:"Cancel editing",discard:"Discard this unsaved disclosure input?",dirty:"There is unsaved or unconfirmed disclosure input. Leave this page?",unknown:"The result is unconfirmed; input is retained and locked. Check this same attempt before submitting again.",check:"Check this attempt",failed:"The change was not accepted. Input is retained; read current authority before retrying.",conflict:"The authorization is no longer in the expected state. Input is retained. Read current records before deciding what to do.",revoke:"Revoke authorization",confirmRevoke:"Revoke this specific authorization? Its scope and any recorded use remain in history.",used:"Recorded actual use",revoked:"Revoked",inactive:"Not currently usable — check authority, expiry and recorded use",active:"Recorded scope currently eligible",use:"Record completed disclosure",confirmUse:"Record that this specific disclosure actually happened at the entered time? This does not make a call, send a message or disclose records.",usedTime:"Actual completed-disclosure date and time",signIn:"Sign in if needed"},
 he:{title:"תיעוד מסירת מידע מוגדרת",new:"רישום הרשאה מוגדרת",help:"יש לתעד את ההיקף שנחתם בפועל ואת הסמכות, כולל מגבלות והפניה למסמך. חשבון אינו ראיה לכך שחתימת הורה אחד מספיקה. זה אינו ויתור גורף או אישור משפטי. הרשומות נשארות פרטיות למטפל ואינן שולחות מידע או פותחות רשומות טיפול.",empty:"לא תועדה הרשאה מוגדרת למפגש הזה.",loading:"טוען רשומות מוגנות…",readError:"לא ניתן לאשר את הרשומות. מידע שנטען קודם אינו ראיה לסמכות נוכחית. יש לנסות קריאה חוזרת.",retry:"ניסיון קריאה חוזר",signer:"חשבון החותם בפועל",choose:"בחירת החותם בפועל",recipient:"נמען מוגדר",purpose:"מטרה מוגדרת",topic:"נושא שהותר",basis:"חתימה, הפניה למסמך, סמכות ומגבלות",authority:"מצב הסמכות",needs_review:"נדרשת בדיקה — השימוש חסום",checked:"הסמכות נבדקה (יש לתעד בסיס)",restricted:"קיימת מגבלה — השימוש חסום",channel:"ערוץ התקשורת שהותר",phone:"טלפון",meeting:"פגישה",secure_message:"הודעה מאובטחת",discussion:"תועדה שיחה עם הילד כאשר נדרש",authorized:"מועד החתימה בפועל",expires:"סיום תוקף ההרשאה",zone:"אזור הזמן",fold:"בחירת ההיסט בפועל לשעה המופיעה פעמיים",invalid:"יש להזין זמנים תקפים, חתימה בפועל בעבר ותוקף שמסתיים אחריה. יש לתקן שעה שאינה קיימת או לבחור היסט בשעה כפולה.",save:"שמירת הרשאה מוגדרת",saved:"נשמר ונקרא מחדש מהרשומה המוגנת",cancel:"ביטול העריכה",discard:"לבטל את הקלט שטרם נשמר?",dirty:"יש קלט מסירת מידע שלא נשמר או שתוצאתו לא אושרה. לצאת מהעמוד?",unknown:"התוצאה לא אושרה; הקלט נשאר כאן ונעול. יש לבדוק את הניסיון הזה לפני שליחה נוספת.",check:"בדיקת הניסיון הזה",failed:"השינוי לא התקבל. הקלט נשאר כאן; יש לקרוא את הסמכות הנוכחית לפני ניסיון נוסף.",conflict:"ההרשאה כבר אינה במצב הצפוי. הקלט נשאר כאן. יש לקרוא את הרשומות הנוכחיות לפני החלטה על המשך.",revoke:"ביטול ההרשאה",confirmRevoke:"לבטל את ההרשאה המוגדרת הזאת? ההיקף וכל שימוש שתועד נשארים בהיסטוריה.",used:"תועד שימוש בפועל",revoked:"בוטלה",inactive:"אינה ניתנת לשימוש כרגע — יש לבדוק סמכות, תוקף ושימוש שתועד",active:"ההרשאה המוגדרת כשירה כרגע",use:"תיעוד מסירה שהושלמה",confirmUse:"לתעד שמסירת המידע המוגדרת הזאת אכן התבצעה במועד שהוזן? הפעולה אינה מתקשרת, שולחת הודעה או מוסרת רשומות.",usedTime:"מועד מסירת המידע שהושלמה בפועל",signIn:"כניסה במידת הצורך"}
};
type Words=(typeof copy)[Locale];
function ActualTime({label,zone,t,value,setValue}:{label:string;zone:string;t:Words;value:string;setValue:(v:string)=>void}){const [fold,setFold]=useState(""),[local,setLocal]=useState("");const candidates=useMemo(()=>consentTimeCandidates(local,zone),[local,zone]);useEffect(()=>{setValue(candidates.length===1?candidates[0]!:candidates.includes(fold)?fold:"");},[candidates,fold,setValue]);return <><label className="lsw-field">{label}<input aria-label={label} type="datetime-local" step="1" required value={local} onChange={e=>{setLocal(e.target.value);setFold("");}}/></label>{candidates.length>1&&<label className="lsw-field">{t.fold}<select required value={fold} onChange={e=>setFold(e.target.value)}><option value="">{t.fold}</option>{candidates.map(at=><option key={at} value={at}>{new Intl.DateTimeFormat("en",{timeZone:zone,hour:"numeric",minute:"numeric",timeZoneName:"shortOffset"}).format(new Date(at))}</option>)}</select></label>}<input type="hidden" value={value}/></>;}
export function SessionDisclosurePanel(props:{locale:Locale;model:SessionDetail}){return <DisclosureInner key={`${props.model.caseId}:${props.model.sessionId}`} {...props}/>;}
function DisclosureInner({locale,model}:{locale:Locale;model:SessionDetail}){
 const t=copy[locale],title=useId(),scope=useMemo(()=>({workspaceId:model.workspaceId,caseId:model.caseId,sessionId:model.sessionId}),[model.workspaceId,model.caseId,model.sessionId]);
 const [items,setItems]=useState<DisclosureView[]|null>(null),[readError,setReadError]=useState(false),[generation,setGeneration]=useState(0),[saved,setSaved]=useState(false),[invalid,setInvalid]=useState(false),[formKey,setFormKey]=useState(0);
 const [signer,setSigner]=useState(""),[recipient,setRecipient]=useState(""),[purpose,setPurpose]=useState(""),[topic,setTopic]=useState(""),[basis,setBasis]=useState(""),[authority,setAuthority]=useState<DisclosureInput["authorityState"]>("needs_review"),[channel,setChannel]=useState<DisclosureInput["channel"]>("phone"),[discussion,setDiscussion]=useState(false),[authorizedAt,setAuthorizedAt]=useState(""),[expiresAt,setExpiresAt]=useState(""),[zone,setZone]=useState(()=>Intl.DateTimeFormat().resolvedOptions().timeZone),[open,setOpen]=useState(false);
 const refresh=()=>setGeneration(v=>v+1),port=useMemo(()=>disclosureRecordPort(scope),[scope]),clear=()=>{setSigner("");setRecipient("");setPurpose("");setTopic("");setBasis("");setAuthority("needs_review");setChannel("phone");setDiscussion(false);setAuthorizedAt("");setExpiresAt("");setFormKey(v=>v+1);setInvalid(false);};
 const command=useCommand(port,()=>{clear();setOpen(false);setSaved(true);refresh();});
 useEffect(()=>{const c=new AbortController();void readDisclosures(scope,undefined,c.signal).then(v=>{if(!c.signal.aborted){setItems(v);setReadError(false);}}).catch(error=>{if(!c.signal.aborted){setReadError(true);if(error instanceof Error&&["UNAUTHENTICATED","FORBIDDEN","NOT_FOUND"].includes(error.message))setItems(null);}});return()=>c.abort();},[scope,generation]);
 const dirty=Boolean(signer||recipient||purpose||topic||basis||authorizedAt||expiresAt||authority!=="needs_review"||channel!=="phone"||discussion);
 return <section className="lsw-card lsw-stack lsw-consent" aria-labelledby={title} lang={locale} dir={locale==="he"?"rtl":"ltr"}><h2 id={title}>{t.title}</h2><UnsavedChangesGuard dirty={dirty||command.locked} message={t.dirty}/>
  {readError&&<div role="alert"><p>{t.readError}</p><button type="button" className="lsw-button" onClick={refresh}>{t.retry}</button></div>}
  {items===null?!readError&&<p role="status">{t.loading}</p>:!items.length?<p>{t.empty}</p>:<div className="lsw-stack">{items.map(item=><DisclosureRow key={item.id} locale={locale} item={item} scope={scope} refresh={refresh} stale={readError}/>)}</div>}
  {saved&&!dirty&&<p role="status">{t.saved}</p>}
  <details className="lsw-details" open={open} onToggle={e=>setOpen(e.currentTarget.open)}><summary>{t.new}</summary><p>{t.help}</p>
   {!model.consentSigners.length&&<p role="alert">{locale==="he"?"אין כרגע בתיק חשבון הורה או מקבל שירות בוגר מורשה לחתימה. חשבון ילד אינו חותם.":"No current parent or adult signing account is authorized for this case. A child account is not a signer."}</p>}
   <form key={formKey} className="lsw-stack" onSubmit={e=>{e.preventDefault();if(command.locked)return;if(!authorizedAt||!expiresAt||Date.parse(authorizedAt)>Date.now()||Date.parse(expiresAt)<=Date.parse(authorizedAt)){setInvalid(true);return;}setInvalid(false);setSaved(false);void command.execute({recipient,purpose,topic,authorityBasis:basis,authorityState:authority,channel,authorizedByAccountId:signer,childDiscussionRecorded:discussion,authorizedAt,expiresAt});}}>
    <fieldset disabled={command.locked||!model.consentSigners.length} className="lsw-stack"><legend>{t.new}</legend>
     <label className="lsw-field">{t.signer}<select aria-label={t.signer} required value={signer} onChange={e=>setSigner(e.target.value)}><option value="">{t.choose}</option>{model.consentSigners.map(s=><option key={s.accountId} value={s.accountId}>{s.name}</option>)}</select></label>
     {([[t.recipient,recipient,setRecipient,200],[t.purpose,purpose,setPurpose,500],[t.topic,topic,setTopic,800]] as const).map(([label,value,setValue,max])=><label className="lsw-field" key={label}>{label}<textarea aria-label={label} dir="auto" required rows={2} maxLength={max} value={value} onChange={e=>setValue(e.target.value)}/></label>)}
     <label className="lsw-field">{t.basis}<textarea aria-label={t.basis} dir="auto" required rows={4} maxLength={4000} value={basis} onChange={e=>setBasis(e.target.value)}/></label>
     <label className="lsw-field">{t.authority}<select value={authority} onChange={e=>setAuthority(e.target.value as DisclosureInput["authorityState"])}>{(["needs_review","checked","restricted"] as const).map(v=><option key={v} value={v}>{t[v]}</option>)}</select></label>
     <label className="lsw-field">{t.channel}<select value={channel} onChange={e=>setChannel(e.target.value as DisclosureInput["channel"])}>{(["phone","meeting","secure_message"] as const).map(v=><option key={v} value={v}>{t[v]}</option>)}</select></label>
     <label className="lsw-choice"><input type="checkbox" checked={discussion} onChange={e=>setDiscussion(e.target.checked)}/>{t.discussion}</label>
     <label className="lsw-field">{t.zone}<input dir="ltr" required maxLength={100} value={zone} onChange={e=>setZone(e.target.value)}/></label><ActualTime label={t.authorized} zone={zone} t={t} value={authorizedAt} setValue={setAuthorizedAt}/><ActualTime label={t.expires} zone={zone} t={t} value={expiresAt} setValue={setExpiresAt}/>
     <div className="lsw-actions"><button className="lsw-button" type="submit" disabled={command.locked||!model.consentSigners.some(s=>s.accountId===signer)}>{t.save}</button><button className="lsw-button lsw-button--secondary" type="button" onClick={()=>{if(!dirty||window.confirm(t.discard)){clear();setOpen(false);}}}>{t.cancel}</button></div>
    </fieldset>
   </form>
  </details>
  {invalid&&<p role="alert">{t.invalid}</p>}{command.error&&<p role="alert">{command.error==="CONFLICT"?t.conflict:t.failed}</p>}{command.phase==="unknown"&&<div role="alert"><p>{t.unknown}</p><button className="lsw-button" type="button" onClick={()=>void command.reconcile()}>{t.check}</button></div>}
  {(command.phase==="unknown"||command.error==="UNAUTHENTICATED")&&<a href={`/${locale}/login?`+new URLSearchParams({next:`/${locale}/app/cases/${scope.caseId}/sessions/${scope.sessionId}`})}>{t.signIn}</a>}
 </section>;
}
function DisclosureRow({locale,item,scope,refresh,stale}:{locale:Locale;item:DisclosureView;scope:{workspaceId:string;caseId:string;sessionId:string};refresh:()=>void;stale:boolean}){
 const t=copy[locale],[usedAt,setUsedAt]=useState(""),[zone,setZone]=useState(()=>Intl.DateTimeFormat().resolvedOptions().timeZone),[invalid,setInvalid]=useState(false),[saved,setSaved]=useState(false),usePort=useMemo(()=>disclosureUsePort(scope,item.id),[scope,item.id]),revokePort=useMemo(()=>disclosureRevokePort(scope,item.id),[scope,item.id]);
 const used=useCommand(usePort,()=>{setUsedAt("");setSaved(true);refresh();}),revoked=useCommand(revokePort,()=>{setSaved(true);refresh();}),locked=used.locked||revoked.locked,unknown=used.phase==="unknown"||revoked.phase==="unknown",error=used.error||revoked.error;
 return <details className="lsw-details"><summary><span dir="auto">{item.recipient}</span> · {item.revokedAt?t.revoked:item.usedAt?t.used:item.effective?t.active:t.inactive}</summary><UnsavedChangesGuard dirty={Boolean(usedAt)||locked} message={t.dirty}/>
  <dl>{([[t.purpose,item.purpose],[t.topic,item.topic],[t.basis,item.authorityBasis],[t.authority,t[item.authorityState]],[t.channel,t[item.channel]],[t.authorized,item.authorizedAt],[t.expires,item.expiresAt],[t.signer,item.authorizedByAccountId],[t.used,item.usedAt],[t.revoked,item.revokedAt]] as const).filter(([,v])=>v!==null).map(([label,v])=><div key={label}><dt>{label}</dt><dd dir="auto">{v}</dd></div>)}</dl>
  {item.effective&&<form className="lsw-stack" onSubmit={e=>{e.preventDefault();if(locked||stale)return;if(!usedAt||Date.parse(usedAt)<Date.parse(item.authorizedAt)||Date.parse(usedAt)>=Date.parse(item.expiresAt)||Date.parse(usedAt)>Date.now()){setInvalid(true);return;}setInvalid(false);if(window.confirm(t.confirmUse))void used.execute({usedAt});}}><fieldset disabled={locked||stale}><legend>{t.use}</legend><label className="lsw-field">{t.zone}<input dir="ltr" required value={zone} maxLength={100} onChange={e=>setZone(e.target.value)}/></label><ActualTime label={t.usedTime} zone={zone} t={t} value={usedAt} setValue={setUsedAt}/><button type="submit" className="lsw-button">{t.use}</button></fieldset></form>}
  {!item.revokedAt&&<button type="button" className="lsw-button lsw-button--secondary" disabled={locked||stale} onClick={()=>{if(window.confirm(t.confirmRevoke))void revoked.execute({expectedUsedAt:item.usedAt});}}>{t.revoke}</button>}
  {saved&&<p role="status">{t.saved}</p>}{invalid&&<p role="alert">{t.invalid}</p>}{error&&<div role="alert"><p>{error==="CONFLICT"?t.conflict:t.failed}</p><button className="lsw-button" type="button" disabled={locked} onClick={refresh}>{t.retry}</button></div>}{unknown&&<div role="alert"><p>{t.unknown}</p><button className="lsw-button" type="button" onClick={()=>void (used.phase==="unknown"?used.reconcile():revoked.reconcile())}>{t.check}</button></div>}
 </details>;
}
