"use client";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import type {Locale} from "./types.ts";
import type {SessionDetail,SessionListItem} from "./database.ts";
import {PractitionerSessionDesk,type SessionDeskActions} from "../../ui/revamp/session-desk.tsx";
import {sessionCommand,sessionEnsure,sessionRead} from "./client.ts";
import {useCommand} from "../../ui/revamp/use-command.ts";

export function SessionListWorkspace({locale,caseId}:{locale:Locale;caseId:string}){
 const [items,setItems]=useState<SessionListItem[]|null>(null),[error,setError]=useState(false),[busy,setBusy]=useState<string|null>(null),router=useRouter(),he=locale==="he";
 useEffect(()=>{const controller=new AbortController();queueMicrotask(()=>void sessionRead<SessionListItem[]>(`?caseId=${encodeURIComponent(caseId)}`,controller.signal).then(value=>{setItems(value);setError(false);}).catch(()=>setError(true)));return()=>controller.abort();},[caseId]);
 async function open(item:SessionListItem){setBusy(item.appointmentId);try{const id=item.sessionId??(await sessionEnsure(caseId,item.appointmentId)).sessionId;router.push(`/${locale}/app/cases/${caseId}/sessions/${id}`);}catch{setError(true);}finally{setBusy(null);}}
 return <main className="lsw-main" lang={locale} dir={he?"rtl":"ltr"}><div className="lsw-breadcrumbs"><a href={`/${locale}/app/clients`}>{he?"לקוחות":"Clients"}</a><span>/</span><a href={`/${locale}/app/cases/${caseId}`}>{he?"התיק הנבחר":"Selected case"}</a><span>/</span><span>{he?"מפגשים":"Sessions"}</span></div><h1>{he?"מפגשים והקלטות":"Sessions & recordings"}</h1><p>{he?"הקלטה, תמלול, ניתוח ותצפיות נשארים פרטיים למטפל. רק עדכון שאושר במפורש משותף.":"Recording, transcript, analysis and observations remain practitioner-private. Only an explicitly approved update is shared."}</p>{error&&<p role="alert">{he?"לא ניתן לאשר את המצב. יש לטעון מחדש לפני ניסיון נוסף.":"The current state could not be confirmed. Reload before trying again."}</p>}{items===null?<p role="status">{he?"טוען…":"Loading…"}</p>:items.length?<div className="lsw-card-list">{items.map(item=><article className="lsw-card" key={item.appointmentId}><h2><time dateTime={item.startsAt}>{new Intl.DateTimeFormat(he?"he-IL":"en-IL",{dateStyle:"medium",timeStyle:"short"}).format(new Date(item.startsAt))}</time></h2><p>{item.processingState?`${item.processingState} · ${item.audioState}`:(he?"ללא הקלטה":"No recording")}</p><button type="button" disabled={busy!==null} onClick={()=>void open(item)}>{busy===item.appointmentId?(he?"פותח…":"Opening…"):(he?"פתיחת רשומת מפגש":"Open session record")}</button></article>)}</div>:<p role="status">{he?"אין פגישות יחיד בתיק הזה.":"No individual appointments are available for this case."}</p>}</main>;
}

export function SessionDetailWorkspace({locale,sessionId}:{locale:Locale;sessionId:string}){
 const [model,setModel]=useState<SessionDetail|null>(null),[error,setError]=useState(false),[revision,setRevision]=useState(0),he=locale==="he";
 useEffect(()=>{const controller=new AbortController();queueMicrotask(()=>void sessionRead<SessionDetail>(`/${sessionId}`,controller.signal).then(value=>{setModel(value);setError(false);}).catch(()=>setError(true)));return()=>controller.abort();},[sessionId,revision]);
 const actions=useMemo<SessionDeskActions>(()=>({
  async upload(){throw new Error("SESSION_PROVIDER_NOT_CONFIGURED");},
  async refresh(){setRevision(value=>value+1);},
  saveRecap:sessionCommand(`/${sessionId}/recap`),speakers:sessionCommand(`/${sessionId}/speakers`),metrics:sessionCommand(`/${sessionId}/observations`),share:sessionCommand(`/${sessionId}/share`),selectAnalysisLanguage(){setRevision(value=>value+1);},
 }),[sessionId]);
 if(error)return <main className="lsw-main"><p role="alert">{he?"רשומת המפגש אינה זמינה או שאינה מורשית.":"The session record is unavailable or unauthorized."}</p></main>;
 if(!model)return <main className="lsw-main"><p role="status">{he?"טוען רשומת מפגש…":"Loading session record…"}</p></main>;
 return <><ConsentPanel locale={locale} model={model} refresh={()=>setRevision(value=>value+1)}/><PractitionerSessionDesk locale={locale} model={model} actions={actions}/></>;
}

function ConsentPanel({locale,model,refresh}:{locale:Locale;model:SessionDetail;refresh:()=>void}){
 const he=locale==="he",[signer,setSigner]=useState(model.recipients[0]?.accountId??""),[evidence,setEvidence]=useState(""),[recording,setRecording]=useState(false),[transcription,setTranscription]=useState(false),[ai,setAi]=useState(false),[informed,setInformed]=useState(false);
 const record=useCommand(sessionCommand(`/${model.sessionId}/consent`),()=>{setEvidence("");refresh();}),withdraw=useCommand(sessionCommand(`/${model.sessionId}/consent/withdraw`),refresh),current=model.processing.consent;
 return <section className="lsw-card lsw-stack" lang={locale} dir={he?"rtl":"ltr"} aria-labelledby="recording-consent-title"><h2 id="recording-consent-title">{he?"הסכמה להקלטה ולעיבוד":"Recording and processing consent"}</h2><p>{he?"העלאה נפתחת רק לאחר רישום סמכות והסכמה בתוקף. רישום זה אינו הסמכה משפטית אוטומטית.":"Upload is enabled only after current authority and consent are recorded. This record is not an automatic legal certification."}</p>{current?<p role="status">{he?`גרסה ${current.version} · ${current.withdrawnAt?"בוטלה":current.authorityState}`:`Version ${current.version} · ${current.withdrawnAt?"withdrawn":current.authorityState}`}</p>:<p role="status">{he?"לא נרשמה הסכמה":"No consent recorded"}</p>}<details><summary>{he?"רישום הסכמה חדשה":"Record new consent"}</summary><div className="lsw-stack"><label>{he?"חותם/ת מורשה":"Authorized signer"}<select value={signer} onChange={event=>setSigner(event.target.value)}>{model.recipients.map(item=><option key={item.accountId} value={item.accountId}>{item.name}</option>)}</select></label><label>{he?"תיעוד מקור ההסכמה":"Consent evidence note"}<textarea value={evidence} maxLength={4000} onChange={event=>setEvidence(event.target.value)}/></label><label><input type="checkbox" checked={recording} onChange={event=>setRecording(event.target.checked)}/>{he?"הקלטה אושרה":"Recording approved"}</label><label><input type="checkbox" checked={transcription} onChange={event=>setTranscription(event.target.checked)}/>{he?"תמלול אושר":"Transcription approved"}</label><label><input type="checkbox" checked={ai} onChange={event=>setAi(event.target.checked)}/>{he?"עיבוד AI אושר":"AI processing approved"}</label><label><input type="checkbox" checked={informed} onChange={event=>setInformed(event.target.checked)}/>{he?"הילד/ה עודכן/ה כאשר נדרש":"Child informed when required"}</label><button type="button" disabled={record.locked||!signer||!evidence.trim()} onClick={()=>void record.execute({signedByAccountId:signer,signedAt:new Date().toISOString(),authorityState:"checked",recordingAllowed:recording,transcriptionAllowed:transcription,aiProcessingAllowed:ai,childInformed:informed,policyVersion:"session-recording-v1",evidence})}>{record.phase==="pending"?(he?"שומר…":"Saving…"):(he?"שמירת גרסת הסכמה":"Save consent version")}</button>{record.phase==="unknown"&&<button type="button" onClick={()=>void record.reconcile()}>{he?"בדיקת תוצאת השמירה":"Reconcile save result"}</button>}{record.error&&<p role="alert">{record.error}</p>}</div></details>{current&&!current.withdrawnAt&&<button type="button" disabled={withdraw.locked} onClick={()=>void withdraw.execute({expectedVersion:current.version})}>{he?"ביטול ההסכמה הנוכחית":"Withdraw current consent"}</button>}{withdraw.phase==="unknown"&&<button type="button" onClick={()=>void withdraw.reconcile()}>{he?"בדיקת תוצאת הביטול":"Reconcile withdrawal result"}</button>}{withdraw.error&&<p role="alert">{withdraw.error}</p>}</section>;
}
