/** SYNTHETIC ONLY. Do not import from production routes or persist into a live database. */
import type { ClientListItem } from "../ui/revamp/client-list.tsx";
import type { CalendarItem } from "../ui/revamp/calendar.tsx";
import type { MetricRecord } from "../features/session-workflow/metrics.ts";
import { blankMetrics, METRICS } from "../features/session-workflow/metrics.ts";
import type { MarketingSnapshot } from "../features/marketing-overview/contracts.ts";
const names = ["Aviv Cedar", "Noam Brook", "Eli Stone", "Oren Lake", "Tal Birch", "Ari Field", "Eitan Grove", "Lior Pine", "Daniel Reed", "Nadav Hill", "Yoav Spring", "Idan Vale", "Matan Sky", "Ori Dawn", "Ben River", "Amit Shore", "Gal Olive", "Shai West"];
export const SYNTHETIC_WORKSPACE_ID = "00000000-0000-4000-8000-000000000901";
export const demoClients: readonly ClientListItem[] = names.map((name, i) => ({ id: `00000000-0000-4000-8000-${String(i + 1).padStart(12, "0")}`, name: `Demo · ${name}`, mode: i % 3 === 0 ? "adult" : i % 3 === 1 ? "minor_parent_managed" : "minor_own_device", status: i === 16 ? "paused" : i === 17 ? "closed" : "active", nextAppointment: i % 5 === 0 ? null : `2026-09-${String(22 + i % 6).padStart(2, "0")}T${String(9 + i % 5).padStart(2, "0")}:00:00+03:00`, currentPractice: i % 4 === 0 ? null : ["Pause and choose", "Daily reflection", "Prepare together", "Ask an open question"][i % 4]!, unreadCount: i % 4, lastSession: `2026-09-${String(15 + i % 6).padStart(2, "0")}T10:00:00+03:00`, href: `?view=session&case=${i}` }));
export const demoCalendar: readonly CalendarItem[] = demoClients.flatMap((c, i) => [
    ...(c.nextAppointment ? [{ id: `appt-${i}`, caseId: c.id, person: c.name, title: "Individual session", kind: "appointment" as const, startsAt: c.nextAppointment, endsAt: null, href: `?view=session&case=${i}`, state: "Scheduled — synthetic" }] : []),
    ...Array.from({ length: 7 }, (_, d) => ({ id: `practice-${i}-${d}`, caseId: c.id, person: c.name, title: i % 2 ? "Home practice" : "Parent support step", kind: i % 2 ? "practice" as const : "parent_support" as const, startsAt: `2026-09-${22 + d}T19:00:00+03:00`, endsAt: null, href: `?view=practice&case=${i}`, state: d === 0 ? "No check-in yet" : "Upcoming" }))
]);
export const demoMetricHistory: readonly MetricRecord[] = Array.from({ length: 8 }, (_, i) => { const values = blankMetrics(); METRICS.forEach((m, j) => { values[m.id] = i === 3 && j === 2 ? { score: null, notObservedReason: "Not observed in this session", note: "Synthetic gap" } : { score: Math.min(9, 3 + (i + j) % 6), notObservedReason: null, note: "Synthetic practitioner observation" }; }); return { schemaVersion: 1, workspaceId: SYNTHETIC_WORKSPACE_ID, caseId: demoClients[0]!.id, sessionId: `demo-session-${i}`, recordedByAccountId: "synthetic-practitioner", source: "practitioner_observation", recordedAt: new Date(Date.UTC(2026, 7, 4 + i * 7, 10)).toISOString(), revision: 1, values }; });
export const demoMarketing: MarketingSnapshot = { source: "synthetic", fetchedAt: "2026-09-22T07:00:00Z", creatives: Array.from({ length: 9 }, (_, i) => ({ assetId: `demo-creative-${i}`, revision: 1, locale: i % 2 ? "he" : "en", width: 1080, height: i % 3 ? 1350 : 1920, imageUrl: null, title: `Mock creative ${i + 1}`, caption: "Synthetic planning example. Not approved for real publication.", contentDigest: "a".repeat(64), review: i < 3 ? "approved" : "draft", approvedDigest: i < 3 ? "a".repeat(64) : null })), publications: [{ id: "mock-post-1", assetId: "demo-creative-0", creativeRevision: 1, creativeDigest: "a".repeat(64), channel: "whatsapp_status", destinationLabel: "Synthetic Status channel", scheduledFor: "2026-09-22T17:00:00Z", timezone: "Asia/Jerusalem", state: "ready", provider: "unbound", receiptKind: "unknown", providerReceiptId: null, providerReadAt: null, postUrl: null, manualReportedAt: null, errorCode: null }, { id: "mock-post-2", assetId: "demo-creative-1", creativeRevision: 1, creativeDigest: "a".repeat(64), channel: "facebook_group_manual", destinationLabel: "Synthetic allowed advertising group", scheduledFor: "2026-09-23T17:00:00Z", timezone: "Asia/Jerusalem", state: "draft", provider: "manual", receiptKind: "unknown", providerReceiptId: null, providerReadAt: null, postUrl: null, manualReportedAt: null, errorCode: null }], ads: [{ id: "mock-ad", name: "Synthetic campaign — not connected", platform: "meta", status: "unknown", creativeAssetIds: [], currency: null, spendMinor: null, inquiries: null, asOf: null, manageUrl: null }], scout: { readyDrafts: null, sourceUrl: null, lastChecked: null, status: "unbound" } };
