import type { Locale } from "@/lib/locale.ts";

export const staffLocales = {
  he: {
    direction: "rtl", loginTitle: "פניות פרטיות — כישורי חיים", loginHelp: "כניסה למלווה מורשה בלבד.", email: "דוא״ל", password: "סיסמה", signIn: "כניסה", signOut: "יציאה", forgotPassword: "שכחתי סיסמה", forgotHelp: "הזינו את כתובת הדוא״ל של החשבון.", requestReset: "בקשת איפוס", requestingReset: "מבקשים…", resetRequestSuccess: "אם קיים חשבון מתאים, בדקו בתיבת הדואר הודעת איפוס של כישורי חיים מ־Office. הקישור תקף ל־15 דקות.", resetRequestError: "לא ניתן לשלוח את הבקשה כרגע. נסו שוב מאוחר יותר.", backToSignIn: "חזרה לכניסה", invalidEmail: "יש להזין כתובת דוא״ל תקינה.",
    activation: "הפעלת חשבון", reset: "איפוס סיסמה", newPassword: "סיסמה חדשה", confirmPassword: "אימות סיסמה", save: "שמירה", language: "שפה", hebrew: "עברית", english: "אנגלית", backToPublic: "חזרה לדף הראשי",
    privateIntake: "פניות פרטיות", manualOnly: "תיאום ידני בלבד. אין כאן קביעת פגישה או אישור תשלום.", issueTitle: "הנפקת קישור פרטי", issueHelp: "למלווה מורשה בלבד. הפעולה אינה שולחת הודעה, אינה יוצרת חשבון הורה ואינה קובעת פגישה.", stableRef: "מזהה פנייה יציב", childCount: "מספר ילדים", issuing: "מנפיקים…", issueLink: "הנפקת קישור", linkExpiry: "תוקף הקישור", copyLink: "העתקת קישור", privateLink: "קישור פרטי להעתקה ידנית", openForm: "פתיחת הטופס", uncertainIssue: "הנפקה במצב לא ודאי; אין לחזור עליה כאן.",
    received: "פניות שהתקבלו", refresh: "רענון", open: "פתיחה", updates: "עדכונים", noItems: "אין פניות להצגה.", original: "פנייה מקורית", amendment: "תיקון של מלווה מורשה", parent: "הורה", noEmail: "ללא דוא״ל", children: "ילדים", location: "מיקום", arrival: "חניה/נגישות", notSpecified: "לא צוין", availability: "זמינות", privateContext: "הקשר פרטי", additionalParent: "הורה נוסף", contactOption: "אפשרות קשר", accessNeed: "צורך בנגישות", consent: "אישור הורה", version: "גרסה", approved: "אושר", notApproved: "לא אושר", nextStep: "השלב הבא: צרו קשר בערוץ מאומת, אשרו זמן ומקום, ותעדו בנפרד אישור מועד ואימות תשלום. אין כאן פגישה מאושרת.", timezone: "Asia/Jerusalem",
    amendButton: "תיקון פרטי תיאום תוך שמירת היסטוריה", amendTitle: "תיקון פרטי תיאום בלבד", consentImmutable: "הסכמה וזהות הילד לא משתנות", preferredLocation: "מיקום מועדף", parking: "חניה ונגישות", convenientDays: "ימים נוחים", timeWindows: "חלונות זמן", availabilityNote: "הערת זמינות", saveAmendment: "שמירת תיקון", cancel: "ביטול עריכה",
    days: { sun: "א׳", mon: "ב׳", tue: "ג׳", wed: "ד׳", thu: "ה׳", fri: "ו׳", sat: "ש׳" }, windows: { morning: "בוקר", afternoon: "צהריים", evening: "ערב" },
    errors: { activationLink: "קישור ההפעלה אינו זמין כרגע.", login: "לא ניתן להיכנס. נדרש חשבון מלווה מורשה.", password: "נדרש קישור תקף ושתי סיסמאות תואמות בנות 6 תווים לפחות.", activation: "לא ניתן להשלים את ההפעלה כרגע.", open: "לא ניתן לפתוח את הפנייה כעת.", refresh: "לא ניתן לרענן כרגע.", days: "יש לבחור לפחות יום וחלון זמן.", amendment: "לא ניתן לאשר שמירת תיקון. רעננו את ההיסטוריה לפני ניסיון נוסף.", issueInput: "נדרש מזהה פנייה תקין ומספר ילדים בין 1 ל־8.", issueSuccess: "נוצר קישור פרטי. העתיקו או פתחו אותו לפני שיתוף ידני בערוץ מאומת.", issueUnknown: "לא ניתן לאשר אם הקישור נוצר. אין לנסות שוב מאותו מסך; רעננו ובדקו את מצב ההנפקות מול הרשומה הפרטית.", copied: "הקישור הועתק. הוא לא נשמר בדפדפן לאחר סגירת או רענון הדף.", copyFailed: "לא ניתן להעתיק אוטומטית. אפשר לפתוח את הקישור ולשתף אותו ידנית בערוץ מאומת.", loggedOut: "נותקת.", logoutFailed: "המידע הוסר מהמסך, אך לא ניתן לאשר יציאה מהשרת. סגרו את החלון.", amendmentSuccess: "נוסף תיקון מיוחס. הפנייה המקורית וההסכמה נשמרו ללא שינוי." }
  },
  en: {
    direction: "ltr", loginTitle: "Private intake — Life Skills", loginHelp: "Authorized practitioner access only.", email: "Email", password: "Password", signIn: "Sign in", signOut: "Sign out", forgotPassword: "Forgot password?", forgotHelp: "Enter the email address for your account.", requestReset: "Request reset", requestingReset: "Requesting…", resetRequestSuccess: "If an eligible account exists, check your inbox for a Life Skills reset email from Office. The link expires in 15 minutes.", resetRequestError: "Unable to submit the request right now. Try again later.", backToSignIn: "Back to sign in", invalidEmail: "Enter a valid email address.",
    activation: "Activate account", reset: "Reset password", newPassword: "New password", confirmPassword: "Confirm password", save: "Save", language: "Language", hebrew: "Hebrew", english: "English", backToPublic: "Back to public landing page",
    privateIntake: "Private intake", manualOnly: "Manual coordination only. This screen does not book appointments or approve payment.", issueTitle: "Issue private link", issueHelp: "Authorized practitioners only. This action sends no message, creates no parent account, and books no appointment.", stableRef: "Stable intake reference", childCount: "Number of children", issuing: "Issuing…", issueLink: "Issue link", linkExpiry: "Link expires", copyLink: "Copy link", privateLink: "Private link to copy manually", openForm: "Open form", uncertainIssue: "Issuance is uncertain; do not repeat it here.",
    received: "Received intakes", refresh: "Refresh", open: "Open", updates: "updates", noItems: "No intakes to display.", original: "Original intake", amendment: "Authorized practitioner amendment", parent: "Parent", noEmail: "No email", children: "Children", location: "Location", arrival: "Parking/accessibility", notSpecified: "Not specified", availability: "Availability", privateContext: "Private context", additionalParent: "Additional parent", contactOption: "Contact option", accessNeed: "Accessibility need", consent: "Parent consent", version: "Version", approved: "Approved", notApproved: "Not approved", nextStep: "Next: contact the family through a verified channel, confirm time and place, and record appointment confirmation and payment verification separately. No appointment is confirmed here.", timezone: "Asia/Jerusalem",
    amendButton: "Amend coordination details while preserving history", amendTitle: "Amend coordination details only", consentImmutable: "Consent and child identity do not change", preferredLocation: "Preferred location", parking: "Parking and accessibility", convenientDays: "Convenient days", timeWindows: "Time windows", availabilityNote: "Availability note", saveAmendment: "Save amendment", cancel: "Cancel editing",
    days: { sun: "Sun", mon: "Mon", tue: "Tue", wed: "Wed", thu: "Thu", fri: "Fri", sat: "Sat" }, windows: { morning: "Morning", afternoon: "Afternoon", evening: "Evening" },
    errors: { activationLink: "The activation link is unavailable right now.", login: "Unable to sign in. An authorized practitioner account is required.", password: "A valid link and two matching passwords of at least 6 characters are required.", activation: "Unable to complete activation right now.", open: "Unable to open the intake right now.", refresh: "Unable to refresh right now.", days: "Select at least one day and one time window.", amendment: "Unable to confirm the amendment was saved. Refresh the history before trying again.", issueInput: "Enter a valid intake reference and between 1 and 8 children.", issueSuccess: "Private link created. Copy or open it before manually sharing through a verified channel.", issueUnknown: "Unable to confirm whether the link was created. Do not retry from this screen; refresh and check issuance status against the private record.", copied: "Link copied. It is not retained in the browser after closing or refreshing this page.", copyFailed: "Automatic copying failed. Open the link and share it manually through a verified channel.", loggedOut: "You have been signed out.", logoutFailed: "The information was removed from the screen, but server sign-out could not be confirmed. Close this window.", amendmentSuccess: "Attributed amendment added. The original intake and consent were preserved unchanged." }
  }
} as const;
export type StaffLocale = keyof typeof staffLocales;
export type StaffCopy = (typeof staffLocales)[StaffLocale];
export const staffCopy = (locale: Locale): StaffCopy => staffLocales[locale];
export const newAmendmentDays = ["sun", "mon", "tue", "wed", "thu"] as const;
export const historicalDays = ["sun", "mon", "tue", "wed", "thu", "fri", "sat"] as const;
