"use client";
import { useEffect, useRef, useState } from "react";
import { sessionInfo } from "../identity/client.ts";
import type { Locale } from "../../lib/locale.ts";
export function PrivateNotesWorkspace({ locale, caseId }: { locale: Locale; caseId: string }) {
  const he = locale === "he";
  const [body, setBody] = useState(""), [revision, setRevision] = useState(0), [busy, setBusy] = useState(true), [notice, setNotice] = useState("");
  const [loadedCase, setLoadedCase] = useState("");
  const contextReady = loadedCase === caseId;
  const epoch = useRef(0), saveAttempt = useRef<{ key: string; payload: string } | null>(null), saving = useRef(false);
  /* eslint-disable react-hooks/set-state-in-effect */
  useEffect(() => { const current = ++epoch.current; const controller = new AbortController(); saveAttempt.current = null; setLoadedCase(""); setBody(""); setRevision(0); setNotice(""); setBusy(true); void fetch(`/api/private-notes?caseId=${encodeURIComponent(caseId)}`, { cache: "no-store", credentials: "same-origin", signal: controller.signal }).then(async (response) => { if (!response.ok) throw new Error("load"); return await response.json() as { data: { body: string; revision: number } }; }).then((payload) => { if (current === epoch.current) { setBody(payload.data.body); setRevision(payload.data.revision); setLoadedCase(caseId); } }).catch(() => { if (current ===epoch.current) setNotice(he ? "לא ניתן לטעון את ההערה הפרטית." : "The private note could not be loaded."); }).finally(() => { if (current === epoch.current) setBusy(false); }); return () => { controller.abort(); if (epoch.current === current) epoch.current = current + 1; }; }, [caseId, he]);
  /* eslint-enable react-hooks/set-state-in-effect */
  async function save() { if (saving.current || !contextReady) return; saving.current = true; const current = epoch.current; const payloadFingerprint = JSON.stringify({ caseId, body, expectedRevision: revision }); if (!saveAttempt.current || saveAttempt.current.payload !== payloadFingerprint) saveAttempt.current = { key: crypto.randomUUID(), payload: payloadFingerprint }; const attempt = saveAttempt.current; setBusy(true); setNotice(""); try { const session = await sessionInfo(); const response = await fetch("/api/private-notes", { method: "POST", credentials: "same-origin", headers: { "content-type": "application/json", "X-CSRF-Token": session.csrfToken }, body: JSON.stringify({ caseId, body, expectedRevision: revision, idempotencyKey: attempt.key }) }); if (!response.ok) throw new Error("save"); const payload = await response.json() as { data: { revision: number } }; if (current === epoch.current) { setRevision(payload.data.revision); setNotice(he ? "ההערה הפרטית נשמרה." : "Private note saved."); } } catch { if (current === epoch.current) setNotice(he ? "השמירה נכשלה או שההערה השתנתה. רעננו ונסו שוב." : "Save failed or the note changed. Refresh and try again."); } finally { if (current === epoch.current) setBusy(false); saving.current = false; } }
  return <main className="lsw-main" lang={locale} dir={he ? "rtl" : "ltr"}><div className="lsw-breadcrumbs"><a href={`/${locale}/app/cases/${caseId}`}>{he ? "חזרה לתיק" : "Back to case"}</a></div><section className="lsw-card"><p className="lsw-eyebrow">{he ? "פרטי לאיש המקצוע בלבד" : "Private to practitioner only"}</p><h1>{he ? "הערות פרטיות לתיק" : "Private case notes"}</h1><p>{he ? "הערה זו מוצפנת ואינה מוצגת למשפחה או נשלחת כהודעה." : "This encrypted note is never projected to family members or sent as a message."}</p><label htmlFor="private-note">{he ? "הערה" : "Note"}</label><textarea id="private-note" value={contextReady ? body : ""} onChange={(event) => setBody(event.target.value)} maxLength={8000} disabled={busy || !contextReady} rows={12} /><button type="button" onClick={() => void save()} disabled={busy || !contextReady}>{busy ? (he ? "שומרים…" : "Saving…") : (he ? "שמירה" : "Save note")}</button>{notice && <p role="status">{notice}</p>}</section></main>;
}
