"use client";
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {formTemplateInputSchema,validateAnswers,type FormAnswers,type FormDefinition,type FormAnswer} from './schema.ts';
type Role='practitioner'|'parent'|'adult_client';
type Option={id:string;label:string};
type Template={id:string;key:string;version:number;locale:'he'|'en';targetRole:'parent'|'adult_client';definition:FormDefinition;active:boolean;state:string};
type Assignment={id:string;caseId:string;templateVersion:number;state:string;definition:FormDefinition;assignedAccountId:string};
type Submission={id:string;answers:FormAnswers;state:string;submittedAt:string};
type DraftField={key:string;kind:FormDefinition['fields'][number]['kind'];label:string;required:boolean;optionsText:string};
export interface FormsWorkspaceProps{role:Role;locale:'he'|'en';csrfToken:string;cases:readonly Option[];caseKind?:'minor'|'adult';audiences?:readonly Option[];responders?:readonly Option[];assignments?:readonly Assignment[];}
const words={en:{title:'Forms',loading:'Loading authorized forms…',empty:'No forms assigned.',error:'Could not confirm the result. Reload saved forms before proceeding.',saved:'Saved',reload:'Reload saved forms',reviewed:'I reviewed saved templates and assignments',uncertain:'This action may have succeeded. Reload and review saved items before starting another action.',new:'Author a new template version',key:'Template key',version:'Version',name:'Title',intro:'Introduction',add:'Add field',remove:'Remove field',label:'Question',kind:'Answer type',required:'Required answer',options:'Choices (one label per line)',publish:'Publish this immutable template version for assignment',create:'Save template version',template:'Published template',respondent:'Respondent',audience:'Sharing audience',private:'Practitioner-only response review',due:'Due date (optional)',assign:'Assign form',open:'Fill in',submit:'Submit answers',retry:'Retry the same submission',review:'Read answers',mark:'Mark reviewed',none:'No response submitted yet.',choose:'Choose…',yes:'Yes',no:'No',invalid:'Check the required fields and answer types.',short_text:'Short text',long_text:'Long text',single_choice:'One choice',multiple_choice:'Multiple choices',boolean:'Yes / no',date:'Date',view:'Submitted answer'},he:{title:'טפסים',loading:'טוען טפסים מורשים…',empty:'לא הוקצו טפסים.',error:'לא ניתן לאשר את התוצאה. יש לטעון את הטפסים השמורים לפני המשך.',saved:'נשמר',reload:'טעינת הטפסים השמורים',reviewed:'בדקתי את התבניות וההקצאות השמורות',uncertain:'ייתכן שהפעולה הצליחה. יש לטעון ולבדוק את הפריטים השמורים לפני פעולה נוספת.',new:'כתיבת גרסה חדשה לתבנית',key:'מפתח תבנית',version:'גרסה',name:'כותרת',intro:'הקדמה',add:'הוספת שאלה',remove:'הסרת שאלה',label:'שאלה',kind:'סוג תשובה',required:'נדרשת תשובה',options:'אפשרויות (תווית אחת בשורה)',publish:'פרסום גרסה קבועה זו להקצאה',create:'שמירת גרסת תבנית',template:'תבנית שפורסמה',respondent:'משיב/ה',audience:'קהל לשיתוף',private:'עיון בתשובות למטפל בלבד',due:'תאריך יעד (רשות)',assign:'הקצאת טופס',open:'מילוי',submit:'שליחת תשובות',retry:'ניסיון חוזר של אותה שליחה',review:'קריאת תשובות',mark:'סימון כנבדק',none:'טרם נשלחו תשובות.',choose:'בחירה…',yes:'כן',no:'לא',invalid:'יש לבדוק את השדות הנדרשים וסוגי התשובות.',short_text:'טקסט קצר',long_text:'טקסט ארוך',single_choice:'בחירה אחת',multiple_choice:'בחירה מרובה',boolean:'כן / לא',date:'תאריך',view:'תשובה שנשלחה'}} as const;
async function api<T>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{...init,credentials:'same-origin',cache:'no-store',redirect:'error'}),body=await response.json() as {ok?:boolean;data:T};if(!response.ok||body.ok!==true||!('data' in body))throw Error('UNCONFIRMED');return body.data;}
/** Parent route owns the authorized case picker. Remount all pending state when the context changes. */
export function FormsWorkspace(props:FormsWorkspaceProps){const caseId=props.cases[0]?.id;if(!caseId)return <p>{words[props.locale].empty}</p>;return <FormsCaseWorkspace key={`${props.role}:${props.locale}:${caseId}`} {...props} caseId={caseId}/>;}
export function FormsCaseWorkspace({role,locale,csrfToken,caseId,caseKind='minor',audiences=[],responders=[]}:FormsWorkspaceProps&{caseId:string}){
 const t=words[locale],practitioner=role==='practitioner',mounted=useRef(false),flight=useRef(false),nextField=useRef(1);
 const [data,setData]=useState<{revision:number;assignments:Assignment[];templates:Template[]}|null>(null),[revision,setRevision]=useState(0),[error,setError]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState<number|null>(null);
 const [template,setTemplate]=useState(''),[respondent,setRespondent]=useState(''),[audience,setAudience]=useState(''),[due,setDue]=useState('');
 const [draftKey,setDraftKey]=useState(''),[version,setVersion]=useState('1'),[title,setTitle]=useState(''),[introduction,setIntroduction]=useState(''),[fields,setFields]=useState<DraftField[]>([]),[published,setPublished]=useState(false);
 const [selected,setSelected]=useState<Assignment|null>(null),[answers,setAnswers]=useState<FormAnswers>({}),[review,setReview]=useState<{assignment:Assignment;submission:Submission}|null>(null),[submissionUncertain,setSubmissionUncertain]=useState(false);
 const pending=useRef<{assignmentId:string;answers:FormAnswers;idempotencyKey:string}|null>(null);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[]);
 useEffect(()=>{const controller=new AbortController();void Promise.all([api<Assignment[]>(`/api/forms/assignments?caseId=${encodeURIComponent(caseId)}`,{signal:controller.signal}),practitioner?api<Template[]>(`/api/forms/templates?locale=${locale}`,{signal:controller.signal}):Promise.resolve([])]).then(([assignments,templates])=>{if(!controller.signal.aborted){setData({revision,assignments,templates});setError(false)}}).catch(()=>{if(!controller.signal.aborted){setData(null);setError(true)}});return()=>controller.abort()},[caseId,locale,practitioner,revision]);
 function begin(){if(flight.current||!mounted.current)return false;flight.current=true;setBusy(true);setMessage('');return true;}
 function end(){flight.current=false;if(mounted.current)setBusy(false);}
 function headers(){return {'Content-Type':'application/json','X-CSRF-Token':csrfToken};}
 async function write(url:string,body:unknown,receipt:string|null,nonIdempotent:boolean,method='POST'){
  if((nonIdempotent&&uncertain!==null)||!begin())return false;
  try{const result=await api<Record<string,unknown>|null>(url,{method,headers:headers(),body:JSON.stringify(body)});if(receipt&&(!result||typeof result[receipt]!=='string'))throw Error('MISSING_RECEIPT');if(!mounted.current)return false;setMessage(t.saved);setRevision(n=>n+1);return true}catch{if(mounted.current){setMessage(t.error);if(nonIdempotent)setUncertain(revision)}return false}finally{end()}
 }
 async function create(event:FormEvent){event.preventDefault();if(!practitioner)return;const input={key:draftKey.trim(),version:Number(version),locale,targetRole:caseKind==='adult'?'adult_client':'parent',definition:{title,introduction,fields:fields.map(field=>({key:field.key,kind:field.kind,label:field.label,required:field.required,...(field.kind==='single_choice'||field.kind==='multiple_choice'?{options:field.optionsText.split('\n').map(v=>v.trim()).filter(Boolean).map((label,i)=>({value:`option_${i+1}`,label}))}:{})}))},provenance:'Practitioner-authored in private workspace',published};const parsed=formTemplateInputSchema.safeParse(input);if(!parsed.success){setMessage(t.invalid);return}if(await write('/api/forms/templates',parsed.data,'templateId',true)){setTitle('');setIntroduction('');setFields([]);setPublished(false)}}
 async function assign(event:FormEvent){event.preventDefault();if(!practitioner||!data?.templates.some(item=>item.id===template&&item.active&&item.state==='published')||!responders.some(item=>item.id===respondent)||(audience&&!audiences.some(item=>item.id===audience)))return;await write('/api/forms/assignments',{caseId,templateId:template,assignedAccountId:respondent,dueDate:due||null,postSubmissionAudienceId:audience||null},'assignmentId',true)}
 async function submit(event?:FormEvent){event?.preventDefault();if(!selected||practitioner||flight.current)return;if(!submissionUncertain){try{validateAnswers(selected.definition,answers)}catch{setMessage(t.invalid);return}pending.current={assignmentId:selected.id,answers:{...answers},idempotencyKey:crypto.randomUUID()}}if(!pending.current)return;const ok=await write('/api/forms/submissions',pending.current,'submissionId',false);if(!mounted.current)return;if(ok){pending.current=null;setSelected(null);setAnswers({});setSubmissionUncertain(false)}else setSubmissionUncertain(true)}
 async function readAnswers(item:Assignment){if(!practitioner||!begin())return;try{const result=await api<Submission[]>(`/api/forms/submissions?caseId=${encodeURIComponent(caseId)}&assignmentId=${encodeURIComponent(item.id)}`);if(!mounted.current)return;const first=result[0];setReview(first?{assignment:item,submission:first}:null);if(!first)setMessage(t.none)}catch{if(mounted.current)setMessage(t.error)}finally{end()}}
 const locked=busy||uncertain!==null,templateChoices=data?.templates.filter(item=>item.active&&item.state==='published'&&item.targetRole===(caseKind==='adult'?'adult_client':'parent'))??[];
 function updateField(key:string,value:Partial<DraftField>){setFields(items=>items.map(item=>item.key===key?{...item,...value}:item))}
 return <section className="lsw-stack" lang={locale} dir={locale==='he'?'rtl':'ltr'}><h2>{t.title}</h2>{!data&&!error&&<p role="status">{t.loading}</p>}{error&&<p role="alert">{t.error}</p>}<button type="button" disabled={busy} onClick={()=>setRevision(n=>n+1)}>{t.reload}</button>{uncertain!==null&&<div role="alert"><p>{t.uncertain}</p>{data&&data.revision>uncertain&&<button type="button" disabled={busy} onClick={()=>{setUncertain(null);setTemplate('');setRespondent('');setAudience('')}}>{t.reviewed}</button>}</div>}
 {practitioner&&data&&<div className="lsu-task-switcher"><details name="forms-tools"><summary>{t.new}</summary><div className="lsu-task-content"><form className="lsw-card lsw-stack" onSubmit={create}><h3>{t.new}</h3><fieldset disabled={locked}><label>{t.key}<input required pattern="[A-Z][A-Z0-9_]{1,63}" maxLength={64} value={draftKey} onChange={e=>setDraftKey(e.target.value.toUpperCase())}/></label><label>{t.version}<input required type="number" min={1} max={10000} value={version} onChange={e=>setVersion(e.target.value)}/></label><label>{t.name}<input required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>{t.intro}<textarea maxLength={1500} value={introduction} onChange={e=>setIntroduction(e.target.value)}/></label>{fields.map(field=><fieldset key={field.key}><label>{t.label}<input required maxLength={240} value={field.label} onChange={e=>updateField(field.key,{label:e.target.value})}/></label><label>{t.kind}<select value={field.kind} onChange={e=>updateField(field.key,{kind:e.target.value as DraftField['kind']})}>{(['short_text','long_text','single_choice','multiple_choice','boolean','date'] as const).map(kind=><option key={kind} value={kind}>{t[kind]}</option>)}</select></label><label><input type="checkbox" checked={field.required} onChange={e=>updateField(field.key,{required:e.target.checked})}/>{t.required}</label>{(field.kind==='single_choice'||field.kind==='multiple_choice')&&<label>{t.options}<textarea required value={field.optionsText} onChange={e=>updateField(field.key,{optionsText:e.target.value})}/></label>}<button type="button" onClick={()=>setFields(items=>items.filter(item=>item.key!==field.key))}>{t.remove}</button></fieldset>)}<button type="button" disabled={fields.length>=80} onClick={()=>setFields(items=>[...items,{key:`field_${nextField.current++}`,kind:'short_text',label:'',required:false,optionsText:''}])}>{t.add}</button><label><input type="checkbox" checked={published} onChange={e=>setPublished(e.target.checked)}/>{t.publish}</label><button type="submit" disabled={!fields.length}>{t.create}</button></fieldset></form></div></details>
 <details name="forms-tools"><summary>{t.assign}</summary><div className="lsu-task-content"><form className="lsw-card lsw-stack" onSubmit={assign}><fieldset disabled={locked}><label>{t.template}<select required value={template} onChange={e=>setTemplate(e.target.value)}><option value="">{t.choose}</option>{templateChoices.map(item=><option key={item.id} value={item.id}>{item.definition.title} · v{item.version}</option>)}</select></label><label>{t.respondent}<select required value={respondent} onChange={e=>setRespondent(e.target.value)}><option value="">{t.choose}</option>{responders.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label>{t.audience}<select value={audience} onChange={e=>setAudience(e.target.value)}><option value="">{t.private}</option>{audiences.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label>{t.due}<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><button type="submit">{t.assign}</button></fieldset></form></div></details></div>}
 {data&&!data.assignments.length&&<p>{t.empty}</p>}{data?.assignments.map(item=><article className="lsw-card" key={item.id}><h3>{item.definition.title} · v{item.templateVersion}</h3><p>{item.state}</p>{practitioner?<button disabled={busy} onClick={()=>void readAnswers(item)}>{t.review}</button>:item.state==='assigned'&&<button disabled={busy||submissionUncertain} onClick={()=>{setSelected(item);setAnswers({});pending.current=null;setReview(null)}}>{t.open}</button>}</article>)}
 {selected&&!practitioner&&<form className="lsw-card lsw-stack" onSubmit={submit}><h3>{selected.definition.title}</h3><p>{selected.definition.introduction}</p><fieldset disabled={busy||submissionUncertain}>{selected.definition.fields.map(field=><label key={field.key}>{field.label}{field.required&&<span aria-label={t.required} style={{color:'#b42318'}}> *</span>}<FormField locale={locale} field={field} value={answers[field.key]} onChange={value=>setAnswers(current=>({...current,[field.key]:value}))}/></label>)}<button type="submit">{t.submit}</button></fieldset>{submissionUncertain&&<button type="button" disabled={busy} onClick={()=>void submit()}>{t.retry}</button>}</form>}
 {review&&practitioner&&<section className="lsw-card"><h3>{review.assignment.definition.title}</h3><FormAnswerReadout locale={locale} definition={review.assignment.definition} answers={review.submission.answers}/><button disabled={busy||review.submission.state==='reviewed'} onClick={()=>void write('/api/forms/submissions/review',{submissionId:review.submission.id},null,false,'PATCH').then(ok=>{if(ok&&mounted.current)setReview(null)})}>{t.mark}</button></section>}{message&&<p role="status">{message}</p>}</section>;
}
export function FormField({locale,field,value,onChange}:{locale:'en'|'he';field:FormDefinition['fields'][number];value:FormAnswer|undefined;onChange:(value:FormAnswer)=>void}){const t=words[locale];if(field.kind==='boolean')return <select required={field.required} value={value===undefined?'':String(value)} onChange={e=>onChange(e.target.value==='true')}><option value="" disabled>{t.choose}</option><option value="true">{t.yes}</option><option value="false">{t.no}</option></select>;if(field.kind==='multiple_choice')return <select required={field.required} multiple value={Array.isArray(value)?[...value]:[]} onChange={e=>onChange(Array.from(e.target.selectedOptions,item=>item.value))}>{field.options?.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select>;if(field.kind==='single_choice')return <select required={field.required} value={typeof value==='string'?value:''} onChange={e=>onChange(e.target.value)}><option value="">{t.choose}</option>{field.options?.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select>;if(field.kind==='long_text')return <textarea required={field.required} maxLength={4000} value={typeof value==='string'?value:''} onChange={e=>onChange(e.target.value)}/>;return <input required={field.required} type={field.kind==='date'?'date':'text'} maxLength={500} value={typeof value==='string'?value:''} onChange={e=>onChange(e.target.value)}/>;}
export function FormAnswerReadout({locale,definition,answers}:{locale:'en'|'he';definition:FormDefinition;answers:FormAnswers}){const t=words[locale];return <dl>{definition.fields.map(field=>{const value=answers[field.key];const label=(part:string)=>field.options?.find(option=>option.value===part)?.label??part;return <div key={field.key}><dt>{field.label}</dt><dd style={{whiteSpace:'pre-wrap'}}>{typeof value==='boolean'?(value?t.yes:t.no):Array.isArray(value)?value.map(label).join(', '):typeof value==='string'?label(value):'—'}</dd></div>})}</dl>;}
