"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {accountRead} from "../identity/client.ts";
import type {Locale} from "../../lib/locale.ts";
type Case={id:string;kind:"minor"|"adult";state:string;displayName:string};
const copy={en:{title:"Clients & parents",lead:"Choose an authorized case to open its workspace.",search:"Search clients",empty:"No authorized cases are available.",loading:"Loading authorized cases…",error:"Could not load the roster."},he:{title:"ילדים והורים",lead:"בחירת תיק מורשה לפתיחת מרחב העבודה.",search:"חיפוש ילדים",empty:"אין תיקים מורשים זמינים.",loading:"טוען תיקים מורשים…",error:"לא ניתן לטעון את הרשימה."}} as const;
export function ClientsRoster({locale}:{locale:Locale}){
 const t=copy[locale];const [rows,setRows]=useState<Case[]>([]),[query,setQuery]=useState(""),[filter,setFilter]=useState<"all"|"active"|"archived">("active"),[state,setState]=useState<"loading"|"ready"|"error">("loading"),active=useRef(true),request=useRef(0);
 const load=()=>{const current=++request.current;setState("loading");void accountRead<Case[]>("cases").then(v=>{if(active.current&&current===request.current){setRows(v);setState("ready")}}).catch(()=>{if(active.current&&current===request.current)setState("error")})};
 useEffect(()=>{active.current=true;queueMicrotask(load);return()=>{active.current=false}},[]);
 const filtered=useMemo(()=>rows.filter(row=>row.displayName.toLocaleLowerCase().includes(query.toLocaleLowerCase())&&(filter==="all"||(filter==="archived"?/closed|archived|revoked/i.test(row.state):!/closed|archived|revoked/i.test(row.state)))),[rows,query,filter]);
 const button=(value:typeof filter)=>`lsw-button lsw-button--${filter===value?"primary":"quiet"}`;
 return <main className="lsw-main" lang={locale} dir={locale==="he"?"rtl":"ltr"}><nav className="lsw-tabs" aria-label={t.title}><button className={button("all")} aria-current={filter==="all"?"page":undefined} onClick={()=>setFilter("all")}>{locale==="he"?"הכול":"All"}</button><a className="lsw-button lsw-button--quiet" href={`/${locale}/app/prospects`}>{locale==="he"?"מתעניינים":"Prospects"}</a><a className="lsw-button lsw-button--quiet" href={`/${locale}/app/prospects?filter=booking`}>{locale==="he"?"שולם — ממתינים למועד":"Paid — awaiting booking"}</a><button className={button("active")} aria-current={filter==="active"?"page":undefined} onClick={()=>setFilter("active")}>{locale==="he"?"פעילים":"Active"}</button><button className={button("archived")} aria-current={filter==="archived"?"page":undefined} onClick={()=>setFilter("archived")}>{locale==="he"?"בארכיון":"Archived"}</button></nav><h1>{t.title}</h1><p>{t.lead}</p>{state==="loading"&&<p role="status">{t.loading}</p>}{state==="error"&&<div role="alert"><p>{t.error}</p><button type="button" onClick={load}>{locale==="he"?"ניסיון נוסף":"Try again"}</button></div>}{state==="ready"&&<><label htmlFor="client-search">{t.search}</label><input id="client-search" className="lsw-input" type="search" value={query} onChange={e=>setQuery(e.target.value)} /><div className="lsw-card-list">{filtered.length?filtered.map(row=><a className="lsw-card" key={row.id} href={`/${locale}/app/cases/${row.id}`}><h2>{row.displayName}</h2><p>{row.kind==="minor"?(locale==="he"?"ילד/ה":"Child"):(locale==="he"?"מבוגר/ת":"Adult client")} · {row.state}</p></a>):<p role="status">{t.empty}</p>}</div></>}</main>;
}
