/* eslint-disable @next/next/no-img-element -- approved original project media uses intrinsic responsive layout and exact public asset paths */
"use client";
import {useEffect,useRef,useState} from "react";
import type {Locale} from "../../lib/locale.ts";
import {GroupApplicationForm} from "./application-form.tsx";
import styles from "./landing.module.css";

type Copy={en:string;he:string};
const pick=(locale:Locale,value:Copy)=>value[locale];
const projectPhotos=[
 {file:"LS-PROJECT-02-making.png",title:{en:"Following an Idea",he:"בעקבות רעיון"},description:{en:"Through a shared task, he practises explaining an idea, listening to others, disagreeing respectfully and working out the next step together.",he:"דרך משימה משותפת הוא מתרגל להסביר רעיון, להקשיב לאחרים, להביע אי־הסכמה בכבוד ולמצוא יחד את הצעד הבא."},alt:{en:"A boy working carefully with a handheld tool at a table",he:"ילד עובד בזהירות עם כלי יד ליד שולחן"},tone:"teal",reverse:false,portrait:false},
 {file:"LS-PROJECT-03-3d-printer.png",title:{en:"Guided curiosity",he:"סקרנות מונחית"},description:{en:"We follow a boy’s questions, help him test an idea and make room to explore what happens.",he:"אנחנו הולכים בעקבות השאלות של הילד, עוזרים לו לבדוק רעיון ונותנים מקום לחקור מה קורה."},alt:{en:"A boy working on the mechanism of a 3D printer",he:"ילד עובד על המנגנון של מדפסת תלת־ממד"},tone:"light",reverse:true,portrait:false},
 {file:"LS-PROJECT-07-music.png",title:{en:"Finding a rhythm",he:"מוצאים קצב"},description:{en:"Calm, regulated adults join in and enjoy the activity too. We guide correction in an encouraging way, helping boys refine an idea, express themselves and notice their own progress.",he:"מבוגרים רגועים, המווסתים את עצמם, משתתפים ונהנים מהפעילות יחד עם הבנים. אנחנו מכוונים לתיקון בדרך מעודדת, ועוזרים להם לחדד רעיון, לבטא את עצמם ולהבחין בהתקדמות שלהם."},alt:{en:"A boy playing an electronic drum kit",he:"ילד מנגן במערכת תופים אלקטרונית"},tone:"teal",reverse:false,portrait:false},
 {file:"LS-PROJECT-05-woodwork.png",title:{en:"Working alongside someone",he:"לעבוד לצד מישהו"},description:{en:"Take turns, disagree appropriately and work things out with friends.",he:"להתחלק בתורות, להביע אי־הסכמה בכבוד ולפתור קשיים עם חברים."},alt:{en:"Two boys working together with wood",he:"שני ילדים עובדים יחד בעץ"},tone:"light",reverse:true,portrait:false},
 {file:"LS-PROJECT-08-electronics.png",title:{en:"Taking time with the details",he:"נותנים זמן לפרטים"},description:{en:"Notice frustration, pause, ask for support and return to an activity more calmly.",he:"לזהות תסכול, לעצור, לבקש תמיכה ולחזור לפעילות ברוגע רב יותר."},alt:{en:"A boy concentrating on an electronics activity",he:"ילד מתרכז בפעילות אלקטרוניקה"},tone:"teal",reverse:false,portrait:true},
 {file:"LS-PROJECT-09-wood-art.png",title:{en:"Making something of his own",he:"יוצר משהו משלו"},description:{en:"Follow curiosity, try an idea and explore a challenge that interests him.",he:"ללכת בעקבות הסקרנות, לנסות רעיון ולחקור אתגר שמעניין אותו."},alt:{en:"A boy working on a wooden artwork",he:"ילד עובד על יצירת עץ"},tone:"light",reverse:true,portrait:true},
] as const;
const skills=[
 [{en:"What matters to me?",he:"מה חשוב לי?"},{en:"Start with what he actually cares about.",he:"מתחילים במה שבאמת חשוב לו."},{en:"I explore what your son enjoys and why. With you, I choose a practical way to give that interest more room at home.",he:"אני בוחן עם בנכם מה הוא אוהב ולמה. יחד אתכם נבחר דרך מעשית לתת לעניין הזה יותר מקום בבית."}],
 [{en:"Who do I want to become?",he:"מי אני רוצה להיות?"},{en:"Choose the kind of person he wants to be.",he:"לבחור איזה אדם הוא רוצה להיות."},{en:"Your son chooses a quality he values. I help him turn it into one action, then work with you on noticing and supporting it.",he:"בנכם בוחר תכונה שחשובה לו. אני עוזר לו להפוך אותה לפעולה אחת, ואז עובד אתכם על זיהוי וחיזוק שלה."}],
 [{en:"From intention to responsibility",he:"מכוונה לאחריות"},{en:"Make a commitment. Follow it through.",he:"להתחייב ולבצע."},{en:"I help your son choose a home responsibility and make a workable plan. With you, we review what happened and adjust the support.",he:"אני עוזר לבנכם לבחור אחריות בבית ולבנות תוכנית מעשית. יחד אתכם בודקים מה קרה ומתאימים את התמיכה."}],
 [{en:"Saying what I need",he:"לומר מה אני צריך"},{en:"Say what he needs so someone can respond.",he:"לומר מה הוא צריך כדי שאפשר יהיה להגיב."},{en:"We practise a conversation your son actually needs to have. I work with you on making space for his request and responding clearly.",he:"אנחנו מתרגלים שיחה שבנכם באמת צריך לקיים. אני עובד אתכם על מתן מקום לבקשה שלו ועל תגובה ברורה."}],
 [{en:"Listening and keeping boundaries",he:"להקשיב ולשמור על גבולות"},{en:"Hear the other person. Keep his own boundaries.",he:"לשמוע את האחר ולשמור על הגבולות שלו."},{en:"I practise listening and boundary-setting with your son. With you, we choose words and limits that everyone can understand at home.",he:"אני מתרגל עם בנכם הקשבה והצבת גבולות. יחד אתכם בוחרים מילים וגבולות שכולם בבית יכולים להבין."}],
 [{en:"Disagreeing respectfully",he:"לא להסכים בכבוד"},{en:"Disagree without losing the conversation.",he:"לא להסכים בלי לאבד את השיחה."},{en:"Your son and I work through a real disagreement. I help you practise the same conversation at home without taking over his part.",he:"בנכם ואני עובדים על מחלוקת אמיתית. אני עוזר לכם לתרגל את אותה שיחה בבית בלי לקחת ממנו את התפקיד שלו."}],
 [{en:"Thinking through a choice",he:"לחשוב על בחירה"},{en:"Think through options before choosing.",he:"לחשוב על האפשרויות לפני שבוחרים."},{en:"Your son and I think through a choice, consider the options and decide what to try. With you, we apply that process to a situation at home.",he:"בנכם ואני חושבים על בחירה, בוחנים אפשרויות ומחליטים מה לנסות. יחד אתכם מיישמים את התהליך במצב מהבית."}],
 [{en:"Choices, consequences and learning",he:"בחירות, תוצאות ולמידה"},{en:"Use the result to make a better next choice.",he:"להשתמש בתוצאה כדי לבחור טוב יותר בפעם הבאה."},{en:"We review a real choice and its consequences. I help your son choose what to change, and work with you on a response that supports learning.",he:"אנחנו בודקים בחירה אמיתית ואת תוצאותיה. אני עוזר לבנכם לבחור מה לשנות ועובד אתכם על תגובה שתומכת בלמידה."}],
 [{en:"Asking for help and trying again",he:"לבקש עזרה ולנסות שוב"},{en:"Ask for useful help. Take the next step.",he:"לבקש עזרה מועילה ולעשות את הצעד הבא."},{en:"I practise asking for help with your son. With you, we work out when to step in, when to wait and how to return the task to him.",he:"אני מתרגל עם בנכם בקשת עזרה. יחד אתכם מבררים מתי להתערב, מתי להמתין ואיך להחזיר אליו את המשימה."}],
 [{en:"Listening to body and feelings",he:"להקשיב לגוף ולרגשות"},{en:"Notice what’s happening before reacting.",he:"לשים לב למה שקורה לפני שמגיבים."},{en:"Your son and I practise noticing body signals and feelings. I help you recognise those moments at home and offer support without speaking for him.",he:"בנכם ואני מתרגלים זיהוי של אותות הגוף והרגשות. אני עוזר לכם לזהות רגעים כאלה בבית ולהציע תמיכה בלי לדבר במקומו."}],
 [{en:"Looking after my energy",he:"לשמור על האנרגיה שלי"},{en:"Learn what his body needs to take part.",he:"ללמוד מה הגוף שלו צריך כדי להשתתף."},{en:"I look with you and your son at sleep, food, movement and everyday routines. We choose one practical change to try and review.",he:"אני בוחן אתכם ועם בנכם שינה, אוכל, תנועה ושגרות יומיומיות. בוחרים שינוי מעשי אחד לניסיון ולבדיקה."}],
 [{en:"Taking the skills forward",he:"לקחת את המיומנויות הלאה"},{en:"Use these skills beyond our sessions.",he:"להשתמש במיומנויות גם מחוץ למפגשים."},{en:"Your son and I review what he has practised. With you, we choose the responsibilities, conversations and routines to keep working on.",he:"בנכם ואני מסכמים מה תרגל. יחד אתכם בוחרים אחריות, שיחות ושגרות להמשך עבודה."}],
] as const;

export function GroupApplicationLanding({locale:initialLocale}:{locale:Locale}){
 const [locale,setLocale]=useState<Locale>(initialLocale);
 const t=(en:string,he:string)=>locale==="he"?he:en;
 const [menuOpen,setMenuOpen]=useState(false),[photo,setPhoto]=useState<{src:string;alt:string;caption:string}|null>(null);
 const slider=useRef<HTMLDivElement>(null);
 const dialog=useRef<HTMLDialogElement>(null);
 const photoOpener=useRef<HTMLButtonElement|null>(null);
 const slide=(direction:number)=>slider.current?.scrollBy({left:direction*(slider.current.clientWidth*.78),behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"});
 const closePhoto=()=>{const opener=photoOpener.current,node=dialog.current;if(node?.open)node.close();setPhoto(null);window.requestAnimationFrame(()=>opener?.focus({preventScroll:true}));};
 useEffect(()=>{document.documentElement.lang=locale;document.documentElement.dir=locale==="he"?"rtl":"ltr";},[locale]);
 useEffect(()=>{if(!photo)return;const node=dialog.current;if(!node)return;if(!node.open)node.showModal();node.querySelector<HTMLButtonElement>("button")?.focus();return()=>{if(node.open)node.close();};},[photo]);
 const switchLanguage=(next:Locale)=>{if(next===locale)return;setMenuOpen(false);setLocale(next);const path=window.location.pathname.replace(/^\/(en|he)(?=\/)/,`/${next}`);window.history.replaceState(window.history.state,"",path+window.location.search+window.location.hash);};
 return <div className={styles.page} lang={locale} dir={locale==="he"?"rtl":"ltr"}>
  <a className={styles.skip} href="#main">{t("Skip to content","דלגו לתוכן")}</a>
  <header className={styles.header}><div className={styles.wrap}><a className={styles.brand} href="#main"><img src="/groups/brand/life-skills-logo.png" alt="כישורי חיים — לחיים שלמים"/><span className={styles.brandText}>Life Skills<small>{t("BEIT SHEMESH","בית שמש")}</small></span></a>
   <button className={styles.menuToggle} type="button" aria-expanded={menuOpen} aria-controls="group-page-nav" aria-label={menuOpen?t("Close navigation","סגירת ניווט"):t("Open navigation","פתיחת ניווט")} onClick={()=>setMenuOpen(value=>!value)}><span aria-hidden="true">{menuOpen?"×":"☰"}</span></button>
   <nav id="group-page-nav" className={`${styles.nav} ${menuOpen?styles.navOpen:""}`} aria-label={t("Page navigation","ניווט בדף")} onClick={()=>setMenuOpen(false)}><a href="#outcomes">{t("The skills","המיומנויות")}</a><a href="#approach">{t("How We Work","איך אנחנו עובדים")}</a><a href="#private-sessions">{t("One-on-one Support","תמיכה אישית")}</a><a className={styles.navSponsor} href="#sponsor">{t("Sponsor a Child","תנו חסות לילד")}</a><a className={styles.navApply} href="#apply">{t("Apply to join a regular group","הגשת בקשה להצטרפות לקבוצה קבועה")} ↗</a></nav>
   <div className={styles.languageControl} aria-label={t("Language","שפה")}><button type="button" lang="en" aria-pressed={locale==="en"} onClick={()=>switchLanguage("en")}>EN</button><button type="button" lang="he" aria-pressed={locale==="he"} onClick={()=>switchLanguage("he")}>עברית</button></div>
  </div></header>
  <main id="main">
   <section className={styles.flyerHero} aria-labelledby="groups-hero-title"><div className={styles.flyerInner}><p className={styles.eyebrow}>{t("Regular hands-on groups for boys","קבוצות מעשיות קבועות לבנים")}</p><h1 id="groups-hero-title"><span>{t("There’s a hero","בכל ילד")}</span><span>{t("in every child.","יש גיבור.")}</span></h1><figure className={styles.flyerPhoto}><img src="/groups/projects/LS-PROJECT-04-working-together.png" alt={t("Boys working together around a table with electronic components","ילדים עובדים יחד סביב שולחן עם רכיבים אלקטרוניים")} fetchPriority="high"/></figure><div className={styles.flyerCopy}><h2>{t("Life Skills Beit Shemesh","כישורי חיים בית שמש")}</h2><p className={styles.flyerSupport}>{t("Hands-on groups where boys practise staying calm, thinking independently and working things out with friends.","קבוצות מעשיות שבהן ילדים מתרגלים להישאר רגועים, לחשוב באופן עצמאי ולפתור דברים יחד עם חברים.")}</p><a className={`${styles.primaryButton} ${styles.flyerAction}`} href="#apply">{t("Apply to join a regular group","הגשת בקשה להצטרפות לקבוצה קבועה")} <span aria-hidden="true">↗</span></a><p className={styles.flyerPrice}><span>{t("₪1,000 per month","1,000 ₪ לחודש")}</span><span aria-hidden="true"> · </span><span>{t("Two 90-minute sessions each week","שני מפגשים של 90 דקות בכל שבוע")}</span></p><p className={styles.flyerTime}>{t("Morning or evening · Let’s discuss the right fit","בבוקר או בערב · נשוחח על ההתאמה")}</p></div></div></section>
   <section className={styles.introStrip}><div className={styles.wrap}><strong>{t("More than what he makes. It’s how he learns to take part.","מעבר למה שהוא יוצר — זו הדרך שבה הוא לומד להשתתף.")}</strong><p>{t("Through shared activities, boys practise self-governance: choosing what matters, considering their options and taking responsibility for the next step.","דרך פעילויות משותפות, ילדים מתרגלים ניהול עצמי: לבחור מה חשוב, לשקול אפשרויות ולקחת אחריות על הצעד הבא.")}</p></div></section>
   <section className={styles.section} id="outcomes"><div className={styles.wrap}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>{t("From practice to everyday life","מתרגול לחיי היום־יום")}</p><h2>{t("What they learn in Life Skills","מה לומדים בכישורי חיים")}</h2></div><p>{t("Skills practised through real activities and everyday interactions.","מיומנויות שמתורגלות דרך פעילויות אמיתיות ואינטראקציות יומיומיות.")}</p></div><div className={styles.outcomes}>{[
    [t("Self-governance","ניהול עצמי"),t("Choose a goal, consider the likely outcomes and take responsibility for the next step.","לבחור מטרה, לשקול את התוצאות האפשריות ולקחת אחריות על הצעד הבא.")],[t("Emotional regulation","ויסות רגשי"),t("Notice frustration, pause, ask for support and return to an activity more calmly.","לזהות תסכול, לעצור, לבקש תמיכה ולחזור לפעילות ברוגע רב יותר.")],[t("Reciprocal communication","תקשורת הדדית"),t("Express a thought or concern, listen to another view and respond to what was said.","להביע מחשבה או דאגה, להקשיב לנקודת מבט אחרת ולהגיב למה שנאמר.")],[t("Intrinsic motivation","מוטיבציה פנימית"),t("Follow curiosity, try an idea and explore a challenge that interests him.","ללכת בעקבות הסקרנות, לנסות רעיון ולחקור אתגר שמעניין אותו.")],[t("Cooperation and conflict resolution","שיתוף פעולה ופתרון קונפליקטים"),t("Take turns, disagree appropriately and work things out with friends.","להתחלק בתורות, לא להסכים באופן מכבד ולפתור דברים יחד עם חברים.")],[t("Social confidence","ביטחון חברתי"),t("Join an activity, ask a question and express a different view respectfully.","להצטרף לפעילות, לשאול שאלה ולהביע דעה שונה בכבוד.")],
   ].map(([title,body],index)=><article className={styles.outcome} key={title}><span>{String(index+1).padStart(2,"0")}</span><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>
   <section className={`${styles.photoChapter} ${styles.chapterLight} ${styles.approach}`} id="approach"><div className={styles.chapterCopy}><p className={styles.eyebrow}>{t("Our staff","הצוות שלנו")}</p><h2>{t("How We Work","איך אנחנו עובדים")}</h2><h3>{t("Connection before correction.","קשר לפני תיקון.")}</h3><p>{t("We take time to connect, listen and understand what a boy is trying to do.","אנחנו מקדישים זמן להתחבר, להקשיב ולהבין מה הילד מנסה לעשות.")}</p><p>{t("We stay calm, join in and offer clear encouragement and correction that helps him try the next step.","אנחנו נשארים רגועים, מצטרפים לעשייה ומציעים עידוד ותיקון ברורים שעוזרים לו לנסות את הצעד הבא.")}</p><div className={styles.approachLines}><p><strong>{t("Listen.","להקשיב.")}</strong>{t("Make space for his feelings and concerns.","לתת מקום לרגשות ולדאגות שלו.")}</p><p><strong>{t("Guide.","להנחות.")}</strong>{t("Help him consider choices and consequences.","לעזור לו לשקול בחירות ותוצאות.")}</p><p><strong>{t("Practise.","לתרגל.")}</strong>{t("Let him take the next step, with support.","לאפשר לו לעשות את הצעד הבא, עם תמיכה.")}</p></div></div><figure className={styles.chapterMedia}><img src="/groups/projects/LS-PROJECT-06-guided-conversation.png" alt={t("An adult listening to a boy during a hands-on activity","מבוגר מקשיב לילד במהלך פעילות מעשית")} loading="lazy"/></figure></section>
   <section className={styles.photoChapters} id="in-practice" aria-label={t("Learning through doing","לומדים דרך עשייה")}>{projectPhotos.map((item,index)=>{const src=`/groups/projects/${item.file}`,title=pick(locale,item.title),classes=[styles.photoChapter,item.tone==="teal"?styles.chapterTeal:styles.chapterLight,item.reverse?styles.chapterReverse:"",item.portrait?styles.chapterPortrait:""].filter(Boolean).join(" ");return <figure className={classes} key={item.file}><figcaption className={styles.chapterCopy}><p className={styles.eyebrow}>{t("Learning through doing","לומדים דרך עשייה")}</p><h2>{title}</h2>{index===0&&<h3>{t("Collaborating — what he’ll gain","שיתוף פעולה — מה הוא ירוויח")}</h3>}<p>{pick(locale,item.description)}</p><span className={styles.chapterNumber} aria-hidden="true">{String(index+1).padStart(2,"0")}</span></figcaption><button className={styles.chapterMedia} type="button" onClick={event=>{photoOpener.current=event.currentTarget;setPhoto({src,alt:pick(locale,item.alt),caption:title});}} aria-label={`${t("Enlarge photograph","הגדלת תמונה")}: ${title}`}><img src={src} alt={pick(locale,item.alt)} loading="lazy"/></button></figure>})}<p className={`${styles.wrap} ${styles.galleryNote}`}><span>{t("Real moments from Life Skills activities. Each image opens in full.","רגעים אמיתיים מפעילויות כישורי חיים. כל תמונה נפתחת בגודל מלא.")}</span><span>{t("The activity is the starting point. The skills are what we practise.","הפעילות היא נקודת ההתחלה. המיומנויות הן מה שאנחנו מתרגלים.")}</span></p></section>
   <section className={`${styles.section} ${styles.private}`} id="private-sessions"><div className={styles.wrap}><div className={styles.privateHeading}><div><p className={styles.eyebrow}>{t("Individual practice, shared support","תרגול אישי, תמיכה משותפת")}</p><h2>{t("One-on-one Support","תמיכה אישית")}</h2></div><div><p>{t("We also work privately with a boy and his parents on the situations that matter to him: choices, communication, setbacks and everyday responsibility.","אנחנו עובדים גם באופן פרטי עם ילד והוריו על המצבים שחשובים לו: בחירות, תקשורת, התמודדות עם קשיים ואחריות יומיומית.")}</p></div></div><div className={styles.privateFlyer}><picture className={styles.privateHero}><source media="(max-width:760px)" srcSet={locale==="he"?"/groups/private/founder-boy-hero-he-mobile.png":"/groups/private/founder-boy-hero-en-mobile.png"}/><img src={locale==="he"?"/groups/private/founder-boy-hero-he-desktop.png":"/groups/private/founder-boy-hero-en-desktop.png"} alt={t("Approved Life Skills one-on-one support information","מידע מאושר על תמיכה אישית בכישורי חיים")} loading="lazy"/></picture><a className={`${styles.primaryButton} ${styles.privateOverlayAction}`} href="https://wa.me/972534932631" target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer">{t("Ask about one-on-one support","שאלו על תמיכה אישית")} <span aria-hidden="true">↗</span></a></div><div className={styles.sliderToolbar}><p>{t("12 skills · Explore the one-on-one approach","12 מיומנויות · היכרות עם הגישה האישית")}</p><div><button type="button" onClick={()=>slide(locale==="he"?1:-1)} aria-label={t("Previous skill notes","הכרטיסים הקודמים")}>←</button><button type="button" onClick={()=>slide(locale==="he"?-1:1)} aria-label={t("Next skill notes","הכרטיסים הבאים")}>→</button></div></div><div className={styles.skillSlider} ref={slider} tabIndex={0} aria-label={t("Twelve one-on-one skill notes","שנים עשר כרטיסי מיומנויות לתמיכה אישית")}>{skills.map(([title,goal,body],index)=><article key={index}><img src={`/groups/private/skill-${String(index+1).padStart(2,"0")}.webp`} alt="" loading="lazy"/><div><p className={styles.skillNumber}>{String(index+1).padStart(2,"0")} / 12 {t("SKILLS","מיומנויות")}</p><h3>{pick(locale,title)}</h3><p className={styles.skillGoal}>{pick(locale,goal)}</p><p>{pick(locale,body)}</p></div></article>)}</div></div></section>
   <section className={`${styles.photoChapter} ${styles.chapterLight} ${styles.chapterFounder}`} id="our-team"><div className={styles.chapterCopy}><p className={styles.eyebrow}>{t("The people behind Life Skills","האנשים שמאחורי כישורי חיים")}</p><h2>{t("Meet Shlomo Dratler","הכירו את שלמה דרטלר")}</h2><p>{t("Shlomo lives in Ramat Beit Shemesh Gimmel and is a father of five. His work focuses on intrinsic motivation, values-based education and integrative Torah study.","שלמה מתגורר ברמת בית שמש ג׳ והוא אב לחמישה. עבודתו מתמקדת במוטיבציה פנימית, חינוך מבוסס ערכים ולימוד תורה אינטגרטיבי.")}</p><p>{t("The work combines conversation and experience with body and emotional awareness, communication, problem solving, motivation, values and self-governance — connecting practice to real situations at home and with friends.","העבודה משלבת שיחה והתנסות עם מודעות לגוף ולרגש, תקשורת, פתרון בעיות, מוטיבציה, ערכים והנהגה עצמית — ומחברת את התרגול למצבים אמיתיים בבית ובין חברים.")}</p></div><figure className={styles.chapterMedia}><img src="/groups/people/founder-grass-group.webp" alt={t("Shlomo Dratler sitting on the grass with a group of boys","שלמה דרטלר יושב על הדשא עם קבוצת ילדים")} loading="lazy"/></figure></section>
   <section className={styles.testimonial}><div className={styles.wrap}><p className={styles.eyebrow}>{t("A parent’s experience","חוויה של הורה")}</p><blockquote><p lang="en" dir="ltr">“Medication is no longer relevant…”</p><footer><cite>LB</cite> · 2024</footer></blockquote></div></section>
   <section className={`${styles.section} ${styles.faq}`} id="questions"><div className={`${styles.wrap} ${styles.faqGrid}`}><div><p className={styles.eyebrow}>{t("Questions are welcome","נשמח לשאלות")}</p><h2>{t("A few questions, answered","כמה תשובות לשאלות נפוצות")}</h2><a className={styles.secondaryButton} href="https://wa.me/972534932631" target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer">{t("Talk on WhatsApp","דברו איתנו בוואטסאפ")} ↗</a></div><div className={styles.faqList}><details><summary>{t("Is this instead of school?","האם זה במקום בית הספר?")}</summary><p>{t("Evening groups are for boys who attend school. The morning program is designed for boys who are homeschooled.","קבוצות הערב מיועדות לילדים שלומדים בבית ספר. תוכנית הבוקר מיועדת לילדים בחינוך ביתי.")}</p></details><details><summary>{t("Where do you meet?","היכן נפגשים?")}</summary><p>{t("We share the location in our WhatsApp group. We meet outdoors when weather permits; otherwise, in Ramat Beit Shemesh Gimmel.","אנחנו משתפים את המיקום בקבוצת הוואטסאפ שלנו. נפגשים בחוץ כשמזג האוויר מאפשר, ובמקרה אחר ברמת בית שמש ג׳.")}</p></details></div></div></section>
   <section className={styles.sponsor} id="sponsor"><div className={`${styles.wrap} ${styles.sponsorRow}`}><div><p className={styles.eyebrow}>{t("Support a child’s participation","תמיכה בהשתתפות של ילד")}</p><h2>{t("Sponsor a Child for One Month — ₪1,000","חסות לילד לחודש אחד — 1,000 ₪")}</h2><p className={styles.sponsorExplanation}>{t("Talk with us about supporting a child’s participation.","דברו איתנו על תמיכה בהשתתפות של ילד.")}</p></div><a className={styles.primaryButton} href="https://wa.me/972534932631" target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer">{t("Sponsor a Child","תנו חסות לילד")} <span aria-hidden="true">↗</span></a></div></section>
   <section className={`${styles.photoChapter} ${styles.chapterTeal} ${styles.chapterClosing}`}><div className={styles.chapterCopy}><p className={styles.eyebrow}>{t("A regular place to practise together","מקום קבוע לתרגל יחד")}</p><h2>{t("A safe place to be themselves","מקום בטוח להיות בו הם עצמם")}</h2><p>{t("Growing together through exploratory activities. We help boys try ideas, express themselves and learn alongside others.","גדלים יחד דרך פעילויות חקר. אנחנו עוזרים לילדים לנסות רעיונות, לבטא את עצמם וללמוד לצד אחרים.")}</p><a className={styles.primaryButton} href="#apply">{t("Apply to join a regular group","הגשת בקשה להצטרפות לקבוצה קבועה")} <span aria-hidden="true">↗</span></a></div><figure className={styles.chapterMedia}><img src="/groups/projects/LS-PROJECT-01-group.jpg" alt={t("A group of boys relaxing together between activities","קבוצת ילדים נחים יחד בין פעילויות")} loading="lazy"/></figure></section>
   <section className={`${styles.section} ${styles.apply}`} id="apply"><div className={`${styles.wrap} ${styles.applicationGrid}`}><div className={styles.applicationCopy}><p className={styles.eyebrow}>{t("The next step","הצעד הבא")}</p><h2>{t("Apply to join a regular group.","הגשת בקשה להצטרפות לקבוצה קבועה.")}</h2><p>{t("Tell us a little about your son and what you are looking for. We can discuss the group, the timing and whether it is a good fit.","ספרו לנו מעט על הילד ועל מה שאתם מחפשים. נוכל לדבר על הקבוצה, על הזמנים ועל ההתאמה.")}</p><ul><li><strong>{t("Groups in Beit Shemesh.","קבוצות בבית שמש.")}</strong> {t("We are also forming groups in Central Israel and Jerusalem. Inquiries from all towns are welcome.","אנחנו מקימים קבוצות גם במרכז הארץ ובירושלים. פניות מכל יישוב מתקבלות בברכה.")}</li><li><strong>{t("First planned group: 25 boys.","הקבוצה הראשונה המתוכננת: 25 ילדים.")}</strong> {t("Meeting twice a week, with the timing still to be confirmed.","מפגשים פעמיים בשבוע, כשהזמנים עדיין ייקבעו.")}</li><li><strong>₪1,000 {t("per month.","לחודש.")}</strong> {t("Details are discussed before any commitment.","הפרטים נדונים לפני כל התחייבות.")}</li></ul><p>{t("Applying starts owner review and does not reserve a place, create a start date or authorize payment.","הגשת הבקשה מתחילה בדיקת בעלים ואינה שומרת מקום, יוצרת תאריך התחלה או מאשרת תשלום.")}</p><a className={styles.secondaryButton} href="https://wa.me/972534932631" target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer">{t("Talk on WhatsApp","דברו איתנו בוואטסאפ")} ↗</a></div><GroupApplicationForm locale={locale}/></div></section>
  </main>
  <footer className={styles.footer}><div className={styles.wrap}><div className={styles.footerGrid}><a className={styles.brand} href="#main"><img src="/groups/brand/life-skills-logo.png" alt="כישורי חיים — לחיים שלמים"/><span className={styles.brandText}>Life Skills<small>{t("BEIT SHEMESH","בית שמש")}</small></span></a><p className={styles.footerMessage}>{t("Skills for life. Practised together.","כישורים לחיים. מתרגלים יחד.")}</p><a className={styles.primaryButton} href="#apply">{t("Apply to join a regular group","הגשת בקשה להצטרפות לקבוצה קבועה")} ↗</a></div><p className={styles.nonprofit}>{t("Life Skills is a project of Bnei Neviim Academy, a New Jersey nonprofit supporting Jewish children’s emotional and educational development, autonomy and self-directed growth.","כישורי חיים הוא מיזם של אקדמיית בני נביאים, עמותה מניו ג׳רזי התומכת בהתפתחותם הרגשית והחינוכית, בעצמאותם ובצמיחתם העצמית של ילדים יהודים.")} <a href="https://bneineviimacademy.org/" target="_blank" rel="noopener noreferrer">Bnei Neviim Academy ↗</a></p><div className={styles.footerBottom}><span>Life Skills {t("Beit Shemesh","בית שמש")}<br/>{t("Our team, alongside your family","הצוות שלנו, לצד המשפחה שלכם")}</span><nav aria-label={t("Footer navigation","ניווט תחתון")}><a href="#approach">{t("How We Work","איך אנחנו עובדים")}</a><a href="#private-sessions">{t("One-on-one Support","תמיכה אישית")}</a></nav></div></div></footer>
  {photo&&<dialog ref={dialog} className={styles.dialog} aria-label={photo.caption} onCancel={event=>{event.preventDefault();closePhoto();}} onClick={event=>{if(event.target===event.currentTarget)closePhoto();}}><div><header><strong>{photo.caption}</strong><button type="button" onClick={closePhoto} aria-label={t("Close photograph","סגירת תמונה")}>×</button></header><img src={photo.src} alt={photo.alt}/></div></dialog>}
 </div>;
}
