"use client";
import {useRef,useState} from "react";
import type {Locale} from "../../lib/locale.ts";
import {GroupApplicationForm} from "./application-form.tsx";
import styles from "./landing.module.css";

type Copy={en:string;he:string};
const pick=(locale:Locale,value:Copy)=>value[locale];
const projectPhotos=[
 {file:"LS-PROJECT-02-making.png",caption:{en:"Following an idea",he:"להמשיך רעיון"},alt:{en:"A boy working carefully with a handheld tool at a table",he:"ילד עובד בזהירות עם כלי יד ליד שולחן"}},
 {file:"LS-PROJECT-03-3d-printer.png",caption:{en:"Exploring how things work",he:"לגלות איך דברים עובדים"},alt:{en:"A boy working on the mechanism of a 3D printer",he:"ילד עובד על המנגנון של מדפסת תלת־ממד"}},
 {file:"LS-PROJECT-07-music.png",caption:{en:"Finding a rhythm",he:"למצוא קצב"},alt:{en:"A boy playing an electronic drum kit",he:"ילד מנגן במערכת תופים אלקטרונית"}},
 {file:"LS-PROJECT-05-woodwork.png",caption:{en:"Working alongside someone",he:"לעבוד יחד"},alt:{en:"Two boys working together with wood",he:"שני ילדים עובדים יחד בעץ"}},
 {file:"LS-PROJECT-08-electronics.png",caption:{en:"Taking time with the details",he:"לתת זמן לפרטים"},alt:{en:"A boy concentrating on an electronics activity",he:"ילד מתרכז בפעילות אלקטרוניקה"}},
 {file:"LS-PROJECT-09-wood-art.png",caption:{en:"Making something his own",he:"ליצור משהו משלו"},alt:{en:"A boy working on a wooden artwork",he:"ילד עובד על יצירת עץ"}},
 {file:"LS-PROJECT-01-group.jpg",caption:{en:"Time together",he:"זמן ביחד"},alt:{en:"A group of boys spending time together outdoors",he:"קבוצת ילדים מבלים יחד בחוץ"}},
] as const;
const skills=[
 [{en:"What matters to me?",he:"מה חשוב לי?"},{en:"Start with what he actually cares about.",he:"מתחילים במה שבאמת חשוב לו."},{en:"I explore what your son enjoys and why. With you, I choose a practical way to give that interest more room at home.",he:"אני בוחן עם בנכם מה הוא אוהב ולמה. יחד אתכם נבחר דרך מעשית לתת לעניין הזה יותר מקום בבית."}],
 [{en:"Who do I want to become?",he:"מי אני רוצה להיות?"},{en:"Choose the kind of person he wants to be.",he:"לבחור איזה אדם הוא רוצה להיות."},{en:"Your son chooses a quality he values. I help him turn it into one action, then work with you on noticing and supporting it.",he:"בנכם בוחר תכונה שחשובה לו. אני עוזר לו להפוך אותה לפעולה אחת, ואז עובד אתכם על זיהוי וחיזוק שלה."}],
 [{en:"From intention to responsibility",he:"מכוונה לאחריות"},{en:"Make a commitment. Follow it through.",he:"להתחייב ולבצע."},{en:"I help your son choose a home responsibility and make a workable plan. With you, we review what happened and adjust the support.",he:"אני עוזר לבנכם לבחור אחריות בבית ולבנות תוכנית מעשית. יחד אתכם בודקים מה קרה ומתאימים את התמיכה."}],
 [{en:"Saying what I need",he:"לומר מה אני צריך"},{en:"Say what he needs so someone can respond.",he:"לומר מה הוא צריך כדי שאפשר יהיה להגיב."},{en:"We practise a conversation your son actually needs to have. I work with you on making space for his request and responding clearly.",he:"אנחנו מתרגלים שיחה שבנכם באמת צריך לקיים. אני עובד אתכם על מתן מקום לבקשה שלו ועל תגובה ברורה."}],
 [{en:"Listening and keeping boundaries",he:"להקשיב ולשמור על גבולות"},{en:"Hear the other person. Keep his own boundaries.",he:"לשמוע את האחר ולשמור על הגבולות שלו."},{en:"I practise listening and boundary-setting with your son. With you, we choose words and limits that everyone can understand at home.",he:"אני מתרגל עם בנכם הקשבה והצבת גבולות. יחד אתכם בוחרים מילים וגבולות שכולם בבית יכולים להבין."}],
 [{en:"Disagreeing respectfully",he:"לא להסכים בכבוד"},{en:"Disagree without losing the conversation.",he:"לא להסכים בלי לאבד את השיחה."},{en:"Your son and I work through a real disagreement. I help you practise the same conversation at home without taking over his part.",he:"בנכם ואני עובדים על מחלוקת אמיתית. אני עוזר לכם לתרגל את אותה שיחה בבית בלי לקחת ממנו את התפקיד שלו."}],
 [{en:"Thinking through a choice",he:"לחשוב על בחירה"},{en:"Think through options before choosing.",he:"לחשוב על האפשרויות לפני שבוחרים."},{en:"Your son and I think through a choice, consider the options and decide what to try. With you, we apply that process to a situation at home.",he:"בנכם ואני חושבים על בחירה, בוחנים אפשרויות ומחליטים מה לנסות. יחד אתכם מיישמים את התהליך במצב מהבית."}],
 [{en:"Choices, consequences and learning",he:"בחירות, תוצאות ולמידה"},{en:"Use the result to make a better next choice.",he:"להשתמש בתוצאה כדי לבחור טוב יותר בפעם הבאה."},{en:"We review a real choice and its consequences. I help your son choose what to change, and work with you on a response that supports learning.",he:"אנחנו בודקים בחירה אמיתית ואת תוצאותיה. אני עוזר לבנכם לבחור מה לשנות ועובד אתכם על תגובה שתומכת בלמידה."}],
 [{en:"Asking for help and trying again",he:"לבקש עזרה ולנסות שוב"},{en:"Ask for useful help. Take the next step.",he:"לבקש עזרה מועילה ולעשות את הצעד הבא."},{en:"I practise asking for help with your son. With you, we work out when to step in, when to wait and how to return the task to him.",he:"אני מתרגל עם בנכם בקשת עזרה. יחד אתכם מבררים מתי להתערב, מתי להמתין ואיך להחזיר אליו את המשימה."}],
 [{en:"Listening to body and feelings",he:"להקשיב לגוף ולרגשות"},{en:"Notice what’s happening before reacting.",he:"לשים לב למה שקורה לפני שמגיבים."},{en:"Your son and I practise noticing body signals and feelings. I help you recognise those moments at home and offer support without speaking for him.",he:"בנכם ואני מתרגלים זיהוי של אותות הגוף והרגשות. אני עוזר לכם לזהות רגעים כאלה בבית ולהציע תמיכה בלי לדבר במקומו."}],
 [{en:"Looking after my energy",he:"לשמור על האנרגיה שלי"},{en:"Learn what his body needs to take part.",he:"ללמוד מה הגוף שלו צריך כדי להשתתף."},{en:"I look with you and your son at sleep, food, movement and everyday routines. We choose one practical change to try and review.",he:"אני בוחן אתכם ועם בנכם שינה, אוכל, תנועה ושגרות יומיומיות. בוחרים שינוי מעשי אחד לניסיון ולבדיקה."}],
 [{en:"Taking the skills forward",he:"לקחת את המיומנויות הלאה"},{en:"Use these skills beyond our sessions.",he:"להשתמש במיומנויות גם מחוץ למפגשים."},{en:"Your son and I review what he has practised. With you, we choose the responsibilities, conversations and routines to keep working on.",he:"בנכם ואני מסכמים מה תרגל. יחד אתכם בוחרים אחריות, שיחות ושגרות להמשך עבודה."}],
] as const;

export function GroupApplicationLanding({locale}:{locale:Locale}){
 const t=(en:string,he:string)=>locale==="he"?he:en;
 const [menuOpen,setMenuOpen]=useState(false),[photo,setPhoto]=useState<{src:string;alt:string;caption:string}|null>(null);
 const slider=useRef<HTMLDivElement>(null);
 const slide=(direction:number)=>slider.current?.scrollBy({left:direction*(slider.current.clientWidth*.78),behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"});
 return <div className={styles.page} lang={locale} dir={locale==="he"?"rtl":"ltr"}>
  <a className={styles.skip} href="#main">{t("Skip to content","דלגו לתוכן")}</a>
  <header className={styles.header}><div className={styles.wrap}><a className={styles.brand} href="#main"><img src="/groups/brand/life-skills-logo.png" alt="כישורי חיים — לחיים שלמים"/><span>Life Skills</span></a>
   <button className={styles.menuToggle} type="button" aria-expanded={menuOpen} aria-controls="group-page-nav" onClick={()=>setMenuOpen(value=>!value)}>{menuOpen?"×":"☰"}<span className={styles.srOnly}>{menuOpen?t("Close navigation","סגירת ניווט"):t("Open navigation","פתיחת ניווט")}</span></button>
   <nav id="group-page-nav" className={`${styles.nav} ${menuOpen?styles.navOpen:""}`} aria-label={t("Page navigation","ניווט בדף")} onClick={()=>setMenuOpen(false)}><a href="#approach">{t("The approach","הגישה")}</a><a href="#in-practice">{t("In practice","בפועל")}</a><a href="#private-sessions">{t("Private sessions","מפגשים פרטניים")}</a><a className={styles.navApply} href="#apply">{t("Apply to join a regular group","הגשת בקשה להצטרפות לקבוצה קבועה")} ↗</a><a href={locale==="he"?"/en/groups/apply":"/he/groups/apply"} lang={locale==="he"?"en":"he"}>{locale==="he"?"English":"עברית"}</a></nav>
  </div></header>
  <main id="main">
   <section className={styles.hero}><div className={`${styles.wrap} ${styles.heroGrid}`}><div><p className={styles.eyebrow}>{t("Hands-on groups for boys · Beit Shemesh","קבוצות מעשיות לבנים · בית שמש")}</p><h1>{t("Hands-on projects. Skills for everyday life.","פרויקטים מעשיים. כישורים לחיי היום־יום.")}</h1><p className={styles.lead}>{t("A place to make, explore and work with others. I guide boys as they practise making choices, communicating clearly and taking responsibility.","מקום ליצור, לחקור ולעבוד עם אחרים. אני מלווה ילדים בתרגול בחירה, תקשורת ברורה ולקיחת אחריות.")}</p><a className={styles.primaryButton} href="#apply">{t("Apply to join a regular group","הגשת בקשה להצטרפות לקבוצה קבועה")} ↗</a><p className={styles.heroNote}>{t("Applying starts a private owner review. It does not reserve a place or create a payment.","הגשת הבקשה מתחילה בדיקה פרטית של הבעלים. היא אינה שומרת מקום ואינה יוצרת תשלום.")}</p></div><figure className={styles.heroPhoto}><img src="/groups/projects/LS-PROJECT-04-working-together.png" alt={t("Boys working together on a hands-on project","ילדים עובדים יחד על פרויקט מעשי")}/><figcaption>{t("Working together on something real","עובדים יחד על משהו אמיתי")}</figcaption></figure></div><div className={`${styles.wrap} ${styles.heroFacts}`}><span><strong>{t("25 boys","25 ילדים")}</strong>{t("one planned first group","קבוצה ראשונה מתוכננת אחת")}</span><span><strong>{t("Twice weekly","פעמיים בשבוע")}</strong>{t("meeting times to be confirmed","זמני המפגשים ייקבעו בהמשך")}</span><span><strong>₪1,000</strong>{t("per month","לחודש")}</span></div></section>
   <section className={styles.section}><div className={styles.wrap}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>{t("What the boys practise","מה הילדים מתרגלים")}</p><h2>{t("Skills grow through doing.","כישורים צומחים דרך עשייה.")}</h2></div><p>{t("Projects give boys a real reason to plan, communicate, cooperate and keep going when something needs another try.","פרויקטים נותנים לילדים סיבה אמיתית לתכנן, לתקשר, לשתף פעולה ולהמשיך כשצריך לנסות שוב.")}</p></div><div className={styles.outcomes}>{[
    [t("Choose and plan","לבחור ולתכנן"),t("Turn an idea into workable next steps.","להפוך רעיון לצעדים מעשיים.")],[t("Communicate clearly","לתקשר בבהירות"),t("Explain an idea, ask for help and listen.","להסביר רעיון, לבקש עזרה ולהקשיב.")],[t("Work with others","לעבוד עם אחרים"),t("Share tools, roles and decisions.","לחלוק כלים, תפקידים והחלטות.")],[t("Handle setbacks","להתמודד עם תקלות"),t("Pause, adjust and try again.","לעצור, להתאים ולנסות שוב.")],[t("Take responsibility","לקחת אחריות"),t("Care for materials, commitments and results.","לשמור על חומרים, התחייבויות ותוצאות.")],[t("Build confidence","לבנות ביטחון"),t("See what changes through steady practice.","לראות מה משתנה בעזרת תרגול עקבי.")],
   ].map(([title,body],index)=><article className={styles.outcome} key={title}><span>{String(index+1).padStart(2,"0")}</span><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>
   <section className={`${styles.section} ${styles.approach}`} id="approach"><div className={`${styles.wrap} ${styles.approachGrid}`}><figure><img src="/groups/projects/LS-PROJECT-06-guided-conversation.png" alt={t("A guided conversation during a practical activity","שיחה מונחית במהלך פעילות מעשית")}/></figure><div><p className={styles.eyebrow}>{t("The approach","הגישה")}</p><h2>{t("Real activities. Thoughtful guidance.","פעילויות אמיתיות. ליווי מתחשב.")}</h2><p>{t("The project is not a reward after the learning. It is where the learning happens. I notice the choices, conversations and difficult moments, and help the boys practise a useful next step.","הפרויקט אינו פרס אחרי הלמידה; הוא המקום שבו הלמידה מתרחשת. אני שם לב לבחירות, לשיחות ולרגעים הקשים ועוזר לילדים לתרגל את הצעד המועיל הבא.")}</p><div className={styles.approachLines}><p><strong>{t("Make","יוצרים")}</strong>{t("Build interest and ownership.","מטפחים עניין ובעלות.")}</p><p><strong>{t("Notice","שמים לב")}</strong>{t("Name what is happening without scoring or diagnosing.","מנסחים מה קורה בלי לציין ציונים או לאבחן.")}</p><p><strong>{t("Practise","מתרגלים")}</strong>{t("Try one concrete skill in the moment.","מנסים מיומנות מעשית אחת ברגע עצמו.")}</p></div></div></div></section>
   <section className={`${styles.section} ${styles.photos}`} id="in-practice"><div className={styles.wrap}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>{t("In practice","בפועל")}</p><h2>{t("Project moments. Shared experiences.","רגעים של פרויקט. חוויות משותפות.")}</h2></div><p>{t("Making, building and exploring give the boys opportunities to work things out together. These are moments from activities, rather than a fixed project schedule.","יצירה, בנייה וחקירה נותנות לילדים הזדמנויות להבין דברים יחד. אלה רגעים מפעילויות, ולא לוח פרויקטים קבוע.")}</p></div><div className={styles.photoGrid}>{projectPhotos.map(item=>{const src=`/groups/projects/${item.file}`;return <figure key={item.file}><button type="button" onClick={()=>setPhoto({src,alt:pick(locale,item.alt),caption:pick(locale,item.caption)})} aria-label={`${t("Enlarge photograph","הגדלת תמונה")}: ${pick(locale,item.caption)}`}><img src={src} alt={pick(locale,item.alt)} loading="lazy"/></button><figcaption>{pick(locale,item.caption)}</figcaption></figure>})}</div></div></section>
   <section className={`${styles.section} ${styles.private}`} id="private-sessions"><div className={styles.wrap}><div className={styles.privateHeading}><div><p className={styles.eyebrow}>{t("A separate path · Private sessions","מסלול נפרד · מפגשים פרטניים")}</p><h2>{t("One to one. With work for home, too.","אחד על אחד. עם עבודה לבית.")}</h2></div><p>{t("Private sessions remain a separate service and enquiry. The notes below show the existing approach; this group application does not open a private case.","מפגשים פרטניים נשארים שירות ופנייה נפרדים. הכרטיסים למטה מציגים את הגישה הקיימת; בקשת הקבוצה אינה פותחת תיק פרטי.")}</p></div><div className={styles.sliderToolbar}><p>{t("12 skills · Explore the private-session approach","12 מיומנויות · היכרות עם הגישה למפגשים פרטניים")}</p><div><button type="button" onClick={()=>slide(locale==="he"?1:-1)} aria-label={t("Previous skill notes","הכרטיסים הקודמים")}>←</button><button type="button" onClick={()=>slide(locale==="he"?-1:1)} aria-label={t("Next skill notes","הכרטיסים הבאים")}>→</button></div></div><div className={styles.skillSlider} ref={slider} tabIndex={0} aria-label={t("Twelve private-session skill notes","שנים עשר כרטיסי מיומנויות למפגשים פרטניים")}>{skills.map(([title,goal,body],index)=><article key={index}><img src={`/groups/private/skill-${String(index+1).padStart(2,"0")}.webp`} alt="" loading="lazy"/><div><p className={styles.skillNumber}>{String(index+1).padStart(2,"0")} / 12 {t("SKILLS","מיומנויות")}</p><h3>{pick(locale,title)}</h3><p className={styles.skillGoal}>{pick(locale,goal)}</p><p>{pick(locale,body)}</p></div></article>)}</div></div></section>
   <section className={`${styles.section} ${styles.apply}`} id="apply"><div className={`${styles.wrap} ${styles.applicationGrid}`}><div className={styles.applicationCopy}><p className={styles.eyebrow}>{t("The next step","הצעד הבא")}</p><h2>{t("Apply to join a regular group.","הגשת בקשה להצטרפות לקבוצה קבועה.")}</h2><p>{t("Tell me a little about your son and what you are looking for. We can discuss the group, the timing and whether it is a good fit.","ספרו לי מעט על הילד ועל מה שאתם מחפשים. נוכל לדבר על הקבוצה, על הזמנים ועל ההתאמה.")}</p><ul><li><strong>{t("Beit Shemesh groups.","קבוצות בבית שמש.")}</strong> {t("Applications from every town are welcome.","בקשות מכל יישוב מתקבלות בברכה.")}</li><li><strong>{t("First planned group: 25 boys.","הקבוצה הראשונה המתוכננת: 25 ילדים.")}</strong> {t("Twice a week, with morning or evening timing to discuss.","פעמיים בשבוע, עם אפשרות לדבר על בוקר או ערב.")}</li><li><strong>₪1,000 {t("per month.","לחודש.")}</strong> {t("Details are discussed before any commitment.","הפרטים נדונים לפני כל התחייבות.")}</li></ul><p>{t("No place, start date or payment commitment is created by applying.","הגשת בקשה אינה יוצרת מקום, תאריך התחלה או התחייבות לתשלום.")}</p></div><GroupApplicationForm locale={locale}/></div></section>
  </main>
  <footer className={styles.footer}><div className={`${styles.wrap} ${styles.footerGrid}`}><a className={styles.brand} href="#main"><img src="/groups/brand/life-skills-logo.png" alt="כישורי חיים — לחיים שלמים"/><span>Life Skills</span></a><div><h3>{t("Groups built around real life.","קבוצות שנבנות סביב החיים עצמם.")}</h3><p>{t("Hands-on learning in Beit Shemesh.","למידה מעשית בבית שמש.")}</p></div><nav><a href="#apply">{t("Apply to join a regular group","הגשת בקשה להצטרפות לקבוצה קבועה")} ↗</a><a href="#private-sessions">{t("Explore private sessions","היכרות עם מפגשים פרטניים")}</a></nav></div></footer>
  {photo&&<dialog className={styles.dialog} open aria-label={photo.caption} onClick={event=>{if(event.target===event.currentTarget)setPhoto(null)}}><div><header><strong>{photo.caption}</strong><button type="button" onClick={()=>setPhoto(null)} aria-label={t("Close photograph","סגירת תמונה")}>×</button></header><img src={photo.src} alt={photo.alt}/></div></dialog>}
 </div>;
}
