import { shiftMonth } from '../../../src/features/calendar/time.ts';
import assert from 'node:assert/strict';
import { AppError } from '../../../src/lib/errors.ts';
import { asId } from '../../../src/lib/ids.ts';
import { authorizeAppointment, assertAvailable, makeNoticeFields, paddedSlot, validateBooking, validateWindows } from '../../../src/features/calendar/policy.ts';
import { possibleInstants, noticeEligibility, endOfAppointment, iso, overlaps, dateRange, civilDate, shiftDay } from '../../../src/features/calendar/time.ts';
import { validateAttendance, countsAsChildSession, attended } from '../../../src/features/attendance/policy.ts';
import { canonical } from '../../../src/features/calendar/store.ts';
import { appointment, audience, facts, guardians, practitioner, parent, parentTwo, booking, uuid } from './fixtures.ts';
export type Register=(name:string,fn:()=>void|Promise<void>)=>unknown;
const rejects=(fn:()=>unknown,code:string)=>assert.throws(fn,(e:unknown)=>e instanceof AppError&&e.code===code);
export function registerDomainTests(test:Register){
 test('month navigation advances month and clamps end-of-month',()=>{assert.equal(shiftMonth('2026-01-31',1),'2026-02-28');assert.equal(shiftMonth('2026-09-07',1),'2026-10-07');assert.equal(shiftMonth('2026-03-31',-1),'2026-02-28');});
 const base=Date.parse(appointment.startsAt);
 for(const [delta,expected] of [[86_400_001,'credit_preserved'],[86_400_000,'credit_preserved'],[86_399_999,'late_notice'],[0,'late_notice'],[-1,'late_notice']] as const)
  test(`notice boundary ${delta} ms => ${expected}`,()=>assert.equal(noticeEligibility(appointment.startsAt,new Date(base-delta).toISOString()),expected));
 test('notice uses elapsed time across spring offset change',()=>assert.equal(noticeEligibility('2026-03-27T12:00:00+03:00','2026-03-26T12:00:00+02:00'),'late_notice'));
 test('notice uses elapsed time across autumn offset change',()=>assert.equal(noticeEligibility('2026-10-25T12:00:00+02:00','2026-10-24T12:00:00+03:00'),'credit_preserved'));
 test('same instant with different offsets has same eligibility',()=>assert.equal(noticeEligibility('2026-09-08T13:00:00+03:00','2026-09-07T10:00:00Z'),'credit_preserved'));
 test('child duration is exactly sixty elapsed minutes',()=>assert.equal(endOfAppointment('2026-10-25T01:30:00+03:00','individual'),'2026-10-24T23:30:00.000Z'));
 test('joint-parent duration is exactly fifteen elapsed minutes',()=>assert.equal(endOfAppointment(appointment.startsAt,'parent_guidance'),'2026-09-08T10:15:00.000Z'));
 test('Jerusalem spring gap is not silently adjusted',()=>assert.deepEqual(possibleInstants('2026-03-27T02:30'),[]));
 test('Jerusalem autumn fold requires one of two instants',()=>assert.deepEqual(possibleInstants('2026-10-25T01:30'),['2026-10-24T22:30:00.000Z','2026-10-24T23:30:00.000Z']));
 test('ordinary Jerusalem local time has one instant',()=>assert.deepEqual(possibleInstants('2026-09-07T13:00'),['2026-09-07T10:00:00.000Z']));
 for(const bad of ['2026-02-30T12:00','2026-09-07T25:00','2026-13-01T12:00','2026-09-07 12:00'])test(`reject invalid local date ${bad}`,()=>rejects(()=>possibleInstants(bad),'INVALID_REQUEST'));
 for(const bad of ['2026-09-07T12:00:00','2026-02-30T12:00:00Z','not-a-date'])test(`reject invalid/naive instant ${bad}`,()=>rejects(()=>iso(bad),'INVALID_REQUEST'));
 test('month produces 42 civil days without assuming 24h days',()=>{const r=dateRange('2026-03-27','month');assert.equal(r.dates.length,42);assert.equal(civilDate(r.from),r.dates[0]);assert.equal(civilDate(r.to),shiftDay(r.dates[41]!,1));});
 test('DST spring civil day is 23h',()=>{const r=dateRange('2026-03-27','day');assert.equal(Date.parse(r.to)-Date.parse(r.from),23*3_600_000);});
 test('DST autumn civil day is 25h',()=>{const r=dateRange('2026-10-25','day');assert.equal(Date.parse(r.to)-Date.parse(r.from),25*3_600_000);});
 test('adjacent half-open appointments do not overlap',()=>assert.equal(overlaps('2026-09-08T10:00:00Z','2026-09-08T11:00:00Z','2026-09-08T11:00:00Z','2026-09-08T12:00:00Z'),false));
 test('one millisecond overlap conflicts',()=>assert.equal(overlaps('2026-09-08T10:00:00Z','2026-09-08T11:00:00.001Z','2026-09-08T11:00:00Z','2026-09-08T12:00:00Z'),true));
 test('padding expands conflict bounds',()=>assert.deepEqual(paddedSlot({...appointment,bufferBefore:10,bufferAfter:15}),{startsAt:'2026-09-08T09:50:00.000Z',endsAt:'2026-09-08T11:15:00.000Z'}));
 const window={id:uuid(20),kind:'open' as const,startsAt:'2026-09-08T09:00:00Z',endsAt:'2026-09-08T12:00:00Z',version:1};
 test('configured free slot is allowed',()=>assert.doesNotThrow(()=>assertAvailable(appointment,[window],[])));
 test('no configured availability fails closed',()=>rejects(()=>assertAvailable(appointment,[],[]),'CONFLICT'));
 test('blocked time takes precedence over open time',()=>rejects(()=>assertAvailable(appointment,[window,{...window,kind:'blocked'}],[]),'CONFLICT'));
 test('padded neighboring appointment blocks slot',()=>rejects(()=>assertAvailable(appointment,[window],[{startsAt:'2026-09-08T10:59:00Z',endsAt:'2026-09-08T12:00:00Z'}]),'CONFLICT'));
 test('owner practitioner reads appointment',()=>assert.doesNotThrow(()=>authorizeAppointment(practitioner,facts,guardians,audience,appointment,true)));
 test('authorized published guardian reads appointment',()=>assert.doesNotThrow(()=>authorizeAppointment(parent,facts,guardians,audience,appointment)));
 test('second authorized guardian has independent access',()=>assert.doesNotThrow(()=>authorizeAppointment(parentTwo,facts,guardians,audience,appointment)));
 test('parent cannot write practitioner-only attendance',()=>rejects(()=>authorizeAppointment(parent,facts,guardians,audience,appointment,true),'NOT_FOUND'));
 test('revoked account has no appointment access',()=>rejects(()=>authorizeAppointment({...parent,state:'revoked'},facts,guardians,audience,appointment),'NOT_FOUND'));
 test('revoked case guardian cannot use retained audience',()=>rejects(()=>authorizeAppointment(parent,facts,guardians.map(g=>({...g,revoked:true})),audience,appointment),'NOT_FOUND'));
 test('membership without explicit audience does not disclose appointment',()=>rejects(()=>authorizeAppointment(parent,facts,guardians,{...audience,accountIds:[]},appointment),'NOT_FOUND'));
 test('unpublished audience is denied to parent',()=>rejects(()=>authorizeAppointment(parent,facts,guardians,{...audience,published:false},appointment),'NOT_FOUND'));
 test('private audience is denied to parent',()=>rejects(()=>authorizeAppointment(parent,facts,guardians,{...audience,visibility:'private'},appointment),'NOT_FOUND'));
 test('cross-workspace scope is uniformly absent',()=>rejects(()=>authorizeAppointment({...parent,workspaceId:asId(uuid(99),'workspace')},facts,guardians,audience,appointment),'NOT_FOUND'));
 test('cross-case audience is uniformly absent',()=>rejects(()=>authorizeAppointment(parent,facts,guardians,{...audience,caseId:asId(uuid(98),'case')},appointment),'NOT_FOUND'));
 test('different practitioner is uniformly absent',()=>rejects(()=>authorizeAppointment({...practitioner,id:asId(uuid(97),'account')},facts,guardians,audience,appointment,true),'NOT_FOUND'));
 test('null case and audience do not reveal existence',()=>rejects(()=>authorizeAppointment(parent,null,guardians,null,appointment),'NOT_FOUND'));
 test('valid child booking consumes the shared policy',()=>assert.equal(validateBooking(practitioner,facts,guardians,audience,booking,'2026-09-07T10:00:00Z').endsAt,appointment.endsAt));
 test('parent cannot create booking',()=>rejects(()=>validateBooking(parent,facts,guardians,audience,booking,'2026-09-07T10:00:00Z'),'FORBIDDEN'));
 for(const state of ['paused','completed','archived'] as const)test(`cannot create new appointment in ${state} case`,()=>rejects(()=>validateBooking(practitioner,{...facts,state},guardians,audience,booking,'2026-09-07T10:00:00Z'),'CONFLICT'));
 test('adult client case permits an individual appointment',()=>assert.equal(validateBooking(practitioner,{...facts,kind:'adult'},[],audience,booking,'2026-09-07T10:00:00Z').endsAt,appointment.endsAt));
 test('adult client case cannot be booked as parent guidance',()=>rejects(()=>validateBooking(practitioner,{...facts,kind:'adult'},[],audience,{...booking,kind:'parent_guidance',parentForId:appointment.id,parentIds:[parent.id]},'2026-09-07T10:00:00Z'),'INVALID_REQUEST'));
 for(const parentIds of [[parent.id],[parent.id,parentTwo.id]])test(`joint-parent check-in permits ${parentIds.length} explicit guardian(s)`,()=>assert.equal(validateBooking(practitioner,facts,guardians,audience,{...booking,kind:'parent_guidance',parentForId:appointment.id,parentIds},'2026-09-07T10:00:00Z').endsAt,'2026-09-08T10:15:00.000Z'));
 test('duplicate parent participants are rejected',()=>rejects(()=>validateBooking(practitioner,facts,guardians,audience,{...booking,kind:'parent_guidance',parentForId:appointment.id,parentIds:[parent.id,parent.id]},'2026-09-07T10:00:00Z'),'INVALID_REQUEST'));
 test('unlinked parent check-in is rejected',()=>rejects(()=>validateBooking(practitioner,facts,guardians,audience,{...booking,kind:'parent_guidance',parentIds:[parent.id]},'2026-09-07T10:00:00Z'),'INVALID_REQUEST'));
 test('unpublished booking is rejected, not silently published',()=>rejects(()=>validateBooking(practitioner,facts,guardians,{...audience,published:false},booking,'2026-09-07T10:00:00Z'),'INVALID_REQUEST'));
 test('booking does not accept an invalid buffer',()=>rejects(()=>validateBooking(practitioner,facts,guardians,audience,{...booking,bufferAfter:-1},'2026-09-07T10:00:00Z'),'INVALID_REQUEST'));
 test('booking must be future-facing',()=>rejects(()=>validateBooking(practitioner,facts,guardians,audience,booking,appointment.startsAt),'INVALID_REQUEST'));
 test('parent proposed windows do not reserve a slot',()=>{const fields=makeNoticeFields(appointment,{kind:'reschedule',proposedWindows:[{startsAt:'2026-09-09T10:00:00Z',endsAt:'2026-09-09T12:00:00Z'}]},'2026-09-07T10:00:00Z','2026-09-07T11:00:00Z');assert.equal(fields.eligibility,'credit_preserved');assert.equal(fields.receivedAt,'2026-09-07T10:00:00.000Z');assert.equal(fields.originalStart,appointment.startsAt);assert.equal(fields.termsVersion,appointment.termsVersion);assert.equal('replacementId' in fields,false);});
 test('processing delay never moves received notice past deadline',()=>assert.equal(makeNoticeFields(appointment,{kind:'cancel',proposedWindows:[]},'2026-09-07T10:00:00Z','2026-09-07T12:00:00Z').noticeMilliseconds,86_400_000));
 test('future manual received time is rejected',()=>rejects(()=>makeNoticeFields(appointment,{kind:'cancel',proposedWindows:[]},'2026-09-07T12:01:00Z','2026-09-07T12:00:00Z'),'INVALID_REQUEST'));
 test('manual receipt cannot predate the original booking',()=>rejects(()=>makeNoticeFields(appointment,{kind:'cancel',proposedWindows:[]},'2026-08-01T12:00:00Z','2026-09-07T12:00:00Z'),'INVALID_REQUEST'));
 test('cancel notice cannot smuggle replacement windows',()=>rejects(()=>validateWindows({kind:'cancel',proposedWindows:[{startsAt:appointment.startsAt,endsAt:appointment.endsAt}]}),'INVALID_REQUEST'));
 for(const state of ['present','late','no_show','canceled'] as const)test(`attendance meaning: ${state}`,()=>{assert.equal(attended(state),state==='present'||state==='late');assert.equal(countsAsChildSession('individual',state),state==='present'||state==='late');assert.equal(countsAsChildSession('parent_guidance',state),false);});
 test('late arrival counts as attendance',()=>assert.equal(validateAttendance(appointment,null,{state:'late',arrivedAt:'2026-09-08T10:05:00Z',expectedVersion:0,correctionReason:null},'2026-09-08T12:00:00Z').attended,true));
 test('no-show only after scheduled end',()=>rejects(()=>validateAttendance(appointment,null,{state:'no_show',arrivedAt:null,expectedVersion:0,correctionReason:null},'2026-09-08T10:59:59Z'),'CONFLICT'));
 test('no-show at exact end counts as non-attendance',()=>assert.equal(validateAttendance(appointment,null,{state:'no_show',arrivedAt:null,expectedVersion:0,correctionReason:null},appointment.endsAt).attended,false));
 test('no attendance can be recorded in advance as present',()=>rejects(()=>validateAttendance(appointment,null,{state:'present',arrivedAt:appointment.startsAt,expectedVersion:0,correctionReason:null},'2026-09-08T09:00:00Z'),'INVALID_REQUEST'));
 test('late state requires actual late arrival',()=>rejects(()=>validateAttendance(appointment,null,{state:'late',arrivedAt:appointment.startsAt,expectedVersion:0,correctionReason:null},'2026-09-08T12:00:00Z'),'INVALID_REQUEST'));
 test('present state cannot hide a late arrival',()=>rejects(()=>validateAttendance(appointment,null,{state:'present',arrivedAt:'2026-09-08T10:10:00Z',expectedVersion:0,correctionReason:null},'2026-09-08T12:00:00Z'),'INVALID_REQUEST'));
 const previous={state:'no_show' as const,attended:false,arrivedAt:null,version:1,recordedAt:'2026-09-08T11:00:00Z',recordedBy:practitioner.id};
 test('correction requires the exact attendance version',()=>rejects(()=>validateAttendance(appointment,previous,{state:'late',arrivedAt:'2026-09-08T10:10:00Z',expectedVersion:0,correctionReason:'Synthetic correction'},'2026-09-08T12:00:00Z'),'CONFLICT'));
 test('correction requires a recorded administrative reason',()=>rejects(()=>validateAttendance(appointment,previous,{state:'late',arrivedAt:'2026-09-08T10:10:00Z',expectedVersion:1,correctionReason:null},'2026-09-08T12:00:00Z'),'INVALID_REQUEST'));
 test('correction creates a new version without mutating the original object',()=>{const corrected=validateAttendance(appointment,previous,{state:'late',arrivedAt:'2026-09-08T10:10:00Z',expectedVersion:1,correctionReason:'Synthetic operational correction'},'2026-09-08T12:00:00Z');assert.equal(corrected.version,2);assert.equal(previous.state,'no_show');assert.equal(corrected.attended,true);});
 test('canonical hashing ignores object property order, not array order',()=>{assert.equal(canonical({b:2,a:1}),canonical({a:1,b:2}));assert.notEqual(canonical([1,2]),canonical([2,1]));});
}
