export const ACADEMY_CALENDAR_ID='62846b7290bb5793c0a65df75709b759ae9c23495700df272e398f57e4d8d21d@group.calendar.google.com' as const;
export const ACADEMY_TIME_ZONE='Asia/Jerusalem' as const;
export type AppointmentType='child'|'parent_call';
export type AppointmentStatus='pending'|'confirmed'|'canceled'|'reschedule_pending'|'conflict';
export type ConferenceSource='google_meet'|'zoom_verified'|'practitioner_supplied'|'none';
export interface EligibilityFacts { consentCleared:boolean; paymentVerified:boolean; payAtSessionApproved:boolean; consumed?:boolean; revoked?:boolean; }
export type EligibilityReason='consent_pending'|'payment_pending'|'paid'|'approved_pay_at_session'|'consumed'|'revoked';
export interface BookingEligibility { eligible:boolean; reason:EligibilityReason; paymentDue:boolean; }
export interface CalendarEvent { id:string; recurringEventId?:string; start:string; end:string; status?:'confirmed'|'cancelled'; location?:string; hangoutLink?:string; conferenceData?:{entryPoints?:Array<{entryPointType?:string;uri?:string}>}; }
export interface CalendarProvider { listEvents(input:{calendarId:string;timeMin:string;timeMax:string;timeZone:string}):Promise<CalendarEvent[]>; createEvent?(input:{calendarId:string;start:string;end:string;timeZone:string;type:AppointmentType}):Promise<CalendarEvent>; }
export interface BookingRequest { requestId:string; entitlementId:string; participantId:string; type:AppointmentType; start:string; idempotencyKey:string; location?:string; }
export interface ManualReview { state:'manual_review'; reason:'booking_url_unverified'|'provider_unavailable'|'payment_due'|'conflict'; calendarId:string; timeZone:string; paymentDue:boolean; instructions:string[]; }
export function createManualReview(reason:ManualReview['reason'], paymentDue=false):ManualReview{return {state:'manual_review',reason,calendarId:ACADEMY_CALENDAR_ID,timeZone:ACADEMY_TIME_ZONE,paymentDue,instructions:['Verify consent clearance and paid or practitioner-approved cash-at-session entitlement.','Check bounded free/busy on the Academy calendar with existing buffers and date exceptions.','Recheck immediately before staff reconciliation; do not mark BOOKED without a stable confirmed provider event ID.','Send only an owner-verified booking URL or coordinate manually; never invent a location or join link.']};}
export interface AppointmentModel { id:string; calendarId:string; occurrenceKey:string; time:{start:string;end:string;timeZone:string}; type:AppointmentType; durationMinutes:60|15; status:AppointmentStatus; location?:string; joinLink?:string; conferenceSource:ConferenceSource; cancellation:{state:'none'|'requested'|'synced';requestedAt?:string}; reschedule:{state:'none'|'requested'}; participants:{id:string;authorized:boolean;declined:boolean}[]; providerEventId?:string; recurringEventId?:string; }
export function getBookingEligibility(f:EligibilityFacts):BookingEligibility { if(f.revoked)return {eligible:false,reason:'revoked',paymentDue:false}; if(f.consumed)return {eligible:false,reason:'consumed',paymentDue:false}; if(!f.consentCleared)return {eligible:false,reason:'consent_pending',paymentDue:false}; if(f.paymentVerified)return {eligible:true,reason:'paid',paymentDue:false}; if(f.payAtSessionApproved)return {eligible:true,reason:'approved_pay_at_session',paymentDue:true}; return {eligible:false,reason:'payment_pending',paymentDue:false}; }
export function durationFor(type:AppointmentType):60|15{return type==='child'?60:15;}
const APPROVED_ZOOM_HOSTS=new Set(['zoom.us','www.zoom.us']);
function verifiedUrl(raw?:string):{joinLink?:string;source:ConferenceSource}{ if(!raw)return {source:'none'}; try { const u=new URL(raw); if(u.protocol!=='https:')return {source:'none'}; if(u.hostname.toLowerCase()==='meet.google.com')return {joinLink:u.toString(),source:'google_meet'}; if(APPROVED_ZOOM_HOSTS.has(u.hostname.toLowerCase()))return {joinLink:u.toString(),source:'zoom_verified'}; } catch {} return {source:'none'}; }
function conference(event:CalendarEvent):{joinLink?:string;source:ConferenceSource}{ const ep=event.conferenceData?.entryPoints?.find(e=>e.entryPointType==='video'&&e.uri); return verifiedUrl(ep?.uri??event.location); }
export class AcademyCalendarAdapter { private readonly reservations=new Map<string,AppointmentModel>(); private readonly fingerprints=new Map<string,string>(); private readonly entitlementKeys=new Map<string,string>(); private readonly cancellations=new Map<string,string>(); private readonly provider:CalendarProvider; private readonly rules:{bufferBeforeMinutes?:number;bufferAfterMinutes?:number}; private queue:Promise<unknown>=Promise.resolve(); constructor(provider:CalendarProvider,rules:{bufferBeforeMinutes?:number;bufferAfterMinutes?:number}={}){this.provider=provider;this.rules=rules;}
 private serialize<T>(fn:()=>Promise<T>):Promise<T>{const run=this.queue.then(fn,fn); this.queue=run.then(()=>undefined,()=>undefined); return run;}
 async reserveAppointment(req:BookingRequest, facts:EligibilityFacts):Promise<AppointmentModel>{ return this.serialize(async()=>{ const fingerprint=JSON.stringify({requestId:req.requestId,entitlementId:req.entitlementId,participantId:req.participantId,type:req.type,start:req.start,location:req.location??''}); const prior=this.reservations.get(req.idempotencyKey); if(prior){if(this.fingerprints.get(req.idempotencyKey)!==fingerprint)throw new Error('idempotency_conflict');return structuredClone(prior);} const consumedKey=this.entitlementKeys.get(req.entitlementId); if(consumedKey&&consumedKey!==req.idempotencyKey)throw new Error('entitlement_consumed'); const eligibility=getBookingEligibility(facts); if(!eligibility.eligible)throw new Error(eligibility.reason); const duration=durationFor(req.type), startMs=Date.parse(req.start); if(!Number.isFinite(startMs))throw new Error('invalid_start'); const endMs=startMs+duration*60000, end=new Date(endMs).toISOString(), min=new Date(startMs-(this.rules.bufferBeforeMinutes??0)*60000).toISOString(), max=new Date(endMs+(this.rules.bufferAfterMinutes??0)*60000).toISOString(); const events=await this.provider.listEvents({calendarId:ACADEMY_CALENDAR_ID,timeMin:min,timeMax:max,timeZone:ACADEMY_TIME_ZONE}); if(events.some(e=>e.status!=='cancelled'&&Date.parse(e.start)<Date.parse(max)&&Date.parse(e.end)>Date.parse(min)))throw new Error('conflict'); const model:AppointmentModel={id:req.requestId,calendarId:ACADEMY_CALENDAR_ID,occurrenceKey:`local:${req.requestId}`,time:{start:req.start,end,timeZone:ACADEMY_TIME_ZONE},type:req.type,durationMinutes:duration,status:'pending',...(req.location?{location:req.location}:{}),conferenceSource:'none',cancellation:{state:'none'},reschedule:{state:'none'},participants:[{id:req.participantId,authorized:true,declined:false}]}; this.reservations.set(req.idempotencyKey,model); this.fingerprints.set(req.idempotencyKey,fingerprint); this.entitlementKeys.set(req.entitlementId,req.idempotencyKey); return structuredClone(model); }); }
 applyCalendarEventChange(binding:{idempotencyKey:string;providerEvent:CalendarEvent}):AppointmentModel { const model=this.reservations.get(binding.idempotencyKey); if(!model)throw new Error('unknown_reservation'); const event=binding.providerEvent; if(!event||typeof event.id!=='string'||!event.id.trim()||!['confirmed','cancelled'].includes(event.status??''))throw new Error('malformed_provider_response'); if(model.providerEventId&&model.providerEventId!==event.id)throw new Error('provider_event_conflict'); if(Date.parse(event.start)!==Date.parse(model.time.start)||Date.parse(event.end)!==Date.parse(model.time.end))throw new Error('provider_time_mismatch'); const c=conference(event); model.providerEventId=event.id; if(event.recurringEventId)model.recurringEventId=event.recurringEventId; model.occurrenceKey=`${event.recurringEventId??event.id}:${event.recurringEventId?(event.start):'single'}`; model.status=event.status==='cancelled'?'canceled':'confirmed'; if(event.status==='cancelled'&&model.cancellation.state==='requested')model.cancellation={...model.cancellation,state:'synced'}; if(event.location)model.location=event.location; else delete model.location; if(c.joinLink)model.joinLink=c.joinLink; else delete model.joinLink; model.conferenceSource=c.source; return structuredClone(model); }
 recordCancellationNotice(id:string,noticedAt:string):AppointmentModel { const m=[...this.reservations.values()].find(x=>x.id===id); if(!m)throw new Error('unknown_reservation'); const prior=this.cancellations.get(id); if(!prior||noticedAt<prior)this.cancellations.set(id,noticedAt); m.cancellation={state:'requested',requestedAt:this.cancellations.get(id)}; return structuredClone(m); }
 setParticipant(id:string,participantId:string,authorized:boolean,declined:boolean){const m=[...this.reservations.values()].find(x=>x.id===id);if(!m||m.type!=='parent_call')throw new Error('unknown_reservation');if(!authorized&&declined)m.participants=m.participants.filter(p=>p.id!==participantId);else {if(!authorized)throw new Error('unauthorized_participant');const existing=m.participants.find(p=>p.id===participantId);if(existing)existing.declined=declined;else m.participants.push({id:participantId,authorized:true,declined});}return structuredClone(m);}
 get(idempotencyKey:string){const m=this.reservations.get(idempotencyKey);return m?structuredClone(m):undefined;}
}
