export const ACADEMY_CALENDAR_ID='62846b7290bb5793c0a65df75709b759ae9c23495700df272e398f57e4d8d21d@group.calendar.google.com' as const;
export const ACADEMY_TIME_ZONE='Asia/Jerusalem' as const;
export type AppointmentType='child'|'parent_call';
export type AppointmentStatus='pending'|'confirmed'|'canceled'|'reschedule_pending'|'conflict';
export type ConferenceSource='google_meet'|'zoom_verified'|'practitioner_supplied'|'none';
export interface EligibilityFacts { consentCleared:boolean; paymentVerified:boolean; payAtSessionApproved:boolean; consumed?:boolean; revoked?:boolean; }
export type EligibilityReason='consent_pending'|'payment_pending'|'paid'|'approved_pay_at_session'|'consumed'|'revoked';
export interface BookingEligibility { eligible:boolean; reason:EligibilityReason; paymentDue:boolean; }
export interface CalendarEvent { id:string; recurringEventId?:string; start:string; end:string; status?:'confirmed'|'cancelled'; location?:string; hangoutLink?:string; conferenceData?:{entryPoints?:Array<{entryPointType?:string;uri?:string}>}; }
export interface CalendarProvider { listEvents(input:{calendarId:string;timeMin:string;timeMax:string;timeZone:string}):Promise<CalendarEvent[]>; createEvent?:never; }
export interface BookingRequest { requestId:string; entitlementId:string; participantId:string; type:AppointmentType; start:string; idempotencyKey:string; location?:string; }
export interface AppointmentModel { id:string; calendarId:string; time:{start:string;end:string;timeZone:string}; type:AppointmentType; durationMinutes:60|15; status:AppointmentStatus; location?:string; joinLink?:string; conferenceSource:ConferenceSource; cancellation:{state:'none'|'requested'|'synced';requestedAt?:string}; reschedule:{state:'none'|'requested'}; providerEventId?:string; recurringEventId?:string; }
export function getBookingEligibility(f:EligibilityFacts):BookingEligibility { if(f.revoked)return {eligible:false,reason:'revoked',paymentDue:false}; if(f.consumed)return {eligible:false,reason:'consumed',paymentDue:false}; if(!f.consentCleared)return {eligible:false,reason:'consent_pending',paymentDue:false}; if(f.paymentVerified)return {eligible:true,reason:'paid',paymentDue:false}; if(f.payAtSessionApproved)return {eligible:true,reason:'approved_pay_at_session',paymentDue:true}; return {eligible:false,reason:'payment_pending',paymentDue:false}; }
export function durationFor(type:AppointmentType):60|15{return type==='child'?60:15;}
function conference(event:CalendarEvent):{joinLink?:string;source:ConferenceSource}{ const ep=event.conferenceData?.entryPoints?.find(e=>e.entryPointType==='video'&&e.uri); if(ep?.uri&&/meet\.google\.com/i.test(ep.uri))return {joinLink:ep.uri,source:'google_meet'}; if(event.location&&/^https:\/\/zoom\.us\//i.test(event.location))return {joinLink:event.location,source:'zoom_verified'}; if(event.location&&/^https:\/\//i.test(event.location))return {joinLink:event.location,source:'practitioner_supplied'}; return {source:'none'}; }
export class AcademyCalendarAdapter { private readonly reservations=new Map<string,AppointmentModel>(); private readonly cancellations=new Map<string,string>(); constructor(private readonly provider:CalendarProvider,private readonly rules:{bufferBeforeMinutes?:number;bufferAfterMinutes?:number}={}){}
 async reserveAppointment(req:BookingRequest, facts:EligibilityFacts):Promise<AppointmentModel>{ const eligibility=getBookingEligibility(facts); if(!eligibility.eligible)throw new Error(eligibility.reason); const prior=this.reservations.get(req.idempotencyKey); if(prior)return structuredClone(prior); const duration=durationFor(req.type), startMs=Date.parse(req.start), end=new Date(startMs+duration*60000).toISOString(); if(!Number.isFinite(startMs))throw new Error('invalid_start'); const min=new Date(startMs-(this.rules.bufferBeforeMinutes??0)*60000).toISOString(), max=new Date(Date.parse(end)+(this.rules.bufferAfterMinutes??0)*60000).toISOString(); const events=await this.provider.listEvents({calendarId:ACADEMY_CALENDAR_ID,timeMin:min,timeMax:max,timeZone:ACADEMY_TIME_ZONE}); if(events.some(e=>e.status!=='cancelled'&&Date.parse(e.start)<Date.parse(max)&&Date.parse(e.end)>Date.parse(min))){throw new Error('conflict');} const model:AppointmentModel={id:req.requestId,calendarId:ACADEMY_CALENDAR_ID,time:{start:req.start,end,timeZone:ACADEMY_TIME_ZONE},type:req.type,durationMinutes:duration,status:'pending',...(req.location?{location:req.location}:{}),conferenceSource:'none',cancellation:{state:'none'},reschedule:{state:'none'}}; this.reservations.set(req.idempotencyKey,model); return structuredClone(model); }
 applyCalendarEventChange(binding:{idempotencyKey:string;providerEvent:CalendarEvent}):AppointmentModel { const model=this.reservations.get(binding.idempotencyKey); if(!model)throw new Error('unknown_reservation'); const c=conference(binding.providerEvent); model.providerEventId=binding.providerEvent.id; if(binding.providerEvent.recurringEventId)model.recurringEventId=binding.providerEvent.recurringEventId; model.status=binding.providerEvent.status==='cancelled'?'canceled':'confirmed'; if(binding.providerEvent.location)model.location=binding.providerEvent.location; else delete model.location; if(c.joinLink)model.joinLink=c.joinLink; else delete model.joinLink; model.conferenceSource=c.source; return structuredClone(model); }
 recordCancellationNotice(id:string,noticedAt:string):AppointmentModel { const m=[...this.reservations.values()].find(x=>x.id===id); if(!m)throw new Error('unknown_reservation'); const prior=this.cancellations.get(id); if(!prior||noticedAt<prior)this.cancellations.set(id,noticedAt); m.cancellation={state:'requested',requestedAt:this.cancellations.get(id)}; m.status='canceled'; return structuredClone(m); }
 get(idempotencyKey:string){const m=this.reservations.get(idempotencyKey);return m?structuredClone(m):undefined;}
}
