import type { ReactElement } from "react";
import { beforeEach, expect, it, vi } from "vitest";

type Slot = { k: "s"; v: unknown } | { k: "r"; v: { current: unknown } } | { k: "e"; d: readonly unknown[] | undefined; c: (() => void) | undefined };
const hook = vi.hoisted(() => { const slots: Slot[] = [], effects: Array<{ i: number; f: () => void | (() => void) }> = []; let cursor = 0, mounted = true, afterUnmount = 0; const changed = (a: readonly unknown[] | undefined, b: readonly unknown[] | undefined) => !a || !b || a.length !== b.length || a.some((v, i) => v !== b[i]); return { reset() { slots.length = 0; effects.length = 0; cursor = 0; mounted = true; afterUnmount = 0; }, render<T>(f: () => T) { cursor = 0; return f(); }, flush() { for (const next of effects.splice(0)) { const slot = slots[next.i]; if (slot?.k === "e") { slot.c?.(); slot.c = next.f() || undefined; } } }, unmount() { mounted = false; for (const slot of slots) if (slot?.k === "e") slot.c?.(); }, afterUnmount: () => afterUnmount, useState<T>(initial: T) { const i = cursor++; let slot = slots[i]; if (!slot) { slot = { k: "s", v: initial }; slots[i] = slot; } if (slot.k !== "s") throw Error("HOOK_ORDER"); return [slot.v as T, (value: T | ((previous: T) => T)) => { if (!mounted) { afterUnmount++; return; } slot.v = typeof value === "function" ? (value as (previous: T) => T)(slot.v as T) : value; }] as const; }, useRef<T>(initial: T) { const i = cursor++; let slot = slots[i]; if (!slot) { slot = { k: "r", v: { current: initial } }; slots[i] = slot; } if (slot.k !== "r") throw Error("HOOK_ORDER"); return slot.v as { current: T }; }, useEffect(f: () => void | (() => void), d?: readonly unknown[]) { const i = cursor++, slot = slots[i]; if (!slot) { slots[i] = { k: "e", d, c: undefined }; effects.push({ i, f }); return; } if (slot.k !== "e") throw Error("HOOK_ORDER"); if (changed(slot.d, d)) { slot.d = d; effects.push({ i, f }); } } }; });
const sessionInfo = vi.hoisted(() => vi.fn(async () => ({ csrfToken: "c".repeat(43) })));
const fetchMock = vi.hoisted(() => vi.fn());
vi.mock("react", async original => { const actual = await original<typeof import("react")>(); return { ...actual, useEffect: hook.useEffect, useRef: hook.useRef, useState: hook.useState }; });
vi.mock("../../src/features/identity/client.ts", () => ({ sessionInfo }));
import { CaseAccessBody } from "../../src/features/identity/case-access.tsx";

const caseId = "123e4567-e89b-12d3-a456-426614174000", accountId = "223e4567-e89b-12d3-a456-426614174000";
const tick = async () => { for (let i = 0; i < 12; i++) await Promise.resolve(); };
type Change = (event: { target: { value: string; checked?: boolean } }) => void;
type Click = () => void;
function renderFor(id = caseId) { return hook.render(() => CaseAccessBody({ locale: "en", caseId: id })); }
function render() { return renderFor(); }
function find(node: unknown, predicate: (item: ReactElement<Record<string, unknown>>) => boolean): ReactElement<Record<string, unknown>> | undefined { if (!node || typeof node !== "object") return undefined; if (Array.isArray(node)) return node.map(item => find(item, predicate)).find(Boolean); const item = node as ReactElement<Record<string, unknown>>; return predicate(item) ? item : find(item.props?.children, predicate); }
function text(node: unknown): string { if (node === null || node === undefined || typeof node === "boolean") return ""; if (typeof node === "string" || typeof node === "number") return String(node); if (Array.isArray(node)) return node.map(text).join(""); return text((node as ReactElement<{ children?: unknown }>).props?.children); }
function member() { return { accountId, displayName: "Synthetic Parent", email: "parent@example.invalid", locale: "en", role: "parent", state: "active", guardianRevokedAt: null }; }
beforeEach(() => { hook.reset(); sessionInfo.mockClear(); fetchMock.mockReset(); vi.stubGlobal("fetch", fetchMock); });

it("renders only human member facts and never a raw internal identifier", async () => { fetchMock.mockResolvedValue(Response.json({ ok: true, data: { caseId, kind: "minor", members: [member()] } })); render(); hook.flush(); await tick(); const output = render(); expect(text(output)).toContain("Synthetic Parent"); expect(text(output)).toContain("parent@example.invalid"); expect(text(output)).not.toContain(caseId); expect(text(output)).not.toContain(accountId); });

it("shows a revoked parent state without offering another revoke action", async () => { fetchMock.mockResolvedValue(Response.json({ ok: true, data: { caseId, kind: "minor", members: [{ ...member(), state: "revoked", guardianRevokedAt: "2026-09-18T00:00:00.000Z" }] } })); render(); hook.flush(); await tick(); const output = render(); expect(text(output)).toContain("Revoked"); expect(find(output, item => item.type === "button" && item.props.children === "Revoke case access")).toBeUndefined(); });

it("does not send an invite until the practitioner explicitly confirms the access grant", async () => { fetchMock.mockImplementation(async (_url: string, init?: RequestInit) => init?.method === "POST" ? Response.json({ ok: true, data: {} }) : Response.json({ ok: true, data: { caseId, kind: "minor", members: [] } })); render(); hook.flush(); await tick(); let output = render(); const inputs = collect(output, item => item.type === "input"); (inputs[0]!.props.onChange as Change)({ target: { value: "Synthetic Parent" } }); (inputs[1]!.props.onChange as Change)({ target: { value: "parent@example.invalid" } }); output = render(); (find(output, item => item.type === "button" && item.props.children === "Send invitation")?.props.onClick as Click)(); await tick(); expect(posts()).toHaveLength(0); const checkbox = collect(output, item => item.type === "input" && item.props.type === "checkbox")[0]!; (checkbox.props.onChange as Change)({ target: { value: "", checked: true } }); output = render(); (find(output, item => item.type === "button" && item.props.children === "Send invitation")?.props.onClick as Click)(); await tick(); expect(posts()).toHaveLength(1); expect(posts()[0]!.url).toBe("/api/identity/invites/parent"); expect(posts()[0]!.init.headers).toMatchObject({ "X-CSRF-Token": "c".repeat(43) }); });

it("offers the independent child invitation only when enabled and uses its protected route", async () => { fetchMock.mockImplementation(async (_url: string, init?: RequestInit) => init?.method === "POST" ? Response.json({ ok: true, data: {} }) : Response.json({ ok: true, data: { caseId, kind: "minor", childAccountsEnabled: true, members: [] } })); render(); hook.flush(); await tick(); let output = render(); expect(text(output)).toContain("Child account"); const selects = collect(output, item => item.type === "select"); (selects[0]!.props.onChange as Change)({ target: { value: "child" } }); const inputs = collect(output, item => item.type === "input"); (inputs[0]!.props.onChange as Change)({ target: { value: "Synthetic Child" } }); (inputs[1]!.props.onChange as Change)({ target: { value: "child@example.invalid" } }); (collect(output, item => item.type === "input" && item.props.type === "checkbox")[0]!.props.onChange as Change)({ target: { value: "", checked: true } }); output = render(); (find(output, item => item.type === "button" && item.props.children === "Send invitation")?.props.onClick as Click)(); await tick(); expect(posts()).toHaveLength(1); expect(posts()[0]!.url).toBe("/api/identity/invites/child"); });

it("requires a second explicit revoke confirmation and keeps parent revocation case-only", async () => { fetchMock.mockImplementation(async (_url: string, init?: RequestInit) => init?.method === "POST" ? Response.json({ ok: true, data: {} }) : Response.json({ ok: true, data: { caseId, kind: "minor", members: [member()] } })); render(); hook.flush(); await tick(); let output = render(); (find(output, item => item.type === "button" && item.props.children === "Revoke access")?.props.onClick as Click)(); await tick(); expect(posts()).toHaveLength(0); output = render(); expect(text(output)).toContain("Parent access is case-specific"); (find(output, item => item.type === "button" && item.props.children === "Confirm revoke access")?.props.onClick as Click)(); await tick(); expect(posts()).toHaveLength(1); expect(posts()[0]!.url).toBe("/api/identity/guardians/revoke"); expect(JSON.parse(String(posts()[0]!.init.body))).toEqual({ caseId, accountId }); });

it("revokes an independent child account and its sessions rather than only one case grant", async () => { fetchMock.mockImplementation(async (_url: string, init?: RequestInit) => init?.method === "POST" ? Response.json({ ok: true, data: {} }) : Response.json({ ok: true, data: { caseId, kind: "minor", childAccountsEnabled: true, members: [{ ...member(), role: "child" }] } })); render(); hook.flush(); await tick(); let output = render(); (find(output, item => item.type === "button" && item.props.children === "Revoke access")?.props.onClick as Click)(); output = render(); (find(output, item => item.type === "button" && item.props.children === "Confirm revoke access")?.props.onClick as Click)(); await tick(); expect(posts()).toHaveLength(1); expect(posts()[0]!.url).toBe("/api/identity/accounts/revoke"); expect(JSON.parse(String(posts()[0]!.init.body))).toEqual({ accountId }); });

it("suppresses delayed access results after unmount", async () => { let resolve!: (response: Response) => void; fetchMock.mockImplementationOnce(() => new Promise<Response>(done => { resolve = done; })); render(); hook.flush(); hook.unmount(); resolve(Response.json({ ok: true, data: { caseId, kind: "minor", members: [member()] } })); await tick(); expect(hook.afterUnmount()).toBe(0); });

it("does not show a delayed prior-case access result after a case switch", async () => { const nextCase = "323e4567-e89b-12d3-a456-426614174000"; let resolveOld!: (response: Response) => void, resolveNew!: (response: Response) => void; fetchMock.mockImplementation((url: string) => url.includes(caseId) ? new Promise<Response>(done => { resolveOld = done; }) : new Promise<Response>(done => { resolveNew = done; })); renderFor(caseId); hook.flush(); renderFor(nextCase); hook.flush(); resolveNew(Response.json({ ok: true, data: { caseId: nextCase, kind: "minor", members: [{ ...member(), displayName: "Synthetic New" }] } })); await tick(); let output = renderFor(nextCase); expect(text(output)).toContain("Synthetic New"); resolveOld(Response.json({ ok: true, data: { caseId, kind: "minor", members: [member()] } })); await tick(); output = renderFor(nextCase); expect(text(output)).toContain("Synthetic New"); expect(text(output)).not.toContain("Synthetic Parent"); });

it("locks same-tick invite double clicks to one write", async () => { let resolve!: (response: Response) => void; fetchMock.mockImplementation((_url: string, init?: RequestInit) => init?.method === "POST" ? new Promise<Response>(done => { resolve = done; }) : Promise.resolve(Response.json({ ok: true, data: { caseId, kind: "minor", members: [] } }))); render(); hook.flush(); await tick(); let output = render(); const inputs = collect(output, item => item.type === "input"); (inputs[0]!.props.onChange as Change)({ target: { value: "Synthetic Parent" } }); (inputs[1]!.props.onChange as Change)({ target: { value: "parent@example.invalid" } }); (collect(output, item => item.type === "input" && item.props.type === "checkbox")[0]!.props.onChange as Change)({ target: { value: "", checked: true } }); output = render(); const invite = find(output, item => item.type === "button" && item.props.children === "Send invitation")?.props.onClick as Click; invite(); invite(); await tick(); expect(posts()).toHaveLength(1); resolve(Response.json({ ok: true, data: {} })); });

it("keeps an uncertain invite locked through a failed reload until explicit review", async () => { let reads = 0; fetchMock.mockImplementation(async (_url: string, init?: RequestInit) => { if (init?.method === "POST") return new Response("", { status: 500 }); reads++; return reads === 1 ? Response.json({ ok: true, data: { caseId, kind: "minor", members: [] } }) : new Response("", { status: 500 }); }); render(); hook.flush(); await tick(); let output = render(); const inputs = collect(output, item => item.type === "input"); (inputs[0]!.props.onChange as Change)({ target: { value: "Synthetic Parent" } }); (inputs[1]!.props.onChange as Change)({ target: { value: "parent@example.invalid" } }); (collect(output, item => item.type === "input" && item.props.type === "checkbox")[0]!.props.onChange as Change)({ target: { value: "", checked: true } }); output = render(); (find(output, item => item.type === "button" && item.props.children === "Send invitation")?.props.onClick as Click)(); await tick(); output = render(); expect(find(output, item => item.type === "fieldset")?.props.disabled).toBe(true); expect(text(output)).toContain("Do not repeat the action"); (find(output, item => item.type === "button" && item.props.children === "Reload case access")?.props.onClick as Click)(); output = render(); hook.flush(); await tick(); output = render(); expect(text(output)).toContain("Do not repeat the action"); expect(text(output)).toContain("Unable to confirm case access"); });

function collect(node: unknown, predicate: (item: ReactElement<Record<string, unknown>>) => boolean, result: ReactElement<Record<string, unknown>>[] = []): ReactElement<Record<string, unknown>>[] { if (!node || typeof node !== "object") return result; if (Array.isArray(node)) { node.forEach(item => collect(item, predicate, result)); return result; } const item = node as ReactElement<Record<string, unknown>>; if (predicate(item)) result.push(item); collect(item.props?.children, predicate, result); return result; }
function posts() { return fetchMock.mock.calls.filter(call => (call[1] as RequestInit | undefined)?.method === "POST").map(call => ({ url: call[0] as string, init: call[1] as RequestInit })); }
