import {createHash,randomUUID} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {describe,expect,it} from 'vitest';
import {DRAFT_GROUP_PLACEMENT_MIGRATION,DRAFT_GROUP_PLACEMENT_SOURCE_PATHS,draftGroupPlacementMigrationInventory,draftGroupPlacementPlan,draftGroupPlacementSourceBundle,type DraftGroupPlacementReleaseSnapshot} from '../../src/db/draft-group-placement-release.ts';
import {validateDraftGroupPlacementEvidence,validateDraftGroupPlacementProof} from '../../src/db/draft-group-placement-evidence.ts';
import type {Migration} from '../../src/db/migration-plan.ts';

const inventory=async()=>{const manifest=JSON.parse(await readFile(new URL('../../migrations/manifest.json',import.meta.url),'utf8')) as {name:string;sha256:string}[];return Promise.all(manifest.map(async entry=>({name:entry.name,checksum:entry.sha256,sql:await readFile(new URL('../../migrations/'+entry.name,import.meta.url),'utf8')})));};
const snapshot=(stage:0|1):DraftGroupPlacementReleaseSnapshot=>({stage,catalogDigest:(stage?'b':'a').repeat(64),draftGroupRows:0,draftGroupOperationRows:0,proposedPlacementRows:0,proposedPlacementOperationRows:0});
describe('draft group placement migration 0128 release boundary',()=>{
 it('selects exactly frozen 0127 plus 0128 and refuses predecessor drift',async()=>{const files=await inventory(),scoped=draftGroupPlacementMigrationInventory(files);expect(scoped.at(-2)).toMatchObject({name:'0127_ls_service_interests.sql',checksum:'af9b7f061682453d4595bfef9f1a9226b1daa955ec518d7bd9d959cd352caf6a'});expect(scoped.at(-1)).toMatchObject({name:DRAFT_GROUP_PLACEMENT_MIGRATION.name,checksum:DRAFT_GROUP_PLACEMENT_MIGRATION.sha256});const future:Migration={name:'0129_future_scope.sql',checksum:'c'.repeat(64),sql:'select 1'};expect(draftGroupPlacementMigrationInventory([...files,future])).toEqual(scoped);expect(()=>draftGroupPlacementMigrationInventory(files.filter(file=>file.name!=='0127_ls_service_interests.sql'))).toThrow('DRAFT_GROUP_PLACEMENT_MIGRATION_SET_MISMATCH');});
 it('requires ledger and explicit schema state to advance together by one',async()=>{const files=await inventory(),scoped=draftGroupPlacementMigrationInventory(files),baseline=scoped.slice(0,-1).map(({name,checksum})=>({name,checksum})),current=scoped.map(({name,checksum})=>({name,checksum}));expect(draftGroupPlacementPlan(files,baseline,snapshot(0)).pending.map(item=>item.name)).toEqual([DRAFT_GROUP_PLACEMENT_MIGRATION.name]);expect(draftGroupPlacementPlan(files,current,snapshot(1))).toMatchObject({stage:1,pending:[]});expect(()=>draftGroupPlacementPlan(files,baseline,snapshot(1))).toThrow('DRAFT_GROUP_PLACEMENT_LEDGER_STATE_CONFLICT');});
 it('binds short-lived evidence to target, exact source, backup, restore and expected poststate',()=>{const now=Date.parse('2026-10-08T11:00:00.000Z'),sha='a'.repeat(64),ids={projectId:'3b756632-1f66-4f75-a016-eabc37aa0d67',environmentId:'dd91bd71-57cc-45e6-a75b-8c858491d7c7',appServiceId:'0267d061-f3ce-4a0a-82d4-ce133e4501e9',databaseServiceId:'354b5343-9e83-45a7-b764-09396f14ae29'},deploymentId=randomUUID(),reviewedCommit='b'.repeat(40),sourceBundleSha256=sha,databaseBindingSha256='c'.repeat(64),nonce=randomUUID();const proof={changeId:'LS-DRAFT-GROUP-PLACEMENT-MIGRATION-20261008-01',scope:'private-app-draft-group-placement-migration-0128',...ids,deploymentId,mode:'apply',reviewedCommit,sourceBundleSha256,manifestSha256:'d'.repeat(64),databaseBindingSha256,baselineStateSha256:'e'.repeat(64),expectedStateSha256:'f'.repeat(64),independentReview:'PASS',isolatedRestore:'PASS',backupId:'private-backup',controlFence:'g'.repeat(32),nonce,issuedAt:'2026-10-08T10:55:00.000Z',expiresAt:'2026-10-08T12:00:00.000Z',evidence:{independentReview:{path:'C:\\private\\review.json',sha256:sha},baselinePreflight:{path:'C:\\private\\preflight.json',sha256:sha},backupReadback:{path:'C:\\private\\backup.json',sha256:sha},isolatedRestore:{path:'C:\\private\\restore.json',sha256:sha},rollbackPlan:{path:'C:\\private\\rollback.json',sha256:sha}}} as const;const parsed=validateDraftGroupPlacementProof(proof,{...ids,deploymentId,mode:'apply',reviewedCommit,sourceBundleSha256,databaseBindingSha256},now),evidence={changeId:proof.changeId,scope:proof.scope,kind:'isolated_restore',status:'PASS',...ids,deploymentId,mode:'apply',reviewedCommit,sourceBundleSha256,databaseBindingSha256,baselineStateSha256:proof.baselineStateSha256,expectedStateSha256:proof.expectedStateSha256,backupId:proof.backupId,controlFence:proof.controlFence,nonce,createdAt:'2026-10-08T10:54:00.000Z'} as const;expect(validateDraftGroupPlacementEvidence(evidence,parsed,'isolated_restore',now).kind).toBe('isolated_restore');expect(()=>validateDraftGroupPlacementProof({...proof,expectedStateSha256:'1'.repeat(64)},{...ids,deploymentId,mode:'apply',reviewedCommit,sourceBundleSha256,databaseBindingSha256},now)).not.toThrow();const changed=validateDraftGroupPlacementProof({...proof,expectedStateSha256:'1'.repeat(64)},{...ids,deploymentId,mode:'apply',reviewedCommit,sourceBundleSha256,databaseBindingSha256},now);expect(()=>validateDraftGroupPlacementEvidence(evidence,changed,'isolated_restore',now)).toThrow('DRAFT_GROUP_PLACEMENT_EVIDENCE_BINDING_MISMATCH');});
 it('keeps the runnable operator schema-only, version-tolerant and full-runtime-source-bound',async()=>{const text=await readFile(new URL('../../scripts/release-draft-group-placement.ts',import.meta.url),'utf8');for(const token of ['LS_DRAFT_GROUP_PLACEMENT_RELEASE_PROOF_SHA256','backupReadback','isolatedRestore','rollbackPlan','assertContactOpsDatabaseIdentity','pg_try_advisory_lock','DRAFT_GROUP_PLACEMENT_APPLY_READBACK_FAILED'])expect(text).toContain(token);const release=await readFile(new URL('../../src/db/draft-group-placement-release.ts',import.meta.url),'utf8');expect(release).toContain("k.contype<>'n'");expect(release).toContain('readServiceInterestReleaseSnapshot');expect(release).toContain('successorAbsent:true');expect(text).not.toContain('createDraftGroup(');expect(text).not.toContain('send_message');const migration=await readFile(new URL('../../migrations/0128_ls_draft_group_placements.sql',import.meta.url));expect(createHash('sha256').update(migration).digest('hex')).toBe(DRAFT_GROUP_PLACEMENT_MIGRATION.sha256);expect(DRAFT_GROUP_PLACEMENT_SOURCE_PATHS).toContain('src/features/group-placement/store.ts');expect(DRAFT_GROUP_PLACEMENT_SOURCE_PATHS).toContain('src/ui/workspace/navigation-model.ts');const entries=await Promise.all(DRAFT_GROUP_PLACEMENT_SOURCE_PATHS.map(async path=>({path,bytes:await readFile(new URL('../../'+path,import.meta.url))}))),actual=draftGroupPlacementSourceBundle(entries),changed=entries.map(entry=>entry.path==='src/features/group-placement/store.ts'?{...entry,bytes:Buffer.concat([entry.bytes,Buffer.from('\n// changed runtime')])}:entry);expect(draftGroupPlacementSourceBundle(changed)).not.toBe(actual);});
});
