import type {ReactElement} from 'react';
import {beforeEach,expect,it,vi} from 'vitest';
type Slot={kind:'state';value:unknown}|{kind:'ref';value:{current:unknown}}|{kind:'effect';deps:readonly unknown[]|undefined;cleanup:(()=>void)|undefined};
const hook=vi.hoisted(()=>{const slots:Slot[]=[],pending:Array<{index:number;effect:()=>void|(()=>void)}>=[];let cursor=0,mounted=true,afterUnmount=0;return{
 reset(){slots.length=0;pending.length=0;cursor=0;mounted=true;afterUnmount=0},render<T>(view:()=>T){cursor=0;return view()},
 flush(){for(const next of pending.splice(0)){const slot=slots[next.index];if(slot?.kind==='effect'){slot.cleanup?.();slot.cleanup=next.effect()||undefined}}},
 unmount(){mounted=false;for(const slot of slots)if(slot.kind==='effect')slot.cleanup?.()},afterUnmount:()=>afterUnmount,
 useState<T>(initial:T|(()=>T)){const index=cursor++;let slot=slots[index];if(!slot){slot={kind:'state',value:typeof initial==='function'?(initial as ()=>T)():initial};slots[index]=slot}if(slot.kind!=='state')throw Error('HOOK_ORDER');return[slot.value as T,(value:T|((previous:T)=>T))=>{if(!mounted){afterUnmount++;return}slot.value=typeof value==='function'?(value as (p:T)=>T)(slot.value as T):value}] as const},
 useRef<T>(initial:T){const index=cursor++;let slot=slots[index];if(!slot){slot={kind:'ref',value:{current:initial}};slots[index]=slot}if(slot.kind!=='ref')throw Error('HOOK_ORDER');return slot.value as {current:T}},
 useEffect(effect:()=>void|(()=>void),deps?:readonly unknown[]){const index=cursor++,slot=slots[index];if(!slot){slots[index]={kind:'effect',deps,cleanup:undefined};pending.push({index,effect});return}if(slot.kind!=='effect')throw Error('HOOK_ORDER');if(!deps||!slot.deps||deps.length!==slot.deps.length||deps.some((v,i)=>v!==slot.deps?.[i])){slot.deps=deps;pending.push({index,effect})}}
}});
const fetchMock=vi.hoisted(()=>vi.fn());
vi.mock('react',async original=>({...await original<typeof import('react')>(),useState:hook.useState,useRef:hook.useRef,useEffect:hook.useEffect}));
import {FormsCaseWorkspace,FormsWorkspace,FormField} from '../../src/features/forms/workspace.tsx';
import type {FormDefinition} from '../../src/features/forms/schema.ts';
const caseId='123e4567-e89b-12d3-a456-426614174000',templateId='223e4567-e89b-12d3-a456-426614174000',parentId='323e4567-e89b-12d3-a456-426614174000';
const definition:FormDefinition={title:'Synthetic questions',introduction:'Synthetic intro',fields:[{key:'long',kind:'long_text',label:'Long answer',required:true},{key:'one',kind:'single_choice',label:'One answer',required:true,options:[{value:'a',label:'First'}]},{key:'many',kind:'multiple_choice',label:'Many answers',required:true,options:[{value:'a',label:'First'},{value:'b',label:'Second'}]}]};
const assignment={id:'423e4567-e89b-12d3-a456-426614174000',caseId,templateVersion:1,state:'assigned',definition,assignedAccountId:parentId};
type Node=ReactElement<Record<string,unknown>>;type Change=(event:{target:{value:string;checked?:boolean}})=>void;type Submit=(event:{preventDefault:()=>void})=>Promise<void>;
function all(node:unknown,predicate:(item:Node)=>boolean,out:Node[]=[]):Node[]{if(!node||typeof node!=='object')return out;if(Array.isArray(node)){node.forEach(item=>all(item,predicate,out));return out}const item=node as Node;if(predicate(item))out.push(item);all(item.props?.children,predicate,out);return out}
function text(node:unknown):string{if(node==null||typeof node==='boolean')return'';if(typeof node==='string'||typeof node==='number')return String(node);if(Array.isArray(node))return node.map(text).join('');return text((node as Node).props?.children)}
const tick=async()=>{for(let i=0;i<20;i++)await Promise.resolve()};
function render(role:'practitioner'|'parent'='practitioner'){return hook.render(()=>FormsCaseWorkspace({role,locale:'en',caseId,csrfToken:'synthetic-csrf',cases:[{id:caseId,label:'Synthetic case'}],responders:[{id:parentId,label:'Synthetic parent'}],audiences:[]}))}
function button(view:unknown,label:string){const node=all(view,item=>item.type==='button'&&text(item.props.children)===label)[0];if(!node)throw Error('MISSING_BUTTON:'+label);return node.props.onClick as ()=>void}
function posts(){return fetchMock.mock.calls.filter(call=>(call[1] as RequestInit|undefined)?.method==='POST')}
function reads(url:string){return Response.json({ok:true,data:url.includes('/templates')?[{id:templateId,key:'SYNTHETIC',version:1,locale:'en',targetRole:'parent',definition,active:true,state:'published'}]:[assignment]})}
async function ready(role:'practitioner'|'parent'='practitioner'){render(role);hook.flush();await tick();return render(role)}
function fillTemplate(view:unknown){const inputs=all(view,item=>item.type==='input');(inputs[0]!.props.onChange as Change)({target:{value:'SYNTHETIC_NEW'}});(inputs[2]!.props.onChange as Change)({target:{value:'Actual operator title'}});button(view,'Add field')();view=render();const question=all(view,item=>item.type==='input'&&item.props.maxLength===240)[0]!;(question.props.onChange as Change)({target:{value:'Actual operator question'}});return render()}
function submitForm(view:unknown,index=0){return all(view,item=>item.type==='form')[index]!.props.onSubmit as Submit}
function fillParent(view:unknown){button(view,'Fill in')();view=render('parent');for(const node of all(view,item=>item.type===FormField)){const field=node.props.field as FormDefinition['fields'][number];(node.props.onChange as (value:string|readonly string[])=>void)(field.key==='long'?'Synthetic actual long answer':field.key==='one'?'a':['a','b'])}return render('parent')}
beforeEach(()=>{hook.reset();fetchMock.mockReset();vi.stubGlobal('fetch',fetchMock)});
it('posts actual operator-authored template inputs once with CSRF even on immediate double submit',async()=>{let resolve!:(value:Response)=>void;fetchMock.mockImplementation((url:string,init?:RequestInit)=>init?.method==='POST'?new Promise<Response>(done=>{resolve=done}):Promise.resolve(reads(url)));const output=fillTemplate(await ready()),submit=submitForm(output);void submit({preventDefault(){}});void submit({preventDefault(){}});await tick();expect(posts()).toHaveLength(1);const request=posts()[0]![1] as RequestInit;expect(request.headers).toMatchObject({'X-CSRF-Token':'synthetic-csrf'});expect(JSON.parse(String(request.body))).toMatchObject({key:'SYNTHETIC_NEW',definition:{title:'Actual operator title',fields:[{label:'Actual operator question',kind:'short_text'}]},published:false});resolve(Response.json({ok:true,data:{templateId}}));await tick()});
it('ok:false create locks until a successful readback and explicit review, not a failed reload',async()=>{let failReads=false;fetchMock.mockImplementation((url:string,init?:RequestInit)=>Promise.resolve(init?.method==='POST'?Response.json({ok:false,data:{templateId}}):failReads?new Response('',{status:503}):reads(url)));let output=fillTemplate(await ready());await submitForm(output)({preventDefault(){}});output=render();expect(text(output)).not.toContain('Saved');expect(all(output,item=>item.type==='fieldset')[0]?.props.disabled).toBe(true);failReads=true;button(output,'Reload saved forms')();render();hook.flush();await tick();output=render();expect(all(output,item=>item.type==='button'&&text(item.props.children)==='I reviewed saved templates and assignments')).toHaveLength(0);expect(posts()).toHaveLength(1);failReads=false;button(output,'Reload saved forms')();render();hook.flush();await tick();output=render();button(output,'I reviewed saved templates and assignments')();output=render();expect(all(output,item=>item.type==='fieldset')[0]?.props.disabled).toBe(false)});
it('submits all actual parent answers and retries an uncertain result with the exact same payload/key',async()=>{let attempts=0;fetchMock.mockImplementation((url:string,init?:RequestInit)=>Promise.resolve(init?.method==='POST'?(++attempts===1?Response.json({ok:false,data:null}):Response.json({ok:true,data:{submissionId:'receipt'}})):reads(url)));let output=fillParent(await ready('parent'));await submitForm(output)({preventDefault(){}});output=render('parent');expect(text(output)).not.toContain('Saved');button(output,'Retry the same submission')();await tick();expect(posts()).toHaveLength(2);const first=posts()[0]![1] as RequestInit,last=posts()[1]![1] as RequestInit;expect(first.body).toBe(last.body);expect(first.headers).toMatchObject({'X-CSRF-Token':'synthetic-csrf'});expect(JSON.parse(String(first.body))).toMatchObject({assignmentId:assignment.id,answers:{long:'Synthetic actual long answer',one:'a',many:['a','b']}});expect(text(render('parent'))).toContain('Saved')});
it('does not apply parent submission results after the family workspace unmounts',async()=>{let resolve!:(value:Response)=>void;fetchMock.mockImplementation((url:string,init?:RequestInit)=>init?.method==='POST'?new Promise<Response>(done=>{resolve=done}):Promise.resolve(reads(url)));const output=fillParent(await ready('parent'));void submitForm(output)({preventDefault(){}});await tick();hook.unmount();resolve(Response.json({ok:true,data:{submissionId:'receipt'}}));await tick();expect(hook.afterUnmount()).toBe(0)});
it('keys all pending forms state by role, language and authorized case',()=>{const view=FormsWorkspace({role:'parent',locale:'he',csrfToken:'c',cases:[{id:caseId,label:'Synthetic'}]});expect(view.key).toBe(`parent:he:${caseId}`)});
it('assigns only explicitly chosen authorized template and respondent identifiers',async()=>{fetchMock.mockImplementation((url:string,init?:RequestInit)=>Promise.resolve(init?.method==='POST'?Response.json({ok:true,data:{assignmentId:assignment.id}}):reads(url)));let output=await ready();const selects=all(output,item=>item.type==='select');(selects[0]!.props.onChange as Change)({target:{value:templateId}});(selects[1]!.props.onChange as Change)({target:{value:parentId}});output=render();await submitForm(output,1)({preventDefault(){}});expect(JSON.parse(String((posts()[0]![1] as RequestInit).body))).toEqual({caseId,templateId,assignedAccountId:parentId,dueDate:null,postSubmissionAudienceId:null})});
