import { createHash, randomUUID } from "node:crypto";
import { mkdtemp, mkdir, rm, unlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { PreEnrollmentService, type IntakeToken, type PreEnrollmentRepository } from "../../src/features/forms/pre-enrollment/service.ts";
import { publicConsentHash, runtimePublicConsent } from "../../src/features/forms/pre-enrollment/consent.ts";
import { runtimeIntakeBankTransfer } from "../../src/features/forms/pre-enrollment/payment.ts";
import { verifyReleaseSourceProvenance } from "../../src/features/forms/pre-enrollment/release-provenance.ts";
import { respondentLink } from "../../src/features/forms/pre-enrollment/staff-link.ts";
import { unseal } from "../../src/features/identity/crypto.ts";

const token="A".repeat(43), digest=createHash("sha256").update(token).digest("hex"), slots=["00000000-0000-4000-8000-000000000001","00000000-0000-4000-8000-000000000002"];
const consent={version:"test-source-20260916",sourceHashes:["701cce537e8cc14f94b593cc6c321330ee0275207386ff8137f259630ca5e073"],displayText:["Synthetic test display text."],acknowledgements:["One.","Two.","Three."]}; const englishConsent={...consent,translations:{en:{displayText:["Exact English paragraph one.","Exact English paragraph two."],acknowledgements:["Exact English acknowledgment one.","Exact English acknowledgment two.","Exact English acknowledgment three."]}}}; process.env.LS_INTAKE_PUBLIC_CONSENT_JSON=JSON.stringify(consent);
afterEach(()=>{process.env.LS_INTAKE_PUBLIC_CONSENT_JSON=JSON.stringify(consent);delete process.env.LS_INTAKE_PRIVATE_OPENINGS_JSON;delete process.env.LS_INTAKE_BANK_TRANSFER_JSON;});
const payload=(childSlotIds=slots)=>({parentName:"Synthetic Parent",contactNumber:"+972500000000",preferredLanguage:"he",email:"",children:childSlotIds.map((childSlotId,i)=>({childSlotId,firstName:`Child ${i}`,age:8})),locationPreference:"coordinate_with_shlomo",arrivalNeeds:"",availableDays:["sun"],timeWindows:["afternoon"],availabilityNote:"",privateContext:"",cp01:"not_now",willingToBeContacted:"yes",accessSupportNeeded:"no",consentAcknowledgements:[true,true,true],consentVersion:consent.version,consentHash:publicConsentHash(consent),consentLanguage:"he",signerName:"Synthetic"});
class MemoryRepo implements PreEnrollmentRepository { row:IntakeToken={tokenDigest:digest,stableLeadId:"LS-LEAD-synthetic",childSlotIds:slots,expiresAt:new Date("2030-01-01"),usedAt:null}; receipts=new Map<string,{receiptId:string;receivedAt:Date;payloadDigest:string;payloadCiphertext?:string}>();transaction<T>(work:(tx:PreEnrollmentRepository)=>Promise<T>):Promise<T>{return work(this)}async findToken(){return this.row}async findReceiptByIdempotency(_:string,key:string){return this.receipts.get(key)??null}async insertReceipt(row:Parameters<PreEnrollmentRepository["insertReceipt"]>[0]){this.receipts.set(row.idempotencyKey,{receiptId:row.receiptId,receivedAt:row.receivedAt,payloadDigest:row.payloadDigest,payloadCiphertext:row.payloadCiphertext});return "inserted" as const}async consumeToken(){this.row={...this.row,usedAt:new Date()};return true}}
describe("pre-enrollment service",()=>{it("rejects duplicated bound slots and replays the same receipt",async()=>{const repo=new MemoryRepo(), service=new PreEnrollmentService(repo,{activeKeyId:"k",keys:{k:Buffer.alloc(32,1)}},()=>new Date("2029-01-01"),true,"00000000-0000-4000-8000-000000000010"),key=randomUUID();await expect(service.submit(token,key,payload([slots[0]!,slots[0]!]))).rejects.toMatchObject({code:"NOT_FOUND"});const first=await service.submit(token,key,payload());const retry=await service.submit(token,key,payload());expect(retry.receiptId).toBe(first.receiptId);expect(retry.duplicate).toBe(true);});});
it("retrieves an already accepted legacy Fri/Sat receipt before new-write validation", async()=>{const repo=new MemoryRepo(), service=new PreEnrollmentService(repo,{activeKeyId:"k",keys:{k:Buffer.alloc(32,1)}},()=>new Date("2029-01-01"),true,"00000000-0000-0000-0000-000000000010"), key=randomUUID(), legacy={...payload(),consentVersion:"trial-intake-20260915-v2",consentHash:"b".repeat(64),availableDays:["fri","sat"]}; delete (legacy as {consentLanguage?: string}).consentLanguage; repo.row={...repo.row,usedAt:new Date("2028-12-31")}; repo.receipts.set(key,{receiptId:"legacy-receipt",receivedAt:new Date("2029-01-01"),payloadDigest:createHash("sha256").update(JSON.stringify(legacy)).digest("hex")}); const result=await service.submit(token,key,legacy); expect(result).toMatchObject({receiptId:"legacy-receipt",duplicate:true}); await expect(service.submit(token,randomUUID(),legacy)).rejects.toThrow();});
it.each(["fri","sat"])("rejects a new %s-only submission", async day=>{const repo=new MemoryRepo(), service=new PreEnrollmentService(repo,{activeKeyId:"k",keys:{k:Buffer.alloc(32,1)}},()=>new Date("2029-01-01"),true,"00000000-0000-0000-0000-000000000010"); await expect(service.submit(token,randomUUID(),{...payload(),availableDays:[day]})).rejects.toThrow();});
it("rejects forged English selection when runtime consent has no translation", async()=>{const repo=new MemoryRepo(), service=new PreEnrollmentService(repo,{activeKeyId:"k",keys:{k:Buffer.alloc(32,1)}},()=>new Date("2029-01-01"),true,"00000000-0000-4000-8000-000000000010"); await expect(service.submit(token,randomUUID(),{...payload(),consentLanguage:"en"})).rejects.toMatchObject({code:"INVALID_REQUEST"});});
it("seals the complete English consent envelope and selected language", async()=>{process.env.LS_INTAKE_PUBLIC_CONSENT_JSON=JSON.stringify(englishConsent); const repo=new MemoryRepo(), ring={activeKeyId:"k",keys:{k:Buffer.alloc(32,1)}}, service=new PreEnrollmentService(repo,ring,()=>new Date("2029-01-01"),true,"00000000-0000-0000-0000-000000000010"), input={...payload(),consentVersion:englishConsent.version,consentHash:publicConsentHash(englishConsent),consentLanguage:"en" as const}, result=await service.submit(token,randomUUID(),input), stored=[...repo.receipts.values()][0]!; expect(result.duplicate).toBe(false); const decoded=JSON.parse(unseal(stored.payloadCiphertext!,`pre-enrollment:00000000-0000-0000-0000-000000000010:LS-LEAD-synthetic:${result.receiptId}:original`,ring)) as {input:typeof input;consent:typeof englishConsent & {hash:string}}; expect(decoded.input.consentLanguage).toBe("en"); expect(decoded.consent.translations?.en.displayText).toEqual(englishConsent.translations.en.displayText); expect(decoded.consent.translations?.en.acknowledgements).toEqual(englishConsent.translations.en.acknowledgements); expect(decoded.consent.hash).toBe(publicConsentHash(englishConsent));});
describe("invitation exchange",()=>{it("does not require or expose legacy opening configuration",async()=>{const service=new PreEnrollmentService(new MemoryRepo(),{activeKeyId:"k",keys:{k:Buffer.alloc(32,1)}},()=>new Date("2029-01-01"),true,"00000000-0000-4000-8000-000000000010");process.env.LS_INTAKE_PRIVATE_OPENINGS_JSON=JSON.stringify([{tokenDigest:digest,stableLeadRef:"LS-LEAD-synthetic",message:"Synthetic legacy opening."}]);const exchange=await service.exchange(token);expect(exchange).not.toHaveProperty("opening");expect(exchange.childSlotIds).toEqual(slots);});});
describe("bank transfer display configuration",()=>{it("only returns a complete validated runtime value",async()=>{const service=new PreEnrollmentService(new MemoryRepo(),{activeKeyId:"k",keys:{k:Buffer.alloc(32,1)}},()=>new Date("2029-01-01"),true,"00000000-0000-4000-8000-000000000010");expect((await service.exchange(token)).bankTransfer).toBeNull();process.env.LS_INTAKE_BANK_TRANSFER_JSON=JSON.stringify({bankName:"Synthetic Bank",bankCode:"12",branchNumber:"345",accountNumber:"67890",accountHolder:"Synthetic Holder"});expect((await service.exchange(token)).bankTransfer).toEqual({bankName:"Synthetic Bank",bankCode:"12",branchNumber:"345",accountNumber:"67890",accountHolder:"Synthetic Holder"});expect(runtimeIntakeBankTransfer(JSON.stringify({bankName:"Synthetic Bank",bankCode:"12"}))).toBeNull();});});
describe("runtime public consent",()=>{it("hashes all displayed evidence and requires exactly three acknowledgements",()=>{const resolved=runtimePublicConsent(JSON.stringify(consent));expect(resolved.hash).toBe(publicConsentHash(consent));expect(resolved.hash).not.toBe(publicConsentHash({...consent,displayText:["changed"]}));expect(()=>runtimePublicConsent(JSON.stringify({...consent,acknowledgements:consent.acknowledgements.slice(0,2)}))).toThrow();});it("has no fallback wording when configuration is absent",()=>{delete process.env.LS_INTAKE_PUBLIC_CONSENT_JSON;expect(()=>runtimePublicConsent()).toThrow();});});
const archiveCommit="a".repeat(40), archiveHash=(value:string|Buffer)=>createHash("sha256").update(value).digest("hex");
async function archiveFixture(change?:(root:string,manifest:{reviewedCommit:string;files:{path:string;sha256:string}[]})=>Promise<void>){const root=await mkdtemp(join(tmpdir(),"intake-archive-"));for(const directory of ["src/forms","scripts","migrations"])await mkdir(join(root,directory),{recursive:true});const contents:Record<string,string>={"src/forms/a.ts":"export{}\n","scripts/a.ts":"export{}\n","migrations/0001_a.sql":"SELECT 1;\n","package.json":"{}\n","package-lock.json":"{}\n"};for(const [path,value] of Object.entries(contents))await writeFile(join(root,path),value);const manifest={reviewedCommit:archiveCommit,files:Object.entries(contents).map(([path,value])=>({path,sha256:archiveHash(value)}))};if(change)await change(root,manifest);const manifestFile=join(root,"source-manifest.json"),bytes=JSON.stringify(manifest);await writeFile(manifestFile,bytes);return {root,manifestFile,proof:{reviewedCommit:archiveCommit,cliSourceManifestSha256:archiveHash(bytes)}};}
describe("CLI archive source provenance",()=>{it("requires a matching provider commit when supplied",async()=>{const fixture=await archiveFixture();try{await expect(verifyReleaseSourceProvenance(fixture.proof,{providerGitCommit:archiveCommit,root:fixture.root})).resolves.toBeUndefined();await expect(verifyReleaseSourceProvenance(fixture.proof,{providerGitCommit:"b".repeat(40),root:fixture.root})).rejects.toThrow("STALE_REVIEW");}finally{await rm(fixture.root,{recursive:true,force:true});}});it("rejects missing proof, traversal, missing or extra files, and changed archive bytes",async()=>{const plain=await archiveFixture();try{await expect(verifyReleaseSourceProvenance({reviewedCommit:archiveCommit},{root:plain.root})).rejects.toThrow("CLI_SOURCE_PROOF");}finally{await rm(plain.root,{recursive:true,force:true});}const traversal=await archiveFixture(async(_root,manifest)=>{manifest.files[0]!.path="src/../secret.ts";});try{await expect(verifyReleaseSourceProvenance(traversal.proof,{cliManifestFile:traversal.manifestFile,root:traversal.root})).rejects.toThrow("CLI_SOURCE_PATH");}finally{await rm(traversal.root,{recursive:true,force:true});}const missing=await archiveFixture();try{await unlink(join(missing.root,"migrations/0001_a.sql"));await expect(verifyReleaseSourceProvenance(missing.proof,{cliManifestFile:missing.manifestFile,root:missing.root})).rejects.toThrow("CLI_SOURCE_INVENTORY");}finally{await rm(missing.root,{recursive:true,force:true});}const extra=await archiveFixture(async root=>{await writeFile(join(root,"src/forms/extra.ts"),"changed");});try{await expect(verifyReleaseSourceProvenance(extra.proof,{cliManifestFile:extra.manifestFile,root:extra.root})).rejects.toThrow("CLI_SOURCE_INVENTORY");}finally{await rm(extra.root,{recursive:true,force:true});}const changed=await archiveFixture(async root=>{await writeFile(join(root,"scripts/a.ts"),"changed");});try{await expect(verifyReleaseSourceProvenance(changed.proof,{cliManifestFile:changed.manifestFile,root:changed.root})).rejects.toThrow("CLI_SOURCE_CONTENT");}finally{await rm(changed.root,{recursive:true,force:true});}});});
describe("staff invitation link",()=>{it("uses only a fragment-held opaque token and rejects malformed values",()=>{const link=respondentLink("https://staff.example.test","A".repeat(43));expect(link).toBe("https://staff.example.test/he/intake#"+"A".repeat(43));expect(link).not.toContain("?");expect(respondentLink("https://staff.example.test","short")).toBeNull();});});
