import { createHash, randomUUID } from "node:crypto";
import { afterEach, describe, expect, it } from "vitest";
import { PreEnrollmentService, type IntakeToken, type PreEnrollmentRepository } from "../../src/features/forms/pre-enrollment/service.ts";
import { publicConsentHash, runtimePublicConsent } from "../../src/features/forms/pre-enrollment/consent.ts";

const token="A".repeat(43), digest=createHash("sha256").update(token).digest("hex"), slots=["00000000-0000-4000-8000-000000000001","00000000-0000-4000-8000-000000000002"];
const consent={version:"test-source-20260916",sourceHashes:["701cce537e8cc14f94b593cc6c321330ee0275207386ff8137f259630ca5e073"],displayText:["Synthetic test display text."],acknowledgements:["One.","Two.","Three."]};process.env.LS_INTAKE_PUBLIC_CONSENT_JSON=JSON.stringify(consent);
afterEach(()=>{process.env.LS_INTAKE_PUBLIC_CONSENT_JSON=JSON.stringify(consent);});
const payload=(childSlotIds=slots)=>({parentName:"Synthetic Parent",contactNumber:"+972500000000",preferredLanguage:"he",email:"",children:childSlotIds.map((childSlotId,i)=>({childSlotId,firstName:`Child ${i}`,age:8})),locationPreference:"coordinate_with_shlomo",arrivalNeeds:"",availableDays:["sun"],timeWindows:["afternoon"],availabilityNote:"",privateContext:"",cp01:"not_now",willingToBeContacted:"yes",accessSupportNeeded:"no",consentAcknowledgements:[true,true,true],consentVersion:consent.version,consentHash:publicConsentHash(consent),signerName:"Synthetic"});
class MemoryRepo implements PreEnrollmentRepository { row:IntakeToken={tokenDigest:digest,stableLeadId:"LS-LEAD-synthetic",childSlotIds:slots,expiresAt:new Date("2030-01-01"),usedAt:null}; receipts=new Map<string,{receiptId:string;receivedAt:Date;payloadDigest:string}>();transaction<T>(work:(tx:PreEnrollmentRepository)=>Promise<T>):Promise<T>{return work(this)}async findToken(){return this.row}async findReceiptByIdempotency(_:string,key:string){return this.receipts.get(key)??null}async insertReceipt(row:Parameters<PreEnrollmentRepository["insertReceipt"]>[0]){this.receipts.set(row.idempotencyKey,{receiptId:row.receiptId,receivedAt:row.receivedAt,payloadDigest:row.payloadDigest});return "inserted" as const}async consumeToken(){this.row={...this.row,usedAt:new Date()};return true}}
describe("pre-enrollment service",()=>{it("rejects duplicated bound slots and replays the same receipt",async()=>{const repo=new MemoryRepo(), service=new PreEnrollmentService(repo,{activeKeyId:"k",keys:{k:Buffer.alloc(32,1)}},()=>new Date("2029-01-01"),true,"00000000-0000-4000-8000-000000000010"),key=randomUUID();await expect(service.submit(token,key,payload([slots[0]!,slots[0]!]))).rejects.toMatchObject({code:"NOT_FOUND"});const first=await service.submit(token,key,payload());const retry=await service.submit(token,key,payload());expect(retry.receiptId).toBe(first.receiptId);expect(retry.duplicate).toBe(true);});});
describe("runtime public consent",()=>{it("hashes all displayed evidence and requires exactly three acknowledgements",()=>{const resolved=runtimePublicConsent(JSON.stringify(consent));expect(resolved.hash).toBe(publicConsentHash(consent));expect(resolved.hash).not.toBe(publicConsentHash({...consent,displayText:["changed"]}));expect(()=>runtimePublicConsent(JSON.stringify({...consent,acknowledgements:consent.acknowledgements.slice(0,2)}))).toThrow();});it("has no fallback wording when configuration is absent",()=>{delete process.env.LS_INTAKE_PUBLIC_CONSENT_JSON;expect(()=>runtimePublicConsent()).toThrow();});});
