import {createHash,randomUUID} from 'node:crypto';
import {mkdir,mkdtemp,readFile,rm,symlink} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {describe,expect,it} from 'vitest';
import {PROPOSED_PLACEMENT_MOVES_MIGRATION,PROPOSED_PLACEMENT_MOVES_SOURCE_PATHS,PROPOSED_PLACEMENT_MOVES_SOURCE_ROOTS,assertProposedPlacementMovesSourceNode,collectProposedPlacementMovesSourceEntries,proposedPlacementMovesMigrationInventory,proposedPlacementMovesPlan,proposedPlacementMovesSourceBundle,type ProposedPlacementMovesReleaseSnapshot} from '../../src/db/proposed-placement-moves-release.ts';
import {validateProposedPlacementMovesEvidence,validateProposedPlacementMovesProof} from '../../src/db/proposed-placement-moves-evidence.ts';
import type {Migration} from '../../src/db/migration-plan.ts';

const inventory=async()=>{const manifest=JSON.parse(await readFile(new URL('../../migrations/manifest.json',import.meta.url),'utf8')) as {name:string;sha256:string}[];return Promise.all(manifest.map(async entry=>({name:entry.name,checksum:entry.sha256,sql:await readFile(new URL('../../migrations/'+entry.name,import.meta.url),'utf8')})));};
const snapshot=(stage:0|1):ProposedPlacementMovesReleaseSnapshot=>({stage,catalogDigest:(stage?'b':'a').repeat(64),moveRows:0,operationRows:0});
describe('proposed placement moves migration 0129 release boundary',()=>{
 it('selects exactly frozen 0128 plus 0129 and refuses predecessor drift',async()=>{const files=await inventory(),scoped=proposedPlacementMovesMigrationInventory(files);expect(scoped.at(-2)).toMatchObject({name:'0128_ls_draft_group_placements.sql',checksum:'08eafdc0f7f5d6ca164b2f483a2e1edf947aa80c076ff370a1cf60504e006bb2'});expect(scoped.at(-1)).toMatchObject({name:PROPOSED_PLACEMENT_MOVES_MIGRATION.name,checksum:PROPOSED_PLACEMENT_MOVES_MIGRATION.sha256});const future:Migration={name:'0130_future_scope.sql',checksum:'c'.repeat(64),sql:'select 1'};expect(proposedPlacementMovesMigrationInventory([...files,future])).toEqual(scoped);expect(()=>proposedPlacementMovesMigrationInventory(files.filter(file=>file.name!=='0128_ls_draft_group_placements.sql'))).toThrow('PROPOSED_PLACEMENT_MOVES_MIGRATION_SET_MISMATCH');});
 it('requires ledger and explicit schema state to advance together by one',async()=>{const files=await inventory(),scoped=proposedPlacementMovesMigrationInventory(files),baseline=scoped.slice(0,-1).map(({name,checksum})=>({name,checksum})),current=scoped.map(({name,checksum})=>({name,checksum}));expect(proposedPlacementMovesPlan(files,baseline,snapshot(0)).pending.map(item=>item.name)).toEqual([PROPOSED_PLACEMENT_MOVES_MIGRATION.name]);expect(proposedPlacementMovesPlan(files,current,snapshot(1))).toMatchObject({stage:1,pending:[]});expect(()=>proposedPlacementMovesPlan(files,baseline,snapshot(1))).toThrow('PROPOSED_PLACEMENT_MOVES_LEDGER_STATE_CONFLICT');});
 it('binds short-lived evidence to target, exact source, backup, restore and expected poststate',()=>{const now=Date.parse('2026-10-08T11:00:00.000Z'),sha='a'.repeat(64),ids={projectId:'3b756632-1f66-4f75-a016-eabc37aa0d67',environmentId:'dd91bd71-57cc-45e6-a75b-8c858491d7c7',appServiceId:'0267d061-f3ce-4a0a-82d4-ce133e4501e9',databaseServiceId:'354b5343-9e83-45a7-b764-09396f14ae29'},deploymentId=randomUUID(),reviewedCommit='b'.repeat(40),sourceBundleSha256=sha,databaseBindingSha256='c'.repeat(64),nonce=randomUUID();const proof={changeId:'LS-PROPOSED-PLACEMENT-MOVES-MIGRATION-20261008-01',scope:'private-app-proposed-placement-moves-migration-0129',...ids,deploymentId,mode:'apply',reviewedCommit,sourceBundleSha256,manifestSha256:'d'.repeat(64),databaseBindingSha256,baselineStateSha256:'e'.repeat(64),expectedStateSha256:'f'.repeat(64),independentReview:'PASS',isolatedRestore:'PASS',backupId:'private-backup',controlFence:'g'.repeat(32),nonce,issuedAt:'2026-10-08T10:55:00.000Z',expiresAt:'2026-10-08T12:00:00.000Z',evidence:{independentReview:{path:'C:\\private\\review.json',sha256:sha},baselinePreflight:{path:'C:\\private\\preflight.json',sha256:sha},backupReadback:{path:'C:\\private\\backup.json',sha256:sha},isolatedRestore:{path:'C:\\private\\restore.json',sha256:sha},rollbackPlan:{path:'C:\\private\\rollback.json',sha256:sha}}} as const;const parsed=validateProposedPlacementMovesProof(proof,{...ids,deploymentId,mode:'apply',reviewedCommit,sourceBundleSha256,databaseBindingSha256},now),evidence={changeId:proof.changeId,scope:proof.scope,kind:'isolated_restore',status:'PASS',...ids,deploymentId,mode:'apply',reviewedCommit,sourceBundleSha256,databaseBindingSha256,baselineStateSha256:proof.baselineStateSha256,expectedStateSha256:proof.expectedStateSha256,backupId:proof.backupId,controlFence:proof.controlFence,nonce,createdAt:'2026-10-08T10:54:00.000Z'} as const;expect(validateProposedPlacementMovesEvidence(evidence,parsed,'isolated_restore',now).kind).toBe('isolated_restore');const changed=validateProposedPlacementMovesProof({...proof,expectedStateSha256:'1'.repeat(64)},{...ids,deploymentId,mode:'apply',reviewedCommit,sourceBundleSha256,databaseBindingSha256},now);expect(()=>validateProposedPlacementMovesEvidence(evidence,changed,'isolated_restore',now)).toThrow('PROPOSED_PLACEMENT_MOVES_EVIDENCE_BINDING_MISMATCH');});
 it('keeps the successor operator schema-only, fail-closed and full-runtime-source-bound',async()=>{const text=await readFile(new URL('../../scripts/release-proposed-placement-moves.ts',import.meta.url),'utf8');for(const token of ['LS_PROPOSED_PLACEMENT_MOVES_RELEASE_PROOF_SHA256','backupReadback','isolatedRestore','rollbackPlan','assertContactOpsDatabaseIdentity','pg_try_advisory_lock(541931,3)','PROPOSED_PLACEMENT_MOVES_APPLY_READBACK_FAILED','collectProposedPlacementMovesSourceEntries'])expect(text).toContain(token);const release=await readFile(new URL('../../src/db/proposed-placement-moves-release.ts',import.meta.url),'utf8');expect(release).toContain('readDraftGroupPlacementReleaseSnapshot');expect(release).toContain('successorAbsent:true');expect(text).not.toContain('moveProposedPlacement(');expect(text).not.toContain('send_message');const migration=await readFile(new URL('../../migrations/0129_ls_proposed_placement_moves.sql',import.meta.url));expect(createHash('sha256').update(migration).digest('hex')).toBe(PROPOSED_PLACEMENT_MOVES_MIGRATION.sha256);expect(PROPOSED_PLACEMENT_MOVES_SOURCE_ROOTS).toEqual(['src']);expect(PROPOSED_PLACEMENT_MOVES_SOURCE_PATHS).toContain('scripts/release-draft-group-placement.ts');const entries=await collectProposedPlacementMovesSourceEntries(new URL('../../',import.meta.url)),actual=proposedPlacementMovesSourceBundle(entries),changed=entries.map(entry=>entry.path==='src/features/group-placement/store.ts'?{...entry,bytes:Buffer.concat([entry.bytes,Buffer.from('\n// changed runtime')])}:entry);expect(entries.some(entry=>entry.path==='src/features/group-interest/candidate.ts')).toBe(true);expect(entries.some(entry=>entry.path==='src/features/identity/runtime.ts')).toBe(true);expect(entries.some(entry=>entry.path==='src/lib/security/csrf.ts')).toBe(true);expect(entries.some(entry=>entry.path==='src/db/service-interest-release.ts')).toBe(true);expect(proposedPlacementMovesSourceBundle(changed)).not.toBe(actual);});
 it('rejects symlinked fixed files and source roots before reading bytes',()=>{const symlink={isSymbolicLink:()=>true,isFile:()=>false,isDirectory:()=>false};expect(()=>assertProposedPlacementMovesSourceNode('package.json','file',symlink)).toThrow('PROPOSED_PLACEMENT_MOVES_SOURCE_SYMLINK_REJECTED');expect(()=>assertProposedPlacementMovesSourceNode('src','directory',symlink)).toThrow('PROPOSED_PLACEMENT_MOVES_SOURCE_SYMLINK_REJECTED');});
 it('rejects an actual symlinked source root before traversal',async()=>{const root=await mkdtemp(join(tmpdir(),'ls-placement-source-')),target=join(root,'real-src');try{await mkdir(target);await symlink(target,join(root,'src'),'junction');await expect(collectProposedPlacementMovesSourceEntries(new URL('./',pathToFileURL(join(root,'app-root'))),[],['src'])).rejects.toThrow('PROPOSED_PLACEMENT_MOVES_SOURCE_SYMLINK_REJECTED');}finally{await rm(root,{recursive:true,force:true});}});
});
