import {createHash,randomUUID} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {describe,expect,it} from 'vitest';
import {PUBLIC_GROUP_APPLICATIONS_MIGRATION,PUBLIC_GROUP_APPLICATIONS_SOURCE_PATHS,PUBLIC_GROUP_APPLICATIONS_SOURCE_ROOTS,assertPublicGroupApplicationsSourceNode,collectPublicGroupApplicationsSourceEntries,publicGroupApplicationsMigrationInventory,publicGroupApplicationsPlan,publicGroupApplicationsSourceBundle,type PublicGroupApplicationsReleaseSnapshot} from '../../src/db/public-group-applications-release.ts';
import {validatePublicGroupApplicationsEvidence,validatePublicGroupApplicationsProof} from '../../src/db/public-group-applications-evidence.ts';
import type {Migration} from '../../src/db/migration-plan.ts';

const inventory=async()=>{const manifest=JSON.parse(await readFile(new URL('../../migrations/manifest.json',import.meta.url),'utf8')) as {name:string;sha256:string}[];return Promise.all(manifest.map(async entry=>({name:entry.name,checksum:entry.sha256,sql:await readFile(new URL('../../migrations/'+entry.name,import.meta.url),'utf8')})));};
const snapshot=(stage:0|1):PublicGroupApplicationsReleaseSnapshot=>({stage,catalogDigest:(stage?'b':'a').repeat(64),applicationRows:0,operationRows:0});

describe('public group applications migration 0131 release boundary',()=>{
 it('selects exactly frozen 0130 plus 0131 and ignores future migrations',async()=>{const files=await inventory(),scoped=publicGroupApplicationsMigrationInventory(files);expect(scoped.at(-2)).toMatchObject({name:'0130_ls_draft_group_meetings.sql',checksum:'106320890c774544cee83648d15243decfdef7061c7e14aea532d89ac5be23e7'});expect(scoped.at(-1)).toMatchObject({name:PUBLIC_GROUP_APPLICATIONS_MIGRATION.name,checksum:PUBLIC_GROUP_APPLICATIONS_MIGRATION.sha256});const future:Migration={name:'0132_future_scope.sql',checksum:'c'.repeat(64),sql:'select 1'};expect(publicGroupApplicationsMigrationInventory([...files,future])).toEqual(scoped);expect(()=>publicGroupApplicationsMigrationInventory(files.filter(file=>file.name!=='0130_ls_draft_group_meetings.sql'))).toThrow('PUBLIC_GROUP_APPLICATIONS_MIGRATION_SET_MISMATCH');});
 it('requires ledger and exact schema state to advance together by one',async()=>{const files=await inventory(),scoped=publicGroupApplicationsMigrationInventory(files),baseline=scoped.slice(0,-1).map(({name,checksum})=>({name,checksum})),current=scoped.map(({name,checksum})=>({name,checksum}));expect(publicGroupApplicationsPlan(files,baseline,snapshot(0)).pending.map(item=>item.name)).toEqual([PUBLIC_GROUP_APPLICATIONS_MIGRATION.name]);expect(publicGroupApplicationsPlan(files,current,snapshot(1))).toMatchObject({stage:1,pending:[]});expect(()=>publicGroupApplicationsPlan(files,baseline,snapshot(1))).toThrow('PUBLIC_GROUP_APPLICATIONS_LEDGER_STATE_CONFLICT');});
 it('binds short-lived evidence to target, exact source, backup, restore and expected poststate',()=>{const now=Date.parse('2026-10-09T12:00:00.000Z'),sha='a'.repeat(64),ids={projectId:'3b756632-1f66-4f75-a016-eabc37aa0d67',environmentId:'dd91bd71-57cc-45e6-a75b-8c858491d7c7',appServiceId:'0267d061-f3ce-4a0a-82d4-ce133e4501e9',databaseServiceId:'354b5343-9e83-45a7-b764-09396f14ae29'},deploymentId=randomUUID(),reviewedCommit='b'.repeat(40),sourceBundleSha256=sha,databaseBindingSha256='c'.repeat(64),nonce=randomUUID();const proof={changeId:'LS-PUBLIC-GROUP-APPLICATIONS-MIGRATION-20261009-01',scope:'private-app-public-group-applications-migration-0131',...ids,deploymentId,mode:'apply',reviewedCommit,sourceBundleSha256,manifestSha256:'d'.repeat(64),databaseBindingSha256,baselineStateSha256:'e'.repeat(64),expectedStateSha256:'f'.repeat(64),independentReview:'PASS',isolatedRestore:'PASS',backupId:'private-backup',controlFence:'g'.repeat(32),nonce,issuedAt:'2026-10-09T11:55:00.000Z',expiresAt:'2026-10-09T13:00:00.000Z',evidence:{independentReview:{path:'C:\\private\\review.json',sha256:sha},baselinePreflight:{path:'C:\\private\\preflight.json',sha256:sha},backupReadback:{path:'C:\\private\\backup.json',sha256:sha},isolatedRestore:{path:'C:\\private\\restore.json',sha256:sha},rollbackPlan:{path:'C:\\private\\rollback.json',sha256:sha}}} as const;const parsed=validatePublicGroupApplicationsProof(proof,{...ids,deploymentId,mode:'apply',reviewedCommit,sourceBundleSha256,databaseBindingSha256},now),evidence={changeId:proof.changeId,scope:proof.scope,kind:'isolated_restore',status:'PASS',...ids,deploymentId,mode:'apply',reviewedCommit,sourceBundleSha256,databaseBindingSha256,baselineStateSha256:proof.baselineStateSha256,expectedStateSha256:proof.expectedStateSha256,backupId:proof.backupId,controlFence:proof.controlFence,nonce,createdAt:'2026-10-09T11:54:00.000Z'} as const;expect(validatePublicGroupApplicationsEvidence(evidence,parsed,'isolated_restore',now).kind).toBe('isolated_restore');expect(()=>validatePublicGroupApplicationsEvidence({...evidence,expectedStateSha256:'1'.repeat(64)},parsed,'isolated_restore',now)).toThrow('PUBLIC_GROUP_APPLICATIONS_EVIDENCE_BINDING_MISMATCH');});
 it('keeps the exact-target operator schema-only and binds runtime plus approved public assets',async()=>{const text=await readFile(new URL('../../scripts/release-public-group-applications.ts',import.meta.url),'utf8');for(const token of ['LS_PUBLIC_GROUP_APPLICATIONS_RELEASE_PROOF_SHA256','backupReadback','isolatedRestore','rollbackPlan','assertContactOpsDatabaseIdentity','pg_try_advisory_lock(541931,5)','PUBLIC_GROUP_APPLICATIONS_APPLY_READBACK_FAILED','collectPublicGroupApplicationsSourceEntries'])expect(text).toContain(token);expect(text).not.toContain('createPerson(');expect(text).not.toContain('send_message');const migration=await readFile(new URL('../../migrations/0131_ls_public_group_applications.sql',import.meta.url));expect(createHash('sha256').update(migration).digest('hex')).toBe(PUBLIC_GROUP_APPLICATIONS_MIGRATION.sha256);expect(migration.toString('utf8')).toContain('REVOKE ALL ON FUNCTION');expect(PUBLIC_GROUP_APPLICATIONS_SOURCE_ROOTS).toEqual(['src','public/groups']);expect(PUBLIC_GROUP_APPLICATIONS_SOURCE_PATHS).toContain('scripts/release-draft-group-meetings.ts');const entries=await collectPublicGroupApplicationsSourceEntries(new URL('../../',import.meta.url)),actual=publicGroupApplicationsSourceBundle(entries),changedRuntime=entries.map(entry=>entry.path==='src/features/group-application/store.ts'?{...entry,bytes:Buffer.concat([entry.bytes,Buffer.from('\n// changed runtime')])}:entry),changedAsset=entries.map(entry=>entry.path==='public/groups/private/founder-boy-hero-en-desktop.png'?{...entry,bytes:Buffer.concat([entry.bytes,Buffer.from('changed asset')])}:entry);expect(entries.some(entry=>entry.path==='src/features/group-application/store.ts')).toBe(true);expect(entries.some(entry=>entry.path==='src/features/identity/runtime.ts')).toBe(true);expect(entries.some(entry=>entry.path==='public/groups/private/founder-boy-hero-en-desktop.png')).toBe(true);expect(publicGroupApplicationsSourceBundle(changedRuntime)).not.toBe(actual);expect(publicGroupApplicationsSourceBundle(changedAsset)).not.toBe(actual);});
 it('rejects symlinked source nodes',()=>{const node={isSymbolicLink:()=>true,isFile:()=>false,isDirectory:()=>false};expect(()=>assertPublicGroupApplicationsSourceNode('package.json','file',node)).toThrow('PUBLIC_GROUP_APPLICATIONS_SOURCE_SYMLINK_REJECTED');expect(()=>assertPublicGroupApplicationsSourceNode('src','directory',node)).toThrow('PUBLIC_GROUP_APPLICATIONS_SOURCE_SYMLINK_REJECTED');});
});
