import type { ReactElement } from "react";
import { beforeEach, expect, it, vi } from "vitest";
import { asId } from "../../src/lib/ids.ts";
import type { ResourceProjection } from "../../src/features/resources/service.ts";

type Slot = { kind: "state"; value: unknown } | { kind: "ref"; value: { current: unknown } } | { kind: "effect"; deps: readonly unknown[] | undefined; cleanup: (() => void) | undefined };
const hook = vi.hoisted(() => { const slots: Slot[] = [], pending: Array<{ index: number; effect: () => void | (() => void) }> = []; let cursor = 0, mounted = true; const changed = (a: readonly unknown[] | undefined, b: readonly unknown[] | undefined) => !a || !b || a.length !== b.length || a.some((value, index) => value !== b[index]); return { reset() { slots.length = 0; pending.length = 0; cursor = 0; mounted = true; }, render<T>(view: () => T): T { cursor = 0; return view(); }, flush() { for (const next of pending.splice(0)) { const slot = slots[next.index]; if (slot?.kind === "effect") { slot.cleanup?.(); slot.cleanup = next.effect() || undefined; } } }, useState<T>(initial: T | (() => T)) { const index = cursor++; let slot = slots[index]; if (!slot) { slot = { kind: "state", value: typeof initial === "function" ? (initial as () => T)() : initial }; slots[index] = slot; } if (slot.kind !== "state") throw new Error("HOOK_ORDER"); return [slot.value as T, (value: T | ((previous: T) => T)) => { if (mounted) slot.value = typeof value === "function" ? (value as (previous: T) => T)(slot.value as T) : value; }] as const; }, useRef<T>(initial: T) { const index = cursor++; let slot = slots[index]; if (!slot) { slot = { kind: "ref", value: { current: initial } }; slots[index] = slot; } if (slot.kind !== "ref") throw new Error("HOOK_ORDER"); return slot.value as { current: T }; }, useEffect(effect: () => void | (() => void), deps?: readonly unknown[]) { const index = cursor++; const slot = slots[index]; if (!slot) { slots[index] = { kind: "effect", deps, cleanup: undefined }; pending.push({ index, effect }); return; } if (slot.kind !== "effect") throw new Error("HOOK_ORDER"); if (changed(slot.deps, deps)) { slot.deps = deps; pending.push({ index, effect }); } } }; });
const sessionInfo = vi.hoisted(() => vi.fn(async () => ({ csrfToken: "c".repeat(43) })));
const fetchMock = vi.hoisted(() => vi.fn());
vi.mock("react", async original => { const actual = await original<typeof import("react")>(); return { ...actual, useEffect: hook.useEffect, useRef: hook.useRef, useState: hook.useState }; });
vi.mock("../../src/features/identity/client.ts", () => ({ sessionInfo }));
import { ResourceContext, ResourceReadout, resourceReferenceForInput } from "../../src/features/resources/workspace.tsx";

const caseId = "123e4567-e89b-12d3-a456-426614174000", audienceId = "223e4567-e89b-12d3-a456-426614174000", resourceId = "323e4567-e89b-12d3-a456-426614174000", assignmentId = "423e4567-e89b-12d3-a456-426614174000";
const tick = async () => { for (let index = 0; index < 16; index++) await Promise.resolve(); };
type Change = (event: { target: { value: string; checked?: boolean } }) => void;
type Submit = (event: { preventDefault: () => void }) => void;
function find(node: unknown, predicate: (item: ReactElement<Record<string, unknown>>) => boolean): ReactElement<Record<string, unknown>> | undefined { if (!node || typeof node !== "object") return undefined; if (Array.isArray(node)) return node.map(item => find(item, predicate)).find(Boolean); const item = node as ReactElement<Record<string, unknown>>; return predicate(item) ? item : find(item.props?.children, predicate); }
function all(node: unknown, predicate: (item: ReactElement<Record<string, unknown>>) => boolean, result: ReactElement<Record<string, unknown>>[] = []): ReactElement<Record<string, unknown>>[] { if (!node || typeof node !== "object") return result; if (Array.isArray(node)) { node.forEach(item => all(item, predicate, result)); return result; } const item = node as ReactElement<Record<string, unknown>>; if (predicate(item)) result.push(item); all(item.props?.children, predicate, result); return result; }
function text(node: unknown): string { if (node === null || node === undefined || typeof node === "boolean") return ""; if (typeof node === "string" || typeof node === "number") return String(node); if (Array.isArray(node)) return node.map(text).join(""); return text((node as ReactElement<{ children?: unknown }>).props?.children); }
function render(role: "practitioner" | "parent" = "practitioner") { return hook.render(() => ResourceContext({ locale: "en", role, caseId })); }
function posts() { return fetchMock.mock.calls.filter(call => (call[1] as RequestInit | undefined)?.method === "POST").map(call => ({ url: call[0] as string, init: call[1] as RequestInit })); }
function readPayload(items: ResourceProjection[] = []) { return (url: string, init?: RequestInit) => { if (init?.method === "POST") return Promise.resolve(Response.json({ ok: true, data: { resourceId } })); if (url.startsWith("/api/resources/assignments")) return Promise.resolve(Response.json({ ok: true, data: items })); if (url.startsWith("/api/identity/audiences")) return Promise.resolve(Response.json({ ok: true, data: [{ id: audienceId, visibility: "family_full", published: true }] })); return Promise.resolve(Response.json({ ok: true, data: [{ resourceId, title: "Synthetic library", type: "text", locale: "en" }] })); }; }
async function ready(role: "practitioner" | "parent" = "practitioner") { render(role); hook.flush(); await tick(); return render(role); }
function fillCreate(output: unknown) { const inputs = all(output, item => item.type === "input"), areas = all(output, item => item.type === "textarea"); (inputs[0]!.props.onChange as Change)({ target: { value: "Synthetic title" } }); (areas[1]!.props.onChange as Change)({ target: { value: "Synthetic content" } }); }
function createForm(output: unknown) { const form = all(output, item => item.type === "form")[0]; if (!form) throw new Error("missing create form"); return form.props.onSubmit as Submit; }

beforeEach(() => { hook.reset(); sessionInfo.mockClear(); fetchMock.mockReset(); vi.stubGlobal("fetch", fetchMock); });

it("maps only text and HTTPS links into client create references", () => { expect(resourceReferenceForInput("text", "Synthetic content")).toEqual({ kind: "inline_text", value: "Synthetic content" }); expect(resourceReferenceForInput("link", "https://example.invalid/resource")).toEqual({ kind: "url", value: "https://example.invalid/resource" }); });

it("submits the operator create payload with the session CSRF token", async () => { fetchMock.mockImplementation(readPayload()); let output = await ready(); fillCreate(output); output = render(); createForm(output)({ preventDefault() {} }); await tick(); expect(posts()).toHaveLength(1); expect(posts()[0]!.url).toBe("/api/resources"); expect(posts()[0]!.init.headers).toMatchObject({ "X-CSRF-Token": "c".repeat(43) }); expect(JSON.parse(String(posts()[0]!.init.body))).toMatchObject({ type: "text", title: "Synthetic title", reference: { kind: "inline_text", value: "Synthetic content" }, downloadable: false, locale: "en" }); });

it("uses a synchronous lock so double-click create makes one POST", async () => { let resolve!: (response: Response) => void; fetchMock.mockImplementation((url: string, init?: RequestInit) => init?.method === "POST" ? new Promise<Response>(done => { resolve = done; }) : readPayload()(url, init)); let output = await ready(); fillCreate(output); output = render(); const submit = createForm(output); submit({ preventDefault() {} }); submit({ preventDefault() {} }); await tick(); expect(posts()).toHaveLength(1); resolve(Response.json({ ok: true, data: { resourceId } })); });

it("keeps ambiguous create locked after a failed reload", async () => { let reads = 0; fetchMock.mockImplementation((url: string, init?: RequestInit) => { if (init?.method === "POST") return Promise.resolve(new Response("", { status: 500 })); reads++; return reads <= 3 ? readPayload()(url, init) : Promise.resolve(new Response("", { status: 500 })); }); let output = await ready(); fillCreate(output); output = render(); createForm(output)({ preventDefault() {} }); await tick(); output = render(); expect(find(output, item => item.type === "fieldset")?.props.disabled).toBe(true); const reload = find(output, item => item.type === "button" && item.props.children === "Reload saved state"); (reload?.props.onClick as () => void)(); output = render(); hook.flush(); await tick(); output = render(); expect(text(output)).toContain("Check the saved state"); expect(posts()).toHaveLength(1); });

it("retries failed completion with the same idempotency key", async () => { const item: ResourceProjection = { assignmentId: asId(assignmentId, "resource_assignment"), resourceId: asId(resourceId, "resource"), title: "Synthetic resource", completed: false, detailsAvailable: true, type: "text", description: "Synthetic", reference: { kind: "inline_text", value: "Synthetic" }, downloadable: false, locale: "en", dueDate: null, displayDate: "2026-09-18", completionEnabled: true, completedByAccountId: null }; fetchMock.mockImplementation((url: string, init?: RequestInit) => init?.method === "POST" ? Promise.resolve(new Response("", { status: 500 })) : readPayload([item])(url, init)); let output = await ready("parent"); const complete = find(output, node => node.type === "button" && node.props.children === "Mark complete")?.props.onClick as () => void; complete(); await tick(); output = render("parent"); (find(output, node => node.type === "button" && node.props.children === "Mark complete")?.props.onClick as () => void)(); await tick(); const writes = posts(); expect(writes).toHaveLength(2); expect(JSON.parse(String(writes[0]!.init.body)).idempotencyKey).toBe(JSON.parse(String(writes[1]!.init.body)).idempotencyKey); });

it("renders title-only rows without injected details and never links storage keys", () => { const titleOnly: ResourceProjection = { assignmentId: asId(assignmentId, "resource_assignment"), resourceId: asId(resourceId, "resource"), title: "Family title", completed: false, detailsAvailable: false }; const privateFile: ResourceProjection = { assignmentId: asId(assignmentId, "resource_assignment"), resourceId: asId(resourceId, "resource"), title: "Private file", completed: false, detailsAvailable: true, type: "pdf", description: "Injected details must not leak", reference: { kind: "storage_key", value: "private/resource.pdf" }, downloadable: false, locale: "en", dueDate: null, displayDate: "2026-09-18", completionEnabled: true, completedByAccountId: null }; const titleView = ResourceReadout({ locale: "en", item: titleOnly }), fileView = ResourceReadout({ locale: "en", item: privateFile }); expect(text(titleView)).toContain("Only the title"); expect(text(titleView)).not.toContain("Injected"); expect(JSON.stringify(fileView)).not.toContain("href"); expect(text(fileView)).toContain("Private file delivery"); });
