"use client";
import {useEffect,useMemo,useRef,useState,type FormEvent} from "react";
import type {Locale} from "../../lib/locale.ts";
import {Breadcrumb} from "../../ui/workspace/surfaces.tsx";
import {accountRead,sessionInfo} from "../identity/client.ts";
import {sharedRecapListSchema} from "../session-workflow/recap-contract.ts";
import {RecapPreview} from "../../ui/revamp/recap-preview.tsx";

type Role="parent"|"adult_client"|"child"|"practitioner";
type Case={id:string;displayName:string;kind:"minor"|"adult"};
export function visibleUpdateCases(role:Role,rows:readonly Case[]):Case[]{
 return role==="practitioner"?[...rows]:rows.filter(row=>row.kind===(role==="adult_client"?"adult":"minor"));
}
type Audience={id:string;visibility:"private"|"family_full"|"family_title_completion"};
type Reply={id:string;body:string;createdAt:string};
type Thread={report:{id:string;body:string;submittedAt:string;reviewState:string};replies:Reply[]};
const copy={en:{title:"Context updates",intro:"Share an observation linked to the exact shared home-practice version.",notice:"A reviewed update means the practitioner read it. It is not a witnessed or clinically verified event.",child:"Child",audience:"Shared practice",body:"What did you notice?",send:"Send attributed update",review:"Mark as reviewed",reply:"Send reply",replyBody:"Practitioner reply",instructions:"Adapted practice instructions",adapt:"Create adapted draft",choose:"Open a shared practice instruction first to add feedback.",practice:"Practice",feedback:"Feedback",success:"Saved",failure:"Unable to complete the request. Your text is still here.",loading:"Loading authorized context…",noCases:"No authorized child context is available.",noUpdates:"No feedback has been shared in this context yet.",history:"Feedback history",inbox:"Feedback inbox",submitted:"Submitted",status:"Status",cancel:"Cancel",openComposer:"Add feedback",viewDetails:"Open feedback details",replyDetails:"Open reply",loadingUpdates:"Loading feedback…",selectAudience:"Choose a shared practice context."},he:{title:"עדכוני הקשר",intro:"שתפו תצפית המקושרת לגרסה המדויקת של תרגול הבית ששותפה.",notice:"עדכון שנבדק פירושו שהמטפל קרא אותו. אין זו עדות לאירוע שנצפה או אומת קלינית.",child:"ילד/ה",audience:"תרגול משותף",body:"מה שמתם לב?",send:"שליחת עדכון מיוחס",review:"סימון כנבדק",reply:"שליחת תגובה",replyBody:"תגובת מטפל",instructions:"הוראות תרגול מותאמות",adapt:"יצירת טיוטה מותאמת",choose:"כדי להוסיף משוב, יש לפתוח קודם הנחיית תרגול ששותפה.",practice:"תרגול",feedback:"משוב",success:"נשמר",failure:"לא ניתן להשלים את הבקשה. הטקסט נשאר כאן.",loading:"טוען הקשרים מורשים…",noCases:"אין הקשר מורשה לילד/ה.",noUpdates:"עדיין לא שותף משוב בהקשר הזה.",history:"היסטוריית משוב",inbox:"תיבת משוב",submitted:"נשלח",status:"סטטוס",cancel:"ביטול",openComposer:"הוספת משוב",viewDetails:"פתיחת פרטי המשוב",replyDetails:"פתיחת תגובה",loadingUpdates:"טוען משוב…",selectAudience:"בחרו הקשר של תרגול משותף."}} as const;
export function feedbackContextReady(initialCaseId:string,selectedCaseId:string,initialAudienceId:string,initialPracticeVersionId:string){return Boolean(initialCaseId&&initialCaseId===selectedCaseId&&initialAudienceId&&initialPracticeVersionId)}
function readableTime(locale:Locale,value:string){return new Intl.DateTimeFormat(locale==="he"?"he-IL":"en-GB",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
export function SharedSessionUpdates({locale,caseId}:{locale:Locale;caseId:string}){
 const he=locale==="he",[state,setState]=useState<{caseId:string;items:ReturnType<typeof sharedRecapListSchema.parse>|null;failed:boolean}>({caseId:"",items:null,failed:false}),[revision,setRevision]=useState(0);
 useEffect(()=>{const controller=new AbortController();queueMicrotask(()=>{if(!controller.signal.aborted)setState({caseId,items:null,failed:false});});void fetch(`/api/sessions/shared?caseId=${encodeURIComponent(caseId)}`,{credentials:"same-origin",cache:"no-store",redirect:"error",referrerPolicy:"no-referrer",signal:controller.signal}).then(async response=>{const body=await response.json() as {ok?:boolean;data?:unknown};if(!response.ok||!body.ok)throw new Error("UNAVAILABLE");const items=sharedRecapListSchema.parse(body.data);if(items.some(item=>item.recap.caseId!==caseId||item.recap.sessionId!==item.sessionId))throw new Error("UNAVAILABLE");if(!controller.signal.aborted)setState({caseId,items,failed:false});}).catch(()=>{if(!controller.signal.aborted)setState({caseId,items:null,failed:true});});return()=>controller.abort();},[caseId,revision]);
 const current=state.caseId===caseId,items=current?state.items:null;
 return <section className="lsw-stack" aria-labelledby="shared-session-updates"><h2 id="shared-session-updates">{he?"עדכוני מפגש ששותפו":"Shared session updates"}</h2>{current&&state.failed?<div role="alert"><p>{he?"לא ניתן לאשר את העדכונים המשותפים כעת.":"Shared updates could not be confirmed right now."}</p><button className="lsw-button" type="button" onClick={()=>setRevision(value=>value+1)}>{he?"ניסיון קריאה חוזר":"Retry this read"}</button></div>:items===null?<p role="status">{he?"טוען עדכונים…":"Loading updates…"}</p>:items.length?<><p className="lsw-help">{he?"עד 100 העדכונים האחרונים ששותפו במפורש עם החשבון הזה.":"Up to 100 latest updates explicitly shared with this account."}</p>{items.map(item=><details className="lsw-card" key={item.publicationId}><summary>{readableTime(locale,item.sharedAt)} · {he?"פתיחת העדכון":"Open update"}</summary><RecapPreview locale={locale} recap={item.recap}/></details>)}</>:<p>{he?"עדיין לא שותף עדכון מפגש לחשבון הזה.":"No session update has been shared with this account yet."}</p>}</section>;
}

export function UpdatesWorkspace({locale,role="parent",initialCaseId="",initialAudienceId="",initialPracticeVersionId=""}:{locale:Locale;role?:Role;initialCaseId?:string|undefined;initialAudienceId?:string|undefined;initialPracticeVersionId?:string|undefined}){
 const t=copy[locale],base=`/${locale}/${role==="parent"?"family":role==="practitioner"?"app":"client"}`;
 const contextLabel=role==="adult_client"?(locale==="he"?"תיק":"Client"):t.child;
 const [cases,setCases]=useState<Case[]>([]),[casesLoaded,setCasesLoaded]=useState(false),[caseId,setCaseId]=useState(initialCaseId),[audiences,setAudiences]=useState<Audience[]>([]),[audienceId,setAudienceId]=useState(initialAudienceId),[threads,setThreads]=useState<Thread[]>([]),[threadsState,setThreadsState]=useState<{key:string;status:"idle"|"loading"|"ready"|"error"}>({key:"",status:"idle"}),[body,setBody]=useState(""),[replyBodies,setReplyBodies]=useState<Record<string,string>>({}),[status,setStatus]=useState(""),[composerOpen,setComposerOpen]=useState(false),[pending,setPending]=useState<Record<string,boolean>>({});const mutations=useRef<Record<string,{body:string;key:string}>>({});
 const mounted=useRef(false),inFlight=useRef(new Set<string>()),generation=useRef(0),[revision,setRevision]=useState(0);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[]);
 useEffect(()=>{let live=true;void accountRead<Case[]>("cases").then(rows=>{if(live)setCases(rows)}).catch(()=>{if(live)setCases([])}).finally(()=>{if(live)setCasesLoaded(true)});return()=>{live=false}},[]);
 const choices=useMemo(()=>visibleUpdateCases(role,cases),[cases,role]);
 const selectedCaseId=choices.some(row=>row.id===caseId)?caseId:choices[0]?.id??"";
 useEffect(()=>{let active=true;const controller=new AbortController();queueMicrotask(()=>{if(active){setAudiences([]);setThreads([])}});if(!selectedCaseId)return()=>{active=false;controller.abort()};void fetch(`/api/identity/audiences?caseId=${encodeURIComponent(selectedCaseId)}`,{credentials:"same-origin",cache:"no-store",signal:controller.signal}).then(async response=>{const payload=await response.json() as {ok?:boolean;data?:Audience[]};if(!response.ok||!payload.ok||!Array.isArray(payload.data))throw new Error("UNAVAILABLE");if(!active)return;const allowed=payload.data.filter(item=>role==="practitioner"||item.visibility==="family_full");setAudiences(allowed);setAudienceId(current=>allowed.some(item=>item.id===current)?current:allowed[0]?.id??"")}).catch(error=>{if(active&&!(error instanceof DOMException&&error.name==="AbortError")){setAudiences([]);setAudienceId("")}});return()=>{active=false;controller.abort()}},[role,selectedCaseId]);
 const familyMember=role!=="practitioner",reporter=role==="parent",parentReady=feedbackContextReady(initialCaseId,selectedCaseId,initialAudienceId,initialPracticeVersionId),activeAudienceId=reporter?(parentReady?initialAudienceId:""):role==="practitioner"?audienceId:"",contextKey=`${selectedCaseId}:${activeAudienceId}`;
 useEffect(()=>()=>{generation.current++},[contextKey]);
 useEffect(()=>{const controller=new AbortController();if(!selectedCaseId||!activeAudienceId){queueMicrotask(()=>{if(!controller.signal.aborted)setThreadsState({key:contextKey,status:"idle"})});return()=>controller.abort()}queueMicrotask(()=>{if(!controller.signal.aborted)setThreadsState({key:contextKey,status:"loading"})});const query=new URLSearchParams({caseId:selectedCaseId,audienceId:activeAudienceId});void fetch(`/api/updates?${query}`,{credentials:"same-origin",cache:"no-store",signal:controller.signal}).then(async response=>{const payload=await response.json() as {ok?:boolean;data?:Thread[]};if(!response.ok||!payload.ok||!Array.isArray(payload.data))throw new Error("UNAVAILABLE");if(!controller.signal.aborted){setThreads(payload.data);setThreadsState({key:contextKey,status:"ready"})}}).catch(error=>{if(!controller.signal.aborted&&!(error instanceof DOMException&&error.name==="AbortError")){setThreads([]);setThreadsState({key:contextKey,status:"error"})}});return()=>controller.abort()},[activeAudienceId,contextKey,selectedCaseId,revision]);
 async function post(slot:string,payload:Record<string,unknown>){if(!mounted.current||inFlight.current.has(slot))return false;inFlight.current.add(slot);const epoch=generation.current,current=()=>mounted.current&&generation.current===epoch;setStatus("");setPending(value=>({...value,[slot]:true}));try{const session=await sessionInfo();if(!current())return false;const response=await fetch("/api/updates",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json","X-CSRF-Token":session.csrfToken},body:JSON.stringify(payload)}),result=await response.json() as {ok:boolean};if(!response.ok||!result.ok)throw new Error("REQUEST_FAILED");if(!current())return false;setStatus(t.success);setRevision(value=>value+1);return true}catch{if(current())setStatus(t.failure);return false}finally{inFlight.current.delete(slot);if(mounted.current)setPending(value=>({...value,[slot]:false}))}}
 function mutation(slot:string,value:string){const prior=mutations.current[slot];if(prior?.body===value)return prior.key;const key=crypto.randomUUID();mutations.current[slot]={body:value,key};return key}
 async function submit(e:FormEvent){e.preventDefault();const value=body,slot=`report:${contextKey}`;if(pending[slot])return;if(await post(slot,{action:"submit_report",caseId:selectedCaseId,audienceId:initialAudienceId,practiceVersionId:initialPracticeVersionId,body:value,idempotencyKey:mutation(slot,value)})){setBody(current=>current===value?"":current);setComposerOpen(false)}}
 async function reply(reportId:string){const response=replyBodies[reportId]??"",slot=`reply:${reportId}`;if(!response.trim()||pending[slot])return;if(await post(slot,{action:"reply",reportId,body:response,publish:true,idempotencyKey:mutation(slot,response)}))setReplyBodies(current=>current[reportId]===response?{...current,[reportId]:""}:current)}
 async function review(reportId:string){await post(`review:${reportId}`,{action:"review",reportId})}
 const visible=threadsState.key===contextKey,showThreads=!visible||threadsState.status==="loading"?<p role="status">{t.loadingUpdates}</p>:threadsState.status==="error"?<p role="alert">{t.failure}</p>:threadsState.status==="ready"&&!threads.length?<p>{t.noUpdates}</p>:threads.map(thread=><article className="lsw-card lsw-stack" key={thread.report.id}><div className="lsw-section-header"><div><strong>{t.submitted}</strong><p className="lsw-help">{readableTime(locale,thread.report.submittedAt)}</p></div><span className="lsw-context">{t.status}: {thread.report.reviewState}</span></div><details className="lsw-details"><summary>{t.viewDetails}</summary><p>{thread.report.body}</p></details>{role==="practitioner"?<section className="lsw-stack"><button className="lsw-button lsw-button--secondary" type="button" disabled={pending[`review:${thread.report.id}`]} onClick={()=>void review(thread.report.id)}>{t.review}</button><div className="lsw-field"><label htmlFor={`reply-${thread.report.id}`}>{t.replyBody}</label><textarea id={`reply-${thread.report.id}`} className="lsw-input" maxLength={8000} value={replyBodies[thread.report.id]??""} onChange={e=>setReplyBodies(current=>({...current,[thread.report.id]:e.target.value}))}/></div><button className="lsw-button lsw-button--primary" type="button" disabled={pending[`reply:${thread.report.id}`]} onClick={()=>void reply(thread.report.id)}>{t.reply}</button></section>:null}{thread.replies.map(reply=><details className="lsw-details" key={reply.id}><summary>{t.replyDetails} · {readableTime(locale,reply.createdAt)}</summary><p>{reply.body}</p></details>)}</article>);
 return <main className="lsw-stack lsw-feedback" lang={locale} dir={locale==="he"?"rtl":"ltr"}><Breadcrumb label={locale==="he"?"מיקום":"Location"} items={[{label:t.practice,href:`${base}/practice`},{label:t.feedback}]}/><header className="lsw-page-header"><div><p className="lsw-eyebrow">{familyMember?(locale==="he"?"הודעות ועדכונים":"Messages and updates"):(locale==="he"?"משוב מהורים":"Parent feedback")}</p><h1>{t.title}</h1><p>{t.intro}</p></div></header><aside className="lsw-attention"><p>{t.notice}</p></aside>{!casesLoaded?<p role="status">{t.loading}</p>:!choices.length?<p role="status">{role==='adult_client'?(locale==='he'?'אין הקשר תיק מורשה זמין.':'No authorized client context is available.'):t.noCases}</p>:<>{choices.length===1?<p className="lsw-context">{contextLabel}: <strong>{choices[0]?.displayName??""}</strong></p>:<div className="lsw-field"><label htmlFor="update-case">{contextLabel}</label><select id="update-case" className="lsw-input" value={selectedCaseId} onChange={e=>setCaseId(e.target.value)}>{choices.map(row=><option key={row.id} value={row.id}>{row.displayName}</option>)}</select></div>}{familyMember&&selectedCaseId?<SharedSessionUpdates locale={locale} caseId={selectedCaseId}/>:null}{role==="practitioner"&&<div className="lsw-field"><label htmlFor="update-audience">{t.audience}</label><select id="update-audience" className="lsw-input" value={audienceId} onChange={e=>setAudienceId(e.target.value)} disabled={!audiences.length}><option value="">{t.selectAudience}</option>{audiences.map(item=><option key={item.id} value={item.id}>{item.visibility}</option>)}</select></div>}{reporter&&!parentReady?<section className="lsw-card"><p>{t.choose}</p><a className="lsw-button lsw-button--secondary" href={`${base}/practice`}>{t.practice}</a></section>:null}{activeAudienceId?<><section className="lsw-section-header"><h2>{reporter?t.history:t.inbox}</h2>{reporter&&!composerOpen?<button className="lsw-button lsw-button--primary" type="button" onClick={()=>setComposerOpen(true)}>{t.openComposer}</button>:null}</section>{reporter&&composerOpen?<form className="lsw-card lsw-stack" onSubmit={submit}><div className="lsw-field"><label htmlFor="update-body">{t.body}</label><textarea id="update-body" className="lsw-input" required maxLength={8000} value={body} onChange={e=>setBody(e.target.value)}/></div><div className="lsw-actions"><button className="lsw-button lsw-button--primary" type="submit">{t.send}</button><button className="lsw-button lsw-button--secondary" type="button" onClick={()=>setComposerOpen(false)}>{t.cancel}</button></div></form>:null}{showThreads}</>:null}<p className="lsw-save-result" role="status" aria-live="polite">{status}</p></>}</main>;
}
