import type { Locale } from "../../lib/locale.ts";
export const calendarCopy = {
  "en": {
    "title": "Calendar & attendance",
    "familyTitle": "Your appointments",
    "context": "A clear plan, without mixing attendance and billing.",
    "familyContext": "Appointment details, cancellation notices and requests to change a time.",
    "case": "Case",
    "allCases": "All authorized cases",
    "selectCase": "Choose a case",
    "empty": "No appointments in this period.",
    "newBooking": "Book an appointment",
    "availability": "Availability",
    "addWindow": "Add availability or blocked time",
    "open": "Available",
    "blocked": "Blocked",
    "remove": "Remove window",
    "kind": "Appointment type",
    "individual": "Individual child appointment · 60 minutes",
    "parent_guidance": "Joint-parent check-in · 15 minutes",
    "startsAt": "Start",
    "endsAt": "End",
    "location": "Agreed location or meeting instructions",
    "locationHelp": "Logistics only. Do not enter therapeutic information. No location is assumed.",
    "audience": "Existing authorized family audience",
    "parent": "Authorized parent",
    "parentFor": "Linked child appointment",
    "checkinReason": "Reason for a discretionary check-in after a missed appointment",
    "checkinReview": "The linked child meeting was missed or changed. This check-in needs practitioner review; it is not automatically owed.",
    "before": "Buffer before (minutes)",
    "after": "Buffer after (minutes)",
    "save": "Save",
    "cancel": "Cancel appointment",
    "reschedule": "Request another time",
    "noticeTitle": "Send a cancellation or reschedule notice",
    "noticeRule": "At least 24 elapsed hours before the original start: your session credit is preserved. With less notice or a no-show, one child-session credit is used, unless the practitioner grants an exception.",
    "noticeExplain": "Sending this notice releases the original appointment. A replacement is not booked until the practitioner confirms an available time.",
    "noticeCheck": "I understand what happens to the original appointment and the applicable notice rule.",
    "sendNotice": "Confirm and send notice",
    "suggestion": "Suggested replacement window (optional)",
    "received": "Your notice was recorded",
    "receivedAt": "Server-received notice time",
    "recordedAt": "Recorded in the system",
    "originalStart": "Original appointment time",
    "protected": "This notice meets the 24-hour rule. The session credit is protected.",
    "lateNotice": "This is late notice. The terms call for use of one child-session credit; no replacement is automatically included.",
    "included": "This is a parent check-in, not a separate child-session credit.",
    "financialSeparate": "This receipt records eligibility, not a posted payment or credit balance. Billing is separate.",
    "pending": "A replacement has not been confirmed.",
    "replacementConfirmed": "A replacement has been confirmed.",
    "openReplacement": "Open replacement",
    "exceptionApproved": "Practitioner-approved protection is recorded.",
    "manual": "Record a phone or WhatsApp notice",
    "source": "How the notice was received",
    "phone": "Phone",
    "whatsapp_manual": "WhatsApp, recorded manually",
    "app": "App",
    "actualReceipt": "Actual time the notice was received",
    "requestedBy": "Parent who gave notice",
    "manualHelp": "Record the actual received time, not the time you read the message. The system also preserves the entry time. Earlier evidence supplements rather than rewrites an existing receipt.",
    "attendance": "Attendance",
    "present": "Present",
    "late": "Arrived late",
    "no_show": "No-show",
    "canceled": "Meeting canceled",
    "unrecorded": "Not recorded",
    "arrivedAt": "Actual arrival time",
    "correctionReason": "Administrative correction reason",
    "reasonHelp": "A short operational reason only. Do not enter therapeutic reports or sensitive history.",
    "attendanceHelp": "A late arrival is attendance, not a late cancellation. No-show can be recorded only after the scheduled end. Corrections never rewrite credit history.",
    "recordAttendance": "Record attendance",
    "history": "Attendance history",
    "loadHistory": "Load attendance history",
    "noHistory": "No attendance history yet.",
    "attendedCount": "Attended child sessions",
    "attendanceOnly": "Counted from attendance only, never from credits.",
    "action": "Practitioner action",
    "exception": "Grant a credit-protection exception",
    "providerCancel": "Cancel because the practitioner is unavailable",
    "closeRequest": "Close replacement request without booking",
    "updateLocation": "Update logistics",
    "reason": "Reason",
    "confirmAction": "I have reviewed this administrative action.",
    "applyAction": "Apply action",
    "confirmReplacement": "Confirm a replacement",
    "replacementHelp": "The new time must fit practitioner availability. A late request needs a recorded exception first. No automatic booking or provider notification occurs.",
    "scheduled": "Scheduled",
    "completed": "Appointment closed",
    "canceled_family": "Original appointment canceled by family",
    "canceled_practitioner": "Canceled by practitioner",
    "rescheduled": "Replaced by another appointment",
    "details": "Appointment details",
    "loading": "Loading appointments…",
    "loadMore": "Load more appointments",
    "partial": "More appointments remain in this period. Load the next page to see them.",
    "retry": "Retry",
    "uncertain": "The server result is not confirmed. Keep this window open and retry the same action; do not submit a different action yet.",
    "saveFailed": "The action could not be completed. Your input remains here.",
    "conflict": "This record or slot changed, or the action is not currently allowed. Refresh it and review before saving again.",
    "forbidden": "This appointment is not available to this account.",
    "invalid": "Check the required fields, times, recipients and current state.",
    "unavailable": "Calendar access is unavailable or not enabled. No action has been confirmed.",
    "saved": "Saved.",
    "refresh": "Refresh this appointment",
    "dirty": "You have unsaved changes or an unconfirmed action. Leave this page?",
    "zone": "All times are Asia/Jerusalem.",
    "gap": "This local time does not exist because the clock changes. Choose another time.",
    "fold": "This time occurs twice. Choose the intended occurrence.",
    "chooseOccurrence": "Choose an occurrence",
    "offset": "UTC instant",
    "go": "Show period",
    "period": "Date in the period",
    "bookHelp": "Choose an existing case and audience. Configure availability first. No identities or family grants are created here.",
    "noAudience": "No suitable published family audience or active engagement exists. Complete the shared case setup first.",
    "noCases": "No authorized child cases are available.",
    "language": "עברית",
    "day": "Day",
    "week": "Week",
    "month": "Month",
    "agenda": "Agenda",
    "previous": "Previous",
    "next": "Next",
    "today": "Today",
    "review": "Review before sending",
    "receiptId": "Receipt reference",
    "version": "Version",
    "emptyAvailability": "No availability windows in this period.",
    "noLinked": "Choose an individual child appointment from the visible period, or open that appointment first.",
    "remaining": "This view contains no private therapeutic reports and does not display credit balances."
  },
  "he": {
    "title": "יומן פגישות ונוכחות",
    "familyTitle": "הפגישות שלכם",
    "context": "תכנון ברור, עם הפרדה בין נוכחות לרישום כספי.",
    "familyContext": "פרטי הפגישות, הודעות ביטול ובקשות לשינוי מועד.",
    "case": "תיק",
    "allCases": "כל התיקים המורשים",
    "selectCase": "בחירת תיק",
    "empty": "אין פגישות בתקופה זו.",
    "newBooking": "קביעת פגישה",
    "availability": "זמינות",
    "addWindow": "הוספת זמן פנוי או חסום",
    "open": "זמן פנוי",
    "blocked": "זמן חסום",
    "remove": "הסרת חלון זמן",
    "kind": "סוג הפגישה",
    "individual": "פגישה אישית עם הילד · 60 דקות",
    "parent_guidance": "שיחת הורים משותפת · 15 דקות",
    "startsAt": "התחלה",
    "endsAt": "סיום",
    "location": "מקום שסוכם או הנחיות למפגש",
    "locationHelp": "פרטים תפעוליים בלבד. אין להזין תוכן טיפולי. לא נקבע כאן מקום קבוע מראש.",
    "audience": "קהל משפחתי מורשה שכבר הוגדר",
    "parent": "הורה מורשה",
    "parentFor": "הפגישה המקושרת של הילד",
    "checkinReason": "סיבה לשיחת הורים לפי שיקול דעת לאחר פגישה שלא התקיימה",
    "checkinReview": "פגישת הילד המקושרת לא התקיימה או שמועדה השתנה. יש לבדוק את שיחת ההורים עם המטפל; היא אינה מגיעה באופן אוטומטי.",
    "before": "מרווח לפני הפגישה, בדקות",
    "after": "מרווח אחרי הפגישה, בדקות",
    "save": "שמירה",
    "cancel": "ביטול הפגישה",
    "reschedule": "בקשה למועד אחר",
    "noticeTitle": "שליחת הודעת ביטול או בקשה לשינוי מועד",
    "noticeRule": "בהודעה שמתקבלת לפחות 24 שעות לפני תחילת הפגישה המקורית, הזכות לפגישה נשמרת. בהודעה מאוחרת יותר או באי־הגעה מנוצלת פגישה אחת מהחבילה, אלא אם המטפל אישר חריגה.",
    "noticeExplain": "שליחת ההודעה מבטלת את המועד המקורי. מועד חלופי ייקבע רק לאחר אישור המטפל ובהתאם לזמינות.",
    "noticeCheck": "ברור לי מה יקרה למועד המקורי ומהו כלל ההודעה המוקדמת שחל עליו.",
    "sendNotice": "אישור ושליחת ההודעה",
    "suggestion": "חלון זמן מוצע למפגש חלופי, לא חובה",
    "received": "ההודעה שלכם נרשמה",
    "receivedAt": "מועד קבלת ההודעה בשרת",
    "recordedAt": "מועד הרישום במערכת",
    "originalStart": "מועד הפגישה המקורית",
    "protected": "ההודעה עומדת בכלל 24 השעות. הזכות לפגישה נשמרת.",
    "lateNotice": "זו הודעה מאוחרת. לפי התנאים מנוצלת פגישה אחת מהחבילה; מפגש חלופי אינו כלול באופן אוטומטי.",
    "included": "זו שיחת הורים, ולא פגישה נוספת של הילד מתוך החבילה.",
    "financialSeparate": "אישור זה מציג את הזכאות לפי ההודעה, ולא חיוב שבוצע או יתרת פגישות. הרישום הכספי נפרד.",
    "pending": "עדיין לא אושר מועד חלופי.",
    "replacementConfirmed": "אושר מועד חלופי.",
    "openReplacement": "פתיחת הפגישה החלופית",
    "exceptionApproved": "נרשם אישור המטפל לשמירת הזכות לפגישה.",
    "manual": "רישום הודעה שהתקבלה בטלפון או בוואטסאפ",
    "source": "אופן קבלת ההודעה",
    "phone": "טלפון",
    "whatsapp_manual": "וואטסאפ, ברישום ידני",
    "app": "האפליקציה",
    "actualReceipt": "המועד שבו ההודעה התקבלה בפועל",
    "requestedBy": "ההורה שמסר את ההודעה",
    "manualHelp": "יש לרשום את מועד הקבלה בפועל, ולא את המועד שבו נקראה ההודעה. גם זמן ההזנה נשמר. ראיה מוקדמת יותר נוספת לרישום הקיים ואינה מוחקת אותו.",
    "attendance": "נוכחות",
    "present": "הגיע בזמן",
    "late": "הגיע באיחור",
    "no_show": "לא הגיע",
    "canceled": "המפגש בוטל",
    "unrecorded": "טרם נרשם",
    "arrivedAt": "מועד ההגעה בפועל",
    "correctionReason": "סיבה תפעולית לתיקון",
    "reasonHelp": "סיבה תפעולית קצרה בלבד. אין להזין דוח טיפולי או היסטוריה רגישה.",
    "attendanceHelp": "הגעה באיחור היא נוכחות, ולא ביטול מאוחר. אפשר לרשום אי־הגעה רק לאחר שעת הסיום שנקבעה. תיקוני נוכחות אינם משכתבים את הרישום הכספי.",
    "recordAttendance": "רישום נוכחות",
    "history": "היסטוריית הנוכחות",
    "loadHistory": "טעינת היסטוריית הנוכחות",
    "noHistory": "עדיין אין היסטוריית נוכחות.",
    "attendedCount": "פגישות הילד שהתקיימו",
    "attendanceOnly": "הספירה מבוססת על נוכחות בלבד, ולא על ניצול החבילה.",
    "action": "פעולת מטפל",
    "exception": "אישור חריגה לשמירת הזכות לפגישה",
    "providerCancel": "ביטול עקב אי־זמינות המטפל",
    "closeRequest": "סגירת הבקשה ללא קביעת מועד חלופי",
    "updateLocation": "עדכון פרטים תפעוליים",
    "reason": "סיבה",
    "confirmAction": "בדקתי את הפעולה התפעולית לפני ביצועה.",
    "applyAction": "ביצוע הפעולה",
    "confirmReplacement": "אישור פגישה חלופית",
    "replacementHelp": "המועד החדש חייב להתאים לזמינות המטפל. בקשה מאוחרת דורשת קודם אישור חריגה מתועד. אין קביעה אוטומטית או שליחת הודעה לספק חיצוני.",
    "scheduled": "מתוכנן",
    "completed": "מועד הפגישה נסגר",
    "canceled_family": "המועד המקורי בוטל על ידי המשפחה",
    "canceled_practitioner": "בוטל על ידי המטפל",
    "rescheduled": "נקבע מפגש חלופי",
    "details": "פרטי הפגישה",
    "loading": "הפגישות נטענות…",
    "loadMore": "טעינת פגישות נוספות",
    "partial": "יש פגישות נוספות בתקופה זו. יש לטעון את העמוד הבא כדי לראות אותן.",
    "retry": "ניסיון חוזר",
    "uncertain": "עדיין אין אישור לתוצאת הפעולה בשרת. יש להשאיר את החלון פתוח ולנסות שוב את אותה הפעולה, ולא לשלוח פעולה אחרת בינתיים.",
    "saveFailed": "לא ניתן היה להשלים את הפעולה. הפרטים שהוזנו נשמרו כאן.",
    "conflict": "הרישום או הזמינות השתנו, או שהפעולה אינה מותרת כעת. יש לרענן ולבדוק לפני שמירה נוספת.",
    "forbidden": "הפגישה אינה זמינה לחשבון זה.",
    "invalid": "יש לבדוק את שדות החובה, המועדים, ההורים המורשים ומצב הפגישה.",
    "unavailable": "הגישה ליומן אינה זמינה או שטרם הופעלה. לא אושרה שום פעולה.",
    "saved": "נשמר.",
    "refresh": "רענון פרטי הפגישה",
    "dirty": "יש שינויים שלא נשמרו או פעולה שטרם אושרה. לצאת מהעמוד?",
    "zone": "כל המועדים מוצגים לפי Asia/Jerusalem.",
    "gap": "השעה המקומית הזו אינה קיימת בשל מעבר שעון. יש לבחור שעה אחרת.",
    "fold": "השעה הזו מופיעה פעמיים בשל מעבר שעון. יש לבחור את המועד הרצוי.",
    "chooseOccurrence": "בחירת המועד הרצוי",
    "offset": "מועד לפי UTC",
    "go": "הצגת התקופה",
    "period": "תאריך בתקופה להצגה",
    "bookHelp": "יש לבחור תיק וקהל מורשה שכבר הוגדרו ולהגדיר זמינות מראש. מסך זה אינו יוצר זהויות או הרשאות משפחתיות.",
    "noAudience": "אין קהל משפחתי מלא שפורסם או התקשרות פעילה מתאימה. יש להשלים תחילה את הגדרת התיק המשותפת.",
    "noCases": "אין תיקי ילדים מורשים להצגה.",
    "language": "English",
    "day": "יום",
    "week": "שבוע",
    "month": "חודש",
    "agenda": "רשימת פגישות",
    "previous": "הקודם",
    "next": "הבא",
    "today": "היום",
    "review": "בדיקה לפני השליחה",
    "receiptId": "מספר אסמכתה",
    "version": "גרסה",
    "emptyAvailability": "לא הוגדרו חלונות זמינות בתקופה זו.",
    "noLinked": "יש לבחור פגישה אישית של הילד מתוך התקופה המוצגת, או לפתוח תחילה את אותה פגישה.",
    "remaining": "מסך זה אינו מציג דוחות טיפוליים פרטיים או יתרות כספיות."
  }
} as const;
export const text = (locale:Locale) => calendarCopy[locale];
export type CalendarText = typeof calendarCopy.en;
