import { randomUUID } from 'node:crypto';
import { AppError } from '../../lib/errors.ts';
import { asId, type CaseId, type WorkspaceId } from '../../lib/ids.ts';
import { caseAccess,type CaseFacts } from '../cases/policy.ts';
import { loadCase,loadGuardians } from '../cases/data.ts';
import { freshActor,lockWorkspace,type AccountRow } from '../identity/data.ts';
import { one,type IdentityStore,type SqlSession } from '../identity/store.ts';
import type { Actor,IdentityClock } from '../identity/types.ts';
import { seal,type Keyring } from '../identity/crypto.ts';
import { APPOINTMENT_RATE_MINOR,BLOCK_PRICE_MINOR,CREDITS_PER_BLOCK,CURRENCY,IDEMPOTENCY_KEY,bodyDigest } from './policy.ts';
import { demoCaseBatch } from '../demo/provenance.ts';
import type { AllocationView,ChargeView,CreditBlockView,CreditEventView,PaymentsOverview,PaymentView,RefundView } from './types.ts';
export interface PaymentContext {tx:SqlSession;actor:AccountRow;workspace:WorkspaceId;now:Date;}
function iso(value:Date|string):string{const result=new Date(value).toISOString();if(result==='Invalid Date')throw new AppError('UNAVAILABLE');return result;}
export class PaymentsStore {
 constructor(readonly database:IdentityStore,private readonly ring:Keyring,private readonly clock:IdentityClock){}
 async read<T>(actor:Actor,work:(context:PaymentContext)=>Promise<T>):Promise<T>{return this.database.transaction(async tx=>{const current=await freshActor(tx,actor,this.clock.now());return work({tx,actor:current,workspace:actor.workspaceId,now:this.clock.now()});});}
 async command<T>(actor:Actor,operation:string,key:string,body:unknown,authorize:(context:PaymentContext)=>Promise<void>,work:(context:PaymentContext)=>Promise<T>):Promise<T>{
  if(!IDEMPOTENCY_KEY.test(key)||operation.length>80)throw new AppError('INVALID_REQUEST');const digest=bodyDigest(body);
  return this.database.transaction(async tx=>{await lockWorkspace(tx,actor.workspaceId);const now=this.clock.now(),current=await freshActor(tx,actor,now),context={tx,actor:current,workspace:actor.workspaceId,now};await authorize(context);
   const cached=await one<{bodyDigest:string;result:unknown}>(tx,'SELECT body_digest AS "bodyDigest",result_json AS result FROM ls_payments.commands WHERE workspace_id=$1 AND account_id=$2 AND operation=$3 AND command_key=$4',[context.workspace,current.id,operation,key]);
   if(cached){if(cached.bodyDigest!==digest)throw new AppError('CONFLICT');return cached.result as T;}
   const result=await work(context);await tx.query('INSERT INTO ls_payments.commands(workspace_id,account_id,operation,command_key,body_digest,result_json,created_at) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7)',[context.workspace,current.id,operation,key,digest,JSON.stringify(result),now]);return result;
  });
 }
 async requireCase(context:PaymentContext,caseId:CaseId,operation:'read'|'write'):Promise<CaseFacts>{const item=await loadCase(context.tx,context.workspace,caseId);caseAccess(context.actor,item,await loadGuardians(context.tx,context.workspace,caseId),operation);if(!item)throw new AppError('NOT_FOUND');return item;}
 async requireMinorCase(context:PaymentContext,caseId:CaseId,operation:'read'|'write'):Promise<void>{const item=await this.requireCase(context,caseId,operation);if(item.kind!=='minor')throw new AppError('NOT_FOUND');if(operation==='write'&&await demoCaseBatch(context.tx,context.workspace,caseId))throw new AppError('FORBIDDEN');}
 private id<K extends string>(kind:K){return asId(randomUUID(),kind);}
 encryptReference(context:PaymentContext,paymentId:string,value:string):string{return seal(value,`payment:${context.workspace}:${paymentId}`,this.ring);}
 async overview(context:PaymentContext,caseId:CaseId):Promise<PaymentsOverview>{
  const charges=await context.tx.query<{id:ChargeView['id'];caseId:CaseId;kind:'four_appointment_block';amountMinor:number;allocatedMinor:number;currency:'ILS';status:'open'|'paid';dueOn:string;createdAt:Date}>(`SELECT c.id,c.case_id AS "caseId",c.kind,c.amount_minor AS "amountMinor",COALESCE(SUM(a.amount_minor),0)::integer AS "allocatedMinor",c.currency,c.status,c.due_on::text AS "dueOn",c.created_at AS "createdAt" FROM ls_payments.charges c LEFT JOIN ls_payments.allocations a ON a.workspace_id=c.workspace_id AND a.charge_id=c.id WHERE c.workspace_id=$1 AND c.case_id=$2 GROUP BY c.id ORDER BY c.created_at,c.id`,[context.workspace,caseId]);
  const payments=await context.tx.query<{id:PaymentView['id'];caseId:CaseId;amountMinor:number;allocatedMinor:number;currency:'ILS';method:PaymentView['method'];receivedAt:Date;recordedAt:Date}>(`SELECT p.id,p.case_id AS "caseId",p.amount_minor AS "amountMinor",COALESCE(SUM(a.amount_minor),0)::integer AS "allocatedMinor",p.currency,p.method,p.received_at AS "receivedAt",p.recorded_at AS "recordedAt" FROM ls_payments.payments p LEFT JOIN ls_payments.allocations a ON a.workspace_id=p.workspace_id AND a.payment_id=p.id WHERE p.workspace_id=$1 AND p.case_id=$2 GROUP BY p.id ORDER BY p.received_at,p.id`,[context.workspace,caseId]);
  const allocations=await context.tx.query<{id:AllocationView['id'];paymentId:AllocationView['paymentId'];chargeId:AllocationView['chargeId'];amountMinor:number;allocatedAt:Date}>(`SELECT id,payment_id AS "paymentId",charge_id AS "chargeId",amount_minor AS "amountMinor",allocated_at AS "allocatedAt" FROM ls_payments.allocations WHERE workspace_id=$1 AND case_id=$2 ORDER BY allocated_at,id`,[context.workspace,caseId]);
  const blocks=await context.tx.query<{id:CreditBlockView['id'];chargeId:CreditBlockView['chargeId'];creditsPurchased:number;purchaseAmountMinor:number;termsVersion:'Product2.3';purchasedAt:Date;remainingCredits:number}>(`SELECT b.id,b.charge_id AS "chargeId",b.credits_purchased AS "creditsPurchased",b.purchase_amount_minor AS "purchaseAmountMinor",b.terms_version AS "termsVersion",b.purchased_at AS "purchasedAt",COALESCE(SUM(e.delta_credits),0)::integer AS "remainingCredits" FROM ls_payments.credit_blocks b LEFT JOIN ls_payments.credit_events e ON e.workspace_id=b.workspace_id AND e.credit_block_id=b.id WHERE b.workspace_id=$1 AND b.case_id=$2 GROUP BY b.id ORDER BY b.purchased_at,b.id`,[context.workspace,caseId]);
  const events=await context.tx.query<{id:CreditEventView['id'];blockId:CreditEventView['blockId'];kind:CreditEventView['kind'];deltaCredits:number;valueMinor:number;appointmentId:string|null;rescheduleRequestId:string|null;reasonCode:string;occurredAt:Date}>(`SELECT id,credit_block_id AS "blockId",kind,delta_credits AS "deltaCredits",value_minor AS "valueMinor",appointment_id AS "appointmentId",reschedule_request_id AS "rescheduleRequestId",reason_code AS "reasonCode",occurred_at AS "occurredAt" FROM ls_payments.credit_events WHERE workspace_id=$1 AND case_id=$2 ORDER BY occurred_at,id`,[context.workspace,caseId]);
  const refunds=await context.tx.query<{id:RefundView['id'];blockId:RefundView['blockId'];credits:number;amountMinor:number;recordedAt:Date}>(`SELECT id,credit_block_id AS "blockId",credits,amount_minor AS "amountMinor",recorded_at AS "recordedAt" FROM ls_payments.refunds WHERE workspace_id=$1 AND case_id=$2 ORDER BY recorded_at,id`,[context.workspace,caseId]);
  const balance=blocks.reduce((sum,item)=>sum+Number(item.remainingCredits),0);
  return {caseId,currency:CURRENCY,appointmentRateMinor:APPOINTMENT_RATE_MINOR,blockPriceMinor:BLOCK_PRICE_MINOR,creditsPerBlock:CREDITS_PER_BLOCK,remainingCredits:balance,remainingValueMinor:balance*APPOINTMENT_RATE_MINOR,asOf:context.now.toISOString(),charges:charges.map(v=>({...v,amountMinor:BLOCK_PRICE_MINOR,allocatedMinor:Number(v.allocatedMinor),outstandingMinor:BLOCK_PRICE_MINOR-Number(v.allocatedMinor),createdAt:iso(v.createdAt)})),payments:payments.map(v=>({...v,amountMinor:Number(v.amountMinor),allocatedMinor:Number(v.allocatedMinor),unallocatedMinor:Number(v.amountMinor)-Number(v.allocatedMinor),receivedAt:iso(v.receivedAt),recordedAt:iso(v.recordedAt)})),allocations:allocations.map(v=>({...v,amountMinor:Number(v.amountMinor),allocatedAt:iso(v.allocatedAt)})),blocks:blocks.map(v=>({...v,creditsPurchased:CREDITS_PER_BLOCK,purchaseAmountMinor:BLOCK_PRICE_MINOR,remainingCredits:Number(v.remainingCredits),purchasedAt:iso(v.purchasedAt)})),events:events.map(v=>({...v,deltaCredits:Number(v.deltaCredits),valueMinor:Number(v.valueMinor),occurredAt:iso(v.occurredAt)})),refunds:refunds.map(v=>({...v,credits:Number(v.credits),amountMinor:Number(v.amountMinor),recordedAt:iso(v.recordedAt)}))};
 }
 newChargeId(){return this.id('payment_charge');}newPaymentId(){return this.id('payment');}newAllocationId(){return this.id('payment_allocation');}newBlockId(){return this.id('credit_block');}newEventId(){return this.id('credit_event');}newRefundId(){return this.id('payment_refund');}
}
