'use client';
import { useCallback,useEffect,useRef,useState,type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import type { Locale } from '../../lib/locale.ts';
import { accountRead,sessionInfo } from '../identity/client.ts';
import { Button,Input,Select,Textarea } from '../../ui/workspace/controls.tsx';
import { Card,EmptyState,ErrorState,LoadingState,PageHeader,StatusChip } from '../../ui/workspace/surfaces.tsx';
import { paymentText } from './copy.ts';
import { parseIlsMinor } from './amount.ts';
import { paymentsRead,paymentsWrite } from './client.ts';
import type { PaymentsOverview } from './types.ts';
type CaseChoice={id:string;displayName:string;kind:'minor'|'adult';state:string};
function money(value:number,locale:Locale){return new Intl.NumberFormat(locale==='he'?'he-IL':'en-IL',{style:'currency',currency:'ILS'}).format(value/100);}
function short(id:string){return id.slice(-6);}
export function PaymentsWorkspace({locale,embedded=false,languageHref,initialCaseId}:{locale:Locale;embedded?:boolean;languageHref?:string;initialCaseId?:string|undefined}){
 const router=useRouter();
 const t=paymentText(locale),[role,setRole]=useState<'practitioner'|'parent'|null>(null),[cases,setCases]=useState<CaseChoice[]>([]),[caseId,setCaseId]=useState(''),[overview,setOverview]=useState<PaymentsOverview|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(false),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false),[uncertain,setUncertain]=useState(false),pendingMutation=useRef<{path:'charges'|'payments'|'allocations'|'refunds';body:unknown;key:string}|null>(null);
 const [amount,setAmount]=useState('2200'),[method,setMethod]=useState<'cash'|'bank_transfer'>('bank_transfer'),[received,setReceived]=useState(()=>new Date().toISOString().slice(0,10)),[dueOn,setDueOn]=useState(()=>new Date().toISOString().slice(0,10)),[reference,setReference]=useState(''),[paymentId,setPaymentId]=useState(''),[chargeId,setChargeId]=useState(''),[blockId,setBlockId]=useState(''),[credits,setCredits]=useState('1'),[reason,setReason]=useState('');
 useEffect(()=>{let current=true;const timer=window.setTimeout(()=>{void Promise.all([sessionInfo(),accountRead<CaseChoice[]>('cases')]).then(([session,items])=>{if(!current)return;const available=session.role==='practitioner'?items:items.filter(item=>item.kind==='minor');setRole(session.role==='practitioner'?'practitioner':'parent');setCases(available);setCaseId(available.find(item=>item.id===initialCaseId)?.id??available[0]?.id??'');setLoading(false);}).catch(()=>{if(current){setError(true);setLoading(false);}});},0);return()=>{current=false;window.clearTimeout(timer);};},[initialCaseId]);
 const load=useCallback(async()=>{if(!caseId){setOverview(null);return;}setLoading(true);setError(false);try{const value=await paymentsRead<PaymentsOverview>(caseId);setOverview(value);setPaymentId(value.payments[0]?.id??'');setChargeId(value.charges.find(item=>item.status==='open')?.id??'');setBlockId(value.blocks.find(item=>item.remainingCredits>0)?.id??'');}catch{setOverview(null);setError(true);}finally{setLoading(false);}},[caseId]);
 useEffect(()=>{let current=true;const timer=window.setTimeout(()=>{if(current)void load();},0);return()=>{current=false;window.clearTimeout(timer);};},[load]);
 async function mutate(path:'charges'|'payments'|'allocations'|'refunds',body:unknown,reconcile=false){if(busy||pendingMutation.current&&!reconcile){setUncertain(true);return false}const command=reconcile?pendingMutation.current:{path,body,key:crypto.randomUUID()};if(!command)return false;pendingMutation.current=command;setBusy(true);setSaved(false);setError(false);try{await paymentsWrite(command.path,command.body,command.key);pendingMutation.current=null;setUncertain(false);setSaved(true);await load();return true}catch{setError(true);setUncertain(true);return false}finally{setBusy(false)}}
 function submit(event:FormEvent<HTMLFormElement>,action:()=>Promise<void>){event.preventDefault();if(!event.currentTarget.reportValidity())return;try{void action().catch(()=>setError(true));}catch{setError(true);}}
 const practitioner=role==='practitioner';
 return <section className={embedded?"lsw-stack lsw-payments":"lsw"} dir={locale==='he'?'rtl':'ltr'} lang={locale}><PageHeader title={t.title} context={t.context} action={<a href={languageHref??`/${locale==='he'?'en':'he'}/payments`}>{t.language}</a>}/><p>{t.price}</p><p className="lsw-help">{t.separate}</p>
 <Select id="payments-case" label={t.caseLabel} value={caseId} onChange={event=>{const next=event.target.value;if(next&&!cases.some(item=>item.id===next))return;setCaseId(next);router.replace(`/${locale}/${embedded?'app/payments':'payments'}${next?`?caseId=${encodeURIComponent(next)}`:''}`,{scroll:false})}} disabled={busy}><option value="">{t.selectCase}</option>{cases.map(item=><option key={item.id} value={item.id}>{item.displayName}</option>)}</Select>
 {loading?<LoadingState locale={locale}/>:error&&!overview?<ErrorState locale={locale} onRetry={()=>void load()}/>:!caseId?<EmptyState locale={locale}/>:overview&&<><div className="lsw-content-grid"><Card id="payment-balance" title={t.balance}><p className="lsw-credit-number">{new Intl.NumberFormat(locale).format(overview.remainingCredits)}</p><p>{t.value}: <strong>{money(overview.remainingValueMinor,locale)}</strong></p><p className="lsw-help">{t.asOf} <time dateTime={overview.asOf}>{new Intl.DateTimeFormat(locale==='he'?'he-IL':'en-IL',{dateStyle:'medium',timeStyle:'short'}).format(new Date(overview.asOf))}</time></p></Card><Card id="payment-blocks" title={t.blocks}>{overview.blocks.length?<ul>{overview.blocks.map(item=><li key={item.id}>{short(item.id)} · {item.remainingCredits}/{item.creditsPurchased} · {money(item.purchaseAmountMinor,locale)}</li>)}</ul>:<p>{t.empty}</p>}</Card></div>
 <div className="lsw-content-grid"><Card id="payment-charges" title={t.charges}>{overview.charges.length?<ul>{overview.charges.map(item=><li key={item.id}>{short(item.id)} · {money(item.amountMinor,locale)} · {t.outstanding}: {money(item.outstandingMinor,locale)} · {t.dueOn}: <time dateTime={item.dueOn}>{item.dueOn}</time> · <StatusChip tone={item.status==='paid'?'positive':'warning'}>{item.status==='paid'?t.paid:t.open}</StatusChip></li>)}</ul>:<p>{t.empty}</p>}</Card><Card id="payment-received" title={t.payments}>{overview.payments.length?<ul>{overview.payments.map(item=><li key={item.id}>{short(item.id)} · {money(item.amountMinor,locale)} · {t.unallocated}: {money(item.unallocatedMinor,locale)} · {item.method==='cash'?t.cash:t.bank_transfer}</li>)}</ul>:<p>{t.empty}</p>}</Card></div>
 <Card id="credit-history" title={t.events}>{overview.events.length?<ol>{overview.events.map(item=><li key={item.id}><time dateTime={item.occurredAt}>{new Intl.DateTimeFormat(locale==='he'?'he-IL':'en-IL',{dateStyle:'medium'}).format(new Date(item.occurredAt))}</time> · {item.kind==='purchase'?t.purchase:item.kind==='consume'?t.consume:item.kind==='restore'?t.restore:t.refundEvent} · {item.deltaCredits>0?'+':''}{item.deltaCredits}</li>)}</ol>:<p>{t.empty}</p>}</Card></>}
 {practitioner&&caseId?<section className="lsw-content-grid" aria-label={t.practitionerOnly}><Card id="new-charge" title={t.newCharge}><p>{t.price}</p><Input id="charge-due-on" label={t.dueOn} type="date" value={dueOn} onChange={event=>setDueOn(event.target.value)} required/><Button busy={busy} onClick={()=>void mutate('charges',{caseId,dueOn})}>{t.newCharge}</Button></Card>
 <Card id="record-payment" title={t.recordPayment}><form onSubmit={event=>submit(event,async()=>{if(await mutate('payments',{caseId,amountMinor:parseIlsMinor(amount),method,receivedAt:received+'T12:00:00Z',privateReference:reference}))setReference('');})}><Input id="payment-amount" label={t.amount} inputMode="decimal" value={amount} onChange={event=>setAmount(event.target.value)} required/><Select id="payment-method" label={t.method} value={method} onChange={event=>setMethod(event.target.value as 'cash'|'bank_transfer')}><option value="cash">{t.cash}</option><option value="bank_transfer">{t.bank_transfer}</option></Select><Input id="payment-received" label={t.received} type="date" value={received} onChange={event=>setReceived(event.target.value)} required/><Input id="payment-reference" label={t.reference} value={reference} onChange={event=>setReference(event.target.value)} maxLength={160} required/><Button type="submit" busy={busy}>{t.save}</Button></form></Card>
 <Card id="allocate-payment" title={t.allocate}><form onSubmit={event=>submit(event,async()=>{await mutate('allocations',{caseId,paymentId,chargeId,amountMinor:parseIlsMinor(amount)})})}><Select id="allocation-payment" label={t.payment} value={paymentId} onChange={event=>setPaymentId(event.target.value)} required><option value="">—</option>{overview?.payments.map(item=><option key={item.id} value={item.id}>{short(item.id)} · {money(item.amountMinor,locale)}</option>)}</Select><Select id="allocation-charge" label={t.charge} value={chargeId} onChange={event=>setChargeId(event.target.value)} required><option value="">—</option>{overview?.charges.filter(item=>item.status==='open').map(item=><option key={item.id} value={item.id}>{short(item.id)} · {money(item.amountMinor,locale)}</option>)}</Select><Input id="allocation-amount" label={t.amount} inputMode="decimal" value={amount} onChange={event=>setAmount(event.target.value)} required/><Button type="submit" busy={busy}>{t.save}</Button></form></Card>
 <Card id="refund-credit" title={t.refund}><form onSubmit={event=>submit(event,async()=>{if(await mutate('refunds',{caseId,blockId,credits:Number(credits),reason}))setReason('');})}><Select id="refund-block" label={t.block} value={blockId} onChange={event=>setBlockId(event.target.value)} required><option value="">—</option>{overview?.blocks.filter(item=>item.remainingCredits>0).map(item=><option key={item.id} value={item.id}>{short(item.id)} · {item.remainingCredits}</option>)}</Select><Input id="refund-credits" label={t.credits} type="number" min={1} max={4} step={1} value={credits} onChange={event=>setCredits(event.target.value)} required/><Textarea id="refund-reason" label={t.reason} value={reason} onChange={event=>setReason(event.target.value)} maxLength={500} required/><Button type="submit" busy={busy}>{t.save}</Button></form></Card></section>:role===null?<p className="lsw-help">{t.practitionerOnly}</p>:null}
 <div role="status" aria-live="polite">{busy?t.saving:saved?t.saved:error?t.failed:''}</div>{uncertain&&<section role="alert" className="lsu-state lsu-state--error"><p>{locale==='he'?'תוצאת השמירה אינה ידועה. הטיוטה והמפתח המקורי נשמרו; יש לבדוק את אותה פעולה לפני יצירת פעולה חדשה.':'The save result is unknown. The draft and original request key are retained; reconcile that same action before creating another.'}</p><Button busy={busy} onClick={()=>void mutate('charges',{},true)}>{locale==='he'?'בדיקת תוצאת הפעולה':'Reconcile saved action'}</Button></section>}</section>;
}
