"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { sessionInfo } from "../identity/client.ts";
import { UnsavedChangesGuard } from "../../ui/workspace/draft-guard.tsx";
import type { CommunitySettings, ScoutRequestedSettings, ScoutSavedControls } from "./settings-bridge.ts";
type Locale = "he" | "en";
type SettingsView = 'all'|'sources'|'budget';
const copy = {
  en: {
    title: "Actual Scout runtime", loading: "Checking Scout settings…", unavailable: "Scout settings could not be verified. Collection and spending must not be assumed active.", retry: "Retry settings",
    collection: "Collection gates", eligible: "Eligible; actual scheduled run unverified", on: "On", off: "Off", groups: "Runtime approved groups", provider: "Provider binding configured", noGroups: "No approved runtime group URLs are configured. Requested sources below do not activate collection.",
    worker: "Worker", auto: "Automatic drafting", max: "Maximum items per run", ai: "AI requests per UTC day", manual: "Manual reply requests used / remaining / total", tokens: "Tokens today (input / output)", cost: "Money spent", unknown: "Not metered here — unknown is not zero", jobs: "Jobs by state", posts: "Unexpired captured posts by status", none: "None", checked: "Runtime checked at", actualHelp: "Read-only actual configuration. Eligibility is not proof of a scheduled run, captured post or publication.",
    requested: "Requested settings", help: "Saving records an owner request in the existing Scout database. It does not configure a provider, install a schedule, enable spending or post replies. Those gates remain separate.", sources: "Allowed public Facebook group URLs", url: "Exact group URL", enabled: "Allowed source", add: "Add group", remove: "Remove group", empty: "No requested groups. Add only public groups you are authorized to read.", lookback: "Lookback days", schedule: "Request one daily collection run", time: "Requested daily time", timezone: "Timezone", draft: "Request automatic drafts", postsLimit: "Posts per run", draftsLimit: "Drafts per day", threadsLimit: "Threads per run", bounds: "New requests must fit actual runtime limits; one generated-and-reviewed draft uses two AI requests.", scraping: "Monthly scraping ceiling (USD cents)", aiBudget: "Monthly AI ceiling (USD cents)", caps: "Blank means not authorized, not unlimited. 100 cents = $1.00. Monetary cost remains unverified until provider metering is connected.", confirm: "I approve these exact increased ceilings as a stored request, not provider activation", save: "Save requested settings", saving: "Saving and reading back…", saved: "Saved and read back from Scout", version: "Settings version", updated: "Last saved", new: "Not yet saved", failed: "Save is unconfirmed. Your input is preserved. Retry the same save; do not assume it was stored.", invalid: "Check exact public group URLs, duplicates, limits, prerequisites and ceiling approval. Your input is preserved.", conflict: "The saved version changed elsewhere. Your input is preserved. Read the saved version to compare; nothing was overwritten.", compare: "Read saved version", replace: "Replace your unsaved settings with the saved version?", leave: "Leave without saving your Scout settings?", lowered: "Saved requests exceed a current runtime limit. They remain visible but cannot activate work; adjust before a new save.", forbidden: "This account cannot change the canonical Scout settings. Your input is preserved.",
  },
  he: {
    title: "הגדרות Scout החיות", loading: "בודק הגדרות Scout…", unavailable: "לא ניתן לאמת את ההגדרות. אין להניח שאיסוף או הוצאה פעילים.", retry: "בדיקה חוזרת",
    collection: "תנאי האיסוף", eligible: "כשיר; הרצה מתוזמנת בפועל לא אומתה", on: "פעיל", off: "כבוי", groups: "קבוצות מאושרות בזמן הריצה", provider: "חיבור הספק מוגדר", noGroups: "אין כתובות קבוצות מאושרות בזמן הריצה. בקשת מקורות למטה אינה מפעילה איסוף.",
    worker: "תהליך רקע", auto: "יצירת טיוטות אוטומטית", max: "פריטים מרביים בהרצה", ai: "בקשות AI ליום UTC", manual: "בקשות ידניות: נוצלו / נותרו / סך הכול", tokens: "טוקנים היום (קלט / פלט)", cost: "הוצאה כספית", unknown: "אינה נמדדת כאן — מצב לא ידוע אינו אפס", jobs: "משימות לפי מצב", posts: "פוסטים שנקלטו ועדיין בתוקף", none: "אין", checked: "ההגדרות החיות נבדקו ב־", actualHelp: "קריאה בלבד של ההגדרות החיות. כשירות אינה הוכחה להרצה מתוזמנת, לפוסט שנקלט או לפרסום.",
    requested: "הגדרות מבוקשות", help: "השמירה מתעדת בקשת בעלים במסד Scout הקיים. היא אינה מגדירה ספק, מתקינה תזמון, מפעילה הוצאה או מפרסמת תגובות. תנאים אלה נשארים נפרדים.", sources: "כתובות קבוצות Facebook ציבוריות מותרות", url: "כתובת הקבוצה המדויקת", enabled: "מקור מותר", add: "הוספת קבוצה", remove: "הסרת קבוצה", empty: "אין קבוצות מבוקשות. הוסיפו רק קבוצות ציבוריות שיש לכם הרשאה לקרוא.", lookback: "מספר ימים לאחור", schedule: "בקשה לאיסוף יומי אחד", time: "שעת איסוף יומית מבוקשת", timezone: "אזור זמן", draft: "בקשה לטיוטות אוטומטיות", postsLimit: "פוסטים בהרצה", draftsLimit: "טיוטות ביום", threadsLimit: "שרשורים בהרצה", bounds: "בקשות חדשות חייבות לעמוד במגבלות החיות. יצירה ובדיקה של טיוטה משתמשות בשתי בקשות AI.", scraping: "תקרת איסוף חודשית (סנטים USD)", aiBudget: "תקרת AI חודשית (סנטים USD)", caps: "שדה ריק משמעו אין אישור, לא תקציב בלתי מוגבל. 100 סנטים = דולר אחד. העלות אינה מאומתת עד לחיבור מדידת הספק.", confirm: "אני מאשר את התקרות המוגדלות המדויקות כבקשה שמורה, לא כהפעלת ספק", save: "שמירת הגדרות מבוקשות", saving: "שומר וקורא בחזרה…", saved: "נשמר ונקרא בחזרה מ־Scout", version: "גרסת הגדרות", updated: "שמירה אחרונה", new: "טרם נשמר", failed: "השמירה לא אומתה. הקלט נשמר במסך. נסו שוב את אותה שמירה; אין להניח שהמידע נשמר במסד.", invalid: "בדקו כתובות קבוצות ציבוריות מדויקות, כפילויות, מגבלות, תנאים ואישור תקרות. הקלט נשמר במסך.", conflict: "הגרסה השמורה השתנתה במקום אחר. הקלט נשמר במסך. קראו את הגרסה השמורה להשוואה; לא נדרס מידע.", compare: "קריאת הגרסה השמורה", replace: "להחליף את ההגדרות שטרם נשמרו בגרסה השמורה?", leave: "לצאת בלי לשמור את הגדרות Scout?", lowered: "הבקשות השמורות חורגות ממגבלה חיה נוכחית. הן עדיין מוצגות אך אינן מפעילות עבודה; התאימו אותן לפני שמירה חדשה.", forbidden: "חשבון זה אינו רשאי לשנות את הגדרות Scout הרשמיות. הקלט נשמר במסך.",
  },
};
async function requestSettings(signal?: AbortSignal): Promise<CommunitySettings> {
  const response = await fetch("/api/community-settings", { credentials: "same-origin", cache: "no-store", redirect: "error", referrerPolicy: "no-referrer", signal: signal ?? null });
  const body = await response.json() as { ok?: boolean; data?: CommunitySettings };
  if (!response.ok || body.ok !== true || !body.data) throw Error("unavailable");
  return body.data;
}
export function ScoutRuntimeReadback({ locale, settings, view='all' }: { locale: Locale; settings: CommunitySettings; view?:SettingsView }) {
  const t = copy[locale], state = (value: boolean) => value ? t.on : t.off;
  const counts = (value: Record<string, number>) => Object.entries(value).length ? Object.entries(value).map(([name, count]) => `${name}: ${count}`).join(" · ") : t.none;
  const pairs = [
    [t.collection, settings.collection.eligible ? t.eligible : t.off], [t.groups, settings.collection.allowedGroupCount], [t.provider, state(settings.collection.providerConfigured)], [t.worker, state(settings.collection.workerEnabled)], [t.auto, state(settings.collection.autoDraft)], [t.max, settings.collection.maxItemsPerRun], [t.ai, `${settings.usageTodayUtc.requests} / ${settings.limits.aiRequestsPerUtcDay}`], [t.manual, `${settings.limits.manualReplyUsed} / ${settings.limits.manualReplyRemaining} / ${settings.limits.manualReplyTotal}`], [t.tokens, `${settings.usageTodayUtc.inputTokens} / ${settings.usageTodayUtc.outputTokens}`], [t.cost, t.unknown], [t.jobs, counts(settings.queue.jobs)], [t.posts, counts(settings.queue.posts)],
  ];
  const visible=view==='sources'?pairs.slice(0,4):pairs;
  return <section className="lsw-card lsw-stack" aria-label={t.title}><h2>{t.title}</h2><p>{t.actualHelp}</p>{settings.collection.allowedGroupCount === 0 && <p role="status">{t.noGroups}</p>}<dl className="lsw-stack">{visible.map(([name, value]) => <div key={name}><dt><strong>{name}</strong></dt><dd>{value}</dd></div>)}</dl><p>{t.checked} <time dateTime={settings.asOf}>{settings.asOf}</time></p></section>;
}
export function ScoutControlsForm({ locale, runtime, value, approve, busy, dirty, onChange, onApprove, onSave,view='all' }: { locale: Locale; runtime: CommunitySettings; value: ScoutRequestedSettings; approve: boolean; busy: boolean; dirty: boolean; onChange: (value: ScoutRequestedSettings) => void; onApprove: (value: boolean) => void; onSave: () => void;view?:SettingsView }) {
  const t = copy[locale];
  const ceiling = (name: "scrapingMonthCents" | "aiMonthCents", raw: string) => {
    const amount = raw === "" ? null : Number(raw);
    if (amount !== value.budgets[name]) onApprove(false);
    onChange({ ...value, budgets: { ...value.budgets, [name]: amount } });
  };
  const over = value.limits.postsPerRun > runtime.collection.maxItemsPerRun || value.limits.threadsPerRun > runtime.collection.maxItemsPerRun || value.limits.draftsPerDay > Math.floor(runtime.limits.aiRequestsPerUtcDay / 2);
  return <section className="lsw-card lsw-stack" aria-label={t.requested}><h2>{t.requested}</h2><p>{t.help}</p><form className="lsw-stack" onSubmit={event => { event.preventDefault(); onSave(); }}>
    {view!=='budget'&&<>
      <fieldset disabled={busy} className="lsw-stack"><legend>{t.sources}</legend>{!value.groups.length && <p>{t.empty}</p>}{value.groups.map((group, index) => <div key={index} className="lsw-stack"><label className="lsw-field">{t.url} {index + 1}<input type="url" dir="ltr" required maxLength={400} value={group.url} onChange={event => onChange({ ...value, groups: value.groups.map((row, i) => i === index ? { ...row, url: event.target.value } : row) })} /></label><label className="lsw-choice"><input type="checkbox" checked={group.enabled} onChange={event => onChange({ ...value, groups: value.groups.map((row, i) => i === index ? { ...row, enabled: event.target.checked } : row) })} />{t.enabled} {index + 1}</label><button type="button" onClick={() => onChange({ ...value, groups: value.groups.filter((_, i) => i !== index) })}>{t.remove} {index + 1}</button></div>)}<div><button type="button" disabled={value.groups.length >= 50} onClick={() => onChange({ ...value, groups: [...value.groups, { url: "", enabled: false }] })}>{t.add}</button></div></fieldset>
      <fieldset disabled={busy} className="lsw-stack"><legend>{t.requested}</legend><label className="lsw-field">{t.lookback}<select value={value.lookbackDays} onChange={event => onChange({ ...value, lookbackDays: Number(event.target.value) as ScoutRequestedSettings["lookbackDays"] })}>{[1, 3, 7, 14, 30].map(days => <option key={days} value={days}>{days}</option>)}</select></label><label className="lsw-choice"><input type="checkbox" checked={value.schedule.requested} onChange={event => onChange({ ...value, schedule: { ...value.schedule, requested: event.target.checked } })} />{t.schedule}</label><div className="lsw-preference-grid"><label className="lsw-field">{t.time}<input type="time" value={value.schedule.localTime ?? ""} onChange={event => onChange({ ...value, schedule: { ...value.schedule, localTime: event.target.value || null } })} /></label><p>{t.timezone}: <bdi>Asia/Jerusalem</bdi></p></div></fieldset>
    </>}
    {view!=='sources'&&<fieldset disabled={busy} className="lsw-stack"><legend>{t.requested}</legend><label className="lsw-choice"><input type="checkbox" checked={value.autoDraftRequested} onChange={event => onChange({ ...value, autoDraftRequested: event.target.checked })} />{t.draft}</label><p>{t.bounds}</p>{over && <p role="alert">{t.lowered}</p>}<div className="lsw-preference-grid">{(["postsPerRun", "draftsPerDay", "threadsPerRun"] as const).map(name => <label className="lsw-field" key={name}>{name === "postsPerRun" ? t.postsLimit : name === "draftsPerDay" ? t.draftsLimit : t.threadsLimit}<input type="number" step="1" min={name === "postsPerRun" ? 1 : 0} max={name === "draftsPerDay" ? Math.floor(runtime.limits.aiRequestsPerUtcDay / 2) : runtime.collection.maxItemsPerRun} required value={value.limits[name]} onChange={event => onChange({ ...value, limits: { ...value.limits, [name]: event.target.valueAsNumber } })} /></label>)}</div><p>{t.caps}</p><div className="lsw-preference-grid"><label className="lsw-field">{t.scraping}<input type="number" min="0" max="1000000" step="1" value={value.budgets.scrapingMonthCents ?? ""} onChange={event => ceiling("scrapingMonthCents", event.target.value)} /></label><label className="lsw-field">{t.aiBudget}<input type="number" min="0" max="1000000" step="1" value={value.budgets.aiMonthCents ?? ""} onChange={event => ceiling("aiMonthCents", event.target.value)} /></label></div><label className="lsw-choice"><input type="checkbox" checked={approve} onChange={event => onApprove(event.target.checked)} />{t.confirm}</label></fieldset>}
    {view==='sources'&&<a href={`/${locale}/app/marketing?section=community&communityView=budget`}>{locale==='he'?'בדיקת תקרות התקציב וההרצה':'Check budget and run ceilings'}</a>}
    <div className="lsw-actions"><button className="lsu-primary" type="submit" disabled={busy || !dirty}>{busy ? t.saving : t.save}</button></div>
  </form></section>;
}
export function CommunitySettingsPanel({ locale, view='all' }: { locale: Locale;view?:SettingsView }) {
  const t = copy[locale], [runtime, setRuntime] = useState<CommunitySettings | null>(null), [value, setValue] = useState<ScoutRequestedSettings | null>(null);
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState(false), [approve, setApprove] = useState(false), [notice, setNotice] = useState(""), [saveError, setSaveError] = useState(false);
  const readEpoch = useRef(0), inFlight = useRef(false), attempt = useRef<{ fingerprint: string; operationId: string } | null>(null);
  const dirty = !!value && !!runtime && JSON.stringify(value) !== JSON.stringify(runtime.controls.settings);
  const load = useCallback(async (signal?: AbortSignal) => {
    const epoch = ++readEpoch.current;
    try { const data = await requestSettings(signal); if (!signal?.aborted && epoch === readEpoch.current) { setRuntime(data); setValue(data.controls.settings); setApprove(false); setError(false); setSaveError(false); setNotice(""); attempt.current = null; } }
    catch { if (!signal?.aborted && epoch === readEpoch.current) setError(true); }
    finally { if (!signal?.aborted && epoch === readEpoch.current) setLoading(false); }
  }, []);
  useEffect(() => {
    const controller = new AbortController(), epoch = ++readEpoch.current;
    void requestSettings(controller.signal)
      .then(data => { if (!controller.signal.aborted && epoch === readEpoch.current) { setRuntime(data); setValue(data.controls.settings); setError(false); } })
      .catch(() => { if (!controller.signal.aborted && epoch === readEpoch.current) setError(true); })
      .finally(() => { if (!controller.signal.aborted && epoch === readEpoch.current) setLoading(false); });
    return () => controller.abort();
  }, []);
  async function save() {
    if (inFlight.current || !runtime || !value || !dirty) return;
    inFlight.current = true; setBusy(true); setSaveError(false); setNotice(t.saving);
    try {
      const session = await sessionInfo(); if (session.role !== "practitioner") throw Error("forbidden");
      const payload = { expectedRevision: runtime.controls.revision, settings: value, approveCeilings: approve }, fingerprint = JSON.stringify(payload);
      if (attempt.current?.fingerprint !== fingerprint) attempt.current = { fingerprint, operationId: crypto.randomUUID() };
      const response = await fetch("/api/community-settings", { method: "PUT", credentials: "same-origin", cache: "no-store", redirect: "error", referrerPolicy: "no-referrer", headers: { "Content-Type": "application/json", "X-CSRF-Token": session.csrfToken }, body: JSON.stringify({ ...payload, operationId: attempt.current.operationId }) });
      if (response.status === 409) throw Error("conflict"); if (response.status === 400) throw Error("invalid"); if (response.status === 403) throw Error("forbidden");
      const result = await response.json() as { ok?: boolean; data?: ScoutSavedControls }; if (!response.ok || !result.ok || !result.data) throw Error("unconfirmed");
      const readback = await requestSettings(); if (readback.controls.revision !== result.data.revision || JSON.stringify(readback.controls.settings) !== JSON.stringify(value)) throw Error("conflict");
      readEpoch.current++; setRuntime(readback); setValue(readback.controls.settings); setApprove(false); attempt.current = null; setNotice(`${t.saved} · ${t.version} ${readback.controls.revision}`);
    } catch (failure) { setSaveError(true); setNotice(failure instanceof Error && failure.message === "conflict" ? t.conflict : failure instanceof Error && failure.message === "invalid" ? t.invalid : failure instanceof Error && failure.message === "forbidden" ? t.forbidden : t.failed); }
    finally { inFlight.current = false; setBusy(false); }
  }
  function reload() { if (inFlight.current || (dirty && !window.confirm(t.replace))) return; setLoading(true); void load(); }
  return <div className="lsw-stack"><UnsavedChangesGuard dirty={dirty} message={t.leave} />{loading && <p role="status">{t.loading}</p>}{error && <section className="lsw-card" role="alert"><p>{t.unavailable}</p><button type="button" disabled={busy} onClick={reload}>{t.retry}</button></section>}{notice && <section className="lsw-card" role={saveError ? "alert" : "status"}><p>{notice}</p></section>}{runtime && value && !loading && <><p>{t.version}: {runtime.controls.revision} · {t.updated}: {runtime.controls.updatedAt ? <time dateTime={runtime.controls.updatedAt}>{runtime.controls.updatedAt}</time> : t.new}</p><ScoutControlsForm locale={locale} runtime={runtime} value={value} approve={approve} busy={busy} dirty={dirty} onChange={setValue} onApprove={setApprove} onSave={() => void save()} view={view}/><div><button type="button" disabled={busy} onClick={reload}>{t.compare}</button></div><ScoutRuntimeReadback locale={locale} settings={runtime} view={view}/></>}</div>;
}
