'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {sessionInfo} from '../identity/client.ts';
import type {CommunityInboxPost} from '../community-inbox/bridge.ts';
import type {CommunityThreads,ThreadCommand} from './threads-bridge.ts';
import {UnsavedChangesGuard} from '../../ui/workspace/draft-guard.tsx';
import {civilDate} from '../calendar/time.ts';
const copy={
 en:{title:'Tracked public replies',help:'Save the exact link to a reply you posted manually. Only an explicitly captured parent-comment relationship counts as a response; names and “marked replied” flags do not. No posting, private messages or new scraper runs.',loading:'Loading tracked replies…',empty:'No tracked replies yet.',unavailable:'Tracked replies could not load. No complete-history claim; your input is preserved.',retry:'Reload tracked replies',post:'Captured post',choose:'Choose a captured post',link:'Exact link to your manually posted comment',confirm:'I posted this reply manually and checked its exact comment link.',save:'Track this exact reply',saved:'Tracking saved and read back. This does not enable collection or confirm provider publication.',failed:'This save is unconfirmed. Keep your input and retry the same save; no reply was sent.',open:'Open my recorded comment',response:'Open captured response',parent:'Captured parent comment ID',first:'First captured public text',at:'Captured at',noResponses:'No captured responses. This is not proof that no one replied on Facebook.',partial:'Bounded or partial capture—not complete conversation history.',check:'Last recorded dataset check',cost:'Observed run cost (USD); excludes unobserved billing',unknown:'Not verified',paused:'This app does not enable autonomous collection or a publishing schedule.',tasks:'Captured responses linked to internal Calendar tasks',taskFailed:'Internal task linking is unconfirmed. Retry safely; already created tasks are deduplicated.',taskRetry:'Retry internal task linking',more:'More pending responses remain; continue internal task linking.',unsaved:'Leave without saving the comment-tracking input?',all:'All tracked replies'},
 he:{title:'מעקב אחר תגובות ציבוריות',help:'שומרים את הקישור המדויק לתגובה שפרסמת ידנית. תגובה המשויכת אליה נספרת רק לפי קשר תגובת־אב שנקלט במפורש; שמות וסימון ״נענה״ אינם הוכחה. אין פרסום, הודעות פרטיות או הפעלת איסוף חדש.',loading:'טוען תגובות במעקב…',empty:'אין עדיין תגובות במעקב.',unavailable:'לא ניתן לטעון תגובות במעקב. אין לטעון שההיסטוריה מלאה; הקלט שלך נשמר במסך.',retry:'טעינה מחדש',post:'הפוסט שנקלט',choose:'בחירת פוסט שנקלט',link:'קישור מדויק לתגובה שפרסמת ידנית',confirm:'פרסמתי את התגובה ידנית ובדקתי את קישור התגובה המדויק.',save:'מעקב אחר התגובה המדויקת',saved:'המעקב נשמר ונקרא מחדש. אין בכך הפעלת איסוף או אימות פרסום מהספק.',failed:'השמירה לא אומתה. יש לשמור את הקלט ולנסות שוב את אותה שמירה; לא נשלחה תגובה.',open:'פתיחת התגובה שתיעדתי',response:'פתיחת התגובה שנקלטה',parent:'מזהה תגובת האב שנקלט',first:'הטקסט הציבורי בקליטה הראשונה',at:'מועד הקליטה',noResponses:'אין תגובות שנקלטו. אין בכך הוכחה שלא הגיבו בפייסבוק.',partial:'קליטה מוגבלת או חלקית — לא היסטוריית שיחה מלאה.',check:'בדיקת הנתונים האחרונה שתועדה',cost:'עלות הריצה שנצפתה בדולר; אינה כוללת חיובים שלא נצפו',unknown:'לא אומת',paused:'האפליקציה אינה מפעילה איסוף עצמאי או לוח פרסום.',tasks:'תגובות שנקלטו וקושרו למשימות פנימיות ביומן',taskFailed:'קישור המשימות לא אומת. אפשר לנסות שוב בבטחה; משימות שכבר נוצרו לא יוכפלו.',taskRetry:'ניסיון חוזר לקישור משימות',more:'נותרו תגובות הממתינות לקישור משימה פנימית.',unsaved:'לצאת בלי לשמור את הקלט למעקב התגובה?',all:'כל התגובות במעקב'}
};
const labels={en:{...copy.en,cost:'Observed run cost (USD, rounded up to cents); unobserved billing is unknown',tasks:'Internal task links verified in this check',taskLink:'Open internal Calendar task'},he:{...copy.he,cost:'עלות הריצה שנצפתה בדולר, בעיגול כלפי מעלה לסנטים; חיובים שלא נצפו אינם ידועים',tasks:'קישורי משימות פנימיות שאומתו בבדיקה הזאת',taskLink:'פתיחת המשימה הפנימית ביומן'}};
export function CommunityThreadPanel({locale,posts}:{locale:'he'|'en';posts:CommunityInboxPost[]}){
 const t=labels[locale],[data,setData]=useState<CommunityThreads|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(false),[postId,setPostId]=useState(''),[commentUrl,setCommentUrl]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[taskError,setTaskError]=useState(false),[moreTasks,setMoreTasks]=useState(false),[linked,setLinked]=useState<number|null>(null);
 const alive=useRef(true),loadId=useRef(0),attempt=useRef<{fingerprint:string;command:ThreadCommand}|null>(null),mutating=useRef(false),selected=useRef<string|undefined>(undefined),[selectedId,setSelectedId]=useState<string|undefined>(undefined);
 const load=useCallback(async()=>{const id=++loadId.current,requested=selected.current;setSelectedId(requested);try{const result=await fetch('/api/community-threads'+(requested?'?threadId='+encodeURIComponent(requested):''),{credentials:'same-origin',cache:'no-store',redirect:'error',referrerPolicy:'no-referrer'}),body=await result.json() as {ok?:boolean;data?:CommunityThreads};if(!result.ok||!body.ok||!body.data)throw Error('unavailable');if(alive.current&&id===loadId.current){setData(body.data);setError(false);}}catch{if(alive.current&&id===loadId.current){setError(true);setData(null);}}finally{if(alive.current&&id===loadId.current)setLoading(false);}},[]);
 const syncTasks=useCallback(async()=>{try{const session=await sessionInfo(),result=await fetch('/api/community-threads',{method:'PUT',credentials:'same-origin',cache:'no-store',redirect:'error',referrerPolicy:'no-referrer',headers:{'Content-Type':'application/json','x-csrf-token':session.csrfToken},body:'{}'}),body=await result.json() as {ok?:boolean;data?:{linked:number;more:boolean}};if(!result.ok||!body.ok||!body.data)throw Error('unconfirmed');if(alive.current){setTaskError(false);setLinked(body.data.linked);setMoreTasks(body.data.more);await load();}}catch{if(alive.current)setTaskError(true);}},[load]);
 useEffect(()=>{alive.current=true;selected.current=new URLSearchParams(window.location.search).get('threadId')??undefined;const startup=window.setTimeout(()=>{void load();void syncTasks();},0);return()=>{window.clearTimeout(startup);alive.current=false;};},[load,syncTasks]);
 async function save(){if(mutating.current)return;mutating.current=true;setBusy(true);setNotice('');try{const fingerprint=JSON.stringify({postId,commentUrl,confirmed});if(attempt.current?.fingerprint!==fingerprint)attempt.current={fingerprint,command:{operationId:crypto.randomUUID(),postId:Number(postId),commentUrl,confirmManualReply:true}};
  const session=await sessionInfo(),result=await fetch('/api/community-threads',{method:'POST',credentials:'same-origin',cache:'no-store',redirect:'error',referrerPolicy:'no-referrer',headers:{'Content-Type':'application/json','x-csrf-token':session.csrfToken},body:JSON.stringify(attempt.current.command)}),body=await result.json() as {ok?:boolean;data?:{id:string;postId:number;commentUrl:string}};if(!result.ok||!body.ok||!body.data)throw Error('unconfirmed');
  const read=await fetch('/api/community-threads?threadId='+encodeURIComponent(body.data.id),{credentials:'same-origin',cache:'no-store',redirect:'error',referrerPolicy:'no-referrer'}),check=await read.json() as {ok?:boolean;data?:CommunityThreads};if(!read.ok||!check.ok||check.data?.threads.length!==1||check.data.threads[0]?.id!==body.data.id||check.data.threads[0].postId!==body.data.postId||check.data.threads[0].commentUrl!==body.data.commentUrl)throw Error('readback');
  if(!alive.current)return;setCommentUrl('');setConfirmed(false);attempt.current=null;setNotice(t.saved);await load();
 }catch{if(alive.current)setNotice(t.failed);}finally{mutating.current=false;if(alive.current)setBusy(false);}}
 return <>{error&&<p role="alert" className="lsr-inline-error">{t.unavailable} <button type="button" disabled={loading||busy} onClick={()=>{setLoading(true);void load();}}>{t.retry}</button></p>}{taskError&&<p role="alert" className="lsr-inline-error">{t.taskFailed} <button type="button" onClick={()=>void syncTasks()}>{t.taskRetry}</button></p>}<details className="lsr-panel"><summary>{t.title}{data?' · '+data.threads.length:''}</summary><p className="lsr-help">{t.help}</p><UnsavedChangesGuard dirty={commentUrl.trim().length>0} message={t.unsaved}/>
  {loading&&<p role="status">{t.loading}</p>}<button type="button" disabled={loading||busy} onClick={()=>{setLoading(true);void load();}}>{t.retry}</button>
  {selectedId&&<button type="button" disabled={busy} onClick={()=>{selected.current=undefined;const url=new URL(window.location.href);url.searchParams.delete('threadId');window.history.replaceState(null,'',url);setLoading(true);void load();}}>{t.all}</button>}
  {data&&!loading&&<><p className="lsr-help">{t.paused}</p>{data.partial&&<p role="status">{t.partial}</p>}<p>{t.check}: {data.captureStatus?.checkedAt??t.unknown} · {data.captureStatus?.reason??''}</p><p>{t.cost}: {data.captureStatus?.observedRunCostCents===null||!data.captureStatus?t.unknown:(data.captureStatus.observedRunCostCents/100).toFixed(2)}</p>{!data.threads.length&&<p>{t.empty}</p>}
   {data.threads.map(thread=><article key={thread.id} className="lsr-publication-row"><a href={thread.commentUrl} target="_blank" rel="noopener noreferrer">{t.open} · {thread.commentId}</a><p>{t.at}: {thread.registeredAt}</p>{!data.responses.some(r=>r.threadId===thread.id)&&<p>{t.noResponses}</p>}{data.responses.filter(r=>r.threadId===thread.id).map(r=><details key={r.id}><summary>{t.first} · {r.capturedAt}</summary><p>{r.text}</p><p>{t.parent}: {r.parentCommentId}</p><a href={r.commentUrl} target="_blank" rel="noopener noreferrer">{t.response}</a>{r.taskId&&<p><a href={`/${locale}/app/calendar?date=${civilDate(r.capturedAt)}&view=agenda#task-${r.taskId}`}>{t.taskLink}</a></p>}</details>)}</article>)}
  </>}
  {!taskError&&<p role="status">{t.tasks}: {linked??t.unknown}</p>}{moreTasks&&<p>{t.more} <button type="button" onClick={()=>void syncTasks()}>{t.taskRetry}</button></p>}
  <div className="lsr-form-grid"><label>{t.post}<select value={postId} disabled={busy} onChange={e=>setPostId(e.target.value)}><option value="">{t.choose}</option>{posts.map(p=><option key={p.id} value={p.id}>{p.groupName} · {p.excerpt.slice(0,60)}</option>)}</select></label><label>{t.link}<input type="url" maxLength={1000} value={commentUrl} disabled={busy} onChange={e=>setCommentUrl(e.target.value)}/></label></div><label><input type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/>{t.confirm}</label><button type="button" disabled={busy||!postId||!commentUrl.trim()||!confirmed} onClick={()=>void save()}>{t.save}</button>{notice&&<p role={notice===t.failed?'alert':'status'}>{notice}</p>}
 </details></>;
}
