"use client";
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {sessionInfo} from '../identity/client.ts';
import type {ResourceProjection} from './service.ts';
type Props={locale:'en'|'he';role:'practitioner'|'parent';caseId:string;audienceId?:string|undefined};
type Audience={id:string;visibility:string;published:boolean};
type Catalog={resourceId:string;title:string;type:string;locale:string};
export function resourceReferenceForInput(type:string,value:string){return type==='text'?{kind:'inline_text' as const,value}:{kind:'url' as const,value};}
const words={en:{title:'Resources',load:'Loading authorized resources…',error:'Could not confirm the result. Check saved resources and assignments before another create or assign.',empty:'No resources assigned.',library:'Resource library',choose:'Choose a resource',audience:'Shared audience',full:'Full shared details',limited:'Title and completion only',create:'Create resource',assign:'Assign selected resource',name:'Title',description:'Description',type:'Resource type',text:'Text',link:'Public HTTPS learning link',content:'Content or HTTPS address',due:'Due date (optional)',display:'Display date',completion:'Allow parent completion',complete:'Mark complete',completed:'Completed',saved:'Saved',reload:'Reload saved state',privateFile:'Private file delivery is not configured. No public download link is exposed.',review:'Check the saved state after reloading; an earlier uncertain request may already have succeeded.',new:'New resource',details:'Open resource',privateDetails:'Only the title and completion status are shared in this audience.'},he:{title:'משאבים',load:'טוען משאבים מורשים…',error:'לא ניתן לאשר את התוצאה. בדקו את המשאבים וההקצאות לפני יצירה או הקצאה נוספת.',empty:'לא הוקצו משאבים.',library:'ספריית משאבים',choose:'בחירת משאב',audience:'קהל לשיתוף',full:'פרטים משותפים מלאים',limited:'כותרת והשלמה בלבד',create:'יצירת משאב',assign:'הקצאת המשאב הנבחר',name:'כותרת',description:'תיאור',type:'סוג משאב',text:'טקסט',link:'קישור לימודי ציבורי ב־HTTPS',content:'תוכן או כתובת HTTPS',due:'תאריך יעד (רשות)',display:'תאריך הצגה',completion:'אפשרות לסימון השלמה',complete:'סימון כהושלם',completed:'הושלם',saved:'נשמר',reload:'טעינת המצב השמור',privateFile:'מסירת קובץ פרטי אינה מוגדרת. לא מוצג קישור הורדה ציבורי.',review:'לאחר הטעינה יש לבדוק את המצב השמור; ייתכן שבקשה קודמת כבר הצליחה.',new:'משאב חדש',details:'פתיחת המשאב',privateDetails:'בקהל זה משותפים רק הכותרת ומצב ההשלמה.'}} as const;
async function get<T>(url:string,signal:AbortSignal):Promise<T>{const response=await fetch(url,{credentials:'same-origin',cache:'no-store',signal}),body=await response.json() as {ok?:boolean;data:T};if(!response.ok||!body.ok)throw Error('READ_FAILED');return body.data;}
async function post<T>(url:string,value:unknown,key?:string):Promise<T>{const session=await sessionInfo(),response=await fetch(url,{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json','X-CSRF-Token':session.csrfToken,...(key?{'Idempotency-Key':key}:{})},body:JSON.stringify(value)}),body=await response.json() as {ok?:boolean;data:T};if(!response.ok||!body.ok)throw Error('WRITE_UNCONFIRMED');return body.data;}
export function ResourcesWorkspace(props:Props){return <ResourceContext key={`${props.locale}:${props.role}:${props.caseId}`} {...props}/>;}
export function ResourceContext({locale,role,caseId,audienceId}:Props){
 const t=words[locale],practitioner=role==='practitioner';
 const [data,setData]=useState<{items:ResourceProjection[];audiences:Audience[];catalog:Catalog[]}|null>(null),[error,setError]=useState(false),[revision,setRevision]=useState(0),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false);
 const [audience,setAudience]=useState(audienceId??''),[resource,setResource]=useState(''),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[type,setType]=useState<'text'|'link'>('text'),[content,setContent]=useState(''),[due,setDue]=useState(''),[display,setDisplay]=useState(()=>new Date().toISOString().slice(0,10)),[completion,setCompletion]=useState(true);
 const mounted=useRef(false),lock=useRef(false),keys=useRef<Record<string,string>>({}),pending=useRef<{kind:'create'|'assign';url:string;value:unknown;key:string}|null>(null);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[]);
 useEffect(()=>{const controller=new AbortController();void Promise.all([get<ResourceProjection[]>(`/api/resources/assignments?caseId=${encodeURIComponent(caseId)}`,controller.signal),practitioner?get<Audience[]>(`/api/identity/audiences?caseId=${encodeURIComponent(caseId)}`,controller.signal):Promise.resolve([]),practitioner?get<Catalog[]>('/api/resources',controller.signal):Promise.resolve([])]).then(([items,audiences,catalog])=>{if(!controller.signal.aborted){setData({items,audiences:audiences.filter(a=>a.published&&a.visibility!=='private'),catalog});setError(false)}}).catch(()=>{if(!controller.signal.aborted){setError(true);setData(null)}});return()=>controller.abort()},[caseId,practitioner,revision]);
 function begin(){if(lock.current||!mounted.current)return false;lock.current=true;setBusy(true);setNotice('');return true;}
 function end(){lock.current=false;if(mounted.current)setBusy(false);}
 async function create(event:FormEvent){event.preventDefault();if(!practitioner||uncertain||!title.trim()||!content.trim()||!begin())return;const command={kind:'create' as const,url:'/api/resources',value:{type,title:title.trim(),description:description.trim(),reference:resourceReferenceForInput(type,content.trim()),downloadable:false,locale},key:crypto.randomUUID()};pending.current=command;try{const result=await post<{resourceId:string}>(command.url,command.value,command.key);if(!result.resourceId)throw Error('MISSING_RECEIPT');pending.current=null;if(mounted.current){setResource(result.resourceId);setTitle('');setContent('');setDescription('');setNotice(t.saved);setRevision(n=>n+1)}}catch{if(mounted.current){setUncertain(true);setNotice(t.error)}}finally{end()}}
 async function assign(event:FormEvent){event.preventDefault();if(!practitioner||uncertain||!data?.catalog.some(r=>r.resourceId===resource)||!data.audiences.some(a=>a.id===audience)||!display||!begin())return;const command={kind:'assign' as const,url:'/api/resources/assignments',value:{resourceId:resource,caseId,audienceId:audience,dueDate:due||null,displayDate:display,completionEnabled:completion},key:crypto.randomUUID()};pending.current=command;try{const result=await post<{assignmentId:string}>(command.url,command.value,command.key);if(!result.assignmentId)throw Error('MISSING_RECEIPT');pending.current=null;if(mounted.current){setNotice(t.saved);setRevision(n=>n+1)}}catch{if(mounted.current){setUncertain(true);setNotice(t.error)}}finally{end()}}
 async function reconcile(){const command=pending.current;if(!command||!begin())return;try{if(command.kind==='create'){const result=await post<{resourceId:string}>(command.url,command.value,command.key);if(!result.resourceId)throw Error('MISSING_RECEIPT');setResource(result.resourceId);setTitle('');setContent('');setDescription('')}else{const result=await post<{assignmentId:string}>(command.url,command.value,command.key);if(!result.assignmentId)throw Error('MISSING_RECEIPT')}pending.current=null;setUncertain(false);setNotice(t.saved);setRevision(n=>n+1)}catch{setNotice(t.error)}finally{end()}}
 async function complete(item:ResourceProjection){if(practitioner||!item.detailsAvailable||!item.completionEnabled||item.completed||!begin())return;keys.current[item.assignmentId]??=crypto.randomUUID();try{const result=await post<{completionId:string}>('/api/resources/completions',{assignmentId:item.assignmentId,idempotencyKey:keys.current[item.assignmentId]});if(!result.completionId)throw Error('MISSING_RECEIPT');if(mounted.current){setNotice(t.saved);setRevision(n=>n+1)}}catch{if(mounted.current)setNotice(t.error)}finally{end()}}
 if(!data&&!error)return <p role="status">{t.load}</p>;
 return <section className="lsw-stack" lang={locale} dir={locale==='he'?'rtl':'ltr'}><h2>{t.title}</h2>{error&&<p role="alert">{t.error}</p>}<button type="button" disabled={busy} onClick={()=>{setRevision(n=>n+1);setNotice(t.review)}}>{t.reload}</button>{uncertain&&<div role="alert"><p>{t.review}</p><button type="button" disabled={busy} onClick={()=>void reconcile()}>{locale==='he'?'בדיקת אותה פעולה':'Reconcile the same action'}</button></div>}
 {practitioner&&data&&<div className="lsu-task-switcher"><details name="resources-tools"><summary>{t.new}</summary><div className="lsu-task-content"><form className="lsw-card lsw-stack" onSubmit={create}><h2>{t.new}</h2><fieldset disabled={busy||uncertain}><label>{t.name}<input required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>{t.description}<textarea maxLength={2000} value={description} onChange={e=>setDescription(e.target.value)}/></label><label>{t.type}<select value={type} onChange={e=>setType(e.target.value as 'text'|'link')}><option value="text">{t.text}</option><option value="link">{t.link}</option></select></label><label>{t.content}{type==='link'?<input required type="url" pattern="https://.*" maxLength={2000} value={content} onChange={e=>setContent(e.target.value)}/>:<textarea required maxLength={20000} value={content} onChange={e=>setContent(e.target.value)}/>}</label><button type="submit">{t.create}</button></fieldset></form></div></details>
 <details name="resources-tools"><summary>{t.assign}</summary><div className="lsu-task-content"><form className="lsw-card lsw-stack" onSubmit={assign}><h2>{t.library}</h2><fieldset disabled={busy||uncertain}><label>{t.choose}<select required value={resource} onChange={e=>setResource(e.target.value)}><option value="">{t.choose}</option>{data.catalog.map(item=><option key={item.resourceId} value={item.resourceId}>{item.title} · {item.locale}</option>)}</select></label><label>{t.audience}<select required value={audience} onChange={e=>setAudience(e.target.value)}><option value="">{t.audience}</option>{data.audiences.map((item,i)=><option key={item.id} value={item.id}>{item.visibility==='family_full'?t.full:t.limited} {i+1}</option>)}</select></label><label>{t.due}<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><label>{t.display}<input required type="date" value={display} onChange={e=>setDisplay(e.target.value)}/></label><label><input type="checkbox" checked={completion} onChange={e=>setCompletion(e.target.checked)}/>{t.completion}</label><button type="submit">{t.assign}</button></fieldset></form></div></details></div>}
 {data&&!data.items.length&&<p>{t.empty}</p>}{data?.items.map(item=><article className="lsw-card" key={item.assignmentId}><ResourceReadout locale={locale} item={item}/>{!practitioner&&item.detailsAvailable&&item.completionEnabled&&!item.completed&&<button type="button" disabled={busy} onClick={()=>void complete(item)}>{t.complete}</button>}</article>)}{notice&&<p role="status">{notice}</p>}</section>;
}
export function ResourceReadout({locale,item}:{locale:'he'|'en';item:ResourceProjection}){const t=words[locale];return <><h2>{item.title}</h2>{item.completed&&<p>{t.completed}</p>}{!item.detailsAvailable?<p>{t.privateDetails}</p>:<><p>{item.description}</p>{item.reference.kind==='inline_text'?<p style={{whiteSpace:'pre-wrap'}}>{item.reference.value}</p>:item.type==='link'&&item.reference.kind==='url'&&/^https:\/\//i.test(item.reference.value)?<a href={item.reference.value} rel="noopener noreferrer">{t.details}</a>:<p>{t.privateFile}</p>}</>}</>}
