"use client";
import { useEffect, useRef, useState } from "react";
import {useRouter} from 'next/navigation';
import { accountRead, sessionInfo } from "../identity/client.ts";
import { PrivateObservationEvidencePanel } from "../session-workflow/private-observation-evidence.tsx";
import {calendarCasesForMode,type CalendarMode} from '../calendar/mode.ts';
import {workspaceHref,type WorkspaceContext} from '../../ui/workspace/navigation-model.ts';
import {UnsavedChangesGuard} from '../../ui/workspace/draft-guard.tsx';
type Locale = "en" | "he"; type Role = "practitioner" | "parent";
type Case = { id: string; displayName: string; kind: string };
type Audience = { id: string; visibility: string; published: boolean };
export type Narrative = { taughtAndPractised: string[]; parentReportedExamples: string[]; practitionerObservations: string[]; usefulChanges: string[]; continuingDifficulty: string[]; uncertainty: string; nextAdjustment: string; informationLimits: string };
export type Review = { id: string; caseId: string; audienceId: string; periodStart: string; periodEnd: string; attendedSessionCount: number; state: "draft" | "published"; narrative: Narrative };
type Draft = { periodStart: string; taught: string; observations: string; useful: string; difficulty: string; uncertainty: string; next: string; limits: string };
const blank: Draft = { periodStart: "", taught: "", observations: "", useful: "", difficulty: "", uncertainty: "", next: "", limits: "" };
const words = {
 en: { title: "Monthly progress reports", intro: "A four-week report based on recorded attendance and your observations.", child: "Child", audience: "Family audience", loading: "Loading authorized reports…", error: "Could not load reports. Please refresh.", empty: "No reports to display.", family: "Only published reports shared with your family appear here.", draft: "Draft", published: "Published", saved: "New draft saved privately.", publishedNow: "Saved report published to this family audience.", save: "Save new draft version", publish: "Publish saved draft", select: "Saved draft", start: "Period start", end: "Period end (exclusive; 28 days later)", taught: "What was taught and practised", observations: "Practitioner observations", useful: "Useful changes", difficulty: "Continuing difficulty", uncertainty: "Uncertainty", next: "Next adjustment", limits: "Information limits", sources: "No parent reports or practice versions are attached in this editor. Do not present your own observations as an attributed parent report.", dirty: "Save these edits as a new draft before publishing.", failed: "The result could not be confirmed. Reload saved reports and check for your draft before trying again. Your text is still here.", reload: "Reload reports (discards unsaved edits)", attended: "Recorded attended sessions", required: "Complete the required fields and select a valid period.", noAudience: "No published full-family audience is available. Set up an authorized audience in the case first.", newDraft: "New draft", back: "Back to cases", busy: "Working…" },
 he: { title: "דוחות התקדמות חודשיים", intro: "דוח של ארבעה שבועות המבוסס על נוכחות מתועדת ותצפיות שלכם.", child: "ילד/ה", audience: "קהל המשפחה", loading: "טוען דוחות מורשים…", error: "לא ניתן לטעון את הדוחות. נסו לרענן.", empty: "אין דוחות להצגה.", family: "כאן מופיעים רק דוחות שפורסמו ושותפו עם המשפחה שלכם.", draft: "טיוטה", published: "פורסם", saved: "נשמרה טיוטה חדשה ופרטית.", publishedNow: "הדוח השמור פורסם לקהל המשפחה הזה.", save: "שמירת גרסת טיוטה חדשה", publish: "פרסום הטיוטה השמורה", select: "טיוטה שמורה", start: "תחילת התקופה", end: "סיום התקופה (לא כולל; כעבור 28 ימים)", taught: "מה נלמד ותורגל", observations: "תצפיות איש המקצוע", useful: "שינויים מועילים", difficulty: "קושי מתמשך", uncertainty: "אי־ודאות", next: "ההתאמה הבאה", limits: "מגבלות המידע", sources: "לעורך זה לא מצורפים דיווחי הורים או גרסאות תרגול. אין להציג תצפיות שלכם כדיווח מיוחס של הורה.", dirty: "יש לשמור את השינויים כטיוטה חדשה לפני הפרסום.", failed: "לא ניתן לאשר את התוצאה. טענו מחדש את הדוחות ובדקו אם הטיוטה נשמרה לפני ניסיון נוסף. הטקסט שלכם עדיין כאן.", reload: "טעינת דוחות מחדש (השינויים שלא נשמרו יאבדו)", attended: "מפגשים שנרשמה בהם נוכחות", required: "מלאו את שדות החובה ובחרו תקופה תקינה.", noAudience: "אין קהל משפחתי מלא ופורסם. יש להגדיר בתיק קהל מורשה תחילה.", newDraft: "טיוטה חדשה", back: "חזרה לתיקים", busy: "מעבד…" },
} as const;
const lines = (text: string) => text.split("\n").map(value => value.trim()).filter(Boolean);
type EditorState={dirty:boolean;busy:boolean;uncertain:boolean};
const idleEditor:EditorState={dirty:false,busy:false,uncertain:false};
const discardMessage=(locale:Locale)=>locale==='he'?'יש שינויים שלא נשמרו. לעבור ולוותר עליהם?':'You have unsaved report edits. Leave and discard them?';
export function periodEnd(start: string) { if (!/^\d{4}-\d{2}-\d{2}$/.test(start)) return ""; const date = new Date(`${start}T00:00:00Z`); if (!Number.isFinite(date.getTime()) || date.toISOString().slice(0,10) !== start) return ""; date.setUTCDate(date.getUTCDate() + 28); return date.toISOString().slice(0,10); }
async function read<T>(url: string, signal: AbortSignal): Promise<T> { const response = await fetch(url, { credentials: "same-origin", cache: "no-store", signal }); const payload = await response.json(); if (!response.ok || payload.ok !== true) throw Error("READ_FAILED"); return payload.data as T; }
async function post<T>(url: string, body: unknown): Promise<T> { const session = await sessionInfo(); const response = await fetch(url, { method: "POST", credentials: "same-origin", cache: "no-store", headers: { "Content-Type": "application/json", "X-CSRF-Token": session.csrfToken }, body: JSON.stringify(body) }); const payload = await response.json(); if (!response.ok || payload.ok !== true) throw Error("MUTATION_UNCONFIRMED"); return payload.data as T; }
export function ReportsPage({ locale, role, caseId, audienceId,mode='live',navigationContext={} }: { locale: Locale; role: Role; caseId?: string | undefined; audienceId?: string | undefined;mode?:CalendarMode;navigationContext?:WorkspaceContext }) {
 const router=useRouter(),context={...navigationContext,mode};
 const t=words[locale],contextKey=`${role}:${role==='practitioner'?mode:'authorized'}:${caseId??''}`;
 const [loaded,setLoaded]=useState<{key:string;items:Case[]}|null>(null),[selection,setSelection]=useState({key:contextKey,id:caseId??''}),[failedFor,setFailedFor]=useState(''),[retry,setRetry]=useState(0),[editorState,setEditorState]=useState<EditorState>(idleEditor);
 useEffect(()=>{let active=true;const promise=role==='practitioner'?accountRead<unknown>('cases',mode).then(items=>calendarCasesForMode(items,mode)):accountRead<Case[]>('cases');
  void promise.then(items=>{if(active){setLoaded({key:contextKey,items});setFailedFor('');}}).catch(()=>{if(active){setLoaded(null);setFailedFor(contextKey);}});return()=>{active=false;};
 },[role,mode,contextKey,retry]);
 const cases=loaded?.key===contextKey?loaded.items:null,selected=selection.key===contextKey?selection.id:caseId??'';
 const activeCase=selected?cases?.find(item=>item.id===selected)?.id??'':cases?.[0]?.id??'',missing=Boolean(cases&&selected&&!activeCase);
 function choose(id:string){if(editorState.busy||editorState.uncertain||id===activeCase||!cases?.some(item=>item.id===id))return;if(editorState.dirty&&!window.confirm(discardMessage(locale)))return;setEditorState(idleEditor);setSelection({key:contextKey,id});if(role==='practitioner')router.replace(workspaceHref(locale,'app/reports',id,context));}
 return <section className="lsw-stack lsw-feature-page" dir={locale==='he'?'rtl':'ltr'}>
  <UnsavedChangesGuard dirty={editorState.dirty||editorState.busy||editorState.uncertain} message={discardMessage(locale)}/>
  <header className="lsw-page-header"><div><h1>{t.title}</h1><p>{t.intro}</p></div></header>
  <a href={workspaceHref(locale,role==='practitioner'?'app/clients':'family',undefined,role==='practitioner'?context:{})}>{t.back}</a>
  {role==='practitioner'&&mode==='demo'&&<p role="status">{locale==='he'?'DEMO — דוחות לתיקים סינתטיים בלבד.':'DEMO — reports for synthetic cases only.'} <a href={`/${locale}/app/reports`}>{locale==='he'?'חזרה לדוחות האמיתיים':'Return to live reports'}</a></p>}
  {failedFor===contextKey?<p role="alert">{t.error} <button type="button" onClick={()=>setRetry(value=>value+1)}>{locale==='he'?'ניסיון חוזר':'Retry case list'}</button></p>:cases===null?<p role="status">{t.loading}</p>:<>
   {cases.length>0&&<label>{role==='practitioner'?(locale==='he'?'לקוח/ה':'Client'):t.child}<select aria-label={role==='practitioner'?(locale==='he'?'לקוח/ה':'Client'):t.child} value={activeCase} disabled={editorState.busy||editorState.uncertain} onChange={event=>choose(event.target.value)}>{missing&&<option value="" disabled>{locale==='he'?'התיק שנבחר אינו זמין':'Selected case unavailable'}</option>}{cases.map(item=><option key={item.id} value={item.id}>{item.displayName}</option>)}</select></label>}
   {missing?<p role="alert">{locale==='he'?'התיק שנבחר אינו זמין ברשימה המורשית הזו. לא נפתח תיק אחר. בחרו תיק מורשה או חזרו לרשימה.':'The selected case is unavailable in this authorized list. No other case was opened. Choose an authorized case or return to the list.'}</p>:!activeCase?<p>{t.empty}</p>:<ReportCaseWorkspace key={`${locale}:${role}:${activeCase}`} locale={locale} role={role} caseId={activeCase} initialAudienceId={!caseId||activeCase===caseId?audienceId:undefined} onEditorStateChange={setEditorState}/>}
  </>}
 </section>;
}
export function ReportCaseWorkspace({ locale, role, caseId, initialAudienceId,onEditorStateChange }: { locale: Locale; role: Role; caseId: string; initialAudienceId?: string | undefined;onEditorStateChange?:(state:EditorState)=>void }) {
 const t = words[locale]; const [data, setData] = useState<{ audiences: Audience[]; reviews: Review[] } | null>(null), [error, setError] = useState(false), [selected, setSelected] = useState(initialAudienceId ?? "");
 const [editorState,setEditorState]=useState<EditorState>(idleEditor);
 useEffect(()=>{onEditorStateChange?.(editorState);},[editorState,onEditorStateChange]);
 useEffect(() => { const controller = new AbortController(); let active = true; void Promise.all([read<Audience[]>(`/api/identity/audiences?caseId=${encodeURIComponent(caseId)}`, controller.signal), read<Review[]>(`/api/progress/reviews?caseId=${encodeURIComponent(caseId)}`, controller.signal)]).then(([audiences,reviews]) => { if (!active) return; const allowed = audiences.filter(item => item.published && item.visibility === "family_full"); setData({ audiences: allowed, reviews: reviews.filter(item => item.caseId === caseId && allowed.some(audience => audience.id === item.audienceId) && (role === "practitioner" || item.state === "published")) }); }).catch(() => { if (active && !controller.signal.aborted) setError(true); }); return () => { active = false; controller.abort(); }; }, [caseId,role]);
 if (error) return <p role="alert">{t.error}</p>; if (!data) return <p role="status">{t.loading}</p>;
 const activeAudience = selected?data.audiences.find(item => item.id === selected)?.id??'':data.audiences[0]?.id??'';
 if(!activeAudience)return selected?<p role="alert">{locale==='he'?'קהל המשפחה שנבחר אינו זמין. לא נבחר קהל אחר. חזרו לרשימה ובחרו קהל מורשה.':'The selected family audience is unavailable. No other audience was selected. Return to the list and choose an authorized audience.'}</p>:<p>{t.noAudience}</p>;
 const reviews = data.reviews.filter(item => item.audienceId === activeAudience);
 function saved(review: Review) { setData(previous => previous ? { ...previous, reviews: [...previous.reviews.filter(item => item.id !== review.id), review] } : previous); }
 function chooseAudience(id:string){if(editorState.busy||editorState.uncertain||id===activeAudience||!data?.audiences.some(item=>item.id===id))return;if(editorState.dirty&&!window.confirm(discardMessage(locale)))return;setEditorState(idleEditor);setSelected(id);}
 return <div className="lsw-stack"><label>{t.audience}<select value={activeAudience} disabled={editorState.busy||editorState.uncertain} onChange={event=>chooseAudience(event.target.value)}>{data.audiences.map((item,index) => <option key={item.id} value={item.id}>{t.audience} {index+1}</option>)}</select></label>{role === "practitioner" ? <ReportEditor key={`${caseId}:${activeAudience}`} locale={locale} caseId={caseId} audienceId={activeAudience} reviews={reviews} onSaved={saved} onStateChange={setEditorState}/> : <p>{t.family}</p>}{!reviews.length && <p>{t.empty}</p>}{reviews.map(review => <ReportReadout key={review.id} locale={locale} review={review} />)}</div>;
}
export function ReportEditor({ locale, caseId, audienceId, reviews, onSaved,onStateChange }: { locale: Locale; caseId: string; audienceId: string; reviews: Review[]; onSaved: (review: Review) => void;onStateChange?:(state:EditorState)=>void }) {
 const t = words[locale]; const [draft, setDraft] = useState<Draft>(blank), [selectedId, setSelectedId] = useState(""), [dirty, setDirty] = useState(false), [busy, setBusy] = useState(false), [uncertain, setUncertain] = useState(false), [notice, setNotice] = useState(""); const lock = useRef(false), mounted = useRef(false);
 useEffect(() => { mounted.current = true; return () => { mounted.current = false; }; }, []);
 useEffect(()=>{onStateChange?.({dirty,busy,uncertain});},[dirty,busy,uncertain,onStateChange]);
 const selected = reviews.find(item => item.id === selectedId && item.caseId === caseId && item.audienceId === audienceId);
 function change(field: keyof Draft, value: string) { if (lock.current) return; setDraft(previous => ({ ...previous, [field]: value })); setDirty(true); }
 function choose(id: string) { if (lock.current||uncertain||id===selectedId) return;if(dirty&&!window.confirm(discardMessage(locale)))return; const review = reviews.find(item => item.id === id&&item.caseId===caseId&&item.audienceId===audienceId); if (!review) { setDraft(blank); setSelectedId(""); setDirty(false); return; } const n = review.narrative; setDraft({ periodStart: review.periodStart, taught: n.taughtAndPractised.join("\n"), observations: n.practitionerObservations.join("\n"), useful: n.usefulChanges.join("\n"), difficulty: n.continuingDifficulty.join("\n"), uncertainty: n.uncertainty, next: n.nextAdjustment, limits: n.informationLimits }); setSelectedId(id); setDirty(false); setNotice(""); }
 async function save() { if (lock.current || uncertain || !dirty) return; const end = periodEnd(draft.periodStart), narrative: Narrative = { taughtAndPractised: lines(draft.taught), parentReportedExamples: [], practitionerObservations: lines(draft.observations), usefulChanges: lines(draft.useful), continuingDifficulty: lines(draft.difficulty), uncertainty: draft.uncertainty.trim(), nextAdjustment: draft.next.trim(), informationLimits: draft.limits.trim() }; if (!end || !narrative.taughtAndPractised.length || !narrative.uncertainty || !narrative.nextAdjustment || !narrative.informationLimits) { setNotice(t.required); return; } lock.current = true; setBusy(true); setNotice("");
  try { const result = await post<{ reviewId: string; attendedSessionCount: number }>("/api/progress/reviews", { caseId, audienceId, periodStart: draft.periodStart, periodEnd: end, assignmentVersionIds: [], parentReportIds: [], narrative }); if (!result.reviewId || !Number.isSafeInteger(result.attendedSessionCount)) throw Error("INVALID_RECEIPT"); if (mounted.current) { onSaved({ id: result.reviewId, caseId, audienceId, periodStart: draft.periodStart, periodEnd: end, attendedSessionCount: result.attendedSessionCount, state: "draft", narrative }); setSelectedId(result.reviewId); setDirty(false); setNotice(t.saved); } } catch { if (mounted.current) { setUncertain(true); setNotice(t.failed); } } finally { lock.current = false; if (mounted.current) setBusy(false); }
 }
 async function publish() { if (lock.current || uncertain || dirty || !selected || selected.state !== "draft") return; lock.current = true; setBusy(true); setNotice(""); const snapshot = selected;
  try { const result = await post<{ reviewId: string; attendedSessionCount: number }>("/api/progress/reviews/publish", { reviewId: snapshot.id }); if (result.reviewId !== snapshot.id || !Number.isSafeInteger(result.attendedSessionCount)) throw Error("INVALID_RECEIPT"); if (mounted.current) { onSaved({ ...snapshot, state: "published", attendedSessionCount: result.attendedSessionCount }); setNotice(t.publishedNow); } } catch { if (mounted.current) { setUncertain(true); setNotice(t.failed); } } finally { lock.current = false; if (mounted.current) setBusy(false); }
 }
 const fields = [["taught",t.taught],["observations",t.observations],["useful",t.useful],["difficulty",t.difficulty],["uncertainty",t.uncertainty],["next",t.next],["limits",t.limits]] as const;
 return <section className="lsw-card lsw-stack"><PrivateObservationEvidencePanel locale={locale} caseId={caseId}/><label>{t.select}<select value={selectedId} disabled={busy} onChange={event => choose(event.target.value)}><option value="">{t.newDraft}</option>{reviews.filter(item => item.state === "draft").map(item => <option key={item.id} value={item.id}>{item.periodStart}–{item.periodEnd}</option>)}</select></label><p>{t.sources}</p><label>{t.start}<input type="date" value={draft.periodStart} disabled={busy} onChange={event => change("periodStart",event.target.value)} /></label><p>{t.end}: {periodEnd(draft.periodStart) || "—"}</p>{fields.map(([field,label]) => <label key={field}>{label}<textarea value={draft[field]} disabled={busy} maxLength={field === "uncertainty" || field === "next" || field === "limits" ? 3000 : 12000} onChange={event => change(field,event.target.value)} /></label>)}<div className="lsw-actions"><button type="button" disabled={busy || uncertain || !dirty} onClick={() => void save()}>{busy ? t.busy : t.save}</button><button type="button" disabled={busy || uncertain || dirty || !selected || selected.state !== "draft"} onClick={() => void publish()}>{t.publish}</button></div>{dirty && <p>{t.dirty}</p>}{notice && <p role="status">{notice}</p>}{uncertain && <button type="button" onClick={() => window.location.reload()}>{t.reload}</button>}</section>;
}
export function ReportReadout({ locale, review }: { locale: Locale; review: Review }) { const t = words[locale], n = review.narrative; const sections = [[t.taught,n.taughtAndPractised],[t.observations,n.practitionerObservations],[locale === "he" ? "דיווחי הורים מיוחסים" : "Attributed parent reports",n.parentReportedExamples],[t.useful,n.usefulChanges],[t.difficulty,n.continuingDifficulty],[t.uncertainty,[n.uncertainty]],[t.next,[n.nextAdjustment]],[t.limits,[n.informationLimits]]] as const; return <article className="lsw-card"><h2>{review.periodStart}–{review.periodEnd} · {review.state === "published" ? t.published : t.draft}</h2><p>{t.attended}: {review.attendedSessionCount}</p>{sections.filter(([,values]) => values.length).map(([label,values]) => <section key={label}><h3>{label}</h3>{values.map((text,index) => <p key={index}>{text}</p>)}</section>)}</article>; }
