"use client";
import type { ReactNode } from "react";
import type { CreativeVersion, FacebookPagePublicationReadModel, MarketingSnapshot, Publication } from "../../features/marketing-overview/contracts.ts";
import { creativePlacement } from "../../features/marketing-overview/creative-filters.ts";
import { safeMarketingUrl } from "../../features/marketing-overview/read-model.ts";
import { adjacentMonth, calendarDates, contentChannel, contentDate, contentDayKey, contentLayout, contentMonth, contentState, contentView, contentViewPublications, contentWeekDates, dateFilteredContent, nextHebrewStatus, orderedContentRecords, orderedPublicationQueue, publicationDisplayTime, publicationStatusText, publicationTimeIssue, shiftContentDate, CONTENT_CHANNELS, CONTENT_STATES, CONTENT_TIMEZONE } from "../../features/marketing-overview/calendar-model.ts";
import { Section, word } from "./primitives.tsx";
import { FacebookPagePublicationStatus } from "./facebook-page-publication-status.tsx";

export interface ContentCalendarQuery { filter?:string|undefined;month?:string|undefined;layout?:string|undefined;date?:string|undefined;channel?:string|undefined;state?:string|undefined;from?:string|undefined;to?:string|undefined;publication?:string|undefined; }
const channelLabels:Readonly<Record<string,readonly[string,string]>>={whatsapp_status:["WhatsApp Status","סטטוס WhatsApp"],facebook_page:["Facebook feed","פיד Facebook"],instagram:["Instagram","Instagram"],facebook_group_manual:["Facebook group (manual)","קבוצת Facebook (ידני)"],whatsapp_group_manual:["WhatsApp group (manual)","קבוצת WhatsApp (ידני)"]};
const stateLabels:Readonly<Record<string,readonly[string,string]>>={draft:["Draft","טיוטה"],held:["Held","מושהה"],ready:["Ready","מוכן"],scheduled:["Scheduled","מתוזמן"],sending:["Sending","בשליחה"],published:["Published state","מצב פורסם"],failed:["Failed","נכשל"],unknown:["Unknown","לא ידוע"],skipped:["Skipped","דולג"],manually_reported:["Manually reported","דווח ידנית"]};
function named(value:string,labels:typeof channelLabels,locale:"en"|"he"){const pair=Object.hasOwn(labels,value)?labels[value]:null;return pair?word(locale,pair[0],pair[1]):value;}
function dateTime(value:string,locale:"en"|"he"){return new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short",timeZone:CONTENT_TIMEZONE}).format(new Date(value));}
function timeIssue(item:Publication,locale:"en"|"he"){const issue=publicationTimeIssue(item);return issue==="manual"?word(locale,"Invalid manual report date — check source","תאריך דיווח ידני שגוי — יש לבדוק במקור"):issue==="scheduled"?word(locale,"Invalid scheduled date — check source","תאריך מתוזמן שגוי — יש לבדוק במקור"):null;}
function sourceLink(asset:CreativeVersion|undefined){return safeMarketingUrl(asset?.sourceUrl??null,["drive.google.com","docs.google.com","github.com"])??safeMarketingUrl(asset?.imageUrl??null,["drive.google.com","docs.google.com","github.com"]);}
function recordedStatusActivity(item:Publication){for(const value of [item.providerReadAt,publicationDisplayTime(item)])if(value&&Number.isFinite(Date.parse(value)))return value;return null;}
function Evidence({item,locale,showError=true}:{item:Publication;locale:"en"|"he";showError?:boolean}){return <>{showError&&item.errorCode&&<p className="lsr-inline-error" role="alert">{word(locale,"Attention needed","דורש טיפול")}: {item.errorCode}</p>}{item.providerReceiptId&&<p>{word(locale,"Provider receipt","אסמכתת ספק")}: {item.providerReceiptId}</p>}{item.providerReadAt&&<p>{word(locale,"Last provider readback","קריאה אחרונה מהספק")}: {item.providerReadAt}</p>}</>;}

/** The registered snapshot is read-only. Navigation never changes approvals or schedules. */
export function MarketingContentCalendar({locale,snapshot,query,renderedAt,thumbnail,facebookPage}:{locale:"en"|"he";snapshot:MarketingSnapshot;query:ContentCalendarQuery;renderedAt:string;thumbnail:(asset:CreativeVersion)=>ReactNode;facebookPage?:FacebookPagePublicationReadModel|undefined}){
  const now=new Date(renderedAt),month=contentMonth(query.month,now),layout=contentLayout(query.layout),view=contentView(query.filter),channel=contentChannel(query.channel),state=contentState(query.state);
  const date=contentDate(query.date)??(month===contentDayKey(renderedAt).slice(0,7)?contentDayKey(renderedAt):`${month}-01`),from=contentDate(query.from),to=contentDate(query.to);
  const invalidRange=Boolean(query.from&&!from||query.to&&!to||from&&to&&from>to);
  const href=(patch:Partial<ContentCalendarQuery>={})=>{
    const values:ContentCalendarQuery={month,layout,date,filter:view,channel:channel??undefined,state:state??undefined,from:query.from,to:query.to,...patch};
    const params=new URLSearchParams({section:"content_calendar"});for(const[key,value]of Object.entries(values))if(value)params.set(key,value);return `/${locale}/app/marketing?${params}`;
  };
  const assetFor=(item:Publication)=>snapshot.creatives.find(asset=>asset.assetId===item.assetId&&asset.revision===item.creativeRevision&&asset.contentDigest===item.creativeDigest);
  const selected=query.publication?snapshot.publications.find(item=>item.id===query.publication):null;
  const filtered=contentViewPublications(snapshot.publications,view).filter(item=>(!channel||item.channel===channel)&&(!state||item.state===state));
  const dated=invalidRange?[]:dateFilteredContent(filtered,from,to),undated=orderedContentRecords(filtered.filter(item=>publicationDisplayTime(item)===null));
  const selectedRecords=orderedContentRecords([...dated.filter(item=>publicationDisplayTime(item)!==null),...undated]);
  const queue=invalidRange?[]:orderedPublicationQueue(selectedRecords),otherRecords=selectedRecords.filter(item=>view!=="all"||!["ready","scheduled","sending"].includes(item.state));
  const dates=layout==="week"?contentWeekDates(date):calendarDates(month),periodDays=new Set(dates.filter((value):value is string=>value!==null)),periodItems=orderedContentRecords(dated.filter(item=>{const instant=publicationDisplayTime(item);return instant&&periodDays.has(contentDayKey(instant));}));
  const next=nextHebrewStatus(snapshot.publications,snapshot.creatives,now);
  const nextHold=snapshot.nextStatusHold?.language==="he"?snapshot.nextStatusHold:null;
  const heldCandidates=nextHold?.candidateAssetIds.map(assetId=>snapshot.creatives.find(asset=>asset.assetId===assetId)).filter((asset):asset is CreativeVersion=>Boolean(asset))??[];
  const unresolvedStatuses=snapshot.publications.filter(item=>item.channel==="whatsapp_status"&&["sending","unknown"].includes(item.state)).slice().sort((a,b)=>(Date.parse(recordedStatusActivity(b)??"")||0)-(Date.parse(recordedStatusActivity(a)??"")||0)||a.id.localeCompare(b.id));
  const latestUnresolvedStatus=unresolvedStatuses[0]??null;
  const unboundStatusDrafts=snapshot.publications.filter(item=>item.channel==="whatsapp_status"&&item.provider==="unbound"&&["draft","held"].includes(item.state));
  const hebrewStatusHolds=snapshot.creatives.filter(asset=>!asset.collection&&asset.locale==="he"&&creativePlacement(asset)==="whatsapp_status"&&Boolean(asset.holdReason?.trim())).slice().sort((a,b)=>b.revision-a.revision||a.assetId.localeCompare(b.assetId)).filter((asset,index,assets)=>assets.findIndex(item=>item.assetId===asset.assetId)===index).sort((a,b)=>a.title.localeCompare(b.title));
  // Exact originals are private and uncached. Bound automatic previews once
  // across the visible period; secondary lists retain links, not more transfers.
  const previewRecords=new Set(periodItems.slice(0,12));
  const fullTime=new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short",timeZone:CONTENT_TIMEZONE}),compactTime=new Intl.DateTimeFormat(locale,{hour:"2-digit",minute:"2-digit",timeZone:CONTENT_TIMEZONE});
  const recordsByDay=new Map<string,Publication[]>();for(const item of periodItems){const day=contentDayKey(publicationDisplayTime(item)!);const list=recordsByDay.get(day)??[];list.push(item);recordsByDay.set(day,list);}
  const itemHref=(item:Publication)=>href({publication:item.id});
  const itemCard=(item:Publication,compact=false,showPreview=false)=>{const asset=assetFor(item),time=publicationDisplayTime(item),issue=timeIssue(item,locale);return <article className="lsr-content-card"><a href={itemHref(item)} className="lsr-content-open" aria-label={`${word(locale,"Open publication","פתיחת רשומת פרסום")}: ${asset?.title??item.assetId}`}>
    {asset&&showPreview&&thumbnail(asset)}<div><strong title={asset?.title??item.assetId}>{asset?.title??item.assetId}</strong><span>{named(item.channel,channelLabels,locale)} · {item.destinationLabel}</span><span>{time?<time dateTime={time}>{(compact?compactTime:fullTime).format(new Date(time))}</time>:word(locale,"Unscheduled","ללא מועד")}</span><span>{publicationStatusText(item,snapshot.creatives,locale)}</span></div></a>{issue&&<p role="alert" className="lsr-inline-error">{issue}</p>}{item.errorCode&&<p role="alert" className="lsr-inline-error">{word(locale,"Attention needed","דורש טיפול")}: {item.errorCode}</p>}</article>;};
  if(query.publication){
    if(!selected)return <Section title={word(locale,"Publication unavailable","רשומת הפרסום אינה זמינה")}><p role="alert">{word(locale,"This record is not present in the current authorized inventory. Return to the calendar and refresh the source.","הרשומה אינה נמצאת במלאי המורשה הנוכחי. אפשר לחזור ליומן ולרענן את המקור.")}</p><a className="lsr-button" href={href()}>{word(locale,"Back to content calendar","חזרה ליומן התוכן")}</a></Section>;
    const asset=assetFor(selected),source=sourceLink(asset),post=safeMarketingUrl(selected.postUrl,["facebook.com","www.facebook.com","m.facebook.com","instagram.com","www.instagram.com","wa.me","web.whatsapp.com"]),time=publicationDisplayTime(selected),issue=timeIssue(selected,locale);
    return <Section title={asset?.title??selected.assetId}><nav aria-label={word(locale,"Publication breadcrumbs","נתיב רשומת הפרסום")}><a href={href()}>{word(locale,"Content calendar","יומן תוכן")}</a><span aria-hidden="true"> / </span><span aria-current="page">{asset?.title??selected.assetId}</span></nav><p>{named(selected.channel,channelLabels,locale)} · {selected.destinationLabel}</p><p className="lsr-status">{publicationStatusText(selected,snapshot.creatives,locale)}</p>{issue?<p role="alert" className="lsr-inline-error">{issue}</p>:<p>{time?<time dateTime={time}>{dateTime(time,locale)}</time>:word(locale,"No recorded date","אין תאריך רשום")} · Asia/Jerusalem</p>}
      {asset?<><div className="lsr-content-detail-image">{thumbnail(asset)}</div><p>{asset.locale.toUpperCase()} · v{asset.revision} · {asset.width} × {asset.height}</p><details><summary>{word(locale,"Registered caption","כיתוב רשום")}</summary><p className="lsr-content-caption">{asset.caption||word(locale,"No registered caption","אין כיתוב רשום")}</p></details></>:<p role="status">{word(locale,"Creative revision unavailable; no other revision has been substituted.","גרסת הקריאייטיב אינה זמינה; לא הוחלפה בגרסה אחרת.")}</p>}
      <Evidence item={selected} locale={locale}/><div className="lsr-actions">{source&&<a className="lsr-button" href={source} target="_blank" rel="noopener noreferrer">{word(locale,"Open source asset","פתיחת קובץ המקור")}</a>}{post&&<a className="lsr-button" href={post} target="_blank" rel="noopener noreferrer">{word(locale,"Open recorded post link","פתיחת קישור הפוסט הרשום")}</a>}<a className="lsr-button" href={href()}>{word(locale,"Back to content calendar","חזרה ליומן התוכן")}</a></div><p className="lsr-help">{word(locale,"This record does not publish, reschedule or approve content. Provider acceptance is not proof of publication.","רשומה זו אינה מפרסמת, משנה מועד או מאשרת תוכן. קבלת הספק אינה הוכחה לפרסום.")}</p></Section>;
  }
  return <Section title={word(locale,"Content calendar","יומן תוכן")}>
    {facebookPage&&<FacebookPagePublicationStatus locale={locale} publication={facebookPage}/>}
    <nav className="lsr-tabs lsr-content-views" tabIndex={0} aria-label={word(locale,"Publication views","תצוגות פרסום")}>{([["all",word(locale,"All","הכול")],["queued",word(locale,"Due & planned","ממתינים ומתוכננים")],["drafts",word(locale,"Drafts","טיוטות")],["published",word(locale,"Published","פורסמו")],["history",word(locale,"History","היסטוריה")]]as const).map(([value,label])=><a className="lsr-button" aria-current={view===value?"page":undefined} href={href({filter:value,state:undefined})} key={value}>{label}</a>)}</nav>
    <details className="lsr-content-filters" open={invalidRange||undefined}><summary>{word(locale,"Filters","סינון")}: {channel?named(channel,channelLabels,locale):word(locale,"All channels","כל הערוצים")} · {state?named(state,stateLabels,locale):word(locale,"All states","כל המצבים")}{from||to?` · ${from??"—"} — ${to??"—"}`:""}</summary>
    <form method="get" action={`/${locale}/app/marketing`} className="lsr-content-filter-form" aria-label={word(locale,"Content filters","סינון תוכן")}><input type="hidden" name="section" value="content_calendar"/><input type="hidden" name="filter" value={view}/><input type="hidden" name="month" value={month}/><input type="hidden" name="layout" value={layout}/><input type="hidden" name="date" value={date}/>
      <label>{word(locale,"Channel","ערוץ")}<select name="channel" defaultValue={channel??""}><option value="">{word(locale,"All channels","כל הערוצים")}</option>{CONTENT_CHANNELS.map(value=><option key={value} value={value}>{named(value,channelLabels,locale)}</option>)}</select></label>
      <label>{word(locale,"Recorded state","מצב רשום")}<select name="state" defaultValue={state??""}><option value="">{word(locale,"All states","כל המצבים")}</option>{CONTENT_STATES.map(value=><option key={value} value={value}>{named(value,stateLabels,locale)}</option>)}</select></label>
      <label>{word(locale,"From date","מתאריך")}<input type="date" name="from" defaultValue={query.from??""}/></label><label>{word(locale,"Through date","עד תאריך")}<input type="date" name="to" defaultValue={query.to??""}/></label><button className="lsr-primary" type="submit">{word(locale,"Apply filters","החלת סינון")}</button><a className="lsr-button" href={href({filter:"all",channel:undefined,state:undefined,from:undefined,to:undefined})}>{word(locale,"Clear filters","ניקוי סינון")}</a>
    </form></details>{invalidRange&&<p role="alert" className="lsr-inline-error">{word(locale,"Use valid dates, with the end date on or after the start. Correct the range or clear filters.","יש לבחור תאריכים תקינים, עם תאריך סיום שאינו לפני ההתחלה. אפשר לתקן את הטווח או לנקות סינון.")}</p>}
    <nav className="lsr-tabs lsr-content-layouts" aria-label={word(locale,"Calendar layout","תצוגת היומן")} tabIndex={0}>{([["month",word(locale,"Month","חודש")],["week",word(locale,"Week","שבוע")],["agenda",word(locale,"Agenda","סדר יום")]]as const).map(([value,label])=><a className="lsr-button" key={value} aria-current={layout===value?"page":undefined} href={href({layout:value})}>{label}</a>)}</nav>
    <nav className="lsr-content-month-nav" aria-label={word(locale,"Content calendar month","חודש ביומן התוכן")}><a className="lsr-button" aria-label={layout==="week"?word(locale,"Previous week","השבוע הקודם"):word(locale,"Previous month","החודש הקודם")} href={layout==="week"?href({date:shiftContentDate(date,-7),month:shiftContentDate(date,-7).slice(0,7)}):href({month:adjacentMonth(month,-1),date:`${adjacentMonth(month,-1)}-01`})}>{word(locale,"Previous","הקודם")}</a><h3>{layout==="week"?`${dates[0]} — ${dates[6]}`:new Intl.DateTimeFormat(locale,{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${month}-01T12:00:00Z`))}</h3><a className="lsr-button" aria-label={layout==="week"?word(locale,"Next week","השבוע הבא"):word(locale,"Next month","החודש הבא")} href={layout==="week"?href({date:shiftContentDate(date,7),month:shiftContentDate(date,7).slice(0,7)}):href({month:adjacentMonth(month,1),date:`${adjacentMonth(month,1)}-01`})}>{word(locale,"Next","הבא")}</a><a className="lsr-button" href={href({month:contentDayKey(renderedAt).slice(0,7),date:contentDayKey(renderedAt)})}>{word(locale,"Today","היום")}</a></nav>
    {layout!=="agenda"?<div className="lsr-content-calendar-scroll" role="region" aria-label={layout==="week"?word(locale,"Weekly content calendar","יומן תוכן שבועי"):word(locale,"Monthly content calendar","יומן תוכן חודשי")} tabIndex={0}><div className="lsr-content-calendar-grid">{Array.from({length:7},(_,index)=><strong className="lsr-content-weekday" key={index}>{new Intl.DateTimeFormat(locale,{weekday:"short",timeZone:"UTC"}).format(new Date(Date.UTC(2023,0,1+index)))}</strong>)}{dates.map((day,index)=><div className="lsr-content-day" key={day??`blank-${index}`} aria-label={day??undefined}><strong>{day?.slice(-2)??""}</strong>{day&&<ul>{(recordsByDay.get(day)??[]).map(item=><li key={item.id}>{itemCard(item,true,previewRecords.has(item))}</li>)}</ul>}</div>)}</div></div>:<div role="region" aria-label={word(locale,"Content agenda","סדר יום תוכן")}><ol className="lsr-content-records">{periodItems.map(item=><li key={item.id}>{itemCard(item,false,previewRecords.has(item))}</li>)}</ol>{!periodItems.length&&<p>{word(locale,"No dated records match this period and these filters.","אין רשומות מתוארכות המתאימות לתקופה ולסינון.")}</p>}</div>}
    {periodItems.length>12&&<p className="lsr-help">{word(locale,"Automatic previews are limited to 12 records. Open a record for its full preview; all records and source errors remain available.","תצוגות אוטומטיות מוגבלות ל־12 רשומות. אפשר לפתוח רשומה לתצוגה מלאה; כל הרשומות ושגיאות המקור נשארות זמינות.")}</p>}
    {latestUnresolvedStatus&&<div className="lsr-inline-error" role="region" aria-label={word(locale,"Unresolved WhatsApp Status attempt","ניסיון סטטוס WhatsApp שלא הוכרע")}><h3>{word(locale,"Latest unresolved WhatsApp Status attempt","ניסיון הסטטוס האחרון שטרם הוכרע")}</h3><p><a href={itemHref(latestUnresolvedStatus)}>{assetFor(latestUnresolvedStatus)?.title??latestUnresolvedStatus.assetId}</a> · {publicationStatusText(latestUnresolvedStatus,snapshot.creatives,locale)}{recordedStatusActivity(latestUnresolvedStatus)&&<> · <time dateTime={recordedStatusActivity(latestUnresolvedStatus)!}>{dateTime(recordedStatusActivity(latestUnresolvedStatus)!,locale)}</time></>}</p><Evidence item={latestUnresolvedStatus} locale={locale}/><p>{word(locale,"A provider receipt records acceptance, not confirmed publication. Do not retry while the result is unknown; reconcile provider history first.","אסמכתת ספק מתעדת קבלה, לא פרסום מאומת. אין לנסות שוב כל עוד התוצאה אינה ידועה; תחילה יש ליישב את היסטוריית הספק.")}</p></div>}
    <details className="lsr-content-next"><summary>{word(locale,"Next planned Hebrew WhatsApp Status in the registry","הסטטוס המתוכנן הבא בעברית במאגר")}: {next?.scheduledFor?<time dateTime={next.scheduledFor}>{dateTime(next.scheduledFor,locale)}</time>:nextHold?`${word(locale,"Held","מושהה")} — ${nextHold.reason}`:word(locale,"No scheduled time recorded","לא רשום מועד מתוזמן")}</summary>{next?.scheduledFor?<p><a href={href({channel:"whatsapp_status",filter:"queued",publication:next.id})}>{assetFor(next)?.title??next.assetId}</a> · {publicationStatusText(next,snapshot.creatives,locale)}</p>:<>{nextHold?<div className="lsr-inline-error" role="status"><p>{word(locale,"The existing publisher records this Hebrew turn as held. No successor is scheduled, and this page cannot release or retry it.","המתזמן הקיים רושם את התור העברי כמושהה. לא נקבע סטטוס ממשיך, והמסך הזה אינו יכול לשחרר או לנסות אותו מחדש.")}</p><p><strong>{word(locale,"Publisher hold reason","סיבת ההשהיה במתזמן")}:</strong> {nextHold.reason}</p>{heldCandidates.length>0&&<ul>{heldCandidates.map(asset=><li key={asset.assetId}><a href={`/${locale}/app/marketing?section=creatives&language=he&placement=whatsapp_status&search=${encodeURIComponent(asset.assetId)}`}>{asset.title}</a> · {asset.assetId}</li>)}</ul>}</div>:<p>{word(locale,"No upcoming Hebrew Status is recorded as ready, scheduled or sending. This registry view is not a provider queue readback.","לא רשום סטטוס עברי עתידי במצב מוכן, מתוזמן או בשליחה. תצוגת המאגר אינה קריאה ישירה מתור הספק.")}</p>}{unboundStatusDrafts.length>0&&<p>{unboundStatusDrafts.length===1?word(locale,"1 unbound Status draft is a planning record, not a live provider-queue item.","טיוטת סטטוס לא מקושרת אחת היא רשומת תכנון, ולא פריט חי בתור הספק."):word(locale,`${unboundStatusDrafts.length} unbound Status drafts are planning records, not live provider-queue items.`,`${unboundStatusDrafts.length} טיוטות סטטוס לא מקושרות הן רשומות תכנון, ולא פריטים חיים בתור הספק.`)}</p>}{hebrewStatusHolds.length>0&&<><p><strong>{word(locale,"Registered Hebrew Status holds","חסימות רשומות של סטטוס בעברית")}:</strong></p><ul>{hebrewStatusHolds.map(asset=><li key={`${asset.assetId}:${asset.revision}:${asset.contentDigest}`}><a href={`/${locale}/app/marketing?section=creatives&language=he&placement=whatsapp_status&search=${encodeURIComponent(asset.assetId)}`}>{asset.title}</a>: {asset.holdReason}</li>)}</ul></>}</>}</details>
    {(view==="all"||view==="queued")&&<details className="lsr-content-secondary"><summary>{word(locale,"Ordered planned and ready records","רשומות מתוכננות ומוכנות לפי סדר")}: {queue.length}</summary><p className="lsr-help">{word(locale,"Ready but unscheduled records are included; this count is not the provider queue count.","רשומות מוכנות אך לא מתוזמנות כלולות; המספר אינו מספר הפריטים בתור הספק.")}</p><ol className="lsr-content-records">{queue.map(item=><li key={item.id}>{itemCard(item)}<Evidence item={item} locale={locale} showError={false}/></li>)}</ol>{!queue.length&&<p>{word(locale,"No planned records in the registry; this is not a provider queue readback.","אין רשומות מתוכננות במאגר; זו אינה קריאה ישירה של תור הספק.")}</p>}</details>}
    <details className="lsr-content-secondary"><summary>{word(locale,"Unscheduled ready records","רשומות מוכנות ללא מועד")}: {undated.filter(item=>item.state==="ready").length}</summary><ol className="lsr-content-records">{undated.filter(item=>item.state==="ready").map(item=><li key={item.id}>{itemCard(item)}</li>)}</ol></details>
    {(view==="all"||view==="drafts"||view==="published"||view==="history")&&<details className="lsr-content-secondary"><summary>{view==="all"?word(locale,"Other registry records","רשומות נוספות במאגר"):word(locale,"Selected records","רשומות שנבחרו")}: {otherRecords.length}</summary><ol className="lsr-content-records">{otherRecords.map(item=><li key={item.id}>{itemCard(item)}<p>{!publicationDisplayTime(item)?word(locale,"No recorded date","אין תאריך רשום"):""}</p><Evidence item={item} locale={locale} showError={false}/></li>)}</ol></details>}
    {selectedRecords.some(item=>publicationTimeIssue(item)||item.errorCode)&&<div role="region" aria-label={word(locale,"Source record errors","שגיאות רשומה במקור")}>{selectedRecords.filter(item=>publicationTimeIssue(item)||item.errorCode).map(item=><p className="lsr-inline-error" role="alert" key={item.id}><a href={itemHref(item)}>{assetFor(item)?.title??item.assetId}</a>: {timeIssue(item,locale)??item.errorCode}</p>)}</div>}
    {!snapshot.publications.length&&<p>{word(locale,"No workbook publishing records are available. This does not mean the publisher is empty.","אין כרגע רשומות פרסום מהחוברת. אין להסיק שמתזמן הספק ריק.")}</p>}
    <details className="lsr-content-secondary"><summary>{word(locale,"About these source records","על רשומות המקור")}</summary><p className="lsr-help">{word(locale,"Read-only registry view. Times use Asia/Jerusalem. Planned, provider-accepted and confirmed published are different states; this page does not schedule or publish.","תצוגת קריאה בלבד של המאגר. הזמנים מוצגים לפי שעון ישראל. תכנון, קבלת הספק ופרסום מאומת הם מצבים שונים; מסך זה אינו מתזמן או מפרסם.")}{snapshot.inventory?.partial?` ${word(locale,"Inventory is partial; missing is not zero.","המלאי חלקי; חוסר מידע אינו אפס.")}`:""}</p></details>
  </Section>;
}
