"use client";
import { useState } from "react";
import Image from "next/image";
import type { Locale } from "../../features/session-workflow/types.ts";
import type { MarketingSnapshot } from "../../features/marketing-overview/contracts.ts";
import { publicationLabel, approvedCreative, safeMarketingUrl } from "../../features/marketing-overview/read-model.ts";
import { Section, word } from "./primitives.tsx";
import "./styles.css";
const sections = ["overview", "content_calendar", "creatives", "publishing", "community_scout"] as const;
const headings = { en: { overview: "Overview", content_calendar: "Content calendar", creatives: "Creatives", publishing: "Publishing", community_scout: "Community Scout" }, he: { overview: "סקירה", content_calendar: "יומן תוכן", creatives: "קריאייטיב", publishing: "פרסום", community_scout: "איתור שיחות בקבוצות" } };
export function MarketingDashboard({ locale, snapshot }: {
    locale: Locale;
    snapshot: MarketingSnapshot;
}) {
    const [section, setSection] = useState<typeof sections[number]>("overview"), h = headings[locale];
    const actual = snapshot.source === "provider_readback";
    return <section className="lsr"><header className="lsr-page-heading"><h1>{word(locale, "Marketing", "שיווק")}</h1><p>{word(locale, "Your graphics and publishing schedule. No client records or leads appear here.", "הגרפיקה ולוח הפרסום שלך. אין כאן רשומות לקוחות או לידים.")}</p><p className="lsr-status">{snapshot.source === "synthetic" ? word(locale, "Synthetic examples — nothing is scheduled or sent", "דוגמאות סינתטיות — דבר לא תוזמן ולא נשלח") : actual ? word(locale, "Provider readback available; inspect each receipt", "זמינה קריאה מספק — יש לבדוק כל אסמכתה") : word(locale, "Publishing connections are not verified in this view", "חיבורי הפרסום אינם מאומתים בתצוגה זו")}</p></header><nav className="lsr-tabs" aria-label={word(locale, "Marketing sections", "חלקי השיווק")}>{sections.map(key => <button type="button" key={key} aria-pressed={section === key} onClick={() => setSection(key)}>{h[key]}</button>)}</nav>
 {section === "overview" && <><div className="lsr-summary-grid"><Section title={word(locale, "Approved creatives", "קריאייטיבים מאושרים")}><strong className="lsr-stat">{snapshot.creatives.length ? snapshot.creatives.filter(approvedCreative).length : "—"}</strong><p>{word(locale, "Exact version approval, not a guessed status.", "אישור לגרסה מדויקת, לא מצב משוער.")}</p></Section><Section title={word(locale, "Upcoming publications", "פרסומים קרובים")}><strong className="lsr-stat">{snapshot.publications.length ? snapshot.publications.filter(p => p.state === "scheduled" || p.state === "ready").length : "—"}</strong><p>{word(locale, "Planned dates and provider-confirmed schedules are shown separately.", "תכנון ואישור תזמון אצל הספק מוצגים בנפרד.")}</p></Section></div><Section title={word(locale, "Ads — read only", "מודעות — לצפייה בלבד")}>
 {!snapshot.ads.length ? <p>{word(locale, "No verified ad snapshots connected.", "עדיין אין נתוני מודעות מאומתים.")}</p> : snapshot.ads.map(ad => { const url = safeMarketingUrl(ad.manageUrl, ["adsmanager.facebook.com", "business.facebook.com", "ads.google.com"]); return <article className="lsr-ad-row" key={ad.id}><h3>{ad.name}</h3><p>{ad.platform} · {ad.status}</p><p>{word(locale, "Spend", "הוצאה")}: {ad.spendMinor !== null && ad.currency ? new Intl.NumberFormat(locale, { style: "currency", currency: ad.currency }).format(ad.spendMinor / 100) : word(locale, "Not available", "לא זמין")}</p><p>{word(locale, "Updated", "עודכן")}: {ad.asOf ?? word(locale, "Not verified", "לא אומת")}</p>{url && <a href={url} target="_blank" rel="noopener noreferrer">{word(locale, "Open ad platform", "פתיחה במערכת המודעות")}</a>}</article>; })}</Section></>}
 {section === "creatives" && <Section title={h.creatives} description={word(locale, "Language, dimensions and approval belong to the exact graphic revision.", "שפה, מידות ואישור שייכים לגרסה המדויקת של הגרפיקה.")}><div className="lsr-creative-grid">{snapshot.creatives.map(a => { const url = safeMarketingUrl(a.imageUrl, ["drive.google.com", "lh3.googleusercontent.com"]); return <article key={`${a.assetId}:${a.revision}`}><div className="lsr-creative-image">{url ? <Image src={url} alt={a.title} width={a.width} height={a.height} unoptimized referrerPolicy="no-referrer"/> : <span>{word(locale, "No verified image attached", "אין תמונה מאומתת מצורפת")}<br />{a.width} × {a.height}</span>}</div><h3>{a.title}</h3><p>{a.locale.toUpperCase()} · v{a.revision} · {approvedCreative(a) ? word(locale, "Approved exact version", "הגרסה המדויקת מאושרת") : word(locale, "Needs review", "ממתין לבדיקה")}</p></article>; })}</div>{!snapshot.creatives.length && <p>{word(locale, "Connect the existing Asset Registry. Do not generate replacements automatically.", "יש לחבר את מרשם הנכסים הקיים. אין לייצר תחליפים אוטומטית.")}</p>}</Section>}
 {(section === "content_calendar" || section === "publishing") && <Section title={h[section]}>{snapshot.publications.map(p => <article className="lsr-publication-row" key={p.id}><h3>{snapshot.creatives.find(a => a.assetId === p.assetId)?.title ?? p.assetId}</h3><p>{p.channel} · {p.destinationLabel}</p><time>{p.scheduledFor ? new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short", timeZone: p.timezone }).format(new Date(p.scheduledFor)) : word(locale, "No scheduled time", "לא תוזמן")}</time><p>{publicationLabel(p, snapshot.creatives)}</p>{p.errorCode && <p role="status">{word(locale, "Attention needed", "דורש טיפול")}: {p.errorCode}</p>}</article>)}{!snapshot.publications.length && <p>{word(locale, "No verified publishing schedule is connected. This does not mean the external scheduler is empty.", "לא חובר לוח פרסום מאומת. אין להסיק שהמתזמן החיצוני ריק.")}</p>}</Section>}
 {section === "community_scout" && <Section title="Community Scout"><p>{word(locale, "Review relevant public questions, edit a useful reply, then copy and post manually. Public posts do not become clinical records or automatic leads.", "בודקים שאלות ציבוריות רלוונטיות, עורכים תשובה מועילה ומעתיקים לפרסום ידני. פוסטים אינם הופכים לרשומות טיפוליות או ללידים אוטומטיים.")}</p><p>{word(locale, "Ready drafts", "טיוטות מוכנות")}: {snapshot.scout.readyDrafts ?? word(locale, "Not connected", "לא מחובר")}</p></Section>}
 </section>;
}
