"use client";
import {useEffect,useRef,useState} from "react";
import type {Locale,RoutineRecap} from "../../features/session-workflow/types.ts";
import type {RecapShareInput} from "../../features/session-workflow/client.ts";
import type {RecapSharePreview} from "../../features/session-workflow/recap-contract.ts";
import {RecapPreview} from "./recap-preview.tsx";
import {SaveStatus,word} from "./primitives.tsx";
import {useCommand,type CommandPort} from "./use-command.ts";
import {UnsavedChangesGuard} from "../workspace/draft-guard.tsx";
export function SessionSharing({locale,sessionId,recap,recapDigest,recipients,port,loadPreview,onLockChange}:{locale:Locale;sessionId:string;recap:RoutineRecap;recapDigest:string|null;recipients:readonly {accountId:string;name:string}[];port:CommandPort<RecapShareInput,{sharedAt:string}>;loadPreview?:((version:number,recipients:readonly string[],signal:AbortSignal)=>Promise<RecapSharePreview>)|undefined;onLockChange?:((locked:boolean)=>void)|undefined}){
 const [selected,setSelected]=useState<string[]>([]),[preview,setPreview]=useState<{key:string;value:RecapSharePreview}|null>(null),[busy,setBusy]=useState(false),[failed,setFailed]=useState(false),[shared,setShared]=useState<{key:string;at:string}|null>(null),controller=useRef<AbortController|null>(null),requestedKey=useRef("");
 const key=JSON.stringify([recap.version,recapDigest,[...selected].sort()]),valid=selected.length>0&&selected.every(id=>recipients.some(row=>row.accountId===id)),confirmed=preview?.key===key?preview.value:null;
 const command=useCommand(port,value=>{setShared({key:requestedKey.current,at:value.sharedAt});});
 useEffect(()=>{onLockChange?.(command.locked);},[command.locked,onLockChange]);
 useEffect(()=>()=>controller.current?.abort(),[]);
 async function review(){if(!loadPreview||busy||command.locked||!valid)return;controller.current?.abort();const attempt=new AbortController();controller.current=attempt;setBusy(true);setFailed(false);setPreview(null);try{const value=await loadPreview(recap.version,selected,attempt.signal);if(!attempt.signal.aborted)setPreview({key,value});}catch{if(!attempt.signal.aborted)setFailed(true);}finally{if(!attempt.signal.aborted)setBusy(false);}}
 const error=command.error==="CONFLICT"?word(locale,"The saved content, attendance, meeting or practice source changed. Nothing new was shared. Refresh the session and prepare a newly reviewed version; your selections remain here.","התוכן השמור, הנוכחות, הפגישה או מקור התרגול השתנו. לא שותף עדכון חדש. יש לרענן את המפגש ולהכין גרסה חדשה לבדיקה; הבחירות שלך נשארו כאן."):command.error?word(locale,"Sharing was not accepted. Check current case and practice permissions before previewing again.","השיתוף לא התקבל. יש לבדוק הרשאות תיק ותרגול לפני תצוגה מקדימה חוזרת."):null;
 return <section className="lsr"><UnsavedChangesGuard dirty={command.locked} message={word(locale,"The publication result is unresolved. Stay here and check its exact receipt before leaving.","תוצאת השיתוף עדיין לא אושרה. יש להישאר ולבדוק את הרשומה המדויקת לפני יציאה.")}/><RecapPreview recap={recap} locale={locale}/>
  <fieldset disabled={command.locked||busy}><legend>{word(locale,"Select authorized recipients","בחירת נמענים מורשים")}</legend>{recipients.map(row=><label key={row.accountId}><input type="checkbox" checked={selected.includes(row.accountId)} onChange={event=>{setFailed(false);setSelected(event.target.checked?[...selected,row.accountId]:selected.filter(id=>id!==row.accountId));}}/>{row.name}</label>)}</fieldset>
  {!valid&&selected.length>0&&<p role="alert">{word(locale,"A selected account no longer appears in the authorized recipient list. Choose current recipients again.","חשבון שנבחר אינו מופיע עוד ברשימת הנמענים המורשים. יש לבחור שוב נמענים נוכחיים.")}</p>}
  <button type="button" className="lsr-primary" disabled={!loadPreview||!recapDigest||!valid||busy||command.locked} onClick={()=>void review()}>{busy?word(locale,"Checking exact update…","בודק את העדכון המדויק…"):word(locale,"Share update","שיתוף עדכון")}</button>
  {!loadPreview&&<p>{word(locale,"This component example cannot publish an app update.","דוגמת הרכיב הזאת אינה יכולה לשתף עדכון באפליקציה.")}</p>}
  {failed&&<p role="alert">{word(locale,"The exact update could not be confirmed. Your selections remain; retry Share update after checking the current source.","לא ניתן לאשר את העדכון המדויק. הבחירות נשארו כאן; יש לבדוק את המקור הנוכחי ולנסות שוב שיתוף עדכון.")}</p>}
  {confirmed&&<section aria-label={word(locale,"Exact sharing preview","תצוגה מדויקת לפני שיתוף")}><h3>{word(locale,"Confirm this version and these recipients","אישור הגרסה הזאת והנמענים האלה")}</h3><p>{confirmed.recipients.map(row=>row.name).join(" · ")}</p><RecapPreview locale={locale} recap={confirmed.recap}/><p className="lsr-help">{word(locale,"Only this routine update is published. Private recordings, transcripts, analysis and scores are not included. Notification delivery is separate.","רק העדכון השגרתי הזה ישותף. הקלטות, תמלולים, ניתוח וציונים פרטיים אינם נכללים. מסירת התראות נבדקת בנפרד.")}</p><div className="lsr-actions"><button type="button" className="lsr-primary" disabled={command.locked||shared?.key===key} onClick={()=>{requestedKey.current=key;void command.execute({sessionId,expectedVersion:confirmed.recap.version,expectedDigest:confirmed.digest,recipientAccountIds:confirmed.recipients.map(row=>row.accountId)});}}>{word(locale,"Confirm share","אישור שיתוף")}</button><button type="button" disabled={command.locked} onClick={()=>setPreview(null)}>{word(locale,"Cancel sharing","ביטול שיתוף")}</button></div></section>}
  <SaveStatus locale={locale} phase={command.phase} error={error} onReconcile={()=>void command.reconcile()}/>{shared?.key===key&&<p role="status">{word(locale,"The exact publication was read back. Delivery status is tracked separately.","רשומת השיתוף המדויקת אושרה בקריאה חוזרת. מצב המסירה נרשם בנפרד.")}</p>}
 </section>;
}
