'use client';
import type { ReactNode } from 'react';
import type { Locale } from './model.ts';
import { localHref } from './model.ts';
import { uiCopy,formatInstant,formatCount } from './i18n.ts';
import { Button,SaveResult } from './controls.tsx';
import { Card,StatusChip } from './surfaces.tsx';
import { Dialog,DialogTrigger } from './dialogs.tsx';
export type AppointmentView={id:string;title:string;startsAt:string;endsAt:string;kind:'individual'|'parentGuidance'|'consultation';status:'scheduled'|'completed'|'rescheduled'|'canceledPractitioner'|'canceledFamily'|'absent'|'late';location?:string|undefined};
export type NoticeReceiptView={originalStartsAt:string;receivedAt:string;credit:'protected'|'consumed'|'exception'|'pending';replacement:'pending'|'confirmed';confirmedReplacementAt?:string|undefined};
export function AppointmentCard({locale,item,action}: {locale:Locale;item:AppointmentView;action?:ReactNode}) {const t=uiCopy(locale);return <Card id={item.id} title={item.title}><div className="lsw-appointment-time"><time dateTime={item.startsAt}>{formatInstant(item.startsAt,locale)}</time><span>—</span><time dateTime={item.endsAt}>{formatInstant(item.endsAt,locale)}</time></div><p>{t[item.kind]} · <bdi>{t.timezone}</bdi></p>{item.location && <p>{item.location}</p>}<StatusChip>{t[item.status]}</StatusChip>{action && <div className="lsw-secondary-action">{action}</div>}</Card>;}
export function RescheduleNotice({id,locale,item,onSend,busy=false,error=false,receipt}: {id:string;locale:Locale;item:AppointmentView;onSend:()=>void;busy?:boolean|undefined;error?:boolean|undefined;receipt?:NoticeReceiptView|undefined}) {const t=uiCopy(locale);return <><DialogTrigger id={id} variant="quiet">{t.reschedule}</DialogTrigger><Dialog id={id} locale={locale} title={t.requestTitle} description={t.requestExplain} busy={busy}>{receipt?<NoticeReceipt locale={locale} receipt={receipt}/>:<><p>{t.originalTime}: <time dateTime={item.startsAt}>{formatInstant(item.startsAt,locale)}</time></p><p>{t.creditRule}</p><p className="lsw-help">{t.creditUnknown}</p><Button variant="danger" busy={busy} onClick={()=>{if(!busy)onSend();}}>{t.sendNotice}</Button><SaveResult locale={locale} error={error} busy={busy}/></>}</Dialog></>;}
export function NoticeReceipt({locale,receipt}: {locale:Locale;receipt:NoticeReceiptView}) {const t=uiCopy(locale);const credit={protected:t.creditProtected,consumed:t.creditConsumed,exception:t.creditException,pending:t.creditPending};return <section className="lsw-receipt" aria-label={t.received}><h3>{t.received}</h3><dl className="lsw-description"><div><dt>{t.originalTime}</dt><dd><time dateTime={receipt.originalStartsAt}>{formatInstant(receipt.originalStartsAt,locale)}</time></dd></div><div><dt>{t.receivedAt}</dt><dd><time dateTime={receipt.receivedAt}>{formatInstant(receipt.receivedAt,locale)}</time></dd></div></dl><StatusChip>{credit[receipt.credit]}</StatusChip><p>{receipt.replacement==='confirmed'&&receipt.confirmedReplacementAt?<time dateTime={receipt.confirmedReplacementAt}>{formatInstant(receipt.confirmedReplacementAt,locale)}</time>:t.pendingReplacement}</p></section>;}
export function CreditBalance({locale,credits,asOf}: {locale:Locale;credits:number|null;asOf:string}) {const t=uiCopy(locale);return <section className="lsw-credit"><h3>{t.remainingCredit}</h3><p className="lsw-credit-number">{credits===null?t.unknown:formatCount(credits,locale)}</p><p className="lsw-help">{t.creditAsOf} <time dateTime={asOf}>{formatInstant(asOf,locale)}</time></p><p className="lsw-help">{t.creditNotAttendance}</p></section>;}
/** Calendar layout only. Domain owns dates, conflicts, booking and route state. Mobile always has a readable agenda. */
export function CalendarShell({locale,period,view,viewHrefs,todayHref,previousHref,nextHref,desktop,agenda}: {locale:Locale;period:string;view:'day'|'week'|'month';viewHrefs:Record<'day'|'week'|'month',string>;todayHref:string;previousHref:string;nextHref:string;desktop:ReactNode;agenda:ReactNode}) {const t=uiCopy(locale);return <section className="lsw-calendar"><header className="lsw-calendar-toolbar"><h2>{period}</h2><nav aria-label={t.calendar}>{(['day','week','month'] as const).map(key=><a key={key} href={localHref(viewHrefs[key])} aria-current={view===key?'page':undefined}>{t[key]}</a>)}</nav><nav aria-label={t.schedule}><a href={localHref(previousHref)}>{t.previous}</a><a href={localHref(todayHref)}>{t.today}</a><a href={localHref(nextHref)}>{t.next}</a></nav><span className="lsw-help" dir="ltr">{t.timezone}</span></header><div className="lsw-calendar-grid">{desktop}</div><div className="lsw-calendar-agenda"><h3>{t.agenda}</h3>{agenda}</div></section>;}
