'use client';
import type { Locale,PageSlice } from './model.ts';
import { checkedPage } from './model.ts';
import { uiCopy,formatInstant,formatCount } from './i18n.ts';
import { Button,Input,Textarea,SaveResult,submitValid } from './controls.tsx';
import { StatusChip,Card,EmptyState,Pagination } from './surfaces.tsx';
export type ObservationDraft={body:string;context:string;tried:string;response:string;question:string;eventDate:string};
export function ObservationComposer({id,locale,draft,onChange,onSubmit,busy=false,error=false,saved=false}: {id:string;locale:Locale;draft:ObservationDraft;onChange:(draft:ObservationDraft)=>void;onSubmit:()=>void;busy?:boolean|undefined;error?:boolean|undefined;saved?:boolean|undefined}) {const t=uiCopy(locale);return <form className="lsw-stack" onSubmit={event=>submitValid(event,()=>{if(!busy&&draft.body.trim())onSubmit();else event.currentTarget.querySelector<HTMLTextAreaElement>('textarea')?.focus();})}><Textarea id={`${id}-body`} label={t.observationTitle} help={t.observationHelp} error={draft.body.length>0&&!draft.body.trim()?t.errorSummary:undefined} rows={4} required maxLength={4000} value={draft.body} disabled={busy} onChange={event=>onChange({...draft,body:event.currentTarget.value})}/><details className="lsw-details"><summary>{t.context}</summary><div className="lsw-stack">{([{key:'context',label:t.context},{key:'tried',label:t.parentTried},{key:'response',label:t.response},{key:'question',label:t.question}] as const).map(field=><Textarea key={field.key} id={`${id}-${field.key}`} label={field.label} rows={2} maxLength={1000} value={draft[field.key]} disabled={busy} onChange={event=>onChange({...draft,[field.key]:event.currentTarget.value})}/>)}<Input id={`${id}-date`} type="date" label={t.eventDate} value={draft.eventDate} disabled={busy} onChange={event=>onChange({...draft,eventDate:event.currentTarget.value})}/></div></details><Button type="submit" busy={busy}>{t.submitObservation}</Button><SaveResult locale={locale} busy={busy} error={error} saved={saved}/><p className="lsw-service-note">{t.serviceExpectation}</p></form>;}
export type AttributedEntry={id:string;author:string;source:'parent'|'practitioner';body:string;submittedAt:string;versionLabel?:string|undefined;eventDateLabel?:string|undefined;status:'submitted'|'reviewed'|'replied'};
export function AttributedObservation({locale,item}: {locale:Locale;item:AttributedEntry}) {const t=uiCopy(locale);return <article className="lsw-observation"><header><strong><bdi>{item.author}</bdi></strong><span className="lsw-help">{item.source==='parent'?t.parentReported:t.practitionerObserved}</span></header><p className="lsw-user-text" dir="auto">{item.body}</p><dl className="lsw-inline-meta"><div><dt>{t.submittedAt}</dt><dd><time dateTime={item.submittedAt}>{formatInstant(item.submittedAt,locale)}</time></dd></div>{item.versionLabel && <div><dt>{t.version}</dt><dd><bdi>{item.versionLabel}</bdi></dd></div>}{item.eventDateLabel && <div><dt>{t.eventDate}</dt><dd>{item.eventDateLabel}</dd></div>}</dl><StatusChip>{t[item.status]}</StatusChip>{item.source==='parent'&&item.status!=='submitted' && <p className="lsw-help">{t.reviewNotWitnessed}</p>}</article>;}
export function UpdateThread({locale,page}: {locale:Locale;page:PageSlice<AttributedEntry>}) {checkedPage(page);return <div>{page.items.length===0?<EmptyState locale={locale}/>:<ol className="lsw-thread">{page.items.map(item=><li key={item.id}><AttributedObservation locale={locale} item={item}/></li>)}</ol>}<Pagination locale={locale} page={page}/></div>;}
export function FourWeekSummary({id,locale,period,attended,examples}: {id:string;locale:Locale;period:string;attended:number|null;examples:readonly AttributedEntry[]}) {const t=uiCopy(locale);if(examples.length>50)throw new RangeError('Paginate summary examples');return <Card id={id} title={t.summary}><p className="lsw-eyebrow">{period}</p><p>{t.attended}: <strong>{attended===null?t.unknown:formatCount(attended,locale)}</strong></p><p>{t.summaryContext}</p>{examples.length===0?<EmptyState locale={locale}/>:examples.map(item=><AttributedObservation key={item.id} locale={locale} item={item}/>)}</Card>;}
export const QualitativeHistory=UpdateThread;
