'use client';
import type { Locale,WorkspaceRole,Destinations } from './model.ts';
import { uiCopy } from './i18n.ts';
import { AppShell } from './shells.tsx';
import { PageHeader,Card,AttentionItem,StatusChip,EmptyState,ErrorState,LoadingState,UnauthorizedState,NotFoundState,DataTable,Timeline,Toast,ProgressBar,Breadcrumb } from './surfaces.tsx';
import { Button,IconButton,Input,Textarea,Select,RadioGroup,Checkbox,Tabs,TabPanel,FormSection } from './controls.tsx';
import { Dialog,DialogTrigger,Drawer } from './dialogs.tsx';
import { HomePracticeCard,TaskCoordination,OccurrenceRow,VisibilityControl } from './practice.tsx';
import type { CoordinationSelection } from './practice.tsx';
import { NotificationSettings } from './notifications.tsx';
import type { NotificationView } from './notifications.tsx';
import { AppointmentCard,RescheduleNotice,CreditBalance,CalendarShell,NoticeReceipt } from './appointments.tsx';
import type { AppointmentView,NoticeReceiptView } from './appointments.tsx';
import { ObservationComposer,FourWeekSummary } from './feedback.tsx';
import type { ObservationDraft,AttributedEntry } from './feedback.tsx';
import type { Visibility } from '../../lib/visibility.ts';
export interface GalleryState { coordination:CoordinationSelection;notifications:NotificationView;draft:ObservationDraft;visibility:Visibility;tab:string;saved:boolean;error:boolean;receipt?:NoticeReceiptView }
export const initialGalleryState:GalleryState={coordination:{parentIds:['synthetic-parent-a','synthetic-parent-b'],mode:'any_assignee'},notifications:{email:true,push:false,whatsapp:false,practice:true,appointments:true,replies:true,quietStart:'21:00',quietEnd:'07:00'},draft:{body:'',context:'',tried:'',response:'',question:'',eventDate:''},visibility:'private',tab:'ready',saved:false,error:false};
export type GalleryEvent={type:'coordination';value:CoordinationSelection}|{type:'notifications';value:NotificationView}|{type:'draft';value:ObservationDraft}|{type:'visibility';value:Visibility}|{type:'tab';value:string}|{type:'save'}|{type:'error'}|{type:'receipt'};
export function GalleryFrame({locale,role,state,onEvent}: {locale:Locale;role:WorkspaceRole;state:GalleryState;onEvent:(event:GalleryEvent)=>void}) {
 const t=uiCopy(locale),he=locale==='he';
 const names:[string,string]=he?['הורה א׳ (דוגמה)','הורה ב׳ (דוגמה)']:['Parent A (example)','Parent B (example)'];
 const parents=[{id:'synthetic-parent-a',label:names[0]},{id:'synthetic-parent-b',label:names[1]}];
 const item={id:'synthetic-practice',title:he?'לעצור רגע, ואז לבחור איך להגיב':'Pause, then choose a response',moduleLabel:he?'תרגול לדוגמה':'Example practice',versionLabel:'v3',why:he?'תוכן סינתטי לבדיקת התצוגה בלבד.':'Synthetic content for reviewing the display only.',instruction:he?'ברגע יומיומי שדורש תשומת לב, אפשר להציע עצירה קצרה ולתת מקום לתשובה במילים של הילד.':'In an everyday moment that needs attention, offer a short pause and make room for a response in the child’s own words.',example:he?'״מה יעזור לך ברגע הזה?״':'“What would help you in this moment?”',avoid:he?'אין ציון, השוואה או דירוג.':'No score, comparison or ranking.',review:he?'לעיון משותף במפגש הבא.':'Review together at the next meeting.'};
 const appointment:AppointmentView={id:'synthetic-appointment',title:t.individual,startsAt:'2026-09-09T13:00:00Z',endsAt:'2026-09-09T14:00:00Z',kind:'individual',status:'scheduled',location:he?'מיקום לדוגמה בלבד':'Example location only'};
 const observations:AttributedEntry[]=[{id:'synthetic-example-1',author:names[0],source:'parent',body:he?'דוגמה סינתטית: לאחר עצירה קצרה נאמר במילים מה היה מתסכל. זהו דיווח לדוגמה, לא תוצאה טיפולית מאומתת.':'Synthetic example: after a short pause, the frustrating part was described in words. This is a sample report, not a verified treatment outcome.',submittedAt:'2026-09-06T09:00:00Z',versionLabel:'v3',status:'reviewed'}];
 const destinations:Destinations={home:'#overview',practice:'#practice',feedback:'#feedback',schedule:'#schedule',calendar:'#calendar',clients:'#table',forms:'#controls',payments:'#credit'};
 return <AppShell locale={locale} role={role} current={role==='parent'?'home':'calendar'} destinations={destinations} languageHref={`/${he?'en':'he'}/dev/ui?role=${role}`} context={t.preview} account={<DialogTrigger id="settings-dialog" variant="quiet">{t.settings}</DialogTrigger>} attention={<><AttentionItem title={t.reviewPoint} description={t.serviceExpectation}/><CreditBalance locale={locale} credits={2} asOf="2026-09-06T09:00:00Z"/></>}>
 <div id="overview"><PageHeader title={role==='parent'?t.practiceNow:t.today} context={t.noData}/></div>
 <nav className="lsw-gallery-nav" aria-label={t.navigation}><a href="#practice">{t.practice}</a><a href="#feedback">{t.feedback}</a><a href="#schedule">{t.schedule}</a><a href="#controls">{t.more}</a></nav>
 <div className="lsw-content-grid"><div className="lsw-stack" id="practice"><HomePracticeCard locale={locale} item={item} action={<a className="lsw-button lsw-button--primary" href="#feedback">{t.report}</a>}/><div><OccurrenceRow locale={locale} period="morning" completedBy={names[0]}/><OccurrenceRow locale={locale} period="evening"/></div></div><div className="lsw-stack" id="schedule"><AppointmentCard locale={locale} item={appointment} action={<RescheduleNotice id="reschedule-dialog" locale={locale} item={appointment} receipt={state.receipt} onSend={()=>onEvent({type:'receipt'})}/>}/><AttentionItem title={t.parentGuidance} description={he?'מפגש הורים לדוגמה — 15 דקות, בנפרד מהמפגש האישי.':'Example parent meeting — 15 minutes, separate from the individual appointment.'}/></div></div>
 <section id="feedback" className="lsw-gallery-section"><Card id="feedback-card" title={t.feedback}><ObservationComposer id="observation" locale={locale} draft={state.draft} saved={state.saved} error={state.error} onChange={value=>onEvent({type:'draft',value})} onSubmit={()=>onEvent({type:'save'})}/></Card></section>
 <FourWeekSummary id="summary" locale={locale} period={he?'תקופה לדוגמה: ארבעה שבועות':'Example period: four weeks'} attended={3} examples={observations}/>
 <section className="lsw-subsection" id="coordination"><h2>{t.whoHandles}</h2><TaskCoordination id="coordination-form" locale={locale} parents={parents} value={state.coordination} onChange={value=>onEvent({type:'coordination',value})} onSave={()=>onEvent({type:'save'})} error={state.error}/></section>
 <section className="lsw-subsection" id="preferences"><h2>{t.notifications}</h2><NotificationSettings id="notification-form" locale={locale} value={state.notifications} available={{email:true,push:false,whatsapp:false}} onChange={value=>onEvent({type:'notifications',value})} onSave={()=>onEvent({type:'save'})} error={state.error} saved={state.saved}/></section>
 <section id="calendar" className="lsw-gallery-section"><CalendarShell locale={locale} period={he?'שבוע לדוגמה':'Example week'} view="week" viewHrefs={{day:'#calendar',week:'#calendar',month:'#calendar'}} todayHref="#calendar" previousHref="#calendar" nextHref="#calendar" desktop={<div className="lsw-demo-week">{(he?['יום א׳','יום ב׳','יום ג׳','יום ד׳','יום ה׳']:['Sunday','Monday','Tuesday','Wednesday','Thursday']).map((day,i)=><div className="lsw-demo-day" key={day}><p>{day}</p>{i%2===0 && <div className="lsw-demo-event"><span>{t.individual}</span><span dir="ltr">16:00–17:00</span><StatusChip>{t.scheduled}</StatusChip></div>}</div>)}</div>} agenda={<AppointmentCard locale={locale} item={{...appointment,id:'synthetic-mobile-appointment'}}/>}/></section>
 <section id="table" className="lsw-gallery-section"><DataTable id="clients-example" locale={locale} caption={t.dense} page={{items:[{id:'example-a',label:he?'תיק סינתטי עם כותרת ארוכה לבדיקת שבירת שורות בעברית':'Synthetic case with a deliberately long title to check wrapping',status:t.notReported},{id:'example-b',label:he?'תיק סינתטי ב׳':'Synthetic case B',status:t.reviewed}],page:1,totalPages:1}} rowKey={row=>row.id} columns={[{id:'label',label:t.clients,render:row=>row.label},{id:'status',label:t.feedback,render:row=><StatusChip>{row.status}</StatusChip>}]}/></section>
 <section id="credit"><CreditBalance locale={locale} credits={null} asOf="2026-09-06T09:00:00Z"/><NoticeReceipt locale={locale} receipt={{originalStartsAt:appointment.startsAt,receivedAt:'2026-09-06T09:00:00Z',credit:'protected',replacement:'pending'}}/></section>
 <section id="controls" className="lsw-subsection"><h2>{t.more}</h2><Breadcrumb label={t.navigation} items={[{label:t.home,href:'#overview'},{label:t.more}]}/><div className="lsw-actions"><Button onClick={()=>onEvent({type:'save'})}>{t.save}</Button><Button variant="secondary" busy>{t.saving}</Button><Button disabled>{t.notAvailable}</Button><IconButton label={t.next} onClick={()=>onEvent({type:'tab',value:'empty'})}>→</IconButton><DialogTrigger id="example-drawer">{t.schedule}</DialogTrigger></div><FormSection id="sample-form" title={t.forms}><Input id="sample-email" label={t.email} type="email" autoComplete="email" spellCheck={false} defaultValue="sample@example.test"/><Input id="sample-error" label={t.question} error={t.errorSummary} defaultValue=""/><Textarea id="sample-long" label={t.dense} defaultValue={(he?'טקסט סינתטי ארוך שמדגים גלישת שורות בלי להסתיר מידע. ':'Synthetic long content to demonstrate wrapping without hiding information. ').repeat(8)}/><Select id="sample-select" label={t.schedule} defaultValue="one"><option value="one">{t.individual}</option><option value="two">{t.parentGuidance}</option></Select><Checkbox id="sample-checkbox" label={t.appointmentReminder} defaultChecked/><RadioGroup id="sample-radio" legend={t.completion} value={state.coordination.mode} options={[{value:'any_assignee',label:t.any},{value:'each_assignee',label:t.each}]} onChange={value=>{if(value==='any_assignee'||value==='each_assignee')onEvent({type:'coordination',value:{...state.coordination,mode:value}});}}/></FormSection>
 <Tabs id="state-tabs" label={t.more} locale={locale} value={state.tab} items={[{id:'ready',label:t.saved},{id:'empty',label:t.emptyTitle},{id:'error',label:t.errorTitle}]} onChange={value=>onEvent({type:'tab',value})}/><TabPanel id="state-tabs" tab="ready" active={state.tab==='ready'}><Toast locale={locale} message={t.saved}/></TabPanel><TabPanel id="state-tabs" tab="empty" active={state.tab==='empty'}><EmptyState locale={locale}/></TabPanel><TabPanel id="state-tabs" tab="error" active={state.tab==='error'}><ErrorState locale={locale} onRetry={()=>onEvent({type:'save'})}/></TabPanel><LoadingState locale={locale}/><UnauthorizedState locale={locale} backHref="#overview"/><NotFoundState locale={locale} backHref="#overview"/><ProgressBar id="operation-only" label={t.operation} value={30}/><VisibilityControl id="visibility" locale={locale} value={state.visibility} audience={names} onChange={value=>onEvent({type:'visibility',value})}/><VisibilityControl id="note" locale={locale} value="private" audience={[]} isPrivateNote onChange={()=>undefined}/><Timeline locale={locale} page={{items:[{id:'timeline-example',instant:'2026-09-06T09:00:00Z',title:t.reviewed,body:t.reviewNotWitnessed}],page:1,totalPages:1}}/></section>
 <Dialog id="settings-dialog" locale={locale} title={t.settings}><NotificationSettings id="settings-dialog-form" locale={locale} value={state.notifications} available={{email:true,push:false,whatsapp:false}} onChange={value=>onEvent({type:'notifications',value})} onSave={()=>onEvent({type:'save'})} saved={state.saved}/></Dialog><Drawer id="example-drawer" locale={locale} title={t.schedule}><AppointmentCard locale={locale} item={{...appointment,id:'drawer-appointment'}}/></Drawer><p className="lsw-demo-banner">{t.preview}</p>
 </AppShell>;
}
