'use client';
import type { Locale } from './model.ts';
import { isTimeOfDay } from './model.ts';
import { uiCopy } from './i18n.ts';
import { Button,Checkbox,Input,SaveResult,submitValid } from './controls.tsx';
export type NotificationView={email:boolean;push:boolean;whatsapp:boolean;practice:boolean;appointments:boolean;replies:boolean;quietStart:string;quietEnd:string};
export function NotificationSettings({id,locale,value,available,onChange,onSave,busy=false,error=false,saved=false}: {id:string;locale:Locale;value:NotificationView;available:{email:boolean;push:boolean;whatsapp:boolean};onChange:(value:NotificationView)=>void;onSave:()=>void;busy?:boolean|undefined;error?:boolean|undefined;saved?:boolean|undefined}) {
 const t=uiCopy(locale);return <form className="lsw-stack" onSubmit={event=>submitValid(event,()=>{if(!busy&&isTimeOfDay(value.quietStart)&&isTimeOfDay(value.quietEnd))onSave();})}><p>{t.ownPreferences}</p><fieldset disabled={busy} className="lsw-fieldset"><legend>{t.channels}</legend>{(['email','push','whatsapp'] as const).map(channel=><Checkbox key={channel} id={`${id}-${channel}`} label={t[channel]} help={available[channel]?undefined:t.notConnected} checked={value[channel] && available[channel]} disabled={!available[channel]} onChange={event=>onChange({...value,[channel]:event.currentTarget.checked})}/>)}</fieldset><fieldset disabled={busy} className="lsw-fieldset"><legend>{t.events}</legend>{([{key:'practice',label:t.practiceReminder},{key:'appointments',label:t.appointmentReminder},{key:'replies',label:t.replyReminder}] as const).map(event=><Checkbox key={event.key} id={`${id}-${event.key}`} label={event.label} checked={value[event.key]} onChange={e=>onChange({...value,[event.key]:e.currentTarget.checked})}/>)}</fieldset><fieldset disabled={busy} className="lsw-fieldset"><legend>{t.quiet}</legend><div className="lsw-two-fields"><Input id={`${id}-start`} type="time" dir="ltr" required label={t.quietStart} value={value.quietStart} onChange={event=>onChange({...value,quietStart:event.currentTarget.value})}/><Input id={`${id}-end`} type="time" dir="ltr" required label={t.quietEnd} value={value.quietEnd} onChange={event=>onChange({...value,quietEnd:event.currentTarget.value})}/></div><p className="lsw-help">{t.quietHelp} <bdi>{t.timezone}</bdi></p></fieldset><Button type="submit" variant="secondary" busy={busy}>{t.save}</Button><SaveResult locale={locale} busy={busy} error={error} saved={saved}/></form>;
}
