'use client';
import type { ReactNode } from 'react';
import type { Visibility } from '../../lib/visibility.ts';
import type { Locale } from './model.ts';
import { validParentSelection } from './model.ts';
import { uiCopy } from './i18n.ts';
import { Button,Checkbox,RadioGroup,SaveResult,submitValid } from './controls.tsx';
import { Card,StatusChip } from './surfaces.tsx';
import { Dialog,DialogTrigger,closeDialog } from './dialogs.tsx';
export interface PracticeView { id:string;title:string;versionLabel:string;moduleLabel:string;why:string;instruction:string;example:string;avoid:string;review:string }
/** Only fully authorized, projected content may be supplied. Hidden/private payloads must never reach the browser. */
export function HomePracticeCard({locale,item,action}: {locale:Locale;item:PracticeView;action:ReactNode}) {const t=uiCopy(locale);return <Card id={item.id} title={item.title}><p className="lsw-eyebrow">{item.moduleLabel} · {t.version} <bdi>{item.versionLabel}</bdi></p><p className="lsw-practice-instruction">{item.instruction}</p><div className="lsw-actions">{action}</div><details className="lsw-details"><summary>{t.practiceDetails}</summary><dl className="lsw-description">{[[t.why,item.why],[t.example,item.example],[t.avoid,item.avoid],[t.reviewPoint,item.review]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></details></Card>;}
export type CoordinationSelection={parentIds:readonly string[];mode:'any_assignee'|'each_assignee'};
export function TaskCoordination({id,locale,parents,value,onChange,onSave,busy=false,error=false}: {id:string;locale:Locale;parents:readonly {id:string;label:string}[];value:CoordinationSelection;onChange:(next:CoordinationSelection)=>void;onSave:()=>void;busy?:boolean|undefined;error?:boolean|undefined}) {
 const t=uiCopy(locale),valid=validParentSelection(value.parentIds,parents.map(p=>p.id));return <form className="lsw-stack" onSubmit={event=>submitValid(event,()=>{if(valid&&!busy)onSave();else event.currentTarget.querySelector<HTMLInputElement>('input[type=checkbox]')?.focus();})}><fieldset disabled={busy} className="lsw-fieldset"><legend>{t.whoHandles}</legend><p>{t.chooseParents}</p>{parents.map((parent,index)=><Checkbox key={parent.id} id={`${id}-parent-${index}`} label={parent.label} checked={value.parentIds.includes(parent.id)} onChange={event=>onChange({...value,parentIds:event.currentTarget.checked?[...value.parentIds,parent.id]:value.parentIds.filter(x=>x!==parent.id)})}/>)}{!valid && <p role="status" className="lsw-field-error">{t.chooseParents}</p>}</fieldset><RadioGroup id={`${id}-mode`} legend={t.completion} value={value.mode} disabled={busy} options={[{value:'any_assignee',label:t.any},{value:'each_assignee',label:t.each}]} onChange={mode=>{if(mode==='any_assignee'||mode==='each_assignee')onChange({...value,mode});}}/><p className="lsw-help">{t.audienceUnchanged}</p><Button type="submit" variant="secondary" busy={busy}>{t.save}</Button><SaveResult locale={locale} error={error} busy={busy}/></form>;
}
export function OccurrenceRow({locale,period,completedBy}: {locale:Locale;period:'morning'|'evening';completedBy?:string|undefined}) {const t=uiCopy(locale);return <div className="lsw-occurrence"><strong>{t[period]}</strong><StatusChip tone={completedBy?'positive':'neutral'}>{completedBy?<>{t.completedBy} <bdi>{completedBy}</bdi></>:t.notReported}</StatusChip></div>;}
export function VisibilityControl({id,locale,value,audience,isPrivateNote=false,busy=false,onChange}: {id:string;locale:Locale;value:Visibility;audience:readonly string[];isPrivateNote?:boolean|undefined;busy?:boolean|undefined;onChange:(value:Visibility)=>void}) {
 const t=uiCopy(locale);if(isPrivateNote)return <p className="lsw-private-note">{t.privateNote}</p>;
 return <fieldset className="lsw-fieldset" disabled={busy}><legend>{t.audience}</legend><p><StatusChip>{value==='private'?t.private:value==='family_full'?t.full:t.titleOnly}</StatusChip></p><p className="lsw-help">{t.audienceExplain}</p><p>{audience.map((name,i)=><bdi key={i}>{i>0?' · ':''}{name}</bdi>)}</p><div className="lsw-actions"><Button variant="quiet" disabled={value==='private'} onClick={()=>onChange('private')}>{t.private}</Button>{(['family_title_completion','family_full'] as const).map(option=><span key={option}>{value==='private'?<><DialogTrigger id={`${id}-${option}`} disabled={audience.length===0}>{option==='family_full'?t.full:t.titleOnly}</DialogTrigger><Dialog id={`${id}-${option}`} locale={locale} title={t.audienceConfirm} description={t.audienceExplain} busy={busy}><p>{option==='family_full'?t.full:t.titleOnly}</p><p>{audience.join(' · ')}</p><Button onClick={()=>{onChange(option);closeDialog(`${id}-${option}`);}} busy={busy}>{t.share}</Button></Dialog></>:<Button variant="secondary" disabled={value===option||audience.length===0} onClick={()=>onChange(option)}>{option==='family_full'?t.full:t.titleOnly}</Button>}</span>)}</div></fieldset>;
}
