'use client';
import type { ReactNode } from 'react';
import { direction } from '../../lib/locale.ts';
import type { Locale,WorkspaceRole,Destination,Destinations } from './model.ts';
import { parentDestinations,practitionerDestinations,localHref } from './model.ts';
import { uiCopy } from './i18n.ts';
export function Sidebar({locale,destinations,current}: {locale:Locale;destinations:Destinations;current:Destination}) {const t=uiCopy(locale);return <aside className="lsw-sidebar"><p className="lsw-eyebrow">{t.practitionerSpace}</p><nav aria-label={t.navigation}>{practitionerDestinations.map(key=><NavItem key={key} label={t[key]} href={destinations[key]} current={current===key}/>)}</nav></aside>;}
function NavItem({label,href,current}: {label:string;href?:string|undefined;current:boolean}) {return href?<a href={localHref(href)} aria-current={current?'page':undefined}>{label}</a>:<span aria-disabled="true">{label}</span>;}
export function MobileNav({locale,role,current,destinations,more}: {locale:Locale;role:WorkspaceRole;current:Destination;destinations:Destinations;more?:ReactNode}) {const t=uiCopy(locale);return <nav className="lsw-mobile-nav" aria-label={t.navigation}>{role==='parent'?parentDestinations.map(key=><NavItem key={key} label={t[key]} href={destinations[key]} current={current===key}/>):<><NavItem label={t.today} href={destinations.calendar} current={current==='calendar'}/><NavItem label={t.clients} href={destinations.clients} current={current==='clients'}/><NavItem label={t.feedback} href={destinations.feedback} current={current==='feedback'}/>{more}</>}</nav>;}
export function AppShell({locale,role,current,destinations,children,account,languageHref,context,attention}: {locale:Locale;role:WorkspaceRole;current:Destination;destinations:Destinations;children:ReactNode;account?:ReactNode;languageHref?:string|undefined;context?:ReactNode;attention?:ReactNode}) {
 const t=uiCopy(locale);return <div className={`lsw lsw-shell lsw-shell--${role}`} lang={locale} dir={direction(locale)}><a className="lsw-skip" href="#lsw-main">{t.skip}</a><header className="lsw-topbar"><div className="lsw-brand"><span aria-hidden="true" className="lsw-brand-mark">L</span><div><b translate="no" dir="ltr">{t.brand}</b><span>{role==='parent'?t.parentSpace:t.practitionerSpace}</span></div></div><div className="lsw-header-actions">{languageHref && <a lang={locale==='he'?'en':'he'} hrefLang={locale==='he'?'en':'he'} href={localHref(languageHref)}>{t.language}</a>}{account}</div></header>{role==='practitioner'?<Sidebar locale={locale} current={current} destinations={destinations}/>:<nav className="lsw-parent-nav" aria-label={t.navigation}>{parentDestinations.map(key=><NavItem key={key} label={t[key]} href={destinations[key]} current={current===key}/>)}</nav>}<div className={`lsw-workarea ${attention?'lsw-workarea--with-rail':''}`}><main id="lsw-main" tabIndex={-1} className="lsw-main">{context && <div className="lsw-context">{context}</div>}{children}</main>{attention && <aside className="lsw-rail">{attention}</aside>}</div><MobileNav locale={locale} role={role} current={current} destinations={destinations} more={<details className="lsw-more"><summary>{t.more}</summary><div>{(['practice','forms','payments'] as const).map(key=><NavItem key={key} label={t[key]} href={destinations[key]} current={current===key}/>)}</div></details>}/></div>;
}
