'use client';
import type { ReactNode } from 'react';
import type { Locale,PageSlice } from './model.ts';
import { checkedPage,localHref } from './model.ts';
import { uiCopy,formatCount,formatInstant } from './i18n.ts';
import { Button } from './controls.tsx';
export function Card({id,title,children,actions}: {id:string;title:string;children:ReactNode;actions?:ReactNode}) {return <section className="lsw-card" aria-labelledby={`${id}-title`}><header className="lsw-section-header"><h2 id={`${id}-title`}>{title}</h2>{actions}</header>{children}</section>;}
export function StatusChip({children,tone='neutral'}: {children:ReactNode;tone?:'neutral'|'positive'|'warning'|'danger'}) {return <span className={`lsw-status lsw-status--${tone}`}><span aria-hidden="true">{tone==='positive'?'✓':tone==='warning'?'!':tone==='danger'?'×':'·'}</span>{children}</span>;}
export function EmptyState({locale,title,children,action}: {locale:Locale;title?:string|undefined;children?:ReactNode;action?:ReactNode}) {const t=uiCopy(locale);return <div className="lsw-empty"><h2>{title ?? t.emptyTitle}</h2><p>{children ?? t.emptyBody}</p>{action}</div>;}
export function ErrorState({locale,onRetry}: {locale:Locale;onRetry?:()=>void}) {const t=uiCopy(locale);return <div className="lsw-alert" role="status"><h2>{t.errorTitle}</h2><p>{t.errorBody}</p>{onRetry && <Button variant="secondary" onClick={onRetry}>{t.retry}</Button>}</div>;}
export function LoadingState({locale}: {locale:Locale}) {return <div role="status" aria-live="polite" className="lsw-loading"><p>{uiCopy(locale).loading}</p><div className="lsw-skeleton" aria-hidden="true"/><div className="lsw-skeleton lsw-skeleton--short" aria-hidden="true"/></div>;}
export function UnauthorizedState({locale,backHref}: {locale:Locale;backHref:string}) {const t=uiCopy(locale);return <section className="lsw-empty"><h2>{t.unauthorizedTitle}</h2><p>{t.unauthorizedBody}</p><a href={localHref(backHref)}>{t.back}</a></section>;}
export function NotFoundState({locale,backHref}: {locale:Locale;backHref:string}) {const t=uiCopy(locale);return <section className="lsw-empty"><h2>{t.notFound}</h2><a href={localHref(backHref)}>{t.back}</a></section>;}
export function Toast({message,onDismiss,locale}: {message:string;onDismiss?:()=>void;locale:Locale}) {return <aside className="lsw-toast"><p role="status" aria-live="polite">{message}</p>{onDismiss && <Button variant="quiet" onClick={onDismiss}>{uiCopy(locale).close}</Button>}</aside>;}
export function AttentionItem({title,description,action}: {title:string;description:string;action?:ReactNode}) {return <aside className="lsw-attention"><div><h3>{title}</h3><p>{description}</p></div>{action}</aside>;}
/** Operational transfer/processing progress only. Never use for child growth or assignment completion. */
export function ProgressBar({id,label,value,max=100}: {id:string;label:string;value:number;max?:number|undefined}) {if(!Number.isFinite(value)||!Number.isFinite(max)||max<=0||value<0||value>max)throw new RangeError('Invalid operation progress');return <div className="lsw-operation"><label htmlFor={id}>{label}</label><progress id={id} value={value} max={max}/></div>;}
export function Breadcrumb({label,items}: {label:string;items:readonly {label:string;href?:string|undefined}[]}) {return <nav aria-label={label}><ol className="lsw-breadcrumb">{items.map((item,i)=><li key={i}>{item.href?<a href={localHref(item.href)}>{item.label}</a>:<span aria-current="page">{item.label}</span>}</li>)}</ol></nav>;}
export function PageHeader({title,context,action}: {title:string;context?:ReactNode;action?:ReactNode}) {return <header className="lsw-page-header"><div>{context && <p className="lsw-eyebrow">{context}</p>}<h1>{title}</h1></div>{action}</header>;}
export function Pagination({locale,page}: {locale:Locale;page:PageSlice<unknown>}) {const t=uiCopy(locale);checkedPage(page);return <nav className="lsw-pagination" aria-label={t.page}>{page.previousHref?<a href={localHref(page.previousHref)} rel="prev">{t.previous}</a>:<span aria-disabled="true">{t.previous}</span>}<span>{t.page} {formatCount(page.page,locale)} / {formatCount(page.totalPages,locale)}</span>{page.nextHref?<a href={localHref(page.nextHref)} rel="next">{t.next}</a>:<span aria-disabled="true">{t.next}</span>}</nav>;}
export function DataTable<T>({id,locale,caption,page,columns,rowKey}: {id:string;locale:Locale;caption:string;page:PageSlice<T>;columns:readonly {id:string;label:string;numeric?:boolean|undefined;render:(item:T)=>ReactNode}[];rowKey:(item:T)=>string}) {checkedPage(page);return <section className="lsw-table-section"><table className="lsw-table" id={id}><caption>{caption}</caption><thead><tr>{columns.map(column=><th key={column.id} scope="col">{column.label}</th>)}</tr></thead><tbody>{page.items.map(item=><tr key={rowKey(item)}>{columns.map((column,i)=>i===0?<th key={column.id} scope="row" data-label={column.label}>{column.render(item)}</th>:<td key={column.id} data-label={column.label} className={column.numeric?'lsw-number':undefined}>{column.render(item)}</td>)}</tr>)}</tbody></table>{page.items.length===0 && <EmptyState locale={locale}/>}<Pagination locale={locale} page={page}/></section>;}
export function Timeline({locale,page}: {locale:Locale;page:PageSlice<{id:string;instant:string;title:string;body:ReactNode}>}) {checkedPage(page);return <div>{page.items.length===0?<EmptyState locale={locale}/>:<ol className="lsw-timeline">{page.items.map(item=><li key={item.id}><time dateTime={item.instant}>{formatInstant(item.instant,locale)}</time><h3>{item.title}</h3><div>{item.body}</div></li>)}</ol>}<Pagination locale={locale} page={page}/></div>;}
