import assert from "node:assert/strict";
import { emptyProvider, parseProvider, parseProviderCommand, parseQuery, selectProviders, possibleDuplicates,
  uuid, dateOnly, practiceDate, webUrl, phoneKey, normalize, ProviderProblem, type ProviderInput, type ProviderRecord } from "../../src/features/provider-index/core.ts";
import { parseReferral, parseReferralCommand } from "../../src/features/provider-referrals/core.ts";
const one="10000000-0000-4000-8000-000000000001", two="10000000-0000-4000-8000-000000000002", three="10000000-0000-4000-8000-000000000003";
const op="20000000-0000-4000-8000-000000000001", caseId="30000000-0000-4000-8000-000000000001";
function entry(values:Partial<ProviderInput>={}):ProviderInput { return {...emptyProvider(),name:"Demo Provider",...values}; }
function record(id:string,values:Partial<ProviderInput>={},archived=false):ProviderRecord { return {id,entry:entry(values),archived,version:1,createdAt:"2026-10-07T12:00:00Z",updatedAt:"2026-10-07T12:00:00Z"}; }
function invalid(work:()=>unknown,reason?:string) { assert.throws(work,(e:unknown)=>e instanceof ProviderProblem && e.code==="INVALID_REQUEST" && (!reason||e.reason===reason)); }
function create(values:Record<string,unknown>={}) { return {action:"create",operationId:op,id:one,entry:entry(),...values}; }
const referral=()=>({providerId:one,caseId:null,happenedOn:"",status:"considering",context:"General professional coordination only",nextAction:"Check public availability",nextOn:""});
export const coreCases:ReadonlyArray<readonly [string,()=>void]> = [
 ["a name-only draft is useful; unknown details remain blank",()=>{const e=parseProvider(entry());assert.equal(e.name,"Demo Provider");assert.equal(e.phone,"");assert.deepEqual(e.services,[]);assert.equal(e.verification.status,"unverified");}],
 ["blank name rejected",()=>invalid(()=>parseProvider(entry({name:"  "})))],
 ["160-character name maximum",()=>invalid(()=>parseProvider(entry({name:"x".repeat(161)})))],
 ["input is trimmed without mutating source",()=>{const e=entry({name:"  Demo  "});assert.equal(parseProvider(e).name,"Demo");assert.equal(e.name,"  Demo  ");}],
 ["unknown clinical fields rejected",()=>invalid(()=>parseProvider({...entry(),diagnosis:"not allowed"}),"UNKNOWN_FIELD")],
 ["unknown nested verification field rejected",()=>invalid(()=>parseProvider(entry({verification:{status:"unverified",basis:"",checkedOn:"",clinicalNotes:"no"} as never})),"UNKNOWN_FIELD")],
 ["client account and case flags are not provider fields",()=>invalid(()=>parseProvider({...entry(),clientId:caseId,createAccount:true}),"UNKNOWN_FIELD")],
 ["non-object provider rejected",()=>invalid(()=>parseProvider(null))],
 ["arrays do not substitute for provider objects",()=>invalid(()=>parseProvider([]))],
 ["numeric phone not silently stringified",()=>invalid(()=>parseProvider(entry({phone:123 as never})))],
 ["reasonable formatted phone accepted",()=>assert.equal(parseProvider(entry({phone:"+972 (50) 555-0101"})).phone,"+972 (50) 555-0101")],
 ["phone alphabet rejected",()=>invalid(()=>parseProvider(entry({phone:"call me"})),"INVALID_PHONE")],
 ["short phone rejected",()=>invalid(()=>parseProvider(entry({phone:"123"})),"INVALID_PHONE")],
 ["phone normalization is only a duplicate hint",()=>{assert.equal(phoneKey("050-5550101"),"972505550101");assert.equal(phoneKey("00972 50 5550101"),"972505550101");}],
 ["malformed email rejected",()=>invalid(()=>parseProvider(entry({email:"a@b"})),"INVALID_EMAIL")],
 ["HTML email rejected",()=>invalid(()=>parseProvider(entry({email:"<a@b.test>"})),"INVALID_EMAIL")],
 ["email is not lowercased in saved display value",()=>assert.equal(parseProvider(entry({email:"Demo@Example.test"})).email,"Demo@Example.test")],
 ["services are capped at ten",()=>invalid(()=>parseProvider(entry({services:Array.from({length:11},(_,n)=>String(n))})))],
 ["case and whitespace equivalent service duplicate rejected",()=>invalid(()=>parseProvider(entry({services:[" Coaching ","coaching"]})),"DUPLICATE_SERVICE")],
 ["empty service tag rejected",()=>invalid(()=>parseProvider(entry({services:[""]})))],
 ["Hebrew services retained",()=>assert.deepEqual(parseProvider(entry({services:["הדרכת הורים"]})).services,["הדרכת הורים"])],
 ["source can be a manual reference without a URL",()=>assert.equal(parseProvider(entry({sources:[{label:"Owner's professional introduction",url:""}]})).sources.length,1)],
 ["empty source row rejected",()=>invalid(()=>parseProvider(entry({sources:[{label:"",url:""}]})),"EMPTY_SOURCE")],
 ["six source rows rejected",()=>invalid(()=>parseProvider(entry({sources:Array.from({length:6},()=>({label:"Reference",url:""}))})))],
 ["non-web source protocols rejected",()=>invalid(()=>parseProvider(entry({sources:[{label:"",url:"javascript:alert(1)"}]})),"INVALID_URL")],
 ["external URL is normalized but never fetched",()=>assert.equal(webUrl("https://EXAMPLE.test"),"https://example.test/")],
 ["credential-bearing source URL rejected",()=>invalid(()=>webUrl("https://user:pass@example.test"),"INVALID_URL")],
 ["file URLs rejected",()=>invalid(()=>webUrl("file:///etc/passwd"),"INVALID_URL")],
 ["data URLs rejected",()=>invalid(()=>webUrl("data:text/plain,hello"),"INVALID_URL")],
 ["relative URLs rejected",()=>invalid(()=>webUrl("/private"),"INVALID_URL")],
 ["checked status needs evidence and date",()=>invalid(()=>parseProvider(entry({verification:{status:"checked",basis:"",checkedOn:""}})),"VERIFICATION_EVIDENCE_REQUIRED")],
 ["self-reported status needs attribution",()=>invalid(()=>parseProvider(entry({verification:{status:"self_reported",basis:"",checkedOn:""}})),"SOURCE_REQUIRED")],
 ["checked status carries its actual evidence",()=>assert.equal(parseProvider(entry({verification:{status:"checked",basis:"Manual source check; illustrative fixture",checkedOn:"2026-10-07"}})).verification.checkedOn,"2026-10-07")],
 ["no inferred credential status",()=>invalid(()=>parseProvider(entry({verification:{status:"best" as never,basis:"",checkedOn:""}})))],
 ["religious fit requires explicit source",()=>invalid(()=>parseProvider(entry({declaredFit:{gender:"",religiousFit:"Religious",source:""}})),"DECLARED_FIT_SOURCE_REQUIRED")],
 ["gender declaration requires explicit source",()=>invalid(()=>parseProvider(entry({declaredFit:{gender:"Male",religiousFit:"",source:""}})),"DECLARED_FIT_SOURCE_REQUIRED")],
 ["attributed fit description is retained",()=>assert.equal(parseProvider(entry({declaredFit:{gender:"Male",religiousFit:"",source:"Explicit self-description in supplied profile"}})).declaredFit.gender,"Male")],
 ["no guessing check dates",()=>assert.equal(parseProvider(entry()).verification.checkedOn,"")],
 ["ordinary notes preserve line breaks",()=>assert.equal(parseProvider(entry({privateNotes:"Public services\nAsk about availability"})).privateNotes,"Public services\nAsk about availability")],
 ["notes length capped",()=>invalid(()=>parseProvider(entry({privateNotes:"x".repeat(2001)})))],
 ["control characters rejected",()=>invalid(()=>parseProvider(entry({name:"demo\u0000"})))],
 ["direction override characters rejected",()=>invalid(()=>parseProvider(entry({name:"demo\u202E"})))],
 ["real leap date accepted",()=>assert.equal(dateOnly("2024-02-29"),"2024-02-29")],
 ["overflow calendar date rejected",()=>invalid(()=>dateOnly("2026-02-29"))],
 ["ambiguous local date rejected",()=>invalid(()=>dateOnly("7/10/2026"))],
 ["UUID normalized",()=>assert.equal(uuid("ABCDEFAB-0000-4000-8000-000000000001"),"abcdefab-0000-4000-8000-000000000001")],
 ["arbitrary record ID rejected",()=>invalid(()=>uuid("someone"))],
 ["search defaults to active, bounded first page",()=>{const q=parseQuery({});assert.equal(q.archive,"active");assert.equal(q.pageSize,25);assert.equal(q.page,1);}],
 ["query tenant override rejected",()=>invalid(()=>parseQuery({workspaceId:one}),"UNKNOWN_FIELD")],
 ["overlarge page size rejected",()=>invalid(()=>parseQuery({pageSize:500}))],
 ["fractional page rejected",()=>invalid(()=>parseQuery({page:1.5}))],
 ["string numeric page not coerced",()=>invalid(()=>parseQuery({page:"1"}))],
 ["unsupported locale rejected",()=>invalid(()=>parseQuery({locale:"fr"}))],
 ["archived entries omitted by default",()=>assert.equal(selectProviders([record(one),record(two,{},true)],{}).total,1)],
 ["explicit archive search retained",()=>assert.equal(selectProviders([record(one),record(two,{},true)],{archive:"archived"}).items[0]?.id,two)],
 ["Hebrew niqqud-independent search",()=>assert.equal(selectProviders([record(one,{name:"יוֹנָה"})],{search:"יונה",locale:"he"}).total,1)],
 ["search terms match independently",()=>assert.equal(selectProviders([record(one,{name:"Demo Alpha",location:"Modiin"})],{search:"alpha modiin"}).total,1)],
 ["service filter matches full tag",()=>assert.equal(selectProviders([record(one,{services:["Coaching"]}),record(two,{services:["Parent coaching"]})],{service:"coaching"}).total,1)],
 ["location filter applied",()=>assert.equal(selectProviders([record(one,{location:"Modiin"}),record(two,{location:"Jerusalem"})],{location:"MODIIN"}).total,1)],
 ["verification filter applied",()=>assert.equal(selectProviders([record(one),record(two,{verification:{status:"needs_review",basis:"",checkedOn:""}})],{verification:"needs_review"}).items[0]?.id,two)],
 ["fit filters combine",()=>assert.equal(selectProviders([record(one,{declaredFit:{gender:"Male",religiousFit:"Religious",source:"Self-described"}}),record(two)],{gender:"male",religiousFit:"religious"}).total,1)],
 ["stable tiebreak keeps pages deterministic",()=>assert.deepEqual(selectProviders([record(three),record(two),record(one)],{pageSize:2}).items.map(r=>r.id),[one,two])],
 ["out-of-range page clamps to last page",()=>assert.equal(selectProviders([record(one),record(two),record(three)],{page:100,pageSize:2}).page,2)],
 ["empty filter result still has page one",()=>{const p=selectProviders([],{page:8});assert.equal(p.page,1);assert.deepEqual(p.items,[]);}],
 ["filter options deduplicate normalized labels",()=>assert.equal(selectProviders([record(one,{services:["Coaching"]}),record(two,{services:["coaching"]})],{}).options.services.length,1)],
 ["selection never mutates original order",()=>{const rows=[record(two),record(one)];selectProviders(rows,{});assert.equal(rows[0]!.id,two);}],
 ["same phone across formats is a warning candidate",()=>assert.equal(possibleDuplicates([record(one,{phone:"050-5550101"})],entry({name:"Other",phone:"+972505550101"})).length,1)],
 ["same site produces a warning, not identity merge",()=>{const rows=[record(one,{website:"https://example.test/"})];assert.equal(possibleDuplicates(rows,entry({name:"Other",website:"https://example.test"})).length,1);assert.equal(rows[0]!.entry.name,"Demo Provider");}],
 ["editing same ID excludes its duplicate hint",()=>assert.equal(possibleDuplicates([record(one)],entry(),one).length,0)],
 ["different names without shared contact are separate",()=>assert.equal(possibleDuplicates([record(one)],entry({name:"Other"})).length,0)],
 ["unknown publish command rejected",()=>invalid(()=>parseProviderCommand({action:"publish",id:one}),"UNKNOWN_ACTION")],
 ["update requires optimistic version",()=>invalid(()=>parseProviderCommand(create({action:"update"})))],
 ["create accepts no account or case instructions",()=>invalid(()=>parseProviderCommand(create({caseId})),"UNKNOWN_FIELD")],
 ["create default is duplicate warning on",()=>{const c=parseProviderCommand(create());assert.equal(c.action,"create");if(c.action==="create")assert.equal(c.allowDuplicate,false);}],
 ["explicit duplicate acknowledgment stays explicit",()=>{const c=parseProviderCommand(create({allowDuplicate:true}));if(c.action==="create")assert.equal(c.allowDuplicate,true);else assert.fail();}],
 ["archive command is boolean, never destructive deletion",()=>{const c=parseProviderCommand({action:"archive",operationId:op,id:one,expectedVersion:1,archived:true});assert.equal(c.action,"archive");invalid(()=>parseProviderCommand({action:"delete",id:one}));}],
 ["operation ID is required",()=>invalid(()=>parseProviderCommand(create({operationId:""})))],
 ["referral keeps general scope explicit",()=>assert.equal(parseReferral(referral()).caseId,null)],
 ["referral never invents a callback date",()=>assert.equal(parseReferral(referral()).nextOn,"")],
 ["case scope is an opaque reference",()=>assert.equal(parseReferral({...referral(),caseId}).caseId,caseId)],
 ["clinical payload rejected in referral DTO",()=>invalid(()=>parseReferral({...referral(),transcript:"not accepted"}),"UNKNOWN_FIELD")],
 ["referral context capped",()=>invalid(()=>parseReferral({...referral(),context:"x".repeat(1001)}))],
 ["referral state not arbitrary lead stage",()=>invalid(()=>parseReferral({...referral(),status:"paid"}))],
 ["referral list cannot request all cases",()=>invalid(()=>parseReferralCommand({action:"list",caseId:null,providerId:null}),"SCOPE_REQUIRED")],
 ["general log requires a selected provider",()=>assert.deepEqual(parseReferralCommand({action:"list",caseId:null,providerId:one}),{action:"list",caseId:null,providerId:one})],
 ["a case list can cover its authorized provider refs",()=>assert.equal(parseReferralCommand({action:"list",caseId,providerId:null}).action,"list")],
 ["referral list must specify null rather than omit case",()=>invalid(()=>parseReferralCommand({action:"list",providerId:one}))],
 ["referral update requires version",()=>invalid(()=>parseReferralCommand({action:"update",operationId:op,id:one,detail:referral()}))],
 ["referral commands do not accept sender controls",()=>invalid(()=>parseReferralCommand({action:"create",operationId:op,id:one,detail:referral(),sendMessage:true}),"UNKNOWN_FIELD")],
 ["verification date uses Jerusalem day at UTC evening",()=>assert.equal(practiceDate(new Date("2026-10-07T22:30:00Z")),"2026-10-08")],
 ["verification date remains same before local midnight",()=>assert.equal(practiceDate(new Date("2026-10-07T12:00:00Z")),"2026-10-07")],
 ["normalization does not remove Hebrew letters",()=>assert.equal(normalize("הדרכת הורים"),"הדרכת הורים")],
];

